act_code: '161179'
requisite: Решение Айтекебийского районного маслихата Актюбинской области от 26 ноября 2021 года № 122. Утратило силу решением Айтекебийского районного маслихата Актюбинской области от 29 марта 2022 года № 164
title:
  rus: Об утверждении регламента Айтекебийского районного маслихата
  kaz: Әйтеке би аудандық мәслихатының Регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-11-26
approved_by:
- '153003000002'
version_date:
  kaz: 2021-11-26
  rus: 2021-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/161179/kaz/26.11.2021
  rus: https://zan.gov.kz/client/#!/doc/161179/rus/26.11.2021
