act_code: '206467'
requisite: Решение Кобдинского районного маслихата Актюбинской области от 31 декабря 2024 года № 286
title:
  rus: Об утверждении бюджета сельского округа имени И. Курманова на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған И. Құрманов атындағы ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-31
approved_by:
- '153012000002'
version_date:
  kaz: 2025-02-24
  rus: 2025-02-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/206467/kaz/24.02.2025
  rus: https://zan.gov.kz/client/#!/doc/206467/rus/24.02.2025
caused_by:
  code: '207513'
  requisite: Решение Кобдинского районного маслихата Актюбинской области от 24 февраля 2025 года № 303
  title:
    rus: О внесении изменений в решение Қобдинского районного маслихата от 31 декабря 2024 года № 286 «Об утверждении бюджета сельского округа имени И. Курманова на 2025-2027 годы»
    kaz: Қобда аудандық мәслихатының 2024 жылғы 31 желтоқсандағы № 286 «2025-2027 жылдарға арналған И. Құрманов атындағы ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/207513/rus
