act_code: '220643'
requisite: Решение Кобдинского районного маслихата Актюбинской области от 26 декабря 2025 года № 438
title:
  rus: Об утверждении бюджета Жиренкопинского сельского округа на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған Жиренқопа ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-26
approved_by:
- '153012000002'
version_date:
  kaz: 2026-05-15
  rus: 2026-05-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/220643/kaz/15.05.2026
  rus: https://zan.gov.kz/client/#!/doc/220643/rus/15.05.2026
caused_by:
  code: '225468'
  requisite: Решение Кобдинского районного маслихата Актюбинской области от 15 мая 2026 года № 470
  title:
    rus: О внесении изменений в решение Қобдинского районного маслихата от 26 декабря 2025 года № 438 «Об утверждении бюджета Жиренкопинского сельского округа на 2026-2028 годы»
    kaz: Қобда аудандық мәслихатының 2025 жылғы 26 желтоқсандағы «2026-2028 жылдарға арналған Жиренқопа ауылдық округінің бюджетін бекіту туралы» № 438 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/225468/rus
