act_code: '42829'
requisite: Ақтөбе облысы Хромтау ауданы Қызылсу ауылдық округі әкімінің 2008 жылғы 28 қарашадағы N 8 шешімі. Ақтөбе облысының Хромтау аудандық әділет басқармасында 2008 жылдың 18 желтоқсанда N 3-12-70 тіркелді
title:
  rus: Қызылсу ауылдық округіне қарасты елді мекендерге көше атауын беру туралы
  kaz: Қызылсу ауылдық округіне қарасты елді мекендерге көше атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-11-28
approved_by:
- '153013010002'
version_date:
  kaz: 2008-11-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/42829/kaz/28.11.2008
