act_code: '46847'
requisite: Ақтөбе облысы Алға аудандық мәслихатының 2009 жылғы 18 маусымдағы № 2 шешімі. Ақтөбе облысының Алға аудандық әділет басқармасында 2009 жылдың 15 шілдеде № 3-3-85 тіркелді. Күші жойылды - Ақтөбе облысы Алға аудандық мәслихатының 2010 жылғы 22 ақпандағы № 3 шешімімен
title:
  rus: 2009 жылы денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына әлеуметтік қолдау ретінде көтерме жәрдемақы беру туралы
  kaz: 2009 жылы денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына әлеуметтік қолдау ретінде көтерме жәрдемақы беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-06-18
approved_by:
- '153004000002'
version_date:
  kaz: 2009-06-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/46847/kaz/18.06.2009
