act_code: '157874'
requisite: Решение Байганинского районного маслихата Актюбинской области от 2 августа 2021 года № 53. Отменено решением Байганинского районного маслихата Актюбинской области от 19 мая 2023 года № 22
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Ащынскому, Жанажолскому, Жаркамысcкому, Культабанскому, Карауылкельдинскому, Копинскому, Кызылбулакскому, Миялинскому, Сартогайскому сельским округам на 2021-2022 годы
  kaz: Байғанин ауданының Ащы, Жаңажол, Жарқамыс, Көлтабан, Қарауылкелді, Қопа, Қызылбұлақ, Миялы, Сартоғай ауылдық округтері бойынша 2021-2022 жылдарға жайылымдарды басқару және оларды пайдалану жөніндегі жоспарын бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2021-08-02
approved_by:
- '153005000002'
version_date:
  kaz: 2021-08-02
  rus: 2021-08-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/157874/kaz/02.08.2021
  rus: https://zan.gov.kz/client/#!/doc/157874/rus/02.08.2021
