act_code: '171671'
requisite: Решение Байганинского районного маслихата Актюбинской области от 31 августа 2022 года № 153. Зарегистрировано в Министерстве юстиции Республики Казахстан 12 сентября 2022 года № 29516
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2022 год по Байганинскому району
  kaz: Байғанин ауданы бойынша шетелдіктер үшін 2022 жылға арналған туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-08-31
approved_by:
- '153005000002'
version_date:
  kaz: 2022-08-31
  rus: 2022-08-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/171671/kaz/31.08.2022
  rus: https://zan.gov.kz/client/#!/doc/171671/rus/31.08.2022
