act_code: '52694'
requisite: Ақтөбе облысы Шалқар аудандық мәслихатының 2010 жылғы 20 сәуірдегі № 201 шешімі. Ақтөбе облысы Шалқар ауданының Әділет басқармасында 2010 жылдың 24 мамырда № 3-13-132 тіркелді. Күші жойылды - Ақтөбе облысы Шалқар аудандық мәслихатының 2012 жылғы 10 тамыздағы № 35 шешімімен
title:
  rus: Шалқар қаласы мен ауданының селолық округтерінің аумақтарын көріктендіру және тазалығын қамтамасыз ету туралы ережесін бекіту
  kaz: Шалқар қаласы мен ауданының селолық округтерінің аумақтарын көріктендіру және тазалығын қамтамасыз ету туралы ережесін бекіту
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-20
approved_by:
- '153014000002'
version_date:
  kaz: 2010-04-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/52694/kaz/20.04.2010
