act_code: '98661'
requisite: Решение маслихата Шалкарского района Актюбинской области от 25 декабря 2015 года № 259. Зарегистрировано Департаментом юстиции Актюбинской области 25 января 2016 года № 4720. Утратило силу решением маслихата Шалкарского района Актюбинской области от 29 августа 2016 года № 51
title:
  rus: Об утверждении Положения государственного учреждения "Аппарат Шалкарского районного маслихата"
  kaz: '"Шалқар аудандық мәслихатының аппараты" мемлекеттік мекемесінің Ережесін бекіту туралы'
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2015-12-25
approved_by:
- '153014000002'
version_date:
  kaz: 2015-12-25
  rus: 2015-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/98661/kaz/25.12.2015
  rus: https://zan.gov.kz/client/#!/doc/98661/rus/25.12.2015
