act_code: '115258'
requisite: Решение маслихата Алгинского района Актюбинской области от 26 сентября 2017 года № 116. Зарегистрировано Департаментом юстиции Актюбинской области 11 октября 2017 года № 5676. Утратило силу решением Алгинского районного маслихата Актюбинской области от 28 марта 2024 года № 137
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Алгинском районе
  kaz: Алға ауданында тұрғын үй көмегін көрсету мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-09-26
approved_by:
- '153004000002'
version_date:
  kaz: 2023-11-16
  rus: 2023-11-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/115258/kaz/16.11.2023
  rus: https://zan.gov.kz/client/#!/doc/115258/rus/16.11.2023
caused_by:
  code: '188932'
  requisite: Решение Алгинского районного маслихата Актюбинской области от 16 ноября 2023 года № 77. Зарегистрировано Департаментом юстиции Актюбинской области 21 ноября 2023 года № 8446. Утратило силу решением Алгинского районного маслихата Актюбинской области от 28 марта 2024 года № 137
  title:
    rus: О внесении изменения в решение Алгинского районного маслихата от 26 сентября 2017 года № 116 «Об определении размера и порядка оказания жилищной помощи в Алгинском районе»
    kaz: Алға аудандық мәслихатының 2017 жылғы 26 қыркүйектегі № 116 «Алға ауданында тұрғын үй көмегін көрсету мөлшерін және тәртібін айқындау туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/188932/rus
