act_code: '162478'
requisite: Решение Хромтауского районного маслихата Актюбинской области от 24 декабря 2021 года № 146. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 декабря 2021 года № 26088
title:
  rus: Об утверждении Хромтауского районного бюджета на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Хромтау ауданының бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '153013000002'
version_date:
  kaz: 2022-11-08
  rus: 2022-11-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/162478/kaz/08.11.2022
  rus: https://zan.gov.kz/client/#!/doc/162478/rus/08.11.2022
caused_by:
  code: '173917'
  requisite: Решение Хромтауского районного маслихата Актюбинской области от 8 ноября 2022 года № 272
  title:
    rus: О внесении изменений в решение Хромтауского районного маслихата от 24 декабря 2021 года № 146 «Об утверждении Хромтауского районного бюджета на 2022-2024 годы»
    kaz: Хромтау аудандық мәслихатының 2021 жылғы 24 желтоқсандағы № 146 «2022-2024 жылдарға арналған Хромтау ауданының бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/173917/rus
