act_code: '162478'
requisite: Решение Хромтауского районного маслихата Актюбинской области от 24 декабря 2021 года № 146. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 декабря 2021 года № 26088
title:
  rus: Об утверждении Хромтауского районного бюджета на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Хромтау ауданының бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '153013000002'
version_date:
  kaz: 2021-12-24
  rus: 2021-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/162478/kaz/24.12.2021
  rus: https://zan.gov.kz/client/#!/doc/162478/rus/24.12.2021
