act_code: '98305'
requisite: Решение маслихата Уилского района Актюбинской области от 24 декабря 2015 года № 272. Зарегистрировано Департаментом юстиции Актюбинской области 22 января 2016 года № 4701. Срок действия решения - до 1 января 2017 года
title:
  rus: Об утверждении бюджета Уилского района на 2016-2018 годы
  kaz: 2016-2018 жылдарға арналған Ойыл ауданының бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-24
approved_by:
- '153011000002'
version_date:
  kaz: 2016-07-04
  rus: 2016-07-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/98305/kaz/04.07.2016
  rus: https://zan.gov.kz/client/#!/doc/98305/rus/04.07.2016
caused_by:
  code: '105206'
  requisite: Решение маслихата Уилского района Актюбинской области от 4 июля 2016 года № 38. Зарегистрировано Департаментом юстиции Актюбинской области 26 июля 2016 года № 5018
  title:
    rus: О внесении изменений и дополнений в решение районного маслихата от 24 декабря 2015 года № 272 «Об утверждении бюджета Уилского района на 2016-2018 годы»
    kaz: Аудандық мәслихаттың «2016-2018 жылдарға арналған Ойыл ауданының бюджетін бекіту туралы» 2015 жылғы 24 желтоқсандағы № 272 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/105206/rus
