act_code: '77432'
requisite: Решение акима Кобдинского района Актюбинской области от 31 января 2014 года № 5. Зарегистрировано Департаментом юстиции Актюбинской области 14 февраля 2014 года № 3781. Утратило силу решением акима Кобдинского района Актюбинской области от 18 июля 2018 года № 3
title:
  rus: Об образовании избирательных участков на территории Кобдинского района
  kaz: Қобда ауданы аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-01-31
approved_by:
- '153012000003'
version_date:
  kaz: 2014-01-31
  rus: 2014-01-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/77432/kaz/31.01.2014
  rus: https://zan.gov.kz/client/#!/doc/77432/rus/31.01.2014
