act_code: '116061'
requisite: Решение маслихата Шалкарского района Актюбинской области от 30 октября 2017 года № 136. Зарегистрировано Департаментом юстиции Актюбинской области 14 ноября 2017 года № 5692. Утратило силу решением Шалкарского районного маслихата Актюбинской области от 27 октября 2023 года № 112
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Шалкарском районе
  kaz: Шалқар ауданында тұрғын үй көмегін көрсету мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-10-30
approved_by:
- '153014000002'
version_date:
  kaz: 2019-12-06
  rus: 2019-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/116061/kaz/06.12.2019
  rus: https://zan.gov.kz/client/#!/doc/116061/rus/06.12.2019
caused_by:
  code: '137048'
  requisite: Решение Шалкарского районного маслихата Актюбинской области от 6 декабря 2019 года № 395. Зарегистрировано Департаментом юстиции Актюбинской области 9 декабря 2019 года № 6537. Утратило силу решением Шалкарского районного маслихата Актюбинской области от 27 октября 2023 года № 112
  title:
    rus: О внесении изменений в решение Шалкарского районного маслихата от 30 октября 2017 года № 136 «Об определении размера и порядка оказания жилищной помощи в Шалкарском районе»
    kaz: Шалқар аудандық мәслихатының 2017 жылғы 30 қазандағы № 136 «Шалқар ауданында тұрғын үй көмегін көрсету мөлшерін және тәртібін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/137048/rus
