act_code: '116061'
requisite: Решение маслихата Шалкарского района Актюбинской области от 30 октября 2017 года № 136. Зарегистрировано Департаментом юстиции Актюбинской области 14 ноября 2017 года № 5692. Утратило силу решением Шалкарского районного маслихата Актюбинской области от 27 октября 2023 года № 112
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Шалкарском районе
  kaz: Шалқар ауданында тұрғын үй көмегін көрсету мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-10-30
approved_by:
- '153014000002'
version_date:
  kaz: 2017-10-30
  rus: 2017-10-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/116061/kaz/30.10.2017
  rus: https://zan.gov.kz/client/#!/doc/116061/rus/30.10.2017
