act_code: '54061'
requisite: Ақтөбе облысы Байғанин аудандық мәслихатының 2010 жылғы 23 шілдедегі № 141 шешімі. Ақтөбе облысының Байғанин аудандық Әділет басқармасында 2010 жылғы 19 тамызда № 3-4-102 тіркелді. Күші жойылды - Ақтөбе облысы Байғанин аудандық мәслихатының 2011 жылғы 28 наурыздағы № 179 шешімімен
title:
  rus: Ауданның ауылдық елді мекендеріне 2010 жылы жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына қолдау көрсету туралы
  kaz: Ауданның ауылдық елді мекендеріне 2010 жылы жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына қолдау көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-23
approved_by:
- '153005000002'
version_date:
  kaz: 2010-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/54061/kaz/23.07.2010
