act_code: '206413'
requisite: Решение Хромтауского районного маслихата Актюбинской области от 27 декабря 2024 года № 277
title:
  rus: Об утверждении бюджета Акжарского сельского округа на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Ақжар ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '153013000002'
version_date:
  kaz: 2024-12-27
  rus: 2024-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/206413/kaz/27.12.2024
  rus: https://zan.gov.kz/client/#!/doc/206413/rus/27.12.2024
