act_code: '56507'
requisite: Решение маслихата города Актобе Актюбинской области от 22 декабря 2010 года № 301. Зарегистрировано Управлением юстиции города Актобе Актюбинской области 10 января 2011 года № 3-1-147. Утратило силу в связи истечением срока действия - письмо маслихата города Актобе Актюбинской области от 1 марта 2012 года № 01-1/465
title:
  rus: О бюджете города Актобе на 2011-2013 годы
  kaz: 2011-2013 жылдарға арналған Ақтөбе қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-22
approved_by:
- '153002000002'
version_date:
  kaz: 2011-01-28
  rus: 2011-01-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/56507/kaz/28.01.2011
  rus: https://zan.gov.kz/client/#!/doc/56507/rus/28.01.2011
caused_by:
  code: '57255'
  requisite: Решение маслихата города Актобе Актюбинской области от 28 января 2011 года № 324. Зарегистрировано Управлением юстиции города Актобе Актюбинской области 14 февраля 2011 года № 3-1-150. Утратило силу в связи истечением срока действия - письмо маслихата города Актобе Актюбинской области от 1 марта 2012 года № 01-1/465
  title:
    rus: О внесении изменений и дополнений в решение маслихата города Актобе от 22 декабря 2010 года № 301 "О бюджете города Актобе на 2011-2013 годы"
    kaz: '"2011-2013 жылдарға арналған Ақтөбе қаласының бюджеті туралы" Ақтөбе қалалық мәслихатының 2010 жылғы 22 желтоқсандағы № 301 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/57255/rus
