act_code: '137755'
requisite: Решение Алгинского районного маслихата Актюбинской области от 25 декабря 2019 года № 323. Зарегистрировано Департаментом юстиции Актюбинской области 27 декабря 2019 года № 6634
title:
  rus: Об утверждении Алгинского районного бюджета на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Алға аудандық бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-25
approved_by:
- '153004000002'
version_date:
  kaz: 2020-10-28
  rus: 2020-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/137755/kaz/28.10.2020
  rus: https://zan.gov.kz/client/#!/doc/137755/rus/28.10.2020
caused_by:
  code: '148116'
  requisite: Решение Алгинского районного маслихата Актюбинской области от 28 октября 2020 года № 431. Зарегистрировано Департаментом юстиции Актюбинской области 30 октября 2020 года № 7567
  title:
    rus: О внесении изменений и дополнения в решение Алгинского районного маслихата от 25 декабря 2019 года № 323 «Об утверждении Алгинского районного бюджета на 2020-2022 годы»
    kaz: Алға аудандық мәслихатының 2019 жылғы 25 желтоқсандағы № 323 «2020-2022 жылдарға арналған Алға аудандық бюджетін бекіту туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/148116/rus
