act_code: '62718'
requisite: Решение маслихата Мугалжарского района Актюбинской области от 21 декабря 2011 года № 286. Зарегистрировано Департаментом юстиции Актюбинской области 16 января 2012 года № 3-9-160. Утратило силу решением маслихата Мугалжарского района от 24 января 2013 года № 73
title:
  rus: О районном бюджете на 2012-2014 годы
  kaz: 2012-2014 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-21
approved_by:
- '153009000002'
version_date:
  kaz: 2012-05-02
  rus: 2012-05-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/62718/kaz/02.05.2012
  rus: https://zan.gov.kz/client/#!/doc/62718/rus/02.05.2012
caused_by:
  code: '65475'
  requisite: Решение маслихата Мугалжарского района Актюбинской области от 2 мая 2012 года № 32. Зарегистрировано Департаментом юстиции Актюбинской области 14 мая 2012 года № 3-9-169. Утратило силу решением маслихата Мугалжарского района от 24 января 2013 года № 73
  title:
    rus: О внесении изменений и дополнений в решение районного маслихата от 21 декабря 2011 года № 286 "О районном бюджете на 2012-2014 годы"
    kaz: Аудандық мәслихаттың 2011 жылғы 21 желтоқсандағы № 286 "2012-2014 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/65475/rus
