act_code: '50085'
requisite: Ақтөбе облысы Қобда аудандық мәслихатының 2009 жылғы 25 желтоқсандағы N 117 шешімі. Ақтөбе облысы Қобда ауданының Әділет басқармасында 2010 жылдың 21 қаңтарда N 3-7-82 тіркелді. Күші жойылды - Ақтөбе облысы Қобда аудандық мәслихатының 2010 жылғы 24 желтоқсандағы № 183 шешімімен
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '153012000002'
version_date:
  kaz: 2009-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/50085/kaz/25.12.2009
