act_code: '71110'
requisite: Решение акима Айтекебийского района Актюбинской области от 19 февраля 2013 года № 1. Зарегистрировано Департаментом юстиции Актюбинской области 21 февраля 2013 года № 3537
title:
  rus: Об образовании избирательных участков по Айтекебийскому району
  kaz: Әйтеке би ауданы бойынша сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-02-19
approved_by:
- '153003000003'
version_date:
  kaz: 2013-02-19
  rus: 2013-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/71110/kaz/19.02.2013
  rus: https://zan.gov.kz/client/#!/doc/71110/rus/19.02.2013
