act_code: '40473'
requisite: Ақтөбе облысы Әйтеке би ауданы Басқұдық ауылы әкімінің 2008 жылғы 25 маусымдағы N 1 шешімі. Ақтөбе облысының Әйтеке би аудандық әділет басқармасында 2008 жылдың 8 шілдеде N 3-2-54 тіркелді
title:
  rus: Көшелерге атау беру туралы
  kaz: Көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-06-25
approved_by:
- '153003006002'
version_date:
  kaz: 2008-06-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/40473/kaz/25.06.2008
