act_code: '40473'
requisite: Ақтөбе облысы Әйтеке би ауданы Басқұдық ауылы әкімінің 2008 жылғы 25 маусымдағы N 1 шешімі. Ақтөбе облысының Әйтеке би аудандық әділет басқармасында 2008 жылдың 8 шілдеде N 3-2-54 тіркелді
title:
  rus: Көшелерге атау беру туралы
  kaz: Көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-06-25
approved_by:
- '153003006002'
version_date:
  kaz: 2017-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/40473/kaz/31.03.2017
caused_by:
  code: '111545'
  requisite: Решение акима Баскудукского сельского округа Айтекебийского района Актюбинской области от 31 марта 2017 года № 3. Зарегистрировано Департаментом юстиции Актюбинской области 13 апреля 2017 года № 5438
  title:
    rus: О внесении изменения в решение акима Баскудукского сельского округа № 1 от 25 июня 2008 года «Көшелерге атау беру туралы»
    kaz: Басқұдық ауылдық округі әкімінің 2008 жылғы 25 маусымдағы № 1 «Көшелерге атау беру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/111545/rus
