act_code: '177749'
requisite: Решение Байганинского районного маслихата Актюбинской области от 29 декабря 2022 года № 193
title:
  rus: Об утверждении бюджета Ащынского сельского округа на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Ащы ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-29
approved_by:
- '153005000002'
version_date:
  kaz: 2023-09-26
  rus: 2023-09-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/177749/kaz/26.09.2023
  rus: https://zan.gov.kz/client/#!/doc/177749/rus/26.09.2023
caused_by:
  code: '186575'
  requisite: Решение Байганинского районного маслихата Актюбинской области от 26 сентября 2023 года № 63
  title:
    rus: О внесении изменения в решение от 29 декабря 2022 года № 193 «Об утверждении бюджета Ащынского сельского округа на 2023-2025 годы»
    kaz: «2023-2025 жылдарға арналған Ащы ауылдық округінің бюджетін бекіту туралы» 2022 жылғы 29 желтоқсандағы № 193 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/186575/rus
