act_code: '198288'
requisite: Решение акима Актогайского сельского округа Актогайского района Павлодарской области от 27 июня 2024 года № 7
title:
  rus: Об установлении публичного сервитута на территории села Актогай Актогайского сельского округа Актогайского района
  kaz: Ақтоғай ауданы Ақтоғай ауылдық округі Ақтоғай ауылы аумағында қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-06-27
approved_by:
- '153014003002'
version_date:
  kaz: 2024-06-27
  rus: 2024-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/198288/kaz/27.06.2024
  rus: https://zan.gov.kz/client/#!/doc/198288/rus/27.06.2024
