act_code: '77974'
requisite: Решение маслихата Иргизского района Актюбинской области от 19 февраля 2014 года № 124. Зарегистрировано Департаментом юстиции Актюбинской области 12 марта 2014 года № 3816. Утратило силу решением Иргизского районного маслихата Актюбинской области от 30 октября 2023 года № 63
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества в Иргизском районе
  kaz: Ырғыз ауданында жергілікті қоғамдастықтың бөлек жиындарын өткізудің қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-02-19
approved_by:
- '153006000002'
version_date:
  kaz: 2019-05-24
  rus: 2019-05-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/77974/kaz/24.05.2019
  rus: https://zan.gov.kz/client/#!/doc/77974/rus/24.05.2019
caused_by:
  code: '132129'
  requisite: Решение Иргизского районного маслихата Актюбинской области от 24 мая 2019 года № 233. Зарегистрировано Департаментом юстиции Актюбинской области 29 мая 2019 года № 6211. Утратило силу решением Иргизского районного маслихата Актюбинской области от 30 октября 2023 года № 63
  title:
    rus: О внесении изменений в решение Иргизского районного маслихата от 19 февраля 2014 года № 124 «Об утверждении Правил проведения раздельных сходов местного сообщества в Иргизском районе»
    kaz: Ырғыз аудандық мәслихатының 2014 жылғы 19 ақпандағы № 124 «Ырғыз ауданында бөлек жергілікті қоғамдастық жиындарын өткізудің қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/132129/rus
