act_code: '50210'
requisite: Решение маслихата Хромтауского района Актюбинской области от 28 декабря 2009 года № 160. Зарегистрировано Управлением юстиции Хромтауского района Актюбинской области 20 января 2010 года № 3-12-109. Утратило силу решением маслихата Хромтауского района Актюбинской области от 28 марта 2011 года № 231
title:
  rus: О бюджете Хромтауского района на 2010-2012 годы
  kaz: 2009-2012 жылдарға арналған Хромтау аудандының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-28
approved_by:
- '153013000002'
version_date:
  kaz: 2010-10-22
  rus: 2010-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/50210/kaz/22.10.2010
  rus: https://zan.gov.kz/client/#!/doc/50210/rus/22.10.2010
caused_by:
  code: '55069'
  requisite: Решение маслихата Хромтауского района Актюбинской области от 22 октября 2010 года № 200. Зарегистрировано Управлением юстиции Хромтауского района Актюбинской области 29 октября 2010 года № 3-12-126. Утратило силу решением маслихата Хромтауского района Актюбинской области от 28 марта 2011 года № 231
  title:
    rus: О внесении изменений и дополнений в решение № 160 районного маслихата от 28 декабря 2009 года "О бюджете Хромтауского района на 2010-2012 годы"
    kaz: Аудандық мәслихаттың 2009 жылғы 28 желтоқсандағы "2010-2012 жылдарға арналған Хромтау ауданының бюджеті туралы" № 160 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/55069/rus
