act_code: '141732'
requisite: Решение Темирского районного маслихата Актюбинской области от 9 апреля 2020 года № 470. Зарегистрировано Департаментом юстиции Актюбинской области 10 апреля 2020 года № 7038
title:
  rus: Об определении категории граждан, расходы которых по плате за пользование жилищем в частном жилищном фонде и арендных домах возлагаются на местный бюджет
  kaz: Жеке тұрғын үй қорындағы және жалға берілетін үйлердегі тұрғынжайды пайдаланғаны үшін төлемақыны төлеу жөніндегі шығыстар үшін жергілікті бюджетке жүктелген азаматтардың санатын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-04-09
approved_by:
- '153010000002'
version_date:
  kaz: 2020-04-09
  rus: 2020-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/141732/kaz/09.04.2020
  rus: https://zan.gov.kz/client/#!/doc/141732/rus/09.04.2020
