act_code: '46053'
requisite: Ақтөбе облысы Қобда аудандық мәслихатының 2009 жылғы 24 сәуірдегі № 88 шешімі. Ақтөбе облысының Қобда аудандық Әділет басқармасында 2009 жылдың 20 мамырда № 3-7-66 тіркелді. Күші жойылды - Ақтөбе облысы Қобда аудандық мәслихатының 2013 жылғы 22 тамыздағы № 115 шешімімен
title:
  rus: Халықтың әлеуметтік әлжуаз санаттарына қосымша әлеуметтік көмек көрсету туралы
  kaz: Халықтың әлеуметтік әлжуаз санаттарына қосымша әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-24
approved_by:
- '153012000002'
version_date:
  kaz: 2013-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/46053/kaz/01.01.2013
