act_code: '42895'
requisite: Решение акима аульного округа Байнассай Мартукского района Актюбинской области от 5 декабря 2008 года № 1. Зарегистрировано управлением юстиции Мартукского района Актюбинской области 23 декабря 2008 года за № 3-8-67
title:
  rus: О присвоении наименований улицам населенных пунктов аульного округа Байнассай
  kaz: Байнассай ауылдық округінің елді мекендерінің көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-05
approved_by:
- '153008007002'
version_date:
  kaz: 2008-12-04
  rus: 2008-12-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/42895/kaz/04.12.2008
  rus: https://zan.gov.kz/client/#!/doc/42895/rus/04.12.2008
