act_code: '206478'
requisite: Решение Кобдинского районного маслихата Актюбинской области от 31 декабря 2024 года № 290
title:
  rus: Об утверждении бюджета Булакского сельского округа на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Бұлақ ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-31
approved_by:
- '153012000002'
version_date:
  kaz: 2024-12-31
  rus: 2024-12-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/206478/kaz/31.12.2024
  rus: https://zan.gov.kz/client/#!/doc/206478/rus/31.12.2024
