act_code: '100264'
requisite: Решение Хромтауского районного маслихата Актюбинской области от 18 февраля 2016 года № 323. Зарегистрировано Департаментом юстиции Актюбинской области 14 марта 2016 года № 4780. Утратило силу решением Хромтауского районного маслихата Актюбинской области от 8 августа 2024 года № 212 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан в Хромтауском районе
  kaz: Хромтау ауданында әлеуметтік көмек көрсету, мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2016-02-18
approved_by:
- '153013000002'
version_date:
  kaz: 2021-03-05
  rus: 2021-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/100264/kaz/05.03.2021
  rus: https://zan.gov.kz/client/#!/doc/100264/rus/05.03.2021
caused_by:
  code: '153465'
  requisite: Решение Хромтауского районного маслихата Актюбинской области от 5 марта 2021 года № 18. Зарегистрировано Департаментом юстиции Актюбинской области 11 марта 2021 года № 8102. Утратило силу решением Хромтауского районного маслихата Актюбинской области от 8 августа 2024 года № 212 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение районного маслихата от 18 февраля 2016 года № 323 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан в Хромтауском районе»
    kaz: Хромтау аудандық мәслихаттың 2016 жылғы 18 ақпандағы № 323 «Хромтау ауданында әлеуметтік көмек көрсету, мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/153465/rus
