act_code: '195133'
requisite: Решение Уилского районного маслихата Актюбинской области от 28 марта 2024 года № 126. Зарегистрировано Департаментом юстиции Актюбинской области 29 марта 2024 года № 8548-04
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2024 год по Уилскому району
  kaz: Ойыл ауданы бойынша 2024 жылға шетелдіктер үшін туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-28
approved_by:
- '153011000002'
version_date:
  kaz: 2024-03-28
  rus: 2024-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/195133/kaz/28.03.2024
  rus: https://zan.gov.kz/client/#!/doc/195133/rus/28.03.2024
