act_code: '58694'
requisite: Решение акима Иргизского сельского округа Иргизского района Актюбинской области от 1 апреля 2011 года № 23. Зарегистрировано Управлением юстиции Иргизского района Актюбинской области 3 мая 2011 года № 3-5-130
title:
  rus: О наименовании улиц села Акши Иргизского сельского округа
  kaz: Ырғыз ауылдық округі Ақши ауылының көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-04-01
approved_by:
- '153006006001'
version_date:
  kaz: 2011-04-01
  rus: 2011-04-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/58694/kaz/01.04.2011
  rus: https://zan.gov.kz/client/#!/doc/58694/rus/01.04.2011
