act_code: '151308'
requisite: Решение Мугалжарского районного маслихата Актюбинской области от 30 декабря 2020 года № 545. Зарегистрировано Департаментом юстиции Актюбинской области 5 января 2021 года № 7909
title:
  rus: Об утверждении бюджета Егиндыбулакского сельского округа на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Егіндібұлақ ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-30
approved_by:
- '153009000002'
version_date:
  kaz: 2021-12-06
  rus: 2021-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/151308/kaz/06.12.2021
  rus: https://zan.gov.kz/client/#!/doc/151308/rus/06.12.2021
caused_by:
  code: '161845'
  requisite: Решение Мугалжарского районного маслихата Актюбинской области от 6 декабря 2021 года № 109
  title:
    rus: О внесении изменений в решение Мугалжарского районного маслихата от 30 декабря 2020 года № 545 «Об утверждении бюджета Егиндыбулакского сельского округа на 2021-2023 годы»
    kaz: Мұғалжар аудандық мәслихатының 2020 жылғы 30 желтоқсандағы № 545 «2021-2023 жылдарға арналған Егіндібұлақ  ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/161845/rus
