act_code: '205378'
requisite: Решение Темирского районного маслихата Актюбинской области от 27 декабря 2024 года № 281
title:
  rus: Об утверждении бюджета Кенкиякского сельского округа на 2025–2027 годы
  kaz: 2025–2027 жылдарға арналған Кеңқияқ ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '153010000002'
version_date:
  kaz: 2025-07-25
  rus: 2025-07-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/205378/kaz/25.07.2025
  rus: https://zan.gov.kz/client/#!/doc/205378/rus/25.07.2025
caused_by:
  code: '212896'
  requisite: Решение Темирского районного маслихата Актюбинской области от 25 июля 2025 года № 355
  title:
    rus: О внесении изменений в решение Темирского районного маслихата от 27 декабря 2024 года № 281 «Об утверждении бюджета Кенкиякского сельского округа на 2025–2027 годы»
    kaz: Темір аудандық мәслихатының 2024 жылғы 27 желтоқсандағы № 281 «2025–2027 жылдарға арналған Кеңқияқ ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/212896/rus
