act_code: '42739'
requisite: 'Решение от 09.11.2008 №27, Акимат Ушкудукского сельского округа. '
title:
  rus: Көшелерге атау беру туралы
  kaz: Көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-11-10
approved_by:
- '153004006001'
version_date:
  kaz: 2015-11-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/42739/kaz/10.11.2015
caused_by:
  code: '96070'
  requisite: Решение от 10.11.2015 №60, Акимат Ушкудукского сельского округа. Зарегистрировано Департаментом юстиции Актюбинской области 03 декабря 2015 года № 4620
  title:
    rus: О внесении изменений в решение от 10 ноября 2008 года № 27 "Көшелерге атау беру туралы"
    kaz: '"Көшелерге атау беру туралы" 2008 жылдың 10 қарашадағы № 27 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/96070/rus
