act_code: '54249'
requisite: Ақтөбе облысы Мәртөк аудандық мәслихатының 2010 жылғы 27 шілдедегі № 174 шешімі. Ақтөбе облысы Мәртөк ауданының Әділет басқармасында 2010 жылғы 1 қыркүйекте № 3-8-118 тіркелді. Күші жойылды - Ақтөбе облысы Мәртөк аудандық мәслихатының 2013 жылғы 28 наурыздағы № 63 шешімімен
title:
  rus: Мәртөк ауданының тұрғындарына коммуналдық қызметтерді тұтынғаны үшін және телефонға абоненттік төлемақы тарифінің өсуіне байланысты шығындарды өтеуге арналғын тұрғын үй көмегін беру Ережесін бекіту туралы
  kaz: Мәртөк ауданының тұрғындарына коммуналдық қызметтерді тұтынғаны үшін және телефонға абоненттік төлемақы тарифінің өсуіне байланысты шығындарды өтеуге арналғын тұрғын үй көмегін беру Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2010-07-27
approved_by:
- '153008000002'
version_date:
  kaz: 2010-07-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/54249/kaz/27.07.2010
