act_code: '69831'
requisite: Решение Мугалжарского районного маслихата Актюбинской области от 28 декабря 2012 года № 70. Зарегистрировано Департаментом юстиции Актюбинской области 9 января 2013 года № 3485. Утратило силу решением Мугалжарского районного маслихата Актюбинской области от 20 февраля 2014 года № 146
title:
  rus: О районном бюджете на 2013-2015 годы
  kaz: 2013-2015 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-28
approved_by:
- '153009000002'
version_date:
  kaz: 2013-04-26
  rus: 2013-04-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/69831/kaz/26.04.2013
  rus: https://zan.gov.kz/client/#!/doc/69831/rus/26.04.2013
caused_by:
  code: '72711'
  requisite: Решение маслихата Мугалжарского района Актюбинской области от 26 апреля 2013 года № 79. Зарегистрировано Департаментом юстиции Актюбинской области 23 мая 2013 года № 3593. Утратило силу решением Мугалжарского районного маслихата Актюбинской области от 20 февраля 2014 года № 146
  title:
    rus: О внесении изменений и дополнений в решение районного маслихата от 28 декабря 2012 года № 70 "О районном бюджете на 2013-2015 годы"
    kaz: Аудандық мәслихаттың 2012 жылғы 28 желтоқсандағы № 70 "2013-2015 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/72711/rus
