act_code: '205836'
requisite: Решение Уилского районного маслихата Актюбинской области от 25 декабря 2024 года № 215
title:
  rus: Об утверждении бюджетов сельских округов Уилского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Ойыл ауданының ауылдық округтерінің бюджеттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '153011000002'
version_date:
  kaz: 2025-02-25
  rus: 2025-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/205836/kaz/25.02.2025
  rus: https://zan.gov.kz/client/#!/doc/205836/rus/25.02.2025
caused_by:
  code: '207605'
  requisite: Решение Уилского районного маслихата Актюбинской области от 25 февраля 2025 года № 225
  title:
    rus: О внесении изменений и дополнения в решение Уилского районного маслихата Актюбинской области от 25 декабря 2024 года № 215 «Об утверждении бюджетов сельских округов Уилского района на 2025-2027 годы»
    kaz: Ақтөбе облысы Ойыл аудандық мәслихатының 2024 жылғы 25 желтоқсандағы № 215 «2025-2027 жылдарға арналған Ойыл ауданының ауылдық округтерінің бюджеттерін бекіту туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/207605/rus
