act_code: '65731'
requisite: Решение акима Егиндибулакского сельского округа Мугалжарского района Актюбинской области от 4 мая 2012 года № 4. Зарегистрировано Управлением юстиции Мугалжарского района Актюбинской области 28 мая 2012 года № 3-9-171
title:
  rus: О присвоении наименований безымянным улицам села Булакты Егиндыбулакского сельского округа Мугалжарского района
  kaz: Мұғалжар ауданы Егіндібұлақ ауылдық округі Бұлақты ауылының атаусыз көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-05-04
approved_by:
- '153009007002'
version_date:
  kaz: 2012-05-04
  rus: 2012-05-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/65731/kaz/04.05.2012
  rus: https://zan.gov.kz/client/#!/doc/65731/rus/04.05.2012
