act_code: '60061'
requisite: Решение маслихата Кобдинского района Актюбинской области от 27 июля 2011 года № 217. Зарегистрировано Департамнтом юстиции Актюбинской области 16 августа 2011 года № 3-7-124. Утратило силу решением маслихата Хобдинского района Актюбинской области от 22 августа 2013 года № 115
title:
  rus: Об оказании социальной помощи туберкулезным больным гражданам получающих амбулаторное лечение Кобдинского района
  kaz: Қобда ауданы бойынша амбулаториялық емделуде жүрген туберкулез ауруымен ауыратын азаматтарға әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-07-27
approved_by:
- '153012000002'
version_date:
  kaz: 2011-07-27
  rus: 2011-07-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/60061/kaz/27.07.2011
  rus: https://zan.gov.kz/client/#!/doc/60061/rus/27.07.2011
