act_code: '65594'
requisite: Решение акима Кайндинского сельского округа Темирского района Актюбинской области от 17 апреля 2012 года № 7. Зарегистрировано Управлением юстиции Темирского района Актюбинской области 14 мая 2012 года № 3-10-166
title:
  rus: О наименований составных частей Каиндинского сельского округа
  kaz: Қайыңды ауылдық округінің құрамды бөліктерін атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-04-17
approved_by:
- '153010005002'
version_date:
  kaz: 2017-02-09
  rus: 2017-02-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/65594/kaz/09.02.2017
  rus: https://zan.gov.kz/client/#!/doc/65594/rus/09.02.2017
caused_by:
  code: '109963'
  requisite: Решение акима Каиндинского сельского округа Темирского района Актюбинской области от 9 февраля 2017 года № 4. Зарегистрировано Департаментом юстиции Актюбинской области 23 февраля 2017 года № 5270
  title:
    rus: О внесении изменений в решение акима Каиндинского сельского округа от 17 апреля 2012 года № 7 «О наименований составных частей Каиндинского сельского округа»
    kaz: Қайыңды селолық округі әкімінің 2012 жылғы 17 сәуірдегі № 7 «Қайыңды селолық округінің құрамды бөліктерін атау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/109963/rus
