act_code: '228700'
requisite: Решение Каргалинского районного маслихата Актюбинской области от 6 августа 2026 года № 493
title:
  rus: О признании утратившим силу решения Каргалинского районного маслихата от 21 апреля 2026 года № 448 «Об оказании дополнительной социальной помощи отдельным категориям нуждающихся граждан Каргалинского района в связи с 40-й годовщиной ликвидации последствий катастрофы на Чернобыльской атомной электростанции»
  kaz: Қарғалы аудандық мәслихатының 2026 жылғы 21 сәуірдегі № 448 «Қарғалы  ауданының кейбір әлеуметтік жағынан мұқтаж санаттағы азаматтарына Чернобыль атом электр станциясындағы апаттың салдарын жоюдың 40-жылдығына байланысты қосымша әлеуметтік көмек көрсету туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-08-06
approved_by:
- '153007000002'
version_date:
  kaz: 2026-08-06
  rus: 2026-08-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/228700/kaz/06.08.2026
  rus: https://zan.gov.kz/client/#!/doc/228700/rus/06.08.2026
