act_code: '50412'
requisite: Ақтөбе облысы Мәртөк аудандық мәслихатының 2009 жылғы 24 желтоқсандағы N 143 шешімі. Ақтөбе облысы Мәртөк ауданының Әділет басқармасында 2010 жылғы 26 қаңтарда N 3-8-103 тіркелді. Күші жойылды - Ақтөбе облысы Мәртөк аудандық мәслихатының 2011 жылғы 30 наурыздағы № 228 шешімімен
title:
  rus: 2010-2012 жылдарға арналған Мәртөк ауданының бюджеті туралы
  kaz: 2010-2012 жылдарға арналған Мәртөк ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-24
approved_by:
- '153008000002'
version_date:
  kaz: 2010-10-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/50412/kaz/27.10.2010
caused_by:
  code: '55114'
  requisite: Ақтөбе облысы Мәртөк аудандық мәслихатының 2010 жылғы 27 қазандағы № 195 шешімі. Ақтөбе облысы Мәртөк ауданының Әділет басқармасында 2010 жылғы 29 қазанда № 3-8-120 тіркелді. Күші жойылды - Ақтөбе облысы Мәртөк аудандық мәслихатының 2011 жылғы 30 наурыздағы № 228 шешімімен
  title:
    rus: Аудандық мәслихаттың 2009 жылғы 24 желтоқсандағы № 143 "2010-2012 жылдарға арналған Мәртөк ауданының бюджеті туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Аудандық мәслихаттың 2009 жылғы 24 желтоқсандағы № 143 "2010-2012 жылдарға арналған Мәртөк ауданының бюджеті туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/55114/rus
