act_code: '42896'
requisite: Решение акима Курмансайского сельского округа Мартукского района Актюбинской области от 2 декабря 2008 года № 1. Зарегистрировано Управлением юстиции Мартукского района Актюбинской области 23 декабря 2008 года за № 3-8-68
title:
  rus: О присвоении наименований улицам населенных пунктов Курмансайского сельского округа
  kaz: Құрмансай ауылдық округі елді мекендерінің көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-02
approved_by:
- '153008013002'
version_date:
  kaz: 2016-08-22
  rus: 2016-08-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/42896/kaz/22.08.2016
  rus: https://zan.gov.kz/client/#!/doc/42896/rus/22.08.2016
caused_by:
  code: '106423'
  requisite: Решение акима Курмансайского сельского округа Мартукского района Актюбинской области от 22 августа 2016 года № 5. Зарегистрировано Департаментом юстиции Актюбинской области 21 сентября 2016 года № 5080
  title:
    rus: О внесении изменений в решение акима Курмансайского сельского округа от 02 декабря 2008 года № 1 «О присвоении наименования улицам населенных пунктов Курмансайского сельского округа»
    kaz: «Құрмансай ауылдық округі елді мекендерінің көшелеріне атау беру туралы» Құрмансай ауылдық округі әкімінің 2008 жылғы 02 желтоқсандағы № 1 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/106423/rus
