act_code: '7473'
requisite: Решение акима Актюбинской области от 9 июня 2000 года № 83. Зарегистрировано Управлением юстиции Актюбинской области 28 ноября 2000 года № 810
title:
  rus: Об утверждении уполномоченных органов Акима области по управлению коммунальными государственными предприятиями и учреждениями и осуществляющих по отношению к ним функции субъекта права государственной собственности
  kaz: Коммуналдық мемлекеттік кәсіпорындарды, мекемелерді басқару және оларға қатысты мемлекеттік меншік құқығы субъектісі функциясын жүзеге асыру жөніндегі облыс әкімінің өкілетті органдарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-06-08
approved_by:
- '153000000003'
version_date:
  kaz: 2000-06-08
  rus: 2000-06-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/7473/kaz/08.06.2000
  rus: https://zan.gov.kz/client/#!/doc/7473/rus/08.06.2000
