act_code: '146071'
requisite: Решение Алгинского районного маслихата Актюбинской области от 26 августа 2020 года № 404. Зарегистрировано Департаментом юстиции Актюбинской области 3 сентября 2020 года № 7388
title:
  rus: Об утверждении порядка и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Алгинского района
  kaz: Алға ауданының ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына бюджет қаражаты есебінен коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету тәртібін және мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-08-26
approved_by:
- '153004000002'
version_date:
  kaz: 2024-07-30
  rus: 2024-07-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/146071/kaz/30.07.2024
  rus: https://zan.gov.kz/client/#!/doc/146071/rus/30.07.2024
caused_by:
  code: '199428'
  requisite: Решение Алгинского районного маслихата Актюбинской области от 30 июля 2024 года № 186. Зарегистрировано Департаментом юстиции Актюбинской области 2 августа 2024 года № 8614-04
  title:
    rus: О внесении изменения в решение Алгинского районного маслихата от 26 августа 2020 года № 404 «Об утверждении порядка и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Алгинского района»
    kaz: Алға аудандық мәслихатының 2020 жылғы 26 тамыздағы № 404 «Алға ауданының ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына бюджет қаражаты есебінен коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету тәртібін және мөлшерін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/199428/rus
