act_code: '163570'
requisite: Решение Алгинского районного маслихата Актюбинской области от 29 декабря 2021 года № 125
title:
  rus: Об утверждении бюджета Бестамакского сельского округа на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Бестамақ ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-29
approved_by:
- '153004000002'
version_date:
  kaz: 2022-12-15
  rus: 2022-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/163570/kaz/15.12.2022
  rus: https://zan.gov.kz/client/#!/doc/163570/rus/15.12.2022
caused_by:
  code: '175923'
  requisite: Решение Алгинского районного маслихата Актюбинской области от 15 декабря 2022 года № 241
  title:
    rus: О внесении изменений в решение Алгинского районного маслихата от 29 декабря 2021 года № 125 «Об утверждении бюджета Бестамакского сельского округа на 2022-2024 годы»
    kaz: Алға аудандық мәслихатының 2021 жылғы 29 желтоқсандағы № 125 «2022-2024 жылдарға арналған Бестамақ ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/175923/rus
