act_code: '51375'
requisite: Ақтөбе облысы Мұғалжар ауданы Құмжарған ауылдық округі әкімінің 2010 жылғы 17 ақпандағы N 5 шешімі. Ақтөбе облысының Мұғалжар аудандық әділет басқармасында 2010 жылдың 17 наурызда N 3-9-118 тіркелді
title:
  rus: Мұғалжар ауданы Құмжарған ауылдық округі Бірлік ауылындағы көшелер атауларын өзгерту туралы
  kaz: Мұғалжар ауданы Құмжарған ауылдық округі Бірлік ауылындағы көшелер атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-17
approved_by:
- '153009011002'
version_date:
  kaz: 2010-02-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/51375/kaz/17.02.2010
