act_code: '220547'
requisite: Решение Хромтауского районного маслихата Актюбинской области от 24 декабря 2025 года № 430
title:
  rus: Об утверждении бюджета Коктюбинского сельского округа на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған Көктөбе ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-24
approved_by:
- '153013000002'
version_date:
  kaz: 2026-07-08
  rus: 2026-07-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/220547/kaz/08.07.2026
  rus: https://zan.gov.kz/client/#!/doc/220547/rus/08.07.2026
caused_by:
  code: '227600'
  requisite: Решение Хромтауского районного маслихата Актюбинской области от 8 июля 2026 года № 501
  title:
    rus: О внесении изменений в решение Хромтауского районного маслихата от 24 декабря 2025 года № 430 «Об утверждении бюджета Коктюбинского сельского округа на 2026-2028 годы»
    kaz: Хромтау аудандық мәслихатының 2025 жылғы 24 желтоқсандағы № 430 «2026-2028 жылдарға арналған Көктөбе ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/227600/rus
