act_code: '221394'
requisite: Решение Темирского районного маслихата Актюбинской области от 15 января 2026 года № 416
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2026 год по Темирскому району
  kaz: Темір ауданы бойынша 2026 жылға шетелдіктер үшін туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-01-15
approved_by:
- '153010000002'
version_date:
  kaz: 2026-01-15
  rus: 2026-01-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/221394/kaz/15.01.2026
  rus: https://zan.gov.kz/client/#!/doc/221394/rus/15.01.2026
