act_code: '162230'
requisite: Решение Мартукского районного маслихата Актюбинской области от 23 декабря 2021 года № 81. Зарегистрировано в Министерстве юстиции Республики Казахстан 24 декабря 2021 года № 25993
title:
  rus: Об утверждении Мартукского районного бюджета на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Мәртөк аудандық бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-23
approved_by:
- '153008000002'
version_date:
  kaz: 2022-06-09
  rus: 2022-06-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/162230/kaz/09.06.2022
  rus: https://zan.gov.kz/client/#!/doc/162230/rus/09.06.2022
caused_by:
  code: '168928'
  requisite: Решение Мартукского районного маслихата Актюбинской области от 9 июня 2022 года № 119
  title:
    rus: О внесении изменений в решение Мартукского районного маслихата от 23 декабря 2021 года № 81 «Об утверждении Мартукского районного бюджета на 2022-2024 годы»
    kaz: Мәртөк аудандық мәслихатының 2021 жылғы 23 желтоқсандағы № 81 «2022-2024 жылдарға арналған Мәртөк аудандық бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/168928/rus
