act_code: '43703'
requisite: Ақтөбе облысы Шалқар аудандық әкімдігінің 2008 жылғы 24 желтоқсандағы N 10 шешімі. Ақтөбе облысының Шалқар аудандық Әділет басқармасында 2009 жылдың 23 қаңтарда N 3-13-92 тіркелді. Күші жойылды - Ақтөбе облысы Шалқар аудандық әкімдігінің 2009 жылғы 3 маусымдағы № 3 шешімімен
title:
  rus: 1992 жылы туылған азаматтарды Шалқар аудандық қорғаныс істер бөлімінің шақыру участкесіне тіркеуді жүргізу туралы
  kaz: 1992 жылы туылған азаматтарды Шалқар аудандық қорғаныс істер бөлімінің шақыру участкесіне тіркеуді жүргізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-24
approved_by:
- '153014000001'
version_date:
  kaz: 2008-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/43703/kaz/24.12.2008
