act_code: '43963'
requisite: Решение маслихата Каргалинского района Актюбинской области от 22 декабря 2008 года N 99. Зарегистрировано Управлением юстиции Каргалинского района Актюбинской области 29 января 2009 года N 3-6-77. Утратило силу решением маслихата Каргалинского района Актюбинской области от 27 июля 2010 года № 225
title:
  rus: Об утверждении Правил содержания собак и кошек по Каргалинскому району
  kaz: Қарғалы ауданы бойынша иттер мен мысықтарды ұстау ережелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-22
approved_by:
- '153007000002'
version_date:
  kaz: 2009-07-22
  rus: 2009-07-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/43963/kaz/22.07.2009
  rus: https://zan.gov.kz/client/#!/doc/43963/rus/22.07.2009
caused_by:
  code: '47612'
  requisite: Решение Каргалинского районного маслихата Актюбинской области от 22 июля 2009 года N 156. Зарегистрировано Управлением юстиции Каргалинского района Актюбинской области 2 сентября 2009 года N 3-6-88. Утратило силу решением маслихата Каргалинского района Актюбинской области от 27 июля 2010 года № 225
  title:
    rus: О внесении изменений в решение Каргалинского районного маслихата от 22 сентября 2008 года № 98 "Об утверждении Правил содержания собак и кошек по Каргалинскому району"
    kaz: Қарғалы ауданы мәслихатының 2008 жылғы 22 желтоқсандағы № 98 "Қарғалы ауданы бойынша иттер мен мысықтарды ұстау Ережелерін бекіту туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/47612/rus
