act_code: '47478'
requisite: Ақтөбе облысы Мәртөк аудандық мәслихатының 2009 жылғы 24 шілдедегі N 128 шешімі. Ақтөбе облысы Мәртөк аудандық әділет басқармасында 2009 жылғы 18 тамызда N 3-8-96 тіркелді. Күші жойылды - Ақтөбе облысы Мәртөк аудандық мәслихатының 2012 жылғы 25 қазандағы № 43 шешімімен
title:
  rus: Ауданда бейбіт жиналыстар, митингілер, шерулер, пикеттер мен демонстрациялар өткізу тәртібін қосымша реттеу туралы
  kaz: Ауданда бейбіт жиналыстар, митингілер, шерулер, пикеттер мен демонстрациялар өткізу тәртібін қосымша реттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-07-24
approved_by:
- '153008000002'
version_date:
  kaz: 2011-07-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/47478/kaz/22.07.2011
caused_by:
  code: '60116'
  requisite: Решение маслихата Мартукского района Актюбинской области от 22 июля 2011 года № 239. Зарегистрировано Департаментом юстиции Актюбинской области 19 августа 2011 года № 3-8-135. Утратило силу решением маслихата Мартукского района Актюбинской области от 25 октября 2012 года № 43
  title:
    rus: О внесении изменения в решение районного маслихата от 24 июля 2009 года № 128 "О дополнительном регламентировании порядка проведения мирных собраний, митингов, шествий, пикетов и демонстраций в районе"
    kaz: Аудандық мәслихаттың 2009 жылғы 24 шілдедегі № 128 "Ауданда бейбіт жиналыстар, митингілер, шерулер, пикеттер, мен демонстрациялар өткізу тәртібін қосымша реттеу туралы шешіміне өзгеріс енгізу туралы"
  link: https://zan.gov.kz/client/#!/doc/60116/rus
