act_code: '147708'
requisite: 'Решение Шалкарского районного маслихата Актюбинской области от 14 октября 2020 года № 533. Зарегистрировано Департаментом юстиции Актюбинской области 19 октября 2020 года № 7545. Утратило силу решением Шалкарского районного маслихата Актюбинской области от 28 апреля 2025 года № 432 (вводится в действие со дня его первого официального опубликования) '
title:
  rus: Об утверждении методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Шалкарского районного маслихата»
  kaz: «Шалқар аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-10-14
approved_by:
- '153014000002'
version_date:
  kaz: 2022-04-07
  rus: 2022-04-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/147708/kaz/07.04.2022
  rus: https://zan.gov.kz/client/#!/doc/147708/rus/07.04.2022
caused_by:
  code: '166259'
  requisite: 'Решение Шалкарского районного маслихата Актюбинской области от 7 апреля 2022 года № 187. Утратило силу решением Шалкарского районного маслихата Актюбинской области от 28 апреля 2025 года № 432 (вводится в действие со дня его первого официального опубликования) '
  title:
    rus: О внесении изменений в решение Шалкарского районного маслихата от 14 октября 2020 года № 533 «Об утверждении методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Шалкарского районного маслихата»
    kaz: Шалқар аудандық мәслихатының 2020 жылғы 14 қазандағы № 533 «Шалқар аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/166259/rus
