act_code: '1305'
requisite: Решение акима Актюбинской области от 29 июля 1998 года № 115. Зарегистрировано Управлением юстиции Актюбинской области 24 сентября 1998 года № 44. Утратило силу в связи с истечением срока применения – письмо акимата Актюбинской области от 21 декабря 2004 года № 08-3/2691
title:
  rus: Об итогах социально-экономического развития и выполнения стратегического плана области за І полугодие 1998 года
  kaz: Облыстың әлеуметтік-экономикалық дамуының және стратегиялық Жоспарының 1998 жылғы бірінші жарты жылдықтағы орындалу қортындысы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-07-28
approved_by:
- '153000000003'
version_date:
  kaz: 1998-07-28
  rus: 1998-07-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/1305/kaz/28.07.1998
  rus: https://zan.gov.kz/client/#!/doc/1305/rus/28.07.1998
