act_code: '167752'
requisite: Решение акима Кумтогайского сельского округа  Иргизского района Актюбинской области от 4 мая 2022 года № 3. Зарегистрировано в Министерстве юстиции Республики Казахстан 6 мая 2022 года № 27932. Утратило силу решением акима Кумтогайского сельского округа Иргизского района Актюбинской области от 23 сентября 2022 года № 5
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-05-04
approved_by:
- '153006002002'
version_date:
  kaz: 2022-05-04
  rus: 2022-05-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/167752/kaz/04.05.2022
  rus: https://zan.gov.kz/client/#!/doc/167752/rus/04.05.2022
