act_code: '51265'
requisite: Решение маслихата Каргалинского района Актюбинской области от 23 февраля 2010 года N 191. Зарегистрировано Управлением юстиции Каргалинского района Актюбинской области 15 марта 2010 года N 3-6-98. Утратило силу решением маслихата Каргалинского района Актюбинской области от 27 июля 2010 года № 225
title:
  rus: Об оказании единовременной социальной помощи в честь празднования 65-летия Победы в Великой Отечественной войне
  kaz: Ұлы Отан соғысындағы Жеңістің 65-жылдық мерекесі құрметіне бір жолғы әлеуметтік жәрдем көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-23
approved_by:
- '153007000002'
version_date:
  kaz: 2010-02-23
  rus: 2010-02-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/51265/kaz/23.02.2010
  rus: https://zan.gov.kz/client/#!/doc/51265/rus/23.02.2010
