act_code: '137669'
requisite: Решение Иргизского районного маслихата Актюбинской области от 25 декабря 2019 года № 261. Зарегистрировано Департаментом юстиции Актюбинской области 27 декабря 2019 года № 6614. Утратило силу решением Иргизского районного маслихата Актюбинской области от 15 сентября 2023 года № 55
title:
  rus: О предоставлении социальной поддержки специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, государственным служащим аппаратов акимов сел, поселков, сельских округов, прибывшим для работы и проживания в сельские населенные пункты Иргизского района
  kaz: Ырғыз ауданының ауылдық елді мекендеріне жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға, ауылдар, кенттер, ауылдық округтер әкімдері аппараттарының мемлекеттік қызметшілеріне әлеуметтік қолдау көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-25
approved_by:
- '153006000002'
version_date:
  kaz: 2020-08-20
  rus: 2020-08-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/137669/kaz/20.08.2020
  rus: https://zan.gov.kz/client/#!/doc/137669/rus/20.08.2020
caused_by:
  code: '145887'
  requisite: Решение Иргизского районного маслихата Актюбинской области от 20 августа 2020 года № 327. Зарегистрировано Департаментом юстиции Актюбинской области 28 августа 2020 года № 7366. Утратило силу решением Иргизского районного маслихата Актюбинской области от 15 сентября 2023 года № 55
  title:
    rus: О внесений изменений в решение Иргизского районного маслихата от 25 декабря 2019 года № 261 «О предоставлении социальной поддержки специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса прибывшим для работы и проживания в сельские населенные пункты Иргизского района на 2020 год»
    kaz: Ырғыз аудандық мәслихатының 2019 жылғы 25 желтоқсандағы № 261 «Ырғыз ауданының ауылдық елді мекендеріне жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға 2020 жылға әлеуметтік қолдау көрсету туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/145887/rus
