act_code: '137669'
requisite: Решение Иргизского районного маслихата Актюбинской области от 25 декабря 2019 года № 261. Зарегистрировано Департаментом юстиции Актюбинской области 27 декабря 2019 года № 6614. Утратило силу решением Иргизского районного маслихата Актюбинской области от 15 сентября 2023 года № 55
title:
  rus: О предоставлении социальной поддержки специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, государственным служащим аппаратов акимов сел, поселков, сельских округов, прибывшим для работы и проживания в сельские населенные пункты Иргизского района
  kaz: Ырғыз ауданының ауылдық елді мекендеріне жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға, ауылдар, кенттер, ауылдық округтер әкімдері аппараттарының мемлекеттік қызметшілеріне әлеуметтік қолдау көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-25
approved_by:
- '153006000002'
version_date:
  kaz: 2021-11-12
  rus: 2021-11-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/137669/kaz/12.11.2021
  rus: https://zan.gov.kz/client/#!/doc/137669/rus/12.11.2021
caused_by:
  code: '160281'
  requisite: Решение Иргизского районного маслихата Актюбинской области от 12 ноября 2021 года № 66
  title:
    rus: О внесении изменения в решение районного маслихата от 25 декабря 2019 года № 261 «О предоставлении социальной поддержки специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, государственным служащим аппаратов акимов сел, поселков, сельских округов, прибывшим для работы и проживания в сельские населенные пункты Иргизского района»
    kaz: Аудандық мәслихаттың 2019 жылғы 25 желтоқсандағы № 261 «Ырғыз ауданының ауылдық елді мекендеріне жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға, ауылдар, кенттер, ауылдық округтер әкімдері аппараттарының мемлекеттік қызметшілеріне әлеуметтік қолдау көрсету туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/160281/rus
