act_code: '82921'
requisite: Решение от 12.08.2014 №25, Акимат Темирского городского округа. Зарегистрировано Департаментом юстиции Актюбинской области 4 сентября 2014 года № 4021. Утратил силу решением акима города Темир Темирского района Актюбинской области от 11.11.2015 № 38
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-08-13
approved_by:
- '153010001001'
version_date:
  kaz: 2014-08-13
  rus: 2014-08-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/82921/kaz/13.08.2014
  rus: https://zan.gov.kz/client/#!/doc/82921/rus/13.08.2014
