act_code: '1729'
requisite: Решение маслихата Актюбинской области от 23 сентября 1998 года № 1. Зарегистрировано Управлением юстиции Актюбинской области 6 ноября 1998 года № 5. Утратило силу в связи с истечением срока применения - письмо областного маслихата Актюбинской области от 20 декабря 2004 года № 1/5-282
title:
  rus: О работе областного управления здравоохранения по выполнению Закона РК «Об охране здоровья граждан Республики Казахстан»
  kaz: «Қазақстан Республикасында азаматтардың денсаулығын қорғау туралы» Қазақстан Республикасының Заңын орындау жөнінде облыстық денсаулық сақтау басқармасының жұмысы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-09-22
approved_by:
- '153000000002'
version_date:
  kaz: 1998-09-22
  rus: 1998-09-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/1729/kaz/22.09.1998
  rus: https://zan.gov.kz/client/#!/doc/1729/rus/22.09.1998
