act_code: '47584'
requisite: Ақтөбе облысы Байғанин аудандық мәслихатының 2009 жылғы 24 шілдедегі № 101 шешімі. Ақтөбе облысының Байғанин аудандық әділет басқармасында 2009 жылдың 27 тамызда N 3-4-81 тіркелді. Күші жойылды - Ақтөбе облысы Байғанин аудандық мәслихатының 2012 жылғы 29 қазандағы № 39 шешімімен; 2012 жылғы 13 желтоқсандағы № 04-13/355 хатымен
title:
  rus: Мұқтаж азаматтардың жекелеген санаттарына әлеуметтік көмек көрсету туралы
  kaz: Мұқтаж азаматтардың жекелеген санаттарына әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-07-24
approved_by:
- '153005000002'
version_date:
  kaz: 2009-07-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/47584/kaz/24.07.2009
