act_code: '15361'
requisite: Решение маслихата Актюбинской области от 27 марта 2003 года № 4. Зарегистрировано Управлением юстиции Актюбинской области 12 мая 2003 года № 2146
title:
  rus: О программе по снижению бедности в Актюбинской области на 2003-2005 годы
  kaz: 2003-2005 жылдарға арналған Ақтөбе облысында кедейлікті төмендету жөніндегі Бағдарламасы туралы
form: РЕШ
type_codes:
- ПРОГ
- РЕШ
approved_on: 2003-03-27
approved_by:
- '153000000002'
version_date:
  kaz: 2003-03-27
  rus: 2003-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/15361/kaz/27.03.2003
  rus: https://zan.gov.kz/client/#!/doc/15361/rus/27.03.2003
