act_code: '134166'
requisite: Решение акима Байганинского района Актюбинской области от 20 августа 2019 года № 13. Зарегистрировано Департаментом юстиции Актюбинской области 20 августа 2019 года № 6366. Утратило силу решением акима Байганинского района Актюбинской области от 26 августа 2024 года № 5 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации природного и техногенного характера объектового масштаба на территории месторождения «Каратобе» Жаркамысского сельского округа Байганинского района
  kaz: Байғанин ауданы Жарқамыс ауылдық округінің «Қаратөбе» кен орыны аумағында объектілік ауқымдағы табиғи және техногендік сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-08-20
approved_by:
- '153005000003'
version_date:
  kaz: 2019-08-20
  rus: 2019-08-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/134166/kaz/20.08.2019
  rus: https://zan.gov.kz/client/#!/doc/134166/rus/20.08.2019
