act_code: '106782'
requisite: Решение маслихата Алгинского района Актюбинской области от 27 сентября 2016 года № 47. Зарегистрировано Департаментом юстиции Актюбинской области 11 октября 2016 года № 5094. Утратило силу решением маслихата Алгинского района Актюбинской области от 22 ноября 2018 года № 205
title:
  rus: «О предоставлении социальной помощи на приобретение топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Алгинского района
  kaz: «Алға ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына отын сатып алу үшін әлеуметтік көмек көрсету туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-09-27
approved_by:
- '153004000002'
version_date:
  kaz: 2016-09-27
  rus: 2016-09-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/106782/kaz/27.09.2016
  rus: https://zan.gov.kz/client/#!/doc/106782/rus/27.09.2016
