act_code: '194923'
requisite: Решение акима Уилского района Актюбинской области от 29 марта 2024 года № 3
title:
  rus: Об объявлении чрезвычайной ситуации природного характера местного масштаба на территории Уилского района Актюбинской области
  kaz: Ақтөбе облысы Ойыл ауданы аумағында жергілікті ауқымдағы табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-29
approved_by:
- '153011000003'
version_date:
  kaz: 2024-03-29
  rus: 2024-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/194923/kaz/29.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194923/rus/29.03.2024
