act_code: '44861'
requisite: Ақтөбе облысы Ырғыз аудандық мәслихатының 2009 жылғы 11 наурыздағы N 76 шешімі. Ақтөбе облысының Ырғыз аудандық Әділет басқармасында 2009 жылғы 18 наурызда N 3-5-91 тіркелді. Күші жойылды - Ақтөбе облысы Ырғыз аудандық мәслихатының 2013 жылғы 25 қаңтардағы № 59 шешімімен
title:
  rus: Бір жолғы талондар құнын белгілеу туралы
  kaz: Бір жолғы талондар құнын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-03-11
approved_by:
- '153006000002'
version_date:
  kaz: 2009-03-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/44861/kaz/11.03.2009
