act_code: '36286'
requisite: Решение Мартукского районного маслихата Актюбинской области от 13 декабря 2007 года N 18. Зарегистрировано управлением юстиции Мартукского района Актюбинской области 27 декабря 2007 года за N 3-8-47. Утратило силу решением Мартукского районного маслихата Актюбинской области от 1 июня 2018 года № 151
title:
  rus: О социальной помощи на приобретение топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Мартукского района
  kaz: Мәртөк ауданының ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына отын сатып алу үшін әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-13
approved_by:
- '153008000002'
version_date:
  kaz: 2010-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/36286/kaz/23.04.2010
