act_code: '153920'
requisite: Решение акима Карабутакского сельского округа Айтекебийского района Актюбинской области от 26 марта 2021 года № 11. Зарегистрировано Департаментом юстиции Актюбинской области 30 марта 2021 года № 8165
title:
  rus: О переименовании некоторых улиц сел Карабутак и Жароткел Карабутакского сельского округа Айтекебийского района
  kaz: Әйтеке би ауданы Қарабұтақ ауылдық округінің Қарабұтақ және Жарөткел ауылдарының кейбір көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-03-26
approved_by:
- '153003010002'
version_date:
  kaz: 2021-03-26
  rus: 2021-03-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/153920/kaz/26.03.2021
  rus: https://zan.gov.kz/client/#!/doc/153920/rus/26.03.2021
