act_code: '206142'
requisite: Решение Мартукского районного маслихата Актюбинской области от 30 декабря 2024 года № 182
title:
  rus: Об утверждении бюджетов сельских округов Мартукского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Мәртөк ауданының ауылдық округтерінің бюджеттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '153008000002'
version_date:
  kaz: 2025-09-22
  rus: 2025-09-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/206142/kaz/22.09.2025
  rus: https://zan.gov.kz/client/#!/doc/206142/rus/22.09.2025
caused_by:
  code: '214839'
  requisite: Решение Мартукского районного маслихата Актюбинской области от 22 сентября 2025 года № 248
  title:
    rus: О внесении изменений и дополнения в решение Мартукского районного маслихата от 30 декабря 2024 года № 182 «Об утверждении бюджетов сельских округов Мартукского района на 2025-2027 годы»
    kaz: Мәртөк аудандық мәслихатының 2024 жылғы 30 желтоқсандағы № 182 «2025-2027 жылдарға арналған Мәртөк ауданының ауылдық округтерінің бюджеттерін бекіту туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/214839/rus
