act_code: '40371'
requisite: Ақтөбе облысы Темір ауданы Алтықарасу селолық округі әкімінің 2008 жылғы 20 маусымдағы № 5 шешімі. Ақтөбе облысының Темір аудандық Әділет басқармасында 2008 жылдың 30 маусымда № 3-10-82 тіркелді
title:
  rus: Алтықарасу, Еңбекші, Сартоғай ауылдарының көшелерін атау туралы
  kaz: Алтықарасу, Еңбекші, Сартоғай ауылдарының көшелерін атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-06-20
approved_by:
- '153010002001'
version_date:
  kaz: 2008-06-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/40371/kaz/20.06.2008
