act_code: '139067'
requisite: Решение Алгинского районного маслихата Актюбинской области от 8 января 2020 года № 331. Зарегистрировано Департаментом юстиции Актюбинской области 15 января 2020 года № 6766
title:
  rus: Об утверждении бюджета города Алга на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Алға қаласының бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-08
approved_by:
- '153004000002'
version_date:
  kaz: 2020-12-15
  rus: 2020-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/139067/kaz/15.12.2020
  rus: https://zan.gov.kz/client/#!/doc/139067/rus/15.12.2020
caused_by:
  code: '150284'
  requisite: Решение Алгинского районного маслихата Актюбинской области от 15 декабря 2020 года № 456. Зарегистрировано Департаментом юстиции Актюбинской области 20 декабря 2020 года № 7810
  title:
    rus: О внесении изменений в решение Алгинского районного маслихата от 8 января 2020 года № 331 «Об утверждении бюджета города Алга на 2020-2022 годы»
    kaz: Алға аудандық мәслихатының 2020 жылғы 8 қаңтардағы № 331 «2020-2022 жылдарға арналған Алға қаласының бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/150284/rus
