act_code: '66425'
requisite: Решение акима Коктауского сельского округа Хромтауского района Актюбинской области от 1 июня 2012 года № 9. Зарегистрировано Управлением юстиции Хромтауского района Актюбинской области 26 июня 2012 года № 3-12-152
title:
  rus: '"О наименовании улиц и составных частей Коктауского сельского округа"'
  kaz: '"Көктау ауылдық округінің көшелері мен құрылымдық бөліктеріне атау беру туралы"'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-06-01
approved_by:
- '153013014001'
version_date:
  kaz: 2015-07-28
  rus: 2015-07-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/66425/kaz/28.07.2015
  rus: https://zan.gov.kz/client/#!/doc/66425/rus/28.07.2015
caused_by:
  code: '92836'
  requisite: Решение акима Коктауского сельского округа Хромтауского района Актюбинской области от 28 июля 2015 года № 20. Зарегистрировано Департаментом юстиции Актюбинской области 19 августа 2015 года № 4473
  title:
    rus: О внесении изменений в решение от 1 июня 2012 года № 9 "О наименовании улиц и составных частей Коктауского сельского округа"
    kaz: '"Көктау селолық округінің көшелері мен құрылымдық бөліктеріне атау беру туралы" 2012 жылғы 1 маусымдағы № 9 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/92836/rus
