act_code: '140377'
requisite: Решение акима Шубаркудыкского сельского округа Темирского района Актюбинской области от 12 марта 2020 года № 43. Зарегистрировано Департаментом юстиции Актюбинской области 16 марта 2020 года № 6874
title:
  rus: О присвоении наименований безымянным улицам поселка Шубаркудык
  kaz: Шұбарқұдық кентінің атаусыз көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-03-12
approved_by:
- '153010009002'
version_date:
  kaz: 2020-11-27
  rus: 2020-11-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/140377/kaz/27.11.2020
  rus: https://zan.gov.kz/client/#!/doc/140377/rus/27.11.2020
caused_by:
  code: '149132'
  requisite: Решение акима Шубаркудыкского сельского округа Темирского района Актюбинской области от 27 ноября 2020 года № 221. Зарегистрировано Департаментом юстиции Актюбинской области 30 ноября 2020 года № 7741
  title:
    rus: О внесении изменения в решение акима Шубаркудыкского сельского округа от 12 марта 2020 года № 43 «О присвоении наименований безымянным улицам поселка Шубаркудык»
    kaz: Шұбарқұдық ауылдық округі әкімінің 2020 жылғы 12 наурыздағы № 43 «Шұбарқұдық кентінің атаусыз көшелеріне атау беру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149132/rus
