act_code: '66423'
requisite: Решение акима Кос-Истекского сельского округа Каргалинского района Актюбинской области от 15 июня 2012 года № 1. Зарегистрировано Управлением юстиции Каргалинского района Актюбинской области 26 июня 2012 года № 3-6-145
title:
  rus: О наименовании и переименовании улиц Кос-Истекского сельского округа
  kaz: Қос Естек ауылдық округінің көшелерін атау және қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-06-15
approved_by:
- '153007006002'
version_date:
  kaz: 2012-06-15
  rus: 2012-06-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/66423/kaz/15.06.2012
  rus: https://zan.gov.kz/client/#!/doc/66423/rus/15.06.2012
