act_code: '217097'
requisite: Решение Шалкарского районного маслихата Актюбинской области от 12 ноября 2025 года № 534
title:
  rus: О понижении размера ставки налогов при применении специального налогового режима на основе упрощенной декларации в Шалкарском районе
  kaz: Шалқар ауданында оңайлатылған декларация негізінде арнаулы салық режимін қолдану кезінде салық мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-12
approved_by:
- '153014000002'
version_date:
  kaz: 2025-11-12
  rus: 2025-11-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/217097/kaz/12.11.2025
  rus: https://zan.gov.kz/client/#!/doc/217097/rus/12.11.2025
