act_code: '44185'
requisite: Ақтөбе облысы Хромтау ауданы Құдықсай ауылдық округі әкімінің 2009 жылғы 9 ақпандағы N 2 шешімі. Ақтөбе облысының Хромтау аудандық әділет басқармасында 2009 жылдың 10 ақпанда N 3-12-81 тіркелді
title:
  rus: Құдықсай ауылдық округінің елді мекендеріне көше атауын беру туралы
  kaz: Құдықсай ауылдық округінің елді мекендеріне көше атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-09
approved_by:
- '153013009002'
version_date:
  kaz: 2009-02-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/44185/kaz/09.02.2009
