act_code: '47407'
requisite: Ақтөбе облысы Ырғыз аудандық мәслихатының 2009 жылғы 22 шілдедегі № 92 шешімі. Ақтөбе облысының Ырғыз аудандық әділет басқармасында 2009 жылдың 10 тамызда N 3-5-103 тіркелді. Күші жойылды - Ақтөбе облысы Ырғыз аудандық мәслихатының 2010 жылғы 17 ақпандағы № 123 шешімімен
title:
  rus: Ауданға жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына 2009 жылы көтерме жәрдемақы үшін әлеуметтік қолдауды ұсыну туралы
  kaz: Ауданға жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына 2009 жылы көтерме жәрдемақы үшін әлеуметтік қолдауды ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-07-22
approved_by:
- '153006000002'
version_date:
  kaz: 2009-07-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/47407/kaz/22.07.2009
