act_code: '127732'
requisite: Решение Темирского районного маслихата Актюбинской области от 20 декабря 2018 года № 286. Зарегистрировано Управлением юстиции Темирского района Департамента юстиции Актюбинской области 27 декабря 2018 года № 3-10-234. Утратило силу решением Темирского районного маслихата Актюбинской области от 20 августа 2020 года № 510
title:
  rus: Об утверждении порядка и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Темирского района
  kaz: Темір ауданының ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына бюджет қаражаты есебінен коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету тәртібін және мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-20
approved_by:
- '153010000002'
version_date:
  kaz: 2020-03-12
  rus: 2020-03-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/127732/kaz/12.03.2020
  rus: https://zan.gov.kz/client/#!/doc/127732/rus/12.03.2020
caused_by:
  code: '140588'
  requisite: Решение Темирского районного маслихата Актюбинской области от 12 марта 2020 года № 443. Зарегистрировано Департаментом юстиции Актюбинской области 17 марта 2020 года № 6899. Утратило силу решением Темирского районного маслихата Актюбинской области от 20 августа 2020 года № 510
  title:
    rus: О внесении изменения в решение районного маслихата от 20 декабря 2018 года № 286 «Об утверждении порядка и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Темирского района»
    kaz: Аудандық мәслихаттың 2018 жылғы 20 желтоқсандағы № 286 «Темір ауданының ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына бюджет қаражаты есебінен коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету тәртібін және мөлшерін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/140588/rus
