act_code: '110808'
requisite: Решение маслихата Кобдинского района Актюбинской области от 24 февраля 2017 года № 61. Зарегистрировано Департаментом юстиции Актюбинской области 27 марта 2017 года № 5354. Утратило силу решением Кобдинского районного маслихата Актюбинской области от 2 марта 2018 года № 137
title:
  rus: Об утверждении методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Кобдинского районного маслихата»
  kaz: «Қобда аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-02-24
approved_by:
- '153012000002'
version_date:
  kaz: 2017-02-24
  rus: 2017-02-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/110808/kaz/24.02.2017
  rus: https://zan.gov.kz/client/#!/doc/110808/rus/24.02.2017
