act_code: '194965'
requisite: Решение Иргизского районного маслихата Актюбинской области от 18 марта 2024 года № 117. Зарегистрировано Департаментом юстиции Актюбинской области 28 марта 2024 года № 8545-04
title:
  rus: Об утверждении размера и Правил оказания жилищной помощи в Иргизском районе
  kaz: Ырғыз ауданында тұрғын үй көмегін көрсетудің мөлшері мен қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2024-03-18
approved_by:
- '153006000002'
version_date:
  kaz: 2025-09-15
  rus: 2025-09-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/194965/kaz/15.09.2025
  rus: https://zan.gov.kz/client/#!/doc/194965/rus/15.09.2025
caused_by:
  code: '214483'
  requisite: Решение Иргизского районного маслихата Актюбинской области от 15 сентября 2025 года № 250. Зарегистрировано в Министерстве юстиции Республики Казахстан 17 сентября 2025 года № 36863
  title:
    rus: О внесении изменений в решение маслихата Иргизского района от 18 марта 2024 года № 117 «Об определении размера и порядка оказания жилищной помощи в Иргизском районе»
    kaz: Ырғыз аудандық мәслихатының 2024 жылғы 18 наурыздағы № 117 «Ырғыз ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/214483/rus
