act_code: '194965'
requisite: Решение Иргизского районного маслихата Актюбинской области от 18 марта 2024 года № 117. Зарегистрировано Департаментом юстиции Актюбинской области 28 марта 2024 года № 8545-04
title:
  rus: Об утверждении размера и Правил оказания жилищной помощи в Иргизском районе
  kaz: Ырғыз ауданында тұрғын үй көмегін көрсетудің мөлшері мен қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2024-03-18
approved_by:
- '153006000002'
version_date:
  kaz: 2024-03-18
  rus: 2024-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/194965/kaz/18.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194965/rus/18.03.2024
