act_code: '102117'
requisite: Решение маслихата Мугалжарского района Актюбинской области от 12 апреля 2016 года № 19
title:
  rus: Об утрате силы решения районного маслихата от 21 декабря 2012 года № 56 «О дополнительном регламентировании порядка проведения мирных собраний, митингов, шествий, пикетов и демонстраций в Мугалжарском районе»
  kaz: Аудандық мәслихаттың 2012 жылғы 21 желтоқсандағы № 56 «Мұғалжар ауданында бейбіт жиналыстар, митингілер, шерулер, пикеттер мен демонстрациялар өткізу тәртібін қосымша регламенттеу туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-04-12
approved_by:
- '153009000002'
version_date:
  kaz: 2016-04-12
  rus: 2016-04-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/102117/kaz/12.04.2016
  rus: https://zan.gov.kz/client/#!/doc/102117/rus/12.04.2016
