act_code: '44912'
requisite: Решение Каргалинского районного маслихата Актюбинской области от 18 февраля 2009 года № 120. Зарегистрировано в Управлении юстиции Каргалинского района Актюбинской области 19 марта 2009 года № 3-6-79. Утратило силу решением Каргалинского районного маслихата Актюбинской области от 1 марта 2018 года № 227
title:
  rus: Об установлении размера ставок фиксированного налога для единиц налогообложения в месяц
  kaz: Айына салық салу бірлігі үшін нақтыланған салық мөлшерлемелерінің мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-18
approved_by:
- '153007000002'
version_date:
  kaz: 2009-02-18
  rus: 2009-02-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/44912/kaz/18.02.2009
  rus: https://zan.gov.kz/client/#!/doc/44912/rus/18.02.2009
