act_code: '205220'
requisite: Решение Каргалинского районного маслихата Актюбинской области от 27 декабря 2024 года № 266
title:
  rus: Об утверждении бюджета Велиховского сельского округа на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Велихов ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '153007000002'
version_date:
  kaz: 2025-05-27
  rus: 2025-05-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/205220/kaz/27.05.2025
  rus: https://zan.gov.kz/client/#!/doc/205220/rus/27.05.2025
caused_by:
  code: '210851'
  requisite: Решение Каргалинского районного маслихата Актюбинской области от 27 мая 2025 года № 334
  title:
    rus: О внесении изменений в решение Каргалинского районного маслихата от 27 декабря 2024 года № 266 «Об утверждении бюджета Велиховского сельского округа на 2025-2027 годы»
    kaz: Қарғалы аудандық мәслихатының 2024 жылғы 27 желтоқсандағы № 266 «2025-2027 жылдарға арналған Велихов ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/210851/rus
