act_code: '128511'
requisite: Решение Уилского районного маслихата Актюбинской области от 4 января 2019 года № 249. Зарегистрировано Управлением юстиции Уилского района Департамента юстиции Актюбинской области 10 января 2019 года № 3-11-157
title:
  rus: Об утверждении бюджета Коптогайского сельского округа на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Көптогай ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-04
approved_by:
- '153011000002'
version_date:
  kaz: 2019-08-09
  rus: 2019-08-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/128511/kaz/09.08.2019
  rus: https://zan.gov.kz/client/#!/doc/128511/rus/09.08.2019
caused_by:
  code: '134169'
  requisite: Решение Уилского районного маслихата Актюбинской области от 9 августа 2019 года № 327. Зарегистрировано Департаментом юстиции Актюбинской области 20 августа 2019 года № 6369
  title:
    rus: О внесении изменений в решение Уилского районного маслихата от 4 января 2019 года № 249 «Об утверждении бюджета Коптогайского сельского округа на 2019-2021 годы
    kaz: Ойыл аудандық мәслихатының 2019 жылғы 4 қаңтардағы № 249 «2019-2021 жылдарға арналған Көптогай ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/134169/rus
