act_code: '58405'
requisite: Решение маслихата Алгинского района Актюбинской области от 30 марта 2011 года № 11. Зарегистрировано Управлением юстиции Алгинского района Актюбинской области 25 апреля 2011 года № 3-3-124. Утратило силу решением маслихата Алгинского района Актюбинской области от 27 июня 2013 года № 93
title:
  rus: Об оказании социальной помощи специалистам социальной сферы, проживающим в сельской местности района на приобретение топлива
  kaz: Аудан аумағындағы ауылдық жерлерде тұратын әлеуметтік сала мамандарына отын сатып алуға әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-03-30
approved_by:
- '153004000002'
version_date:
  kaz: 2011-03-30
  rus: 2011-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/58405/kaz/30.03.2011
  rus: https://zan.gov.kz/client/#!/doc/58405/rus/30.03.2011
