act_code: '163565'
requisite: Решение Алгинского районного маслихата Актюбинской области от 29 декабря 2021 года № 129
title:
  rus: Об утверждении бюджета Карахобдинского сельского округа на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Қарақобда ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-29
approved_by:
- '153004000002'
version_date:
  kaz: 2021-12-29
  rus: 2021-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/163565/kaz/29.12.2021
  rus: https://zan.gov.kz/client/#!/doc/163565/rus/29.12.2021
