act_code: '177516'
requisite: Решение Иргизского районного маслихата Актюбинской области от 30 декабря 2022 года № 199
title:
  rus: Об утверждении бюджета Кызылжарского сельского округа на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Қызылжар ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-30
approved_by:
- '153006000002'
version_date:
  kaz: 2023-11-01
  rus: 2023-11-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/177516/kaz/01.11.2023
  rus: https://zan.gov.kz/client/#!/doc/177516/rus/01.11.2023
caused_by:
  code: '187916'
  requisite: Решение Иргизского районного маслихата Актюбинской области от 1 ноября 2023 года № 68
  title:
    rus: О внесении изменений в решение районного маслихата от 30 декабря 2022 года № 199 «Об утверждении бюджет Кызылжарского сельского округа на 2023-2025 годы»
    kaz: Аудандық мәслихаттың 2022 жылғы 30 желтоқсандағы № 199 «2023-2025 жылдарға арналған Қызылжар ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/187916/rus
