act_code: '138712'
requisite: Решение Байганинского районного маслихата Актюбинской области от 30 декабря 2019 года № 292. Зарегистрировано Департаментом юстиции Актюбинской области 14 января 2020 года № 6691
title:
  rus: Об утверждении бюджета Культабанского сельского округа на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Көлтабан ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-30
approved_by:
- '153005000002'
version_date:
  kaz: 2020-12-09
  rus: 2020-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/138712/kaz/09.12.2020
  rus: https://zan.gov.kz/client/#!/doc/138712/rus/09.12.2020
caused_by:
  code: '149898'
  requisite: Решение Байганинского районного маслихата Актюбинской области от 9 декабря 2020 года № 390. Зарегистрировано Департаментом юстиции Актюбинской области 14 декабря 2020 года № 7785
  title:
    rus: О внесении изменений в решение Байганинского районного маслихата от 30 декабря 2019 года № 292 «Об утверждении бюджета Культабанского сельского округа на 2020-2022 годы»
    kaz: Байғанин аудандық мәслихатының 2019 жылғы 30 желтоқсандағы № 292 «2020-2022 жылдарға арналған Көлтабан ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149898/rus
