act_code: '124833'
requisite: Решение маслихата Айтекебийского района Актюбинской области от 27 августа 2018 года № 225. Зарегистрировано Управлением юстиции Айтекебийского района Департамента юстиции Актюбинской области 25 сентября 2018 года № 3-2-162. Утратило силу решением Айтекебийского районного маслихата Актюбинской области от 27 марта 2024 года № 181
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Айтекебийском районе
  kaz: Әйтеке би ауданында тұрғын үй көмегін көрсету мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-08-27
approved_by:
- '153003000002'
version_date:
  kaz: 2020-08-24
  rus: 2020-08-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/124833/kaz/24.08.2020
  rus: https://zan.gov.kz/client/#!/doc/124833/rus/24.08.2020
caused_by:
  code: '145977'
  requisite: Решение Айтекебийского районного маслихата Актюбинской области от 24 августа 2020 года № 451. Зарегистрировано Департаментом юстиции Актюбинской области 1 сентября 2020 года № 7368. Утратило силу решением Айтекебийского районного маслихата Актюбинской области от 27 марта 2024 года № 181
  title:
    rus: О внесении изменений в решение районного маслихата от 27 августа 2018 года № 225 «Об определении размера и порядка оказания жилищной помощи в Айтекебийском районе»
    kaz: Аудандық мәслихатының 2018 жылғы 27 тамыздағы № 225 «Әйтеке би ауданында тұрғын үй көмегін көрсету мөлшерін және тәртібін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/145977/rus
