act_code: '137752'
requisite: Решение Хромтауского районного маслихата Актюбинской области от 25 декабря 2019 года № 392. Зарегистрировано Департаментом юстиции Актюбинской области 27 декабря 2019 года № 6629
title:
  rus: Об утверждении Хромтауского районного бюджета на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Хромтау ауданының бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-25
approved_by:
- '153013000002'
version_date:
  kaz: 2020-10-28
  rus: 2020-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/137752/kaz/28.10.2020
  rus: https://zan.gov.kz/client/#!/doc/137752/rus/28.10.2020
caused_by:
  code: '148250'
  requisite: Решение Хромтауского районного маслихата Актюбинской области от 28 октября 2020 года № 519. Зарегистрировано Департаментом юстиции Актюбинской области 4 ноября 2020 года № 7582
  title:
    rus: О внесении изменений в решение Хромтауского районного маслихата от 25 декабря 2019 года № 392 «Об утверждении Хромтауского районного бюджета на 2020-2022 годы»
    kaz: Хромтау аудандық мәслихатының 2019 жылғы 25 желтоқсандағы № 392 «2020-2022 жылдарға арналған Хромтау ауданының бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/148250/rus
