act_code: '137752'
requisite: Решение Хромтауского районного маслихата Актюбинской области от 25 декабря 2019 года № 392. Зарегистрировано Департаментом юстиции Актюбинской области 27 декабря 2019 года № 6629
title:
  rus: Об утверждении Хромтауского районного бюджета на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Хромтау ауданының бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-25
approved_by:
- '153013000002'
version_date:
  kaz: 2020-08-24
  rus: 2020-08-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/137752/kaz/24.08.2020
  rus: https://zan.gov.kz/client/#!/doc/137752/rus/24.08.2020
caused_by:
  code: '145877'
  requisite: Решение Хромтауского районного маслихата Актюбинской области от 24 августа 2020 года № 494. Зарегистрировано Департаментом юстиции Актюбинской области 27 августа 2020 года № 7357
  title:
    rus: О внесении изменений в решение Хромтауского районного маслихата от 25 декабря 2019 года № 392 «Об утверждении Хромтауского районного бюджета на 2020-2022 годы»
    kaz: Хромтау аудандық мәслихатының 2019 жылғы 25 желтоқсандағы № 392 «2020-2022 жылдарға арналған Хромтау ауданының бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/145877/rus
