act_code: '50086'
requisite: Ақтөбе облысы Мұғалжар ауданы әкімінің 2009 жылғы 7 желтоқсандағы N 27 шешімі. Ақтөбе облысының Мұғалжар аудандық әділет басқармасында 2010 жылдың 19 қаңтарда N 3-9-112 тіркелді. Қолданылу мерзімінің аяқталуына байланысты күші жойылды - (Ақтөбе облысы Мұғалжар аудандық әкім аппаратының 2013 жылғы 18 ақпандағы № 423 хатымен)
title:
  rus: 1993 жылы туған азаматтарды "Мұғалжар ауданы қорғаныс істер жөніндегі басқармасы" мемлекеттік мекемесінің шақыру учаскесінде тіркеу жүргізу туралы
  kaz: 1993 жылы туған азаматтарды "Мұғалжар ауданы қорғаныс істер жөніндегі басқармасы" мемлекеттік мекемесінің шақыру учаскесінде тіркеу жүргізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-07
approved_by:
- '153009000003'
version_date:
  kaz: 2009-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/50086/kaz/07.12.2009
