act_code: '187453'
requisite: Решение Алгинского районного маслихата Актюбинской области от 27 октября 2023 года № 74. Зарегистрировано Департаментом юстиции Актюбинской области 31 октября 2023 года № 8418
title:
  rus: О признании утратившим силу решения Алгинского районного маслихата от 21 апреля 2023 года № 12 «Об утверждении ставок туристского взноса для иностранцев на 2023 год по Алгинскому району»
  kaz: Алға аудандық мәслихатының 2023 жылғы 21 сәуірдегі № 12 «Алға ауданы бойынша шетелдіктер үшін 2023 жылға арналған туристік жарна мөлшерлемелерін бекіту туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-10-27
approved_by:
- '153004000002'
version_date:
  kaz: 2023-10-27
  rus: 2023-10-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/187453/kaz/27.10.2023
  rus: https://zan.gov.kz/client/#!/doc/187453/rus/27.10.2023
