act_code: '177865'
requisite: Решение Алгинского районного маслихата Актюбинской области от 28 декабря 2022 года № 258
title:
  rus: Об утверждении бюджета Карагашского сельского округа на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Қарағаш ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-28
approved_by:
- '153004000002'
version_date:
  kaz: 2023-05-04
  rus: 2023-05-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/177865/kaz/04.05.2023
  rus: https://zan.gov.kz/client/#!/doc/177865/rus/04.05.2023
caused_by:
  code: '181154'
  requisite: Решение Алгинского районного маслихата Актюбинской области от 4 мая 2023 года № 24
  title:
    rus: О внесении изменений в решение Алгинского районного маслихата от 28 декабря 2022 года № 258 «Об утверждении бюджета Карагашского сельского округа на 2023-2025 годы»
    kaz: Алға аудандық мәслихатының 2022 жылғы 28 желтоқсандағы № 258 «2023-2025 жылдарға арналған Қарағаш ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/181154/rus
