act_code: '151126'
requisite: Решение Шалкарского районного маслихата Актюбинской области от 29 декабря 2020 года № 619. Зарегистрировано Департаментом юстиции Актюбинской области 30 декабря 2020 года № 7880
title:
  rus: Об утверждении бюджета Кауылжырского сельского округа на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Қауылжыр ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-29
approved_by:
- '153014000002'
version_date:
  kaz: 2021-11-23
  rus: 2021-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/151126/kaz/23.11.2021
  rus: https://zan.gov.kz/client/#!/doc/151126/rus/23.11.2021
caused_by:
  code: '160889'
  requisite: Решение Шалкарского районного маслихата Актюбинской области от 23 ноября 2021 года № 129
  title:
    rus: О внесении изменений в решение Шалкарского районного маслихата Актюбинской области от 29 декабря 2020 года № 619 «Об утверждении бюджета Кауылжырского сельского округа на 2021-2023 годы»
    kaz: Ақтөбе облысы Шалқар аудандық мәслихатының 2020 жылғы 29 желтоқсандағы № 619 «2021-2023 жылдарға арналған Қауылжыр ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/160889/rus
