act_code: '139254'
requisite: Решение Хромтауского районного маслихата Актюбинской области от 20 января 2020 года № 413. Зарегистрировано Департаментом юстиции Актюбинской области 24 января 2020 года № 6792
title:
  rus: Об утверждении бюджета сельского округа Дөң на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Дөң ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-20
approved_by:
- '153013000002'
version_date:
  kaz: 2020-09-09
  rus: 2020-09-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/139254/kaz/09.09.2020
  rus: https://zan.gov.kz/client/#!/doc/139254/rus/09.09.2020
caused_by:
  code: '146563'
  requisite: Решение Хромтауского районного маслихата Актюбинской области от 9 сентября 2020 года № 506. Зарегистрировано Департаментом юстиции Актюбинской области 18 сентября 2020 года № 7436
  title:
    rus: О внесении изменений в решение Хромтауского районного маслихата от 20 января 2020 года № 413 «Об утверждении бюджета сельского округа Дөң на 2020-2022 годы»
    kaz: Хромтау аудандық мәслихатының 2020 жылғы 20 қаңтардағы № 413 «2020-2022 жылдарға арналған Дөң ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/146563/rus
