act_code: '139254'
requisite: Решение Хромтауского районного маслихата Актюбинской области от 20 января 2020 года № 413. Зарегистрировано Департаментом юстиции Актюбинской области 24 января 2020 года № 6792
title:
  rus: Об утверждении бюджета сельского округа Дөң на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Дөң ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-20
approved_by:
- '153013000002'
version_date:
  kaz: 2020-11-06
  rus: 2020-11-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/139254/kaz/06.11.2020
  rus: https://zan.gov.kz/client/#!/doc/139254/rus/06.11.2020
caused_by:
  code: '148637'
  requisite: Решение Хромтауского районного маслихата Актюбинской области от 6 ноября 2020 года № 533. Зарегистрировано Департаментом юстиции Актюбинской области 13 ноября 2020 года № 7639
  title:
    rus: О внесении изменений в решение Хромтауского районного маслихата от 20 января 2020 года № 413 «Об утверждении бюджета сельского округа Дөң на 2020-2022 годы»
    kaz: Хромтау аудандық мәслихатының 2020 жылғы 20 қаңтардағы № 413 «2020-2022 жылдарға арналған Дөң ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/148637/rus
