act_code: '138544'
requisite: Решение Кобдинского районного маслихата Актюбинской области от 8 января 2020 года № 284. Зарегистрировано Департаментом юстиции Актюбинской области 14 января 2020 года № 6668
title:
  rus: Об утверждении бюджета Булакского сельского округа на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Бұлақ ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-08
approved_by:
- '153012000002'
version_date:
  kaz: 2020-12-24
  rus: 2020-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/138544/kaz/24.12.2020
  rus: https://zan.gov.kz/client/#!/doc/138544/rus/24.12.2020
caused_by:
  code: '150775'
  requisite: Решение Кобдинского районного маслихата Актюбинской области от 24 декабря 2020 года № 396. Зарегистрировано Департаментом юстиции Актюбинской области 28 декабря 2020 года № 7851
  title:
    rus: О внесении изменений в решение Кобдинского районного маслихата от 8 января 2020 года № 284 «Об утверждении бюджета Булакского сельского округа на 2020-2022 годы»
    kaz: Қобда аудандық мәслихатының 2020 жылғы 8 қаңтардағы № 284 «2020-2022 жылдарға арналған Бұлақ ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/150775/rus
