act_code: '182572'
requisite: Решение акима Аксайского сельского округа Темирского района Актюбинской области от 31 мая 2023 года № 22
title:
  rus: Об утрате силы решения акима Аксайского сельского округа от 14 апреля № 17 «Об установлении карантина
  kaz: Ақсай ауылдық округі әкімінің 2023 жылғы 14 сәуірдегі «Карантин белгілеу туралы» № 17 шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-05-31
approved_by:
- '153010003002'
version_date:
  kaz: 2023-05-31
  rus: 2023-05-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/182572/kaz/31.05.2023
  rus: https://zan.gov.kz/client/#!/doc/182572/rus/31.05.2023
