act_code: '105931'
requisite: Решение маслихата Мугалжарского района Актюбинской области от 4 августа 2016 года № 35. Зарегистрировано Департаментом юстиции Актюбинской области 29 августа 2016 года № 5039. Утратило силу решением маслихата Мугалжарского района Актюбинской области от 5 декабря 2018 года № 255
title:
  rus: О предоставлении социальной помощи на приобретение топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Мугалжарского района
  kaz: Мұғалжар ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына отын сатып алу үшін әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-08-04
approved_by:
- '153009000002'
version_date:
  kaz: 2016-08-04
  rus: 2016-08-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/105931/kaz/04.08.2016
  rus: https://zan.gov.kz/client/#!/doc/105931/rus/04.08.2016
