act_code: '162830'
requisite: Решение Шалкарского районного маслихата Актюбинской области от 27 декабря 2021 года № 157
title:
  rus: Об утверждении бюджета Бершугирского сельского округа на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Бершүгір ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-27
approved_by:
- '153014000002'
version_date:
  kaz: 2022-06-22
  rus: 2022-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/162830/kaz/22.06.2022
  rus: https://zan.gov.kz/client/#!/doc/162830/rus/22.06.2022
caused_by:
  code: '169360'
  requisite: Решение Шалкарского районного маслихата Актюбинской области от 22 июня 2022 года № 262
  title:
    rus: О внесении изменения в решение Шалкарского районного маслихата от 27 декабря 2021 года № 157 «Об утверждении бюджета Бершугирского сельского округа на 2022-2024 годы»
    kaz: Шалқар аудандық мәслихатының 2021 жылғы 27 желтоқсандағы № 157 «2022-2024 жылдарға арналған Бершүгір ауылдық округ бюджетін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/169360/rus
