act_code: '151083'
requisite: Решение Каргалинского районного маслихата Актюбинской области от 24 декабря 2020 года № 531. Зарегистрировано Департаментом юстиции Актюбинской области 29 декабря 2020 года № 7864
title:
  rus: О предоставлении мер социальной поддержки специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, государственным служащим аппаратов акимов сел, поселков, сельских округов, прибывшим для работы и проживания в сельские населенные пункты Каргалинского района на 2021 год
  kaz: Қарғалы ауданының ауылдық елді мекендеріне жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға, ауылдар, кенттер, ауылдық округтер әкімдері аппараттарының мемлекеттік қызметшілеріне 2021 жылға әлеуметтік қолдау көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-24
approved_by:
- '153007000002'
version_date:
  kaz: 2021-03-12
  rus: 2021-03-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/151083/kaz/12.03.2021
  rus: https://zan.gov.kz/client/#!/doc/151083/rus/12.03.2021
caused_by:
  code: '153661'
  requisite: Решение Каргалинского районного маслихата Актюбинской области от 12 марта 2021 года № 15. Зарегистрировано Департаментом юстиции Актюбинской области 17 марта 2021 года № 8136
  title:
    rus: О внесении изменения в решение Каргалинского районного маслихата от 24 декабря 2020 года № 531 «О представлении мер социальной поддержки специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, государственным служащим аппаратов акимов сел, поселков, сельских округов, прибывшим для работы и проживания в сельские населенные пункты Каргалинского района на 2021 год»
    kaz: Қарғалы аудандық мәслихатының 2020 жылғы 24 желтоқсандағы № 531 «Қарғалы ауданының ауылдық елді мекендерге жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға, ауылдар, кенттер, ауылдық округтер әкімдері аппараттарының мемлекеттік қызметшілеріне 2021 жылға әлеуметтік қолдау көрсету туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/153661/rus
