act_code: '195282'
requisite: Решение Айтекебийского районного маслихата Актюбинской области от 27 марта 2024 года № 181. Зарегистрировано Департаментом юстиции Актюбинской области 2 апреля 2024 года № 8553-04
title:
  rus: Об утверждении размера и Правил оказания жилищной помощи в Айтекебийском районе
  kaz: Әйтеке би ауданында тұрғын үй көмегін көрсетудің мөлшері мен қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2024-03-27
approved_by:
- '153003000002'
version_date:
  kaz: 2024-03-27
  rus: 2024-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/195282/kaz/27.03.2024
  rus: https://zan.gov.kz/client/#!/doc/195282/rus/27.03.2024
