act_code: '5963'
requisite: Решение акима Актюбинской области от 13 марта 2000 года № 36. Зарегистрировано Управлением юстиции Актюбинской области 15 мая 2000 года № 504
title:
  rus: О внедрении единой системы клиринговых расчетов в хозяйственном обороте Актюбинской области
  kaz: Ақтөбе облысының шаруашылық айналымында клирингтік есептесудің бірыңғай жүйесін енгізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-03-13
approved_by:
- '153000000003'
version_date:
  kaz: 2000-03-13
  rus: 2000-03-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/5963/kaz/13.03.2000
  rus: https://zan.gov.kz/client/#!/doc/5963/rus/13.03.2000
