act_code: '42631'
requisite: Ақтөбе облысы Мұғалжар ауданы Қ. Жұбанов атындағы ауылдық округі әкімінің 2008 жылғы 20 қарашадағы N 3 шешімі. Ақтөбе облысының Мұғалжар аудандық әділет басқармасында 2008 жылдың 2 желтоқсанда N 3-9-85 тіркелді
title:
  rus: Қ. Жұбанов атындағы ауылдық округіне қарасты Жаңатұрмыс ауылындағы көшеге атау беру туралы
  kaz: Қ. Жұбанов атындағы ауылдық округіне қарасты Жаңатұрмыс ауылындағы көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-11-20
approved_by:
- '153009014002'
version_date:
  kaz: 2017-09-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/42631/kaz/25.09.2017
caused_by:
  code: '115468'
  requisite: Решение акима сельского округа имени К. Жубанова Мугалжарского района Актюбинской области от 25 сентября 2017 года № 8. Зарегистрировано Департаментом юстиции Актюбинской области 6 октября 2017 года № 5672
  title:
    rus: О внесении изменений в некоторые решения акима сельского округа имени К. Жубанова Мугалжарского района
    kaz: Мұғалжар ауданы Қ. Жұбанов атындағы ауылдық округі әкімінің кейбір шешімдеріне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/115468/rus
