act_code: '159271'
requisite: Решение акима Монкебийского сельского округа Шалкарского района Актюбинской области от 5 октября 2021 года № 18
title:
  rus: Об установлении публичного сервитута
  kaz: Қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-10-05
approved_by:
- '153014013002'
version_date:
  kaz: 2021-10-05
  rus: 2021-10-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/159271/kaz/05.10.2021
  rus: https://zan.gov.kz/client/#!/doc/159271/rus/05.10.2021
