act_code: '48304'
requisite: Ақтөбе облысы Байғанин ауданы Қарауылкелді ауылдық округінің әкімінің 2009 жылғы 24 қыркүйектегі № 104 шешімі. Ақтөбе облысы Байғанин ауданының Әділет басқармасында 2009 жылдың 22 қазанда № 3-4-84 тіркелді
title:
  rus: Көшені қайта атау туралы
  kaz: Көшені қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-09-24
approved_by:
- '153005008001'
version_date:
  kaz: 2014-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/48304/kaz/25.12.2014
caused_by:
  code: '86107'
  requisite: Решение акима Карауылкелдинского сельского округа Байганинского района Актюбинской области от 25 декабря 2014 года № 182. Зарегистрировано Департаментом юстиции Актюбинской области 23 января 2015 года № 4181
  title:
    rus: О внесении изменений в решение акима Карауылкелдинского сельского округа от 24 сентября 2009 года № 104 «О переименовании улицы»
    kaz: Қарауылкелді ауылдық округінің әкімінің 2009 жылғы 24 қыркүйектегі № 104 «Көшені қайта атау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/86107/rus
