act_code: '48304'
requisite: Ақтөбе облысы Байғанин ауданы Қарауылкелді ауылдық округінің әкімінің 2009 жылғы 24 қыркүйектегі № 104 шешімі. Ақтөбе облысы Байғанин ауданының Әділет басқармасында 2009 жылдың 22 қазанда № 3-4-84 тіркелді
title:
  rus: Көшені қайта атау туралы
  kaz: Көшені қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-09-24
approved_by:
- '153005008001'
version_date:
  kaz: 2009-09-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/48304/kaz/24.09.2009
