act_code: '192300'
requisite: Решение Хромтауского районного маслихата Актюбинской области от 27 декабря 2023 года № 130
title:
  rus: Об утверждении бюджета Тасоткельского сельского округа на 2024-2026 годы
  kaz: 2024-2026 жылдарға арналған Тасөткел ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-27
approved_by:
- '153013000002'
version_date:
  kaz: 2024-11-18
  rus: 2024-11-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/192300/kaz/18.11.2024
  rus: https://zan.gov.kz/client/#!/doc/192300/rus/18.11.2024
caused_by:
  code: '203104'
  requisite: Решение Хромтауского районного маслихата Актюбинской области от 18 ноября 2024 года № 254
  title:
    rus: О внесении изменений в решение Хромтауского районного маслихата от 27 декабря 2023 года № 130 «Об утверждении бюджета Тасоткельского сельского округа на 2024-2026 годы»
    kaz: Хромтау аудандық мәслихатының 2023 жылғы 27 желтоқсандағы № 130 «2024-2026 жылдарға арналған Tасөткел ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/203104/rus
