act_code: '58634'
requisite: Решение акима Бадамшинского сельского округа Каргалинского района Актюбинской области от 4 апреля 2011 года № 1. Зарегистрировано Управлением юстиции Каргалинского района Актюбинской области 28 апреля 2011 года № 3-6-121
title:
  rus: О переименовании улицы Мира села Бадамша в улицу имени Жоныса Укубаева
  kaz: Бадамша ауылының Мир көшесін Жоныс Үкібаев атындағы көшесі деп қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-04-04
approved_by:
- '153007008002'
version_date:
  kaz: 2011-04-04
  rus: 2011-04-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/58634/kaz/04.04.2011
  rus: https://zan.gov.kz/client/#!/doc/58634/rus/04.04.2011
