act_code: '55877'
requisite: Ақтөбе облысы Ырғыз аудандық әкімінің 2010 жылғы 24 қарашадағы № 9 шешімі. Ақтөбе облысы Әділет департаментінде 2010 жылдың 13 желтоқсанда № 3-5-123 тіркелді. Күші жойылды - Ақтөбе облысы Ырғыз аудандық әкімдігінің 2011 жылғы 22 шілдедегі № 5 шешімімен
title:
  rus: Аудандық қорғаныс істері жөніндегі бөлімінің шақыру учаскесіне 1994 жылы туылған азаматтарды кезекті тіркеу жайлы
  kaz: Аудандық қорғаныс істері жөніндегі бөлімінің шақыру учаскесіне 1994 жылы туылған азаматтарды кезекті тіркеу жайлы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-24
approved_by:
- '153006000003'
version_date:
  kaz: 2010-11-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/55877/kaz/24.11.2010
