act_code: '84805'
requisite: Решение от 21.11.2014 №6, Акимат аульного округа им. И. Билтабанова. Зарегистрировано Департаментом юстиции Актюбинской области 04 декабря 2014 года № 4087. Утратило силу решением акима сельского округа имени И. Билтабанова Хобдинского района Актюбинской области от 25.12.2015 № 8.
title:
  rus: Об установлении карантина в крестьянском хозяйстве "Макпал", находящиеся на территории сельского округа имени И. Билтабанова
  kaz: И. Білтабанов атындағы ауылдық округі аумағында орналасқан, "Мақпал" шаруа қожалығында карантин белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-11-21
approved_by:
- '153012005001'
version_date:
  kaz: 2014-11-21
  rus: 2014-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/84805/kaz/21.11.2014
  rus: https://zan.gov.kz/client/#!/doc/84805/rus/21.11.2014
