act_code: '199706'
requisite: Решение акима Культабанского сельского округа Байганинского района Актюбинской области от 13 августа 2024 года № 21
title:
  rus: Об отмене некоторых решений акима Культабанского сельского округа
  kaz: Көлтабан ауылдық округі әкімінің кейбір шешімдерін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-08-13
approved_by:
- '153005004002'
version_date:
  kaz: 2024-08-13
  rus: 2024-08-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/199706/kaz/13.08.2024
  rus: https://zan.gov.kz/client/#!/doc/199706/rus/13.08.2024
