act_code: '128277'
requisite: Решение акима Акайского сельского округа Алгинского района Актюбинской области от 10 января 2019 года № 1. Зарегистрировано Управлением юстиции Алгинского района Департамента юстиции Актюбинской области 11 января 2019 года № 3-3-194. Утратило силу решением акима Аксайского сельского округа Алгинского района Актюбинской области от 5 апреля 2019 года № 7
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-10
approved_by:
- '153004005002'
version_date:
  kaz: 2019-01-10
  rus: 2019-01-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/128277/kaz/10.01.2019
  rus: https://zan.gov.kz/client/#!/doc/128277/rus/10.01.2019
