act_code: '44924'
requisite: Ақтөбе облысы Шалқар ауданы Шетырғыз ауылдық округі әкімдігінің 2009 жылғы 13 наурыздағы N 4 шешімі. Ақтөбе облысының Шалқар аудандық әділет басқармасында 2009 жылдың 19 наурызында N 3-13-101 тіркелді
title:
  rus: Көшелерге атау беру туралы
  kaz: Көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-03-13
approved_by:
- '153014010002'
version_date:
  kaz: 2009-03-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/44924/kaz/13.03.2009
