act_code: '44924'
requisite: Ақтөбе облысы Шалқар ауданы Шетырғыз ауылдық округі әкімдігінің 2009 жылғы 13 наурыздағы N 4 шешімі. Ақтөбе облысының Шалқар аудандық әділет басқармасында 2009 жылдың 19 наурызында N 3-13-101 тіркелді
title:
  rus: Көшелерге атау беру туралы
  kaz: Көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-03-13
approved_by:
- '153014010002'
version_date:
  kaz: 2017-03-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/44924/kaz/13.03.2017
caused_by:
  code: '111168'
  requisite: Решение акима Шетиргизского сельского округа Шалкарского района Актюбинской области от 13 марта 2017 года № 2. Зарегистрировано Департаментом юстиции Актюбинской области 6 апреля 2017 года № 5409
  title:
    rus: О внесении изменения в решение акима Шетиргизского сельского округа Шалкарского района от 13 марта 2009 года № 4 «Көшелерге атау беру туралы»
    kaz: Шалқар ауданының Шетырғыз селолық округі әкімінің 2009 жылғы 13 наурыздағы № 4 «Көшелерге атау беру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/111168/rus
