act_code: '177081'
requisite: Решение Кобдинского районного маслихата Актюбинской области от 28 декабря 2022 года № 276
title:
  rus: Об утверждении бюджета Кобдинского сельского округа на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Қобда ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-28
approved_by:
- '153012000002'
version_date:
  kaz: 2023-12-07
  rus: 2023-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/177081/kaz/07.12.2023
  rus: https://zan.gov.kz/client/#!/doc/177081/rus/07.12.2023
caused_by:
  code: '190170'
  requisite: Решение Кобдинского районного маслихата Актюбинской области от 7 декабря 2023 года № 114
  title:
    rus: О внесении изменений в решение Кобдинского районного маслихата от 28 декабря 2022 года № 276 «Об утверждении бюджета Кобдинского сельского округа на 2023-2025 годы»
    kaz: Қобда аудандық мәслихатының 2022 жылғы 28 желтоқсандағы «2023-2025 жылдарға арналған Қобда ауылдық округінің бюджетін бекіту туралы» № 276 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/190170/rus
