act_code: '128520'
requisite: Решение Темирского районного маслихата Актюбинской области от 4 января 2019 года № 312. Зарегистрировано Управлением юстиции Темирского района Департамента юстиции Актюбинской области 10 января 2019 года № 3-10-241
title:
  rus: Об утверждении бюджета Кенкиякского сельского округа на 2019–2021 годы
  kaz: 2019–2021 жылдарға арналған Кеңқияқ ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-04
approved_by:
- '153010000002'
version_date:
  kaz: 2019-04-08
  rus: 2019-04-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/128520/kaz/08.04.2019
  rus: https://zan.gov.kz/client/#!/doc/128520/rus/08.04.2019
caused_by:
  code: '130619'
  requisite: Решение Темирского районного маслихата Актюбинской области от 8 апреля 2019 года № 341. Зарегистрировано Департаментом юстиции Актюбинской области 12 апреля 2019 года № 6098
  title:
    rus: О внесении изменений в решение районного маслихата от 4 января 2019 года № 312 «Об утверждении бюджета Кенкиякского сельского округа на 2019–2021 годы»
    kaz: Аудандық мәслихаттың 2019 жылғы 4 қаңтардағы № 312 «2019–2021 жылдарға арналған Кеңқияқ ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/130619/rus
