act_code: '220663'
requisite: Решение Хромтауского районного маслихата Актюбинской области от 24 декабря 2025 года № 435
title:
  rus: Об утверждении бюджета Табантальского сельского округа на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған Табантал ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-24
approved_by:
- '153013000002'
version_date:
  kaz: 2026-02-13
  rus: 2026-02-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/220663/kaz/13.02.2026
  rus: https://zan.gov.kz/client/#!/doc/220663/rus/13.02.2026
caused_by:
  code: '222475'
  requisite: Решение Хромтауского районного маслихата Актюбинской области от 13 февраля 2026 года № 456
  title:
    rus: О внесении изменений в решение Хромтауского районного маслихата от 24 декабря 2025 года № 435 «Об утверждении бюджета Табантальского сельского округа на 2026-2028 годы»
    kaz: Хромтау аудандық мәслихатының 2025 жылғы 24 желтоқсандағы № 435 «2026-2028 жылдарға арналған Табантал ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/222475/rus
