act_code: '148806'
requisite: Решение акима Шетиргизского сельского округа Шалкарского района Актюбинской области от 18 ноября 2020 года № 15. Зарегистрировано Департаментом юстиции Актюбинской области 19 ноября 2020 года № 7676
title:
  rus: О снятии ограничительных мероприятий и признании утратившими силу некоторых решений акима Шетиргизского сельского округа
  kaz: Шектеу іс-шараларын алу және Шетырғыз ауылдық округі әкімінің кейбір шешімдерінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-11-18
approved_by:
- '153014010002'
version_date:
  kaz: 2020-11-18
  rus: 2020-11-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/148806/kaz/18.11.2020
  rus: https://zan.gov.kz/client/#!/doc/148806/rus/18.11.2020
