act_code: '43705'
requisite: Ақтөбе облысы Шалқар аудандық мәслихатының 2008 жылғы 19 желтоқсандағы N 90 шешімі. Ақтөбе облысы Шалқар ауданының Әділет басқармасында 2009 жылдың 23 қаңтарда N 3-13-93 тіркелді. Күші жойылды - Ақтөбе облысы Шалқар аудандық мәслихатының 2009 жылғы 28 желтоқсандағы N 166 шешімімен
title:
  rus: 2009 жылға біржолғы талондардың құнын бекіту туралы
  kaz: 2009 жылға біржолғы талондардың құнын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-19
approved_by:
- '153014000002'
version_date:
  kaz: 2008-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/43705/kaz/19.12.2008
