act_code: '43172'
requisite: Ақтөбе облысы Шалқар аудандық мәслихатының 2008 жылғы 19 желтоқсандағы N 88 шешімі. Ақтөбе облысы Шалқар ауданының Әділет басқармасында 2009 жылғы 6 қаңтарда N 3-13-91 тіркелді. Күші жойылды - Ақтөбе облысы Шалқар аудандық мәслихатының 2009 жылғы 28 желтоқсандағы N 166 шешімімен
title:
  rus: 2009 жылға арналған аудан бюджеті туралы
  kaz: 2009 жылға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-19
approved_by:
- '153014000002'
version_date:
  kaz: 2008-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/43172/kaz/19.12.2008
