act_code: '177411'
requisite: Решение Мугалжарского районного маслихата Актюбинской области от 29 декабря 2022 года № 290
title:
  rus: Об утверждении бюджета Батпаккольского сельского округа на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Батпақкөл ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-29
approved_by:
- '153009000002'
version_date:
  kaz: 2023-12-15
  rus: 2023-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/177411/kaz/15.12.2023
  rus: https://zan.gov.kz/client/#!/doc/177411/rus/15.12.2023
caused_by:
  code: '190612'
  requisite: Решение Мугалжарского районного маслихата Актюбинской области от 15 декабря 2023 года № 130
  title:
    rus: О внесении изменений в решениеМугалжарскогорайонного маслихата от 29 декабря 2022 года №290 «Об утверждении бюджета Батпаккольского сельского округа на 2023-2025 годы»
    kaz: Мұғалжар аудандық мәслихатының 2022 жылғы  29 желтоқсандағы №290 «2023-2025 жылдарға арналған Батпақкөл  ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/190612/rus
