act_code: '152360'
requisite: Решение акима Бершугирского сельского округа Шалкарского района Актюбинской области от 20 января 2021 года № 1. Зарегистрировано Департаментом юстиции Актюбинской области 21 января 2021 года № 8019
title:
  rus: О присвоении наименования безымянной улице в селе Бершугир Бершугирского сельского округа
  kaz: Бершүгір ауылдық округі Бершүгір ауылындағы атаусыз көшеге атау беру туралы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-01-20
approved_by:
- '153014011002'
version_date:
  kaz: 2021-01-20
  rus: 2021-01-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/152360/kaz/20.01.2021
  rus: https://zan.gov.kz/client/#!/doc/152360/rus/20.01.2021
