act_code: '152787'
requisite: Решение акима Карабутакского сельского округа Айтекебийского района Актюбинской области от 9 февраля 2021 года № 07. Зарегистрировано Департаментом юстиции Актюбинской области 11 февраля 2021 года № 8048
title:
  rus: О переименовании улицы села Карабутак Карабутакского сельского округа Айтекебийского района
  kaz: Әйтеке би ауданы Қарабұтақ ауылдық округі Қарабұтақ ауылының көшесін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-02-09
approved_by:
- '153003010002'
version_date:
  kaz: 2021-02-09
  rus: 2021-02-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/152787/kaz/09.02.2021
  rus: https://zan.gov.kz/client/#!/doc/152787/rus/09.02.2021
