act_code: '150116'
requisite: Решение акима Уилского сельского округа Уилского района Актюбинской области от 15 декабря 2020 года № 137. Зарегистрировано Департаментом юстиции Актюбинской области 15 декабря 2020 года № 7806. Утратило силу решением акима Уилского сельского округа Уилского района Актюбинской области от 2 февраля 2021 года № 10
title:
  rus: Об установлении карантина на территории крестьянского хозяйства «Мурагер» Уилского сельского округа Уилского района
  kaz: Ойыл ауданы Ойыл ауылдық округінің «Мұрагер» шаруа қожалығы аумағында карантин белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-15
approved_by:
- '153011007002'
version_date:
  kaz: 2020-12-15
  rus: 2020-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/150116/kaz/15.12.2020
  rus: https://zan.gov.kz/client/#!/doc/150116/rus/15.12.2020
