act_code: '45714'
requisite: Ақтөбе облысы Шалқар ауданы Бозой ауылдық округі әкімінің 2009 жылғы 13 сәуірдегі N 7 шешімі. Ақтөбе облысының Шалқар аудандық әділет басқармасында 2009 жылдың 8 мамырда N 3-13-105 тіркелді
title:
  rus: Елді мекендерге көше атауларын беру туралы
  kaz: Елді мекендерге көше атауларын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-13
approved_by:
- '153014004002'
version_date:
  kaz: 2009-04-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/45714/kaz/12.04.2009
