act_code: '77304'
requisite: Решение акима Байганинского района Актюбинской области от 27 января 2014 года № 1. Зарегистрировано Департаментом юстиции Актюбинской области 6 февраля 2014 года № 3775
title:
  rus: Об образовании избирательных участков на территории Байганинского района
  kaz: Байғанин ауданы аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-01-27
approved_by:
- '153005000003'
version_date:
  kaz: 2024-06-18
  rus: 2024-06-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/77304/kaz/18.06.2024
  rus: https://zan.gov.kz/client/#!/doc/77304/rus/18.06.2024
caused_by:
  code: '198190'
  requisite: Решение акима Байганинского района Актюбинской области от 18 июня 2024 года № 4. Зарегистрировано Департаментом юстиции Актюбинской области 26 июня 2024 года № 8600-04
  title:
    rus: О внесении изменения в решение акима Байганинского района от 27 января 2014 года № 1 «Об образовании избирательных участков на территории Байганинского района»
    kaz: Байғанин ауданы әкімінің 2014 жылғы 27 қаңтардағы № 1 «Байғанин ауданы аумағында сайлау учаскелерін құру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/198190/rus
