act_code: '114213'
requisite: Решение акима Каргалинского района Актюбинской области от 1 августа 2017 года № 4. Зарегистрировано Департаментом юстиции Актюбинской области 18 августа 2017 года № 5631
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-08-01
approved_by:
- '153007000003'
version_date:
  kaz: 2024-05-20
  rus: 2024-05-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/114213/kaz/20.05.2024
  rus: https://zan.gov.kz/client/#!/doc/114213/rus/20.05.2024
caused_by:
  code: '196922'
  requisite: Решение акима Каргалинского района Актюбинской области от 20 мая 2024 года № 13. Зарегистрировано Департаментом юстиции Актюбинской области 22 мая 2024 года № 8583-04
  title:
    rus: О внесении изменения в решение акима Каргалинского района от 1 августа 2017 года № 4 «Об образовании избирательных участков»
    kaz: Қарғалы ауданы әкімінің 2017 жылғы 1 тамыздағы № 4 «Сайлау учаскелерін құру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/196922/rus
