act_code: '123188'
requisite: Решение акима Карагашского сельского округа Алгинского района Актюбинской области от 29 июня 2018 года № 5. Зарегистрировано Управлением юстиции Алгинского района Департамента юстиции Актюбинской области 4 июля 2018 года № 3-3-168. Утратило силу решением акима Карагашского сельского округа Алгинского района Актюбинской области от 2 октября 2018 года № 19
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-06-29
approved_by:
- '153004012002'
version_date:
  kaz: 2018-06-29
  rus: 2018-06-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/123188/kaz/29.06.2018
  rus: https://zan.gov.kz/client/#!/doc/123188/rus/29.06.2018
