act_code: '50345'
requisite: Ақтөбе облысы Ойыл ауданының әкімінің 2010 жылғы 10 қаңтардағы N 1 шешімі. Ақтөбе облысының Ойыл аудандық Әділет басқармасында 2010 жылдың 28 қаңтарда N 3-11-72 тіркелді. Күші жойылды - Ақтөбе облысы Ойыл ауданының әкімінің 2010 жылғы 26 сәуірдегі № 5 шешімімен
title:
  rus: '"Ойыл аудандық қорғаныс істері жөніндегі бөлімі" мемлекеттік мекемесінің шақыру учаскесінде 1993 жылғы туған азаматтарды тіркеу туралы'
  kaz: '"Ойыл аудандық қорғаныс істері жөніндегі бөлімі" мемлекеттік мекемесінің шақыру учаскесінде 1993 жылғы туған азаматтарды тіркеу туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-01-10
approved_by:
- '153011000003'
version_date:
  kaz: 2010-01-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/50345/kaz/10.01.2010
