act_code: '72651'
requisite: Решение маслихата Айтекебийского района Актюбинской области от 29 апреля 2013 года № 94. Зарегистрировано Департаментом юстиции Актюбинской области 21 мая 2013 года № 3591. Утратило силу решением маслихата Айтекебийского района Актюбинской области от 15 апреля 2014 года № 148
title:
  rus: О предоставлении мер социальной поддержки специалистам здравоохранения, образования, социального обеспечения, культуры, спорта и ветеринарии в 2013 году
  kaz: 2013 жылы Әйтеке би ауданы бойынша ауылдық елді мекендерге жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және ветеринария мамандарына әлеуметтік қолдау шараларын ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-04-29
approved_by:
- '153003000002'
version_date:
  kaz: 2013-04-29
  rus: 2013-04-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/72651/kaz/29.04.2013
  rus: https://zan.gov.kz/client/#!/doc/72651/rus/29.04.2013
