act_code: '85943'
requisite: ''
title:
  rus: 'О бюджете Мартукского района на 2015-2017 годы '
  kaz: '2015-2017 жылдарға арналған Мәртөк ауданының бюджеті туралы '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-23
approved_by:
- '153008000002'
version_date:
  kaz: 2015-07-31
  rus: 2015-07-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/85943/kaz/31.07.2015
  rus: https://zan.gov.kz/client/#!/doc/85943/rus/31.07.2015
caused_by:
  code: '92696'
  requisite: Решение от 31.07.2015 №194, Маслихат Мартукского района
  title:
    rus: О внесении изменений в решение Мартукского районного маслихата от 23 декабря 2014 года № 150 «О бюджете Мартукского района на 2015-2017 годы»
    kaz: Мәртөк аудандық мәслихаттың «2015-2017 жылдарға арналған Мәртөк ауданының бюджеті туралы» 2014 жылғы 23 желтоқсандағы № 150 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/92696/rus
