act_code: '52514'
requisite: Ақтөбе облысы Темір ауданы Шұбарқұдық ауылдық округ әкімінің 2010 жылғы 22 сәуірдегі № 50 шешімі. Ақтөбе облысының Темір аудандық Әділет басқармасында 2010 жылдың 7 мамырда № 3-10-130 тіркелді
title:
  rus: Шұбарқұдық ауылының көшесіне атау беру туралы
  kaz: Шұбарқұдық ауылының көшесіне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-22
approved_by:
- '153010009002'
version_date:
  kaz: 2010-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/52514/kaz/22.04.2010
