act_code: '190193'
requisite: Решение Кобдинского районного маслихата Актюбинской области от 7 декабря 2023 года № 92. Зарегистрировано Департаментом юстиции Актюбинской области 13 декабря 2023 года № 8459
title:
  rus: Об утверждении Правил оказания социальной помощи, установления её размеров и определения перечня отдельных категорий нуждающихся граждан в Кобдинском районе
  kaz: Қобда ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-12-07
approved_by:
- '153012000002'
version_date:
  kaz: 2024-06-28
  rus: 2024-06-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/190193/kaz/28.06.2024
  rus: https://zan.gov.kz/client/#!/doc/190193/rus/28.06.2024
caused_by:
  code: '198527'
  requisite: Решение Кобдинского районного маслихата Актюбинской области от 28 июня 2024 года № 181. Зарегистрировано Департаментом юстиции Актюбинской области 3 июля 2024 года № 8604-04
  title:
    rus: О внесении изменения в решение Кобдинского районного маслихата от 7 декабря 2023 года № 92 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан в Кобдинском районе»
    kaz: Қобда аудандық мәслихатының 2023 жылғы 7 желтоқсандағы № 92 «Қобда ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/198527/rus
