act_code: '145054'
requisite: Решение акима Кызылсуского сельского округа Хромтауского района Актюбинской области от 17 июля 2020 года № 6. Зарегистрировано Департаментом юстиции Актюбинской области 23 июля 2020 года № 7316. Утратило силу решением акима Кызылсуского сельского округа Хромтауского района Актюбинской области от 11 ноября 2020 года № 11
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-07-17
approved_by:
- '153013010002'
version_date:
  kaz: 2020-07-17
  rus: 2020-07-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/145054/kaz/17.07.2020
  rus: https://zan.gov.kz/client/#!/doc/145054/rus/17.07.2020
