act_code: '77265'
requisite: Решение акима Уилского района Актюбинской области от 24 января 2014 года № 3. Зарегистрировано Департаментом юстиции Актюбинской области 4 февраля 2014 года № 3774. Утратило силу решением акима Уилского района Актюбинской области от 14 февраля 2020 года № 1
title:
  rus: Об образовании избирательных участков на территории Уилского района
  kaz: Ойыл ауданы аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-01-24
approved_by:
- '153011000003'
version_date:
  kaz: 2018-11-29
  rus: 2018-11-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/77265/kaz/29.11.2018
  rus: https://zan.gov.kz/client/#!/doc/77265/rus/29.11.2018
caused_by:
  code: '126478'
  requisite: Решение акима Уилского района Актюбинской области от 29 ноября 2018 года № 5. Зарегистрировано Управлением юстиции Уилского района Департамента юстиции Актюбинской области 30 ноября 2018 года № 3-11-147. Утратило силу решением акима Уилского района Актюбинской области от 14 февраля 2020 года № 1
  title:
    rus: О внесении изменений в решение акима Уилского района от 24 января 2014 года № 3 «Об образовании избирательных участков на территории Уилского района»
    kaz: Ойыл ауданы әкімінің 2014 жылғы 24 қаңтардағы № 3 «Ойыл ауданы аумағында сайлау учаскелерін құру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/126478/rus
