act_code: '50222'
requisite: Ақтөбе облысы Алға ауданының әкімінің 2009 жылғы 25 желтоқсандағы N 5 шешімі. Ақтөбе облысының Алға аудандық әділет басқармасында 2010 жылдың 26 қаңтарда N 3-3-101 тіркелді. Күші жойылды - Ақтөбе облысы Алға ауданы әкімінің 2010 жылғы 14 желтоқсандағы № 6 шешімімен
title:
  rus: Алға ауданы Қорғаныс істері бөлімінің шакыру участкесіне 1993 жылы туылған ер азаматтарды тіркеуге алу жұмысын жүргізу туралы
  kaz: Алға ауданы Қорғаныс істері бөлімінің шакыру участкесіне 1993 жылы туылған ер азаматтарды тіркеуге алу жұмысын жүргізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '153004000001'
version_date:
  kaz: 2009-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/50222/kaz/25.12.2009
