act_code: '38773'
requisite: Решение Актюбинского областного Маслихата от 26 марта 2008 года N 52. Зарегистрировано Департаментом юстиции Актюбинской области 4 апреля 2008 года за N 3240. Утратило силу решением Актюбинского областного маслихата от 21 декабря 2009 года № 235
title:
  rus: Об утверждении размеров ставок платы за пользование водными ресурсами из поверхностных источников
  kaz: Жер үсті көздеріндегі су ресурстарын пайдаланғаны үшін төлемақы ставкілерінің мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-03-26
approved_by:
- '153000000002'
version_date:
  kaz: 2008-03-26
  rus: 2008-03-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/38773/kaz/26.03.2008
  rus: https://zan.gov.kz/client/#!/doc/38773/rus/26.03.2008
