act_code: '98229'
requisite: Решение маслихата Иргизского района Актюбинской области от 23 декабря 2015 года № 227. Зарегистрировано Департаментом юстиции Актюбинской области 25 января 2016 года № 4712. Утратило силу - решением маслихата Иргизского района Актюбинской области от 29 августа 2016 года № 37.
title:
  rus: Об утверждении Положения государственного учреждения "Аппарат Иргизского районного маслихата"
  kaz: '"Ырғыз аудандық мәслихатының аппараты" мемлекеттік мекемесінің Ережесін бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-23
approved_by:
- '153006000002'
version_date:
  kaz: 2015-12-23
  rus: 2015-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/98229/kaz/23.12.2015
  rus: https://zan.gov.kz/client/#!/doc/98229/rus/23.12.2015
