act_code: '219927'
requisite: Решение Байганинского районного маслихата Актюбинской области от 19 декабря 2025 года № 348
title:
  rus: Об утверждении бюджета Ащынского сельского округа на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған Ащы ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-19
approved_by:
- '153005000002'
version_date:
  kaz: 2026-04-10
  rus: 2026-04-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/219927/kaz/10.04.2026
  rus: https://zan.gov.kz/client/#!/doc/219927/rus/10.04.2026
caused_by:
  code: '224210'
  requisite: Решение Байганинского районного маслихата Актюбинской области от 10 апреля 2026 года № 370
  title:
    rus: О внесении изменения в решение «Об утверждении бюджета Ащынского сельского округа на 2026-2028 годы» от 19 декабря 2025 года № 348
    kaz: «2026-2028 жылдарға арналған Ащы ауылдық округінің бюджетін бекіту туралы» 2025 жылғы 19 желтоқсандағы № 348 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/224210/rus
