act_code: '61896'
requisite: Решение акима Байнассайского сельского округа Мартукского района Актюбинской обласити от 22 ноября 2011 года № 1. Зарегистрировано Управлением юстиции Мартукского района Актюбинской области 7 декабря 2011 года № 3-8-143
title:
  rus: О присвоении наименований улицам села Байнассай
  kaz: Байнассай ауылының көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-11-22
approved_by:
- '153008007002'
version_date:
  kaz: 2019-06-04
  rus: 2019-06-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/61896/kaz/04.06.2019
  rus: https://zan.gov.kz/client/#!/doc/61896/rus/04.06.2019
caused_by:
  code: '132145'
  requisite: Решение акима Байнассайского сельского округа Мартукского района Актюбинской области от 4 июня 2019 года № 1. Зарегистрировано Департаментом юстиции Актюбинской области 5 июня 2019 года № 6224
  title:
    rus: О внесении изменений в решение акима Байнассайского сельского округа от 22 ноября 2011 года № 1 «О наименовании улиц села Байнассай»
    kaz: Байнассай ауылдық округі әкімінің 2011 жылғы 22 қарашадағы № 1 «Байнассай ауылының көшелеріне атау беру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/132145/rus
