act_code: '42884'
requisite: Ақтөбе облысы Қобда аудандық әкімдігінің 2008 жылғы 3 желтоқсандағы № 7 шешімі. Ақтөбе облысының Қобда аудандық Әділет басқармасында 2008 жылдың 22 желтоқсанда № 3-7-56 тіркелді. Қолданылу мерзімінің аяқталуына байланысты күші жойылды - (Ақтөбе облысы Қобда аудандық әкімінің аппаратының 2013 жылғы 22 ақпандағы № 04-53 хатымен)
title:
  rus: 1992 жылы туылған азаматтарды қорғаныс істері жөніндегі бөлімінің шақыру учаскесіне тіркеуді өткізу туралы
  kaz: 1992 жылы туылған азаматтарды қорғаныс істері жөніндегі бөлімінің шақыру учаскесіне тіркеуді өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-03
approved_by:
- '153012000001'
version_date:
  kaz: 2008-12-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/42884/kaz/03.12.2008
