act_code: '45454'
requisite: Ақтөбе облысы Алға аудандық мәслихатының 2009 жылғы 8 сәуірдегі N 4 шешімі. Ақтөбе облысының Алға аудандық әділет басқармасында 2009 жылдың 27 сәуірде N 3-3-74 тіркелді. Күші жойылды - Ақтөбе облысы Алға аудандық мәслихатының 2012 жылғы 21 желтоқсандағы № 64 шешімімен
title:
  rus: Алға қаласындағы базарларда тауар сататын жеке тұлғалар үшін бір жолғы талондардың бағасын белгілеу туралы
  kaz: Алға қаласындағы базарларда тауар сататын жеке тұлғалар үшін бір жолғы талондардың бағасын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-08
approved_by:
- '153004000002'
version_date:
  kaz: 2009-10-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/45454/kaz/20.10.2009
caused_by:
  code: '48702'
  requisite: Ақтөбе облысы Алға аудандық мәслихатының 2009 жылғы 20 қазандағы № 6 шешімі. Ақтөбе облысының Алға аудандық Әділет басқармасында 2009 жылдың 16 қарашада № 3-3-93 тіркелді. Күші жойылды - Ақтөбе облысы Алға аудандық мәслихатының 2012 жылғы 21 желтоқсандағы № 64 шешімімен
  title:
    rus: Аудандық мәслихаттың 2009 жылғы 8 сәуірдегі № 4 "Алға қаласындағы базарларда тауар сататын жеке тұлғалар үшін бір жолғы талондардың бағасын белгілеу туралы" шешіміне өзгеріс енгізу туралы
    kaz: Аудандық мәслихаттың 2009 жылғы 8 сәуірдегі № 4 "Алға қаласындағы базарларда тауар сататын жеке тұлғалар үшін бір жолғы талондардың бағасын белгілеу туралы" шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/48702/rus
