act_code: '163992'
requisite: Решение Мартукского районного маслихата Актюбинской области от 12 января 2022 года № 94
title:
  rus: Об утверждении бюджетов сельских округов Мартукского района на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Мәртөк ауданының ауылдық округтерінің бюджеттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-01-12
approved_by:
- '153008000002'
version_date:
  kaz: 2022-11-23
  rus: 2022-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/163992/kaz/23.11.2022
  rus: https://zan.gov.kz/client/#!/doc/163992/rus/23.11.2022
caused_by:
  code: '174256'
  requisite: Решение Мартукского районного маслихата Актюбинской области от 23 ноября 2022 года № 139
  title:
    rus: О внесении изменений в решение Мартукского районного маслихата от 12 января 2022 года № 94 «Об утверждении бюджетов сельских округов Мартукского района на 2022-2024 годы»
    kaz: Мәртөк аудандық мәслихатының 2022 жылғы 12 қаңтардағы № 94 «2022-2024 жылдарға арналған Мәртөк ауданының ауылдық округтерінің бюджеттерін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/174256/rus
