act_code: '23615'
requisite: Ақтөбе облысы Темір ауданы Шұбарқұдық кент округінің 2005 жылғы 6 сәуірдегі № 31 шешімі. Ақтөбе облысы Әділет департаментінің Темір ауданының Әділет басқармасында 2005 жылғы 28 сәуірде № 3-10-2 болып тіркелді
title:
  rus: Шұбарқұдық кент округіне қарасты елді мекендерді көркейту, санитарлық тазалау және көгалдандыру айлығын өткізу туралы
  kaz: Шұбарқұдық кент округіне қарасты елді мекендерді көркейту, санитарлық тазалау және көгалдандыру айлығын өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-04-06
approved_by:
- '153010009002'
version_date:
  kaz: 2005-04-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/23615/kaz/06.04.2005
