act_code: '73294'
requisite: Решение маслихата Актюбинской области от 5 июня 2013 года № 122. Зарегистрировано Департаментом юстиции Актюбинской области 4 июля 2013 года № 3601. Утратило силу решением маслихата Актюбинской области от 24 декабря 2021 года № 108
title:
  rus: О Правилах содержания собак и кошек в городах и других населенных пунктах Актюбинской области
  kaz: Ақтөбе облысының қалаларында және басқа да елдi мекендерінде иттер мен мысықтарды асырау және серуендету, қаңғыбас иттер мен мысықтарды аулау және жою Қағидалары туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2013-06-05
approved_by:
- '153000000002'
version_date:
  kaz: 2013-06-05
  rus: 2013-06-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/73294/kaz/05.06.2013
  rus: https://zan.gov.kz/client/#!/doc/73294/rus/05.06.2013
