act_code: '73294'
requisite: Решение маслихата Актюбинской области от 5 июня 2013 года № 122. Зарегистрировано Департаментом юстиции Актюбинской области 4 июля 2013 года № 3601. Утратило силу решением маслихата Актюбинской области от 24 декабря 2021 года № 108
title:
  rus: О Правилах содержания собак и кошек в городах и других населенных пунктах Актюбинской области
  kaz: Ақтөбе облысының қалаларында және басқа да елдi мекендерінде иттер мен мысықтарды асырау және серуендету, қаңғыбас иттер мен мысықтарды аулау және жою Қағидалары туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2013-06-05
approved_by:
- '153000000002'
version_date:
  kaz: 2020-06-05
  rus: 2020-06-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/73294/kaz/05.06.2020
  rus: https://zan.gov.kz/client/#!/doc/73294/rus/05.06.2020
caused_by:
  code: '143806'
  requisite: Решение маслихата Актюбинской области от 5 июня 2020 года № 531. Зарегистрировано Департаментом юстиции Актюбинской области 11 июня 2020 года № 7175. Утратило силу решением маслихата Актюбинской области от 24 декабря 2021 года № 108
  title:
    rus: О внесении изменений и дополнений в решение областного маслихата от 5 июня 2013 года № 122 «О Правилах содержания и выгула собак и кошек, отлова и уничтожения бродячих собак и кошек в городах и других населенных пунктах Актюбинской области»
    kaz: Облыстық мәслихаттың 2013 жылғы 5 маусымдағы № 122 «Ақтөбе облысының қалаларында және басқа да елді мекендерінде иттер мен мысықтарды асырау және серуендету, қаңғыбас иттер мен мысықтарды аулау және жою Қағидалары туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/143806/rus
