act_code: '6690'
requisite: Решение акима Актюбинской области от 15 июня 2000 года № 86. Зарегистрировано Управлением юстиции Актюбинской области 8 августа 2000 года № 647
title:
  rus: О размещении государственного заказа в средних профессиональных учебных заведениях
  kaz: Орта кәсіптік білім беретін оқу орындарында мемлекеттік тапсырысты орналастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-06-14
approved_by:
- '153000000003'
version_date:
  kaz: 2000-06-14
  rus: 2000-06-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/6690/kaz/14.06.2000
  rus: https://zan.gov.kz/client/#!/doc/6690/rus/14.06.2000
