act_code: '372'
requisite: Решение акима Актюбинской области от 21 июля 1997 года № 144. Зарегистрировано Управлением юстиции Актюбинской области 24 ноября 1997 года № 4. Утратило силу решением акима Актюбинской области от 6 декабря 2004 года № 12
title:
  rus: Об образовании городского отдела экономики и государственной поддержки развития малого предпринимательства
  kaz: Ақтөбе қалалық экономика және шағын кәсіпкерліктің дамуын мемлекеттік қолдау бөлімін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1997-07-20
approved_by:
- '153000000003'
version_date:
  kaz: 1997-07-20
  rus: 1997-07-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/372/kaz/20.07.1997
  rus: https://zan.gov.kz/client/#!/doc/372/rus/20.07.1997
