act_code: '31283'
requisite: Решение очередной тридцать пятой сессии Маслихата города Актобе Актюбинской области от 26 декабря 2006 года N 284. Зарегистрировано в Управлении юстиции города Актобе Актюбинской области 9 января 2007 года за N 3-1-63. Утратило силу в связи с истечением срока действия - письмом управления юстиции города Актобе Актюбинской области от 10 января 2008 года N 1-06/82
title:
  rus: О бюджете города Актобе на 2007 год
  kaz: 2007 жылғы арналған Ақтөбе қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-26
approved_by:
- '153002000002'
version_date:
  kaz: 2007-10-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/31283/kaz/30.10.2007
caused_by:
  code: '35759'
  requisite: Решение внеочередной второй сессии маслихата города Актобе Актюбинской области от 30 октября 2007 года N 16. Зарегистрировано Управлением юстиции города Актобе Актюбинской области 14 ноября 2007 года N 3-1-77. Утратило силу в связи с истечением срока действия - (письмо Управления юстиции города Актобе Актюбинской области от 10 января 2008 года N 1-06/82)
  title:
    rus: О внесении изменений и дополнений в решение N 284 очередной тридцать пятой сессии маслихата города Актобе от 26 декабря 2006 года "О бюджете города Актобе на 2007 год", зарегистрированного в управлении юстиции 9 января 2007 года за N 3-1-63
    kaz: Ақтөбе қалалық мәслихатының кезекті отыз бесінші сессиясының 2006 жылғы 26 желтоқсандағы "2007 жылға арналған Ақтөбе қаласының бюджеті туралы" әділет басқармасында 2007 жылғы 9 қаңтарда N 3-1-63 санымен тіркелген N 284 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/35759/rus
