act_code: '178127'
requisite: Решение Хромтауского районного маслихата Актюбинской области от 30 декабря 2022 года № 323
title:
  rus: Об утверждении бюджета Копинского сельского округа на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Қопа ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-30
approved_by:
- '153013000002'
version_date:
  kaz: 2023-04-14
  rus: 2023-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/178127/kaz/14.04.2023
  rus: https://zan.gov.kz/client/#!/doc/178127/rus/14.04.2023
caused_by:
  code: '180164'
  requisite: Решение Хромтауского районного маслихата Актюбинской области от 14 апреля 2023 года № 22
  title:
    rus: О внесении изменений в решение Хромтауского районного маслихата от 30 декабря 2022 года № 323 «Об утверждении бюджета Копинского сельского округа на 2023-2025 годы»
    kaz: Хромтау аудандық мәслихатының 2022 жылғы 30 желтоқсанындағы № 323 шешімі негізінде «2023-2025 жылдарға арналған Қопа ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/180164/rus
