act_code: '43500'
requisite: Ақтөбе облысы Алға аудандық мәслихатының 2008 жылғы 23 желтоқсандағы N 3 шешімі. Ақтөбе облысының Алға аудандық Әділет басқармасында 2009 жылғы 14 қаңтарда N 3-3-68 тіркелді. Шешімнің қабылдау мерзімінің отуіне байланысты қолдану тоқтатылды - Ақтөбе облысы Алға аудандық мәслихатының 2009 жылғы 31 желтоқсандағы N 0-04/413 хатымен
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-23
approved_by:
- '153004000002'
version_date:
  kaz: 2009-10-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/43500/kaz/20.10.2009
caused_by:
  code: '48518'
  requisite: Ақтөбе облысы Алға аудандық мәслихатының 2009 жылғы 20 қазандағы № 2 шешімі. Ақтөбе облысының Алға аудандық Әділет басқармасында 2009 жылдың 09 қарашада № 3-3-90 тіркелді. Шешімнің қабылдау мерзімінің өтуіне байланысты қолдану тоқтатылды - Ақтөбе облысы Алға аудандық мәслихатының 2009 жылғы 31 желтоқсандағы N 0-04/413 хатымен
  title:
    rus: Аудандық мәслихаттың 2008 жылғы 23 желтоқсандағы № 3 "2009 жылға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Аудандық мәслихаттың 2008 жылғы 23 желтоқсандағы № 3 "2009 жылға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/48518/rus
