act_code: '50237'
requisite: Решение маслихата Актюбинской области от 21 декабря 2009 года № 236. Зарегистрировано Департаментом юстиции Актюбинской области 27 января 2010 года № 3326
title:
  rus: О ставках платы за лесные пользования на участках государственного лесного фонда
  kaz: Мемлекеттік орман қоры учаскелерінде орман пайдалану төлемақысының мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-21
approved_by:
- '153000000002'
version_date:
  kaz: 2016-06-03
  rus: 2016-06-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/50237/kaz/03.06.2016
  rus: https://zan.gov.kz/client/#!/doc/50237/rus/03.06.2016
caused_by:
  code: '103993'
  requisite: Решение маслихата Актюбинской области от 3 июня 2016 года № 24. Зарегистрировано Департаментом юстиции Актюбинской области 5 июля 2016 года № 4982
  title:
    rus: О внесении изменений и дополнений в решение областного маслихата от 21 декабря 2009 года № 236 "О ставках платы за лесные пользования на участках государственного лесного фонда"
    kaz: '"Мемлекеттік орман қоры учаскелерінде орман пайдалану төлемақысының ставкалары туралы" облыстық мәслихаттың 2009 жылғы 21 желтоқсандағы № 236 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/103993/rus
