act_code: '165344'
requisite: Решение акима Культабанского сельского округа Байганинского района Актюбинской области от 18 февраля 2022 года № 3. Зарегистрировано в Министерстве юстиции Республики Казахстан 28 февраля 2022 года № 26941. Утратило силу решением акима Культабанского сельского округа Байганинского района Актюбинской области от 20 апреля 2022 года № 8
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-02-18
approved_by:
- '153005004002'
version_date:
  kaz: 2022-02-18
  rus: 2022-02-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/165344/kaz/18.02.2022
  rus: https://zan.gov.kz/client/#!/doc/165344/rus/18.02.2022
