act_code: '195574'
requisite: Решение акима Карауылкелдинского сельского округа Байганинского района Актюбинской области от 9 апреля 2024 года № 38
title:
  rus: О снятии ограничительных мероприятий и признании утратившим силу решения акима Карауылкелдинского сельского округа от 16 января 2024 года № 9 «Об установлении ограничительных мероприятий»
  kaz: Шектеу іс-шараларын алу және Қарауылкелді ауылдық округі әкімінің «Шектеу іс-шараларын белгілеу туралы» 2024 жылғы 16 қаңтардағы № 9 шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-04-09
approved_by:
- '153005008002'
version_date:
  kaz: 2024-04-09
  rus: 2024-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/195574/kaz/09.04.2024
  rus: https://zan.gov.kz/client/#!/doc/195574/rus/09.04.2024
