act_code: '206548'
requisite: Решение Мугалжарского районного маслихата Актюбинской области от 30 декабря 2024 года № 330
title:
  rus: Об утверждении бюджета Кайындинского сельского округа на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Қайыңды ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '153009000002'
version_date:
  kaz: 2025-11-05
  rus: 2025-11-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/206548/kaz/05.11.2025
  rus: https://zan.gov.kz/client/#!/doc/206548/rus/05.11.2025
caused_by:
  code: '216992'
  requisite: Решение Мугалжарского районного маслихата Актюбинской области от 5 ноября 2025 года № 465
  title:
    rus: О внесении изменений в решение Мугалжарского районного маслихата от 30 декабря 2024 года № 330 «Об утверждении бюджета Кайындинского сельского округа на 2025-2027 годы»
    kaz: Мұғалжар аудандық мәслихатының 2024 жылғы 30 желтоқсандағы № 330 «2025-2027 жылдарға арналған Қайыңды ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/216992/rus
