act_code: '176377'
requisite: Решение Кобдинского районного маслихата Актюбинской области от 21 декабря 2022 года № 260
title:
  rus: Об утверждении Кобдинского районного бюджета на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Қобда аудандық бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-21
approved_by:
- '153012000002'
version_date:
  kaz: 2023-04-27
  rus: 2023-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/176377/kaz/27.04.2023
  rus: https://zan.gov.kz/client/#!/doc/176377/rus/27.04.2023
caused_by:
  code: '180987'
  requisite: Решение Кобдинского районного маслихата Актюбинской области от 27 апреля 2023 года № 10
  title:
    rus: О внесении изменений и дополнений в решение Кобдинского районного маслихата от 21 декабря 2022 года № 260 «Об утверждении Кобдинского районного бюджета на 2023-2025 годы»
    kaz: Қобда аудандық мәслихатының 2022 жылғы 21 желтоқсандағы «2023-2025 жылдарға арналған Қобда аудандық бюджетін бекіту туралы» № 260 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/180987/rus
