act_code: '150882'
requisite: Решение маслихата города Актобе Актюбинской области от 22 декабря 2020 года № 617. Зарегистрировано Департаментом юстиции Актюбинской области 28 декабря 2020 года № 7855
title:
  rus: Об утверждении бюджета города Актобе на 2021 - 2023 годы
  kaz: 2021 - 2023 жылдарға арналған Ақтөбе қаласының бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-22
approved_by:
- '153002000002'
version_date:
  kaz: 2021-12-15
  rus: 2021-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/150882/kaz/15.12.2021
  rus: https://zan.gov.kz/client/#!/doc/150882/rus/15.12.2021
caused_by:
  code: '162226'
  requisite: Решение маслихата города Актобе Актюбинской области от 15 декабря 2021 года № 112. Зарегистрировано в Министерстве юстиции Республики Казахстан 23 декабря 2021 года № 25947
  title:
    rus: О внесении изменений в решение маслихата города Актобе от 22 декабря 2020 года № 617 «Об утверждении бюджета города Актобе на 2021-2023 годы»
    kaz: Ақтөбе қалалық мәслихатының 2020 жылғы 22 желтоқсандағы № 617 «2021-2023 жылдарға арналған Ақтөбе қаласының бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/162226/rus
