act_code: '195281'
requisite: Решение Айтекебийского районного маслихата Актюбинской области от 27 марта 2024 года № 179. Зарегистрировано Департаментом юстиции Актюбинской области 2 апреля 2024 года № 8554-04
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2024 год по Айтекебийскому району
  kaz: Әйтеке би ауданы бойынша 2024 жылға шетелдіктер үшін туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-27
approved_by:
- '153003000002'
version_date:
  kaz: 2024-03-27
  rus: 2024-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/195281/kaz/27.03.2024
  rus: https://zan.gov.kz/client/#!/doc/195281/rus/27.03.2024
