act_code: '47583'
requisite: Ақтөбе облысы Қобда аудандық мәслихатының 2009 жылғы 22 шілдедегі N 106 шешімі. Ақтөбе облысы Қобда ауданының Әділет басқармасында 2009 жылдың 28 тамызда N 3-7-75 тіркелді. Күші жойылды - Ақтөбе облысы Қобда аудандық мәслихатының 2010 жылғы 07 шілдедегі N 143 шешімімен
title:
  rus: Жерді аймақтарға бөлу жобасын бекіту туралы
  kaz: Жерді аймақтарға бөлу жобасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-07-22
approved_by:
- '153012000002'
version_date:
  kaz: 2009-07-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/47583/kaz/22.07.2009
