act_code: '72089'
requisite: Решение маслихата Хромтауского района Актюбинской области от 27 марта 2013 года № 98. Зарегистрировано Департаментом юстиции Актюбинской области 23 апреля 2013 года № 3566. Утратило силу решением маслихата Хромтауского района Актюбинской области от 17 февраля 2017 года № 89
title:
  rus: Об утверждении Правил оказания жилищной помощи малообеспеченным семьям (гражданам), проживающим в Хромтауском районе
  kaz: Хромтау ауданында тұратын аз қамтылған отбасыларына (азаматтарға) тұрғын үй көмегін көрсету Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2013-03-27
approved_by:
- '153013000002'
version_date:
  kaz: 2013-03-27
  rus: 2013-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/72089/kaz/27.03.2013
  rus: https://zan.gov.kz/client/#!/doc/72089/rus/27.03.2013
