act_code: '163402'
requisite: Решение Хромтауского районного маслихата Актюбинской области от 30 декабря 2021 года № 171
title:
  rus: Об утверждении бюджета села Никельтау на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Никельтау ауылының бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '153013000002'
version_date:
  kaz: 2021-12-30
  rus: 2021-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/163402/kaz/30.12.2021
  rus: https://zan.gov.kz/client/#!/doc/163402/rus/30.12.2021
