act_code: '163402'
requisite: Решение Хромтауского районного маслихата Актюбинской области от 30 декабря 2021 года № 171
title:
  rus: Об утверждении бюджета села Никельтау на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Никельтау ауылының бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '153013000002'
version_date:
  kaz: 2022-04-07
  rus: 2022-04-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/163402/kaz/07.04.2022
  rus: https://zan.gov.kz/client/#!/doc/163402/rus/07.04.2022
caused_by:
  code: '166931'
  requisite: Решение Хромтауского районного маслихата Актюбинской области от 7 апреля 2022 года № 210
  title:
    rus: О внесении изменений в решение Хромтауского районного маслихата от 30 декабря 2021 года № 171 «Об утверждении бюджета села Никельтау на 2022-2024 годы»
    kaz: Хромтау аудандық мәслихатының 2021 жылғы 30 желтоқсандағы № 171 «2022-2024 жылдарға арналған Никельтау ауылының бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/166931/rus
