act_code: '219836'
requisite: Решение Актюбинского областного маслихата от 10 декабря 2025 года № 298
title:
  rus: Об областном бюджете на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-10
approved_by:
- '153000000002'
version_date:
  kaz: 2026-03-31
  rus: 2026-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/219836/kaz/31.03.2026
  rus: https://zan.gov.kz/client/#!/doc/219836/rus/31.03.2026
caused_by:
  code: '224050'
  requisite: Решение Актюбинского областного маслихата от 31 марта 2026 года № 314
  title:
    rus: О внесении изменений и дополнений в решение областного маслихата от 10 декабря 2025 года № 298 «Об областном бюджете на 2026-2028 годы»
    kaz: Облыстық мәслихаттың 2025 жылғы 10 желтоқсандағы № 298 «2026-2028 жылдарға арналған облыстық бюджет туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/224050/rus
