act_code: '138640'
requisite: Решение Кобдинского районного маслихата Актюбинской области от 8 января 2020 года № 285. Зарегистрировано Департаментом юстиции Актюбинской области 14 января 2020 года № 6680
title:
  rus: Об утверждении бюджета Бестауского сельского округа на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Бестау ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-08
approved_by:
- '153012000002'
version_date:
  kaz: 2020-11-26
  rus: 2020-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/138640/kaz/26.11.2020
  rus: https://zan.gov.kz/client/#!/doc/138640/rus/26.11.2020
caused_by:
  code: '149549'
  requisite: Решение Кобдинского районного маслихата Актюбинской области от 26 ноября 2020 года № 389. Зарегистрировано Департаментом юстиции Актюбинской области 8 декабря 2020 года № 7761
  title:
    rus: О внесении изменений в решение Кобдинского районного маслихата от 8 января 2020 года № 285 «Об утверждении бюджета Бестауского сельского округа на 2020-2022 годы»
    kaz: Қобда аудандық мәслихатының 2020 жылғы 8 қаңтардағы № 285 «2020-2022 жылдарға арналған Бестау ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149549/rus
