act_code: '98175'
requisite: Решение маслихата Мартуксого района Актюбинской области от 25 декабря 2015 года № 205. Зарегистрировано Департаментом юстиции Актюбинской области 22 января 2016 года № 4702
title:
  rus: Об утверждении бюджета Мартукского района на 2016-2018 годы
  kaz: 2016-2018 жылдарға арналған Мәртөк ауданының бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-25
approved_by:
- '153008000002'
version_date:
  kaz: 2016-08-26
  rus: 2016-08-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/98175/kaz/26.08.2016
  rus: https://zan.gov.kz/client/#!/doc/98175/rus/26.08.2016
caused_by:
  code: '105955'
  requisite: Решение маслихата Мартукского района Актюбинской области от 26 августа 2016 года № 34. Зарегистрировано Департаментом юстиции Актюбинской области 8 сентября 2016 года № 5058
  title:
    rus: О внесении изменений и дополнений в решение Мартукского районного маслихата от 25 декабря 2015 года № 205 "Об утверждении бюджета Мартукского района на 2016-2018 годы"
    kaz: '"2016-2018 жылдарға арналған Мәртөк ауданының бюджетін бекіту туралы" 2015 жылғы 25 желтоқсандағы № 205 Мәртөк аудандық мәслихаттың шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/105955/rus
