act_code: '5739'
requisite: Решение акима Актюбинской области от 12 января 2000 года № 5. Зарегистрировано Управлением юстиции Актюбинской области 12 апреля 2000 года № 446
title:
  rus: Об организации обучения населения области мерам защиты и действиям в чрезвычайных ситуациях
  kaz: Төтенше жағдайлар кезіңде қорғаныс шараларын және іс-қимылдарын облыс халқына оқытуды ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-01-12
approved_by:
- '153000000003'
version_date:
  kaz: 2000-01-12
  rus: 2000-01-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/5739/kaz/12.01.2000
  rus: https://zan.gov.kz/client/#!/doc/5739/rus/12.01.2000
