act_code: '120129'
requisite: Решение маслихата Иргизского района Актюбинской области от 5 марта 2018 года № 134. Зарегистрировано Управлением юстиции Иргизского района Актюбинской области 26 марта 2018 года № 3-5-169. Утратило силу решением маслихата Иргизского района Актюбинской области от 7 декабря 2018 года № 180
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Иргизскому району на 2018–2019 годы
  kaz: Ырғыз ауданы бойынша 2018–2019 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарын бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2018-03-05
approved_by:
- '153006000002'
version_date:
  kaz: 2018-03-05
  rus: 2018-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/120129/kaz/05.03.2018
  rus: https://zan.gov.kz/client/#!/doc/120129/rus/05.03.2018
