act_code: '30793'
requisite: Решение Актюбинского областного маслихата от 12 декабря 2006 года № 317. Зарегистрировано Департаментом юстиции Актюбинской области 25 декабря 2006 года № 3193. Утратило силу решением маслихата Актюбинской области от 14 августа 2013 года № 152
title:
  rus: О предоставлении льгот
  kaz: Жеңілдіктер беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-12
approved_by:
- '153000000002'
version_date:
  kaz: 2007-07-11
  rus: 2007-07-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/30793/kaz/11.07.2007
  rus: https://zan.gov.kz/client/#!/doc/30793/rus/11.07.2007
caused_by:
  code: '34283'
  requisite: Решение Актюбинского областного Маслихата от 11 июля 2007 года № 376. Зарегистрировано Департаментом юстиции Актюбинской области 27 июля 2006 года № 3224. Утратило силу решением маслихата Актюбинской области от 14 августа 2013 года № 152
  title:
    rus: О внесении дополнений в решение областного маслихата от 12 декабря 2006 года N 317 "О предоставлении льгот"
    kaz: Облыстық мәслихаттың 2006 жылғы 12 желтоқсандағы N 317 "Жеңілдіктер беру туралы" шешіміне толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/34283/rus
