act_code: '30793'
requisite: Решение Актюбинского областного маслихата от 12 декабря 2006 года № 317. Зарегистрировано Департаментом юстиции Актюбинской области 25 декабря 2006 года № 3193. Утратило силу решением маслихата Актюбинской области от 14 августа 2013 года № 152
title:
  rus: О предоставлении льгот
  kaz: Жеңілдіктер беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-12
approved_by:
- '153000000002'
version_date:
  rus: 2008-03-26
source:
  rus: https://zan.gov.kz/client/#!/doc/30793/rus/26.03.2008
caused_by:
  code: '38835'
  requisite: Решение Актюбинского областного маслихата от 26 марта 2008 года N 53. Зарегистрировано Департаментом юстиции Актюбинской области 10 апреля 2008 года N 3247. Утратило силу решением маслихата Актюбинской области от 14 августа 2013 года № 152
  title:
    rus: О внесении изменений и дополнений в решение областного маслихата от 12 декабря 2006 года N 317 "О предоставлении льгот"
    kaz: Облыстық мәслихаттың 2006 жылғы 12 желтоқсандағы N 317 "Жеңілдіктер беру туралы" шешіміне толықтырулар мен өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/38835/rus
