act_code: '146859'
requisite: Решение Каргалинского районного маслихата Актюбинской области от 16 сентября 2020 года № 501. Зарегистрировано Департаментом юстиции Актюбинской области 25 сентября 2020 года № 7487
title:
  rus: Об определении специализированных мест для организации и проведения мирных собраний, порядка использования специализированных мест для организации и проведения мирных собраний, норм их предельной заполняемости, а также требований к материально-техническому и организационному обеспечению специализированных мест для организации и проведения мирных собраний, границ прилегающих территорий, в которых запрещено проведение пикетирования в Каргалинском районе
  kaz: Қарғалы ауданында бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды пайдалану тәртібін, олардың шекті толу нормаларын, сондай-ақ бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптарды, пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекараларын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-16
approved_by:
- '153007000002'
version_date:
  kaz: 2024-02-09
  rus: 2024-02-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/146859/kaz/09.02.2024
  rus: https://zan.gov.kz/client/#!/doc/146859/rus/09.02.2024
caused_by:
  code: '193245'
  requisite: Решение Каргалинского районного маслихата Актюбинской области от 9 февраля 2024 года № 129. Зарегистрировано Департаментом юстиции Актюбинской области 13 февраля 2024 года № 8500
  title:
    rus: О внесении изменения в решение Каргалинского районного маслихата от 16 сентября 2020 года № 501 «Об определении специализированных мест для организации и проведения мирных собраний, порядка использования специализированных мест для организации и проведения мирных собраний, норм их предельной заполняемости, а также требований к материально-техническому и организационному обеспечению специализированных мест для организации и проведения мирных собраний, границ прилегающих территорий, в которых запрещено проведение пикетирования в Каргалинском районе»
    kaz: Қарғалы аудандық мәслихатының 2020 жылғы 16 қыркүйектегі № 501 «Қарғалы ауданында бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды пайдалану тәртібін, олардың шекті толу нормаларын, сондай-ақ бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптарды, пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекараларын айқындау туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/193245/rus
