act_code: '69830'
requisite: Решение маслихата Алгинского района Актюбинской области от 21 декабря 2012 года № 62. Зарегистрировано Департаментом юстиции Актюбинской области 9 января 2013 года № 3483. Утратило силу решением маслихата Алгинского района Актюбинской области от 24 декабря 2013 года № 130
title:
  rus: О районном бюджете на 2013-2015 годы
  kaz: 2013-2015 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-21
approved_by:
- '153004000002'
version_date:
  kaz: 2013-11-08
  rus: 2013-11-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/69830/kaz/08.11.2013
  rus: https://zan.gov.kz/client/#!/doc/69830/rus/08.11.2013
caused_by:
  code: '75311'
  requisite: Решение маслихата Алгинского района Актюбинской области от 8 ноября 2013 года № 111. Зарегистрировано Департаментом юстиции Актюбинской области 13 ноября 2013 года № 3667. Утратило силу решением маслихата Алгинского района Актюбинской области от 24 декабря 2013 года № 130
  title:
    rus: О внесении изменений в решение районного маслихата от 21 декабря 2012 года № 62 "О районном бюджете на 2013-2015 годы"
    kaz: Аудандық мәслихаттың 2012 жылғы 21 желтоқсандағы № 62 "2013-2015 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/75311/rus
