act_code: '117612'
requisite: Решение маслихата Кобдинского района Актюбинской области от 22 декабря 2017 года № 128. Зарегистрировано Департаментом юстиции Актюбинской области 8 января 2018 года № 5805
title:
  rus: Об утверждении бюджета Кобдинского сельского округа на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған Қобда ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-22
approved_by:
- '153012000002'
version_date:
  kaz: 2018-06-22
  rus: 2018-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/117612/kaz/22.06.2018
  rus: https://zan.gov.kz/client/#!/doc/117612/rus/22.06.2018
caused_by:
  code: '123404'
  requisite: Решение Кобдинского районного маслихата Актюбинской области от 22 июня 2018 года № 164. Зарегистрировано Управлением юстиции Кобдинского района Департамента юстиции Актюбинской области 9 июля 2018 года № 3-7-173
  title:
    rus: О внесении изменения и дополнения в решение районного маслихата от 22 декабря 2017 года № 128 «Об утверждении бюджета Кобдинского сельского округа на 2018-2020 годы»
    kaz: Аудандық мәслихаттың 2017 жылғы 22 желтоқсандағы № 128 «2018-2020 жылдарға арналған Қобда ауылдық округ бюджетін бекіту туралы» шешіміне өзгеріс пен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123404/rus
