act_code: '158250'
requisite: Решение акима Жайсанбайского сельского округа Иргизского района Актюбинской области от 31 августа 2021 года № 16. Утратило силу решением акима Жайсанбайского сельского округа Иргизского района Актюбинской области от 16 марта 2026 года № 13 (вводится со дня его первого официального опубликования)
title:
  rus: Об установлении карантина
  kaz: Карантин белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-08-31
approved_by:
- '153006007002'
version_date:
  kaz: 2021-08-31
  rus: 2021-08-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/158250/kaz/31.08.2021
  rus: https://zan.gov.kz/client/#!/doc/158250/rus/31.08.2021
