act_code: '64143'
requisite: Решение акима сельского округа имени К. Жубанова Мугалжарского района Актюбинской области от 17 февраля 2012 года № 5. Зарегистрировано Управлением юстиции Мугалжарского района Актюбинской области 19 марта 2012 года № 3-9-166
title:
  rus: О присвоении наименований безымянным улицам аула Каракол аульного округа имени К. Жубанова Мугалжарского района
  kaz: Мұғалжар ауданы Қ. Жұбанов атындағы ауылдық округі Қаракөл ауылының атаусыз көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-02-17
approved_by:
- '153009014002'
version_date:
  kaz: 2014-12-19
  rus: 2014-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/64143/kaz/19.12.2014
  rus: https://zan.gov.kz/client/#!/doc/64143/rus/19.12.2014
caused_by:
  code: '86135'
  requisite: Решение акима сельского округа имени К.Жубанова Мугалжарского района Актюбинской области от 19 декабря 2014 года № 4. Зарегистрировано Департаментом юстиции Актюбинской области 21 января 2015 года № 4175
  title:
    rus: О внесении изменений в решение акима сельского округа имени К. Жубанова от 17 февраля 2012 года № 5 «О присвоении наименований безымянным улицам аула Каракол аульного округа имени К. Жубанова Мугалжарского района»
    kaz: Қ.Жұбанов атындағы ауылдық округі әкімінің 2012 жылғы 17 ақпандағы № 5 «Мұғалжар ауданы Қ. Жұбанов атындағы ауылдық округі  Қаракөл ауылының  атаусыз көшелеріне  атау беру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/86135/rus
