act_code: '194967'
requisite: Решение Каргалинского районного маслихата Актюбинской области от 20 марта 2024 года № 144. Утратило силу решением Каргалинского районного маслихата Актюбинской области от 2 мая 2025 года № 308 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении плана по управлению пастбищами и их использованию по Каргалинскому району на 2024-2025 годы
  kaz: Қарғалы ауданы бойынша 2024-2025 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарын бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2024-03-20
approved_by:
- '153007000002'
version_date:
  kaz: 2024-03-20
  rus: 2024-03-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/194967/kaz/20.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194967/rus/20.03.2024
