act_code: '57048'
requisite: Ақтөбе облысы Темір ауданының әкімінің 2010 жылғы 10 желтоқсандағы № 10 шешімі. Ақтөбе облысының Темір аудандық Әділет басқармасында 2011 жылғы 10 қаңтарда № 3-10-140 тіркелді. Қолдану мерзімі өтуіне байланысты күші жойылды - Ақтөбе облысы Темір ауданы әкімі аппаратының жетекшісінің 2012 жылғы 2 наурыздағы № 04-2/354 хаты
title:
  rus: 1994 жылы туған азаматтарды "Ақтөбе облысы Темір ауданының қорғаныс істері жөніндегі бөлімі" мемлекеттік мекемесінің шақыру учаскесіне тіркеу туралы
  kaz: 1994 жылы туған азаматтарды "Ақтөбе облысы Темір ауданының қорғаныс істері жөніндегі бөлімі" мемлекеттік мекемесінің шақыру учаскесіне тіркеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-10
approved_by:
- '153010000003'
version_date:
  kaz: 2010-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/57048/kaz/10.12.2010
