act_code: '206237'
requisite: Решение Шалкарского районного маслихата Актюбинской области от 30 декабря 2024 года № 381
title:
  rus: Об утверждении бюджета Есет Котибарулы сельского округа на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Есет Көтібарұлы ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '153014000002'
version_date:
  kaz: 2025-07-18
  rus: 2025-07-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/206237/kaz/18.07.2025
  rus: https://zan.gov.kz/client/#!/doc/206237/rus/18.07.2025
caused_by:
  code: '212815'
  requisite: Решение Шалкарского районного маслихата Актюбинской области от 18 июля 2025 года № 476
  title:
    rus: О внесении изменений в решение Шалкарского районного маслихата от 30 декабря 2024 года № 381 «Об утверждении бюджета Есет Котибарулы сельского округа на 2025-2027 годы»
    kaz: Шалқар аудандық мәслихатының 2024 жылғы 30 желтоқсандағы № 381 «2025-2027 жылдарға арналған Есет Көтібарұлы ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/212815/rus
