act_code: '60356'
requisite: Решение акима Каиындинского сельского округа Уилского района Актюбинской области от 2 августа 2011 года № 1. Зарегистрировано Управлением юстиции Уилского района Актюбинской области 7 сентября 2011 года № 3-11-93
title:
  rus: О присвоении наименований улицам населенных пунктов Каиындинского сельского округа
  kaz: Қайыңды ауылдық округінің елді мекендерінің көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-08-02
approved_by:
- '153011001002'
version_date:
  kaz: 2017-04-04
  rus: 2017-04-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/60356/kaz/04.04.2017
  rus: https://zan.gov.kz/client/#!/doc/60356/rus/04.04.2017
caused_by:
  code: '111659'
  requisite: Решение акима Кайындинского сельского округа Уилского района Актюбинской области от 4 апреля 2017 года № 5. Зарегистрировано Департаментом юстиции Актюбинской области 21 апреля 2017 года № 5457
  title:
    rus: О внесении изменений в решение акима Кайындинского сельского округа от 2 августа 2011 года № 1 «О присвоении наименований улицам населенных пунктов Кайындинского сельского округа»
    kaz: Қайыңды ауылдық округі әкімінің 2011 жылғы 2 тамыздағы № 1 «Қайыңды ауылдық округінің елді мекендерінің көшелеріне атау беру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/111659/rus
