act_code: '60356'
requisite: Решение акима Каиындинского сельского округа Уилского района Актюбинской области от 2 августа 2011 года № 1. Зарегистрировано Управлением юстиции Уилского района Актюбинской области 7 сентября 2011 года № 3-11-93
title:
  rus: О присвоении наименований улицам населенных пунктов Каиындинского сельского округа
  kaz: Қайыңды ауылдық округінің елді мекендерінің көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-08-02
approved_by:
- '153011001002'
version_date:
  kaz: 2011-08-02
  rus: 2011-08-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/60356/kaz/02.08.2011
  rus: https://zan.gov.kz/client/#!/doc/60356/rus/02.08.2011
