act_code: '50221'
requisite: Ақтөбе облысы Алға аудандық мәслихатының 2009 жылғы 24 желтоқсандағы № 3 шешімі. Ақтөбе облысының Алға аудандық Әділет басқармасында 2010 жылдың 22 қаңтарда № 3-3-100 тіркелді. Қабылдау мерзімі аяқталуына байланысты қолдану тоқтатылды - Ақтөбе облысы Алға аудандық мәслихатының 2011 жылғы 5 қаңтардағы № 0-04/1 хатымен
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-24
approved_by:
- '153004000002'
version_date:
  kaz: 2010-10-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/50221/kaz/21.10.2010
caused_by:
  code: '55152'
  requisite: Ақтөбе облысы Алға аудандық мәслихатының 2010 жылғы 21 қазандағы № 4 шешімі. Ақтөбе облысының Алға аудандық Әділет басқармасында 2010 жылдың 29 қазанда № 3-3-112 тіркелді. Қабылдау мерзімі аяқталуына байланысты қолдану тоқтатылды - Ақтөбе облысы Алға аудандық мәслихатының 2011 жылғы 5 қаңтардағы № 0-04/1 хатымен
  title:
    rus: Аудандық мәслихаттың 2009 жылғы 24 желтоқсандағы № 3 "2010-2012 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Аудандық мәслихаттың 2009 жылғы 24 желтоқсандағы № 3 "2010-2012 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/55152/rus
