act_code: '50221'
requisite: Ақтөбе облысы Алға аудандық мәслихатының 2009 жылғы 24 желтоқсандағы № 3 шешімі. Ақтөбе облысының Алға аудандық Әділет басқармасында 2010 жылдың 22 қаңтарда № 3-3-100 тіркелді. Қабылдау мерзімі аяқталуына байланысты қолдану тоқтатылды - Ақтөбе облысы Алға аудандық мәслихатының 2011 жылғы 5 қаңтардағы № 0-04/1 хатымен
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-24
approved_by:
- '153004000002'
version_date:
  kaz: 2009-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/50221/kaz/24.12.2009
