act_code: '186403'
requisite: Решение Шалкарского районного маслихата Актюбинской области от 15 сентября 2023 года № 105. Зарегистрировано Департаментом юстиции Актюбинской области 20 сентября 2023 года № 8402
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан в Шалкарском районе
  kaz: Шалқар ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-09-15
approved_by:
- '153014000002'
version_date:
  kaz: 2025-04-28
  rus: 2025-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/186403/kaz/28.04.2025
  rus: https://zan.gov.kz/client/#!/doc/186403/rus/28.04.2025
caused_by:
  code: '209769'
  requisite: Решение Шалкарского районного маслихата Актюбинской области от 28 апреля 2025 года № 428. Зарегистрировано Департаментом юстиции Актюбинской области 5 мая 2025 года № 8704-04
  title:
    rus: О внесении изменения в решение Шалкарского районного маслихата от 15 сентября 2023 года № 105 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан в Шалкарском районе»
    kaz: Шалқар аудандық мәслихатының 2023 жылғы 15 қыркүйектегі № 105 «Шалқар ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/209769/rus
