act_code: '194669'
requisite: Решение Шалкарского районного маслихата Актюбинской области от 15 марта 2024 года № 220. Зарегистрировано Департаментом юстиции Актюбинской области 20 марта 2024 года № 8534-04. Утратило силу решением Шалкарского районного маслихата Актюбинской области от 15 декабря 2025 года № 548 (вводится в действие с 01.01.2026)
title:
  rus: О понижении размера ставки налогов при применении специального налогового режима розничного налога в Шалкарском районе
  kaz: Шалқар ауданында бөлшек салықтың арнаулы салық режимін қолдану кезінде салық мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-15
approved_by:
- '153014000002'
version_date:
  kaz: 2024-03-15
  rus: 2024-03-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/194669/kaz/15.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194669/rus/15.03.2024
