act_code: '120072'
requisite: Решение маслихата Мартукского района Актюбинской области от 5 марта 2018 года № 127. Зарегистрировано Управлением юстиции Мартукского района Актюбинской области 29 марта 2018 года № 3-8-162
title:
  rus: О повышении ставок единого земельного налога на не используемые земли сельскохозяйственного назначения по Мартукскому району на 2018-2019 годы
  kaz: 2018-2019 жылдары Мәртөк ауданы бойынша пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерге бірыңғай жер салығының мөлшерлемесін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-03-05
approved_by:
- '153008000002'
version_date:
  kaz: 2018-03-05
  rus: 2018-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/120072/kaz/05.03.2018
  rus: https://zan.gov.kz/client/#!/doc/120072/rus/05.03.2018
