act_code: '1308'
requisite: Решение акима Актюбинской области от 25 июня 1998 года № 104. Зарегистрировано Управлением юстиции Актюбинской области 24 сентября 1998 года № 47. Утратило силу – письмо акимата Актюбинской области от 21 декабря 2004 года № 08-3/2691
title:
  rus: О предоставлении совместному предприятию "Актобе Пройссаг Мунай ЛТД" право временного использования земельных участков для производства сейсморазведочных работ в Байганинском районе Актюбинской области
  kaz: Ақтөбе облысының Байғанин ауданында сейсмологиялық барлау жұмыстарын жүргізу үшін «АҚТӨБЕ ПРОЙССАГ МУНАЙ ЛТД» біріккен кәсіпорынына уақытша жер бөлігін пайдалану құқылығын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-06-24
approved_by:
- '153000000003'
version_date:
  kaz: 1998-06-24
  rus: 1998-06-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/1308/kaz/24.06.1998
  rus: https://zan.gov.kz/client/#!/doc/1308/rus/24.06.1998
