act_code: '43498'
requisite: Ақтөбе облысы Қобда аудандық мәслихатының 2008 жылғы 20 желтоқсандағы N 68 шешімі. Ақтөбе облысының Қобда аудандық әділет басқармасында 2009 жылдың 15 қаңтарда N 3-7-57 тіркелді. Күші жойылды - Ақтөбе облысы Қобда аудандық мәслихатының 2009 жылғы 25 желтоқсандағы № 128 шешімімен
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-20
approved_by:
- '153012000002'
version_date:
  kaz: 2009-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/43498/kaz/26.11.2009
caused_by:
  code: '49395'
  requisite: Ақтөбе облысы Қобда аудандық мәслихатының 2009 жылғы 26 қарашадағы N 112 шешімі. Ақтөбе облысының Қобда аудандық әділет басқармасында 2009 жылдың 20 желтоқсанда N 3-7-78 тіркелді. Күші жойылды - Ақтөбе облысы Қобда аудандық мәслихатының 2009 жылғы 25 желтоқсандағы № 128 шешімімен
  title:
    rus: Аудандық мәслихаттың 2008 жылғы 20 желтоқсандағы N 68 "2009 жылға арналған аудан бюджеті туралы" шешіміне өзгерістер енгізу туралы
    kaz: Аудандық мәслихаттың 2008 жылғы 20 желтоқсандағы N 68 "2009 жылға арналған аудан бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/49395/rus
