act_code: '72083'
requisite: Решение маслихата Иргизского района Актюбинской области от 29 марта 2013 года № 63. Зарегистрировано Департаментом юстиции Актюбинской области 18 апреля 2013 года № 3560
title:
  rus: Об определении категории граждан, расходы которых по плате за пользование жилищем в частном жилищном фонде и арендных домах возлагаются на местный бюджет
  kaz: Жеке тұрғын үй қорындағы және жалға берілетін үйлердегі тұрғынжайды пайдаланғаны үшін төлемақы төлеу жөніндегі шығыстары жергілікті бюджетке жүктелген азаматтардың санаттарын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-03-29
approved_by:
- '153006000002'
version_date:
  kaz: 2021-12-21
  rus: 2021-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/72083/kaz/21.12.2021
  rus: https://zan.gov.kz/client/#!/doc/72083/rus/21.12.2021
caused_by:
  code: '162487'
  requisite: Решение Иргизского районного маслихата Актюбинской области от 21 декабря 2021 года № 87. Зарегистрировано в Министерстве юстиции Республики Казахстан 28 декабря 2021 года № 26155
  title:
    rus: О внесении изменений в решение районного маслихата от 29 марта 2013 года № 63 «Об определении категории граждан, расходы которых по плате за пользование жилищем в частном жилищном фонде и арендных домах возлагаются на местный бюджет»
    kaz: Аудандық мәслихаттың 2013 жылғы 29 наурыздағы № 63 «Жеке тұрғын үй қорындағы және жалға берілетін үйлердегі тұрғынжайды пайдаланғаны үшін төлемақы төлеу жөніндегі шығыстары жергілікті бюджетке жүктелген азаматтардың санаттарын айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/162487/rus
