act_code: '46167'
requisite: Ақтөбе облысы Темір аудандық мәслихатының 2009 жылғы 23 сәуірдегі № 117 шешімі. Ақтөбе облысының Темір аудандық әділет басқармасында 2009 жылдың 28 мамырда № 3-10-109 тіркелді. Күші жойылды - Ақтөбе облысы Темір аудандық мәслихатының 2010 жылғы 12 ақпандағы N 179 шешімімен
title:
  rus: Аз қамтамасыз етілген азаматтарға тұрғын үй көмегін көрсету қағидасы туралы
  kaz: Аз қамтамасыз етілген азаматтарға тұрғын үй көмегін көрсету қағидасы туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2009-04-23
approved_by:
- '153010000002'
version_date:
  kaz: 2009-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/46167/kaz/23.04.2009
