act_code: '128195'
requisite: Решение Байганинского районного маслихата Актюбинской области от 29 декабря 2018 года № 204. Зарегистрировано Управлением юстиции Байганинского района Департамента юстиции Актюбинской области 4 января 2019 года № 3-4-197
title:
  rus: Об утверждении бюджета Карауылкелдинского сельского округа на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Қарауылкелді ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-29
approved_by:
- '153005000002'
version_date:
  kaz: 2019-12-11
  rus: 2019-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/128195/kaz/11.12.2019
  rus: https://zan.gov.kz/client/#!/doc/128195/rus/11.12.2019
caused_by:
  code: '137109'
  requisite: Решение Байганинского районного маслихата Актюбинской области от 11 декабря 2019 года № 276. Зарегистрировано Департаментом юстиции Актюбинской области 13 декабря 2019 года № 6548
  title:
    rus: О внесении изменений в решение Байганинского районного маслихата от 29 декабря 2018 года № 204 «Об утверждении бюджета Карауылкелдинского сельского округа на 2019-2021 годы»
    kaz: Байғанин аудандық мәслихатының 2018 жылғы 29 желтоқсандағы № 204 «2019-2021 жылдарға арналған Қарауылкелді ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/137109/rus
