act_code: '162233'
requisite: Решение Темирского районного маслихата Актюбинской области от 23 декабря 2021 года № 132. Зарегистрировано в Министерстве юстиции Республики Казахстан 24 декабря 2021 года № 25998
title:
  rus: Об утверждении Темирского районного бюджета на 2022–2024 годы
  kaz: 2022–2024 жылдарға арналған Темір аудандық бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-23
approved_by:
- '153010000002'
version_date:
  kaz: 2021-12-23
  rus: 2021-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/162233/kaz/23.12.2021
  rus: https://zan.gov.kz/client/#!/doc/162233/rus/23.12.2021
