act_code: '138725'
requisite: Решение Мугалжарского районного маслихата Актюбинской области от 6 января 2020 года № 389. Зарегистрировано Департаментом юстиции Актюбинской области 14 января 2020 года № 6695
title:
  rus: Об утверждении бюджета Аккемирского сельского округа на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Ақкемер ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-06
approved_by:
- '153009000002'
version_date:
  kaz: 2020-08-25
  rus: 2020-08-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/138725/kaz/25.08.2020
  rus: https://zan.gov.kz/client/#!/doc/138725/rus/25.08.2020
caused_by:
  code: '146030'
  requisite: Решение Мугалжарского районного маслихата Актюбинской области от 25 августа 2020 года № 482. Зарегистрировано Департаментом юстиции Актюбинской области 2 сентября 2020 года № 7383
  title:
    rus: О внесении изменений в решение Мугалжарского районного маслихата от 6 января 2020 года № 389 «Об утверждении бюджета Аккемирского сельского округа на 2020-2022 годы»
    kaz: Мұғалжар аудандық мәслихатының 2020 жылғы 6 қаңтардағы № 389 «2020-2022 жылдарға арналған Ақкемер ауылдық округ бюджетін бекіту туралы» шеіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/146030/rus
