act_code: '19083'
requisite: Ақтөбе облысы Ырғыз аудандық мәслихатының 2004 жылғы 26 ақпандағы N 2 шешімі. Ақтөбе облыстық Әділет Департаментінде 2004 жылғы 24 наурызда N 2627 тіркелді. Күші жойылды - Ақтөбе облысы Ырғыз аудандық мәслихатының 2009 жылғы 22 шілдедегі № 96 шешімімен
title:
  rus: Қазақстан Республикасының "Әкiмшiлiк құқық бұзушылық туралы" Кодексiнiң 300, 311, 387 баптарының бұзылғаны үшiн әкiмшiлiк жауаптылық көзделетiн ережелерiн белгiлеу туралы
  kaz: Қазақстан Республикасының "Әкiмшiлiк құқық бұзушылық туралы" Кодексiнiң 300, 311, 387 баптарының бұзылғаны үшiн әкiмшiлiк жауаптылық көзделетiн ережелерiн белгiлеу туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2004-02-26
approved_by:
- '153006000002'
version_date:
  kaz: 2004-02-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/19083/kaz/26.02.2004
