act_code: '65593'
requisite: Решение акима Кайндинского сельского округа Темирского района Актюбинской области от 17 апреля 2012 года № 6. Зарегистрировано Управлением юстиции Темирского района Актюбинской области 14 мая 2012 года № 3-10-165. Утратило силу решением акима Кайындинского сельского округа Темирского района Актюбинской области от 12 октября 2012 года № 12
title:
  rus: Об установлении ветеринарного режима Карантинной зоны в селе "Кумкудук" Каиндинского сельского округа
  kaz: Қайыңды селолық округінің "Құмқұдық" ауылына карантин аймағының ветеринариялық режимін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-04-17
approved_by:
- '153010005002'
version_date:
  kaz: 2012-04-17
  rus: 2012-04-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/65593/kaz/17.04.2012
  rus: https://zan.gov.kz/client/#!/doc/65593/rus/17.04.2012
