act_code: '44136'
requisite: Решение маслихата Мартукского района Актюбинской области от 20 декабря 2008 года N 71. Зарегистрировано Управлением юстиции Мартукского района Актюбинской области 13 января 2009 года N 3-8-74. Утратило силу решением маслихата Мартукского района Актюбинской области от 5 февраля 2010 года № 155
title:
  rus: О бюджете Мартукского района на 2009 год
  kaz: 2009 жылға арналған Мәртөк ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-20
approved_by:
- '153008000002'
version_date:
  kaz: 2009-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/44136/kaz/28.10.2009
caused_by:
  code: '48689'
  requisite: Ақтөбе облысы Мәртөк аудандық мәслихатының 2009 жылғы 28 қазандағы N 138 шешімі. Ақтөбе облысы Мәртөк аудандық әділет басқармасында 2009 жылғы 13 қарашада N 3-8-99 тіркелді
  title:
    rus: Аудандық мәслихаттың шешіміне 2008 жылғы 20 желтоқсандағы N 71 "2009 жылға арналған Мәртөк ауданының бюджеті туралы" өзгерістер мен толықтырулар енгізу туралы
    kaz: Аудандық мәслихаттың шешіміне 2008 жылғы 20 желтоқсандағы N 71 "2009 жылға арналған Мәртөк ауданының бюджеті туралы" өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/48689/rus
