act_code: '146298'
requisite: Решение Уилского районного маслихата Актюбинской области от 3 сентября 2020 года № 448. Зарегистрировано Департаментом юстиции Актюбинской области 14 сентября 2020 года № 7407
title:
  rus: Об определении специализированных мест для организации и проведения мирных собраний, порядка использования специализированных мест для организации и проведения мирных собраний, норм их предельной заполняемости, а также требований к материально-техническому и организационному обеспечению специализированных мест для организации и проведения мирных собраний, границ прилегающих территорий, в которых запрещено проведение пикетирования в Уилском районе
  kaz: Ойыл ауданында бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды пайдалану тәртібін, олардың шекті толу нормаларын, сондай-ақ бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптарды, пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекараларын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-03
approved_by:
- '153011000002'
version_date:
  kaz: 2020-10-27
  rus: 2020-10-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/146298/kaz/27.10.2020
  rus: https://zan.gov.kz/client/#!/doc/146298/rus/27.10.2020
caused_by:
  code: '148370'
  requisite: Решение Уилского районного маслихата Актюбинской области от 27 октября 2020 года № 451. Зарегистрировано Департаментом юстиции Актюбинской области 6 ноября 2020 года № 7591
  title:
    rus: О внесении изменений в решение Уилского районного маслихата от 3 сентября 2020 года № 448 «Об определении специализированных мест для организации и проведения мирных собраний, порядка использования специализированных мест для организации и проведения мирных собраний, норм их предельной заполняемости, а также требований к материально-техническому и организационному обеспечению специализированных мест для организации и проведения мирных собраний, границ прилегающих территорий, в которых запрещено проведение пикетирования в Уилском районе»
    kaz: Ойыл аудандық мәслихатының 2020 жылғы 3 қыркүйегіндегі № 448 «Ойыл ауданында бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды пайдалану тәртібін, олардың шекті толу нормаларын, сондай-ақ бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптарды, пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекараларын айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/148370/rus
