act_code: '40468'
requisite: Ақтөбе облысы Әйтеке би ауданы Үшқатты селолық округі әкімінің 2008 жылғы 23 маусымдағы № 1 шешімі. Ақтөбе облысының Әйтеке би аудандық әділет басқармасында 2008 жылдың 4 шілдеде № 3-2-49 тіркелді
title:
  rus: Көшелерді қайта атау туралы
  kaz: Көшелерді қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-06-23
approved_by:
- '153003015002'
version_date:
  kaz: 2008-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/40468/kaz/23.06.2008
