act_code: '163746'
requisite: Решение Иргизского районного маслихата Актюбинской области от 31 декабря 2021 года № 97
title:
  rus: Об утверждении бюджета Нуринского сельского округа на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Нұра ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-31
approved_by:
- '153006000002'
version_date:
  kaz: 2021-12-31
  rus: 2021-12-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/163746/kaz/31.12.2021
  rus: https://zan.gov.kz/client/#!/doc/163746/rus/31.12.2021
