act_code: '100809'
requisite: Решение маслихата Иргизского района Актюбинской области от 29 февраля 2016 года № 245. Зарегистрировано Департаментом юстиции Актюбинской области 24 марта 2016 года № 4807. Утратило силу решением Иргизского районного маслихата Актюбинской области от 13 марта 2020 года № 282
title:
  rus: Об утверждении правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан в Иргизском районе
  kaz: Ырғыз ауданында әлеуметтік көмек көрсетудің, мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2016-02-29
approved_by:
- '153006000002'
version_date:
  kaz: 2019-05-14
  rus: 2019-05-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/100809/kaz/14.05.2019
  rus: https://zan.gov.kz/client/#!/doc/100809/rus/14.05.2019
caused_by:
  code: '131631'
  requisite: Решение Иргизского районного маслихата Актюбинской области от 14 мая 2019 года № 226. Зарегистрировано Департаментом юстиции Актюбинской области 16 мая 2019 года № 6150. Утратило силу решением Иргизского районного маслихата Актюбинской области от 13 марта 2020 года № 282
  title:
    rus: О внесении изменений в решение районного маслихата от 29 февраля 2016 года № 245 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан в Иргизском районе»
    kaz: Аудандық мәслихаттың 2016 жылғы 29 ақпандағы № 245 «Ырғыз ауданында әлеуметтік көмек көрсетудің, мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/131631/rus
