act_code: '30188'
requisite: Ақтөбе қалалық мәслихатының кезектен тыс отыз үшінші сессиясының 2006 жылғы 16 қазандағы N 278 шешімі. Ақтөбе қаласының Әділет басқармасында 2006 жылғы 3 қарашада N 3-1-60 тіркелді. Күші жойылды - Ақтөбе облысы Ақтөбе қалалық мәслихатының 2007 жылғы 30 қазандағы N 19 шешімімен
title:
  rus: Біржолғы талондардың бағасын бекіту жөнінде
  kaz: Біржолғы талондардың бағасын бекіту жөнінде
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-10-16
approved_by:
- '153002000002'
version_date:
  kaz: 2006-10-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/30188/kaz/16.10.2006
