act_code: '46056'
requisite: Ақтөбе облысы Қобда аудандық мәслихатының 2009 жылғы 24 сәуірдегі N 86 шешімі. Ақтөбе облысының Қобда аудандық Әділет басқармасында 2009 жылдың 20 мамырда N 3-7-68 тіркелді
title:
  rus: Жер салығының базалық мөлшерлемесін арттыру туралы
  kaz: Жер салығының базалық мөлшерлемесін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-24
approved_by:
- '153012000002'
version_date:
  kaz: 2018-03-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/46056/kaz/02.03.2018
caused_by:
  code: '119919'
  requisite: 'Решение Кобдинского районного маслихата Актюбинской области от 2 марта 2018 года № 140. Зарегистрировано Управлением юстиции Кобдинского района Актюбинской области 27 марта 2018 года № 3-7-159. Утратило силу решением Кобдинского районного маслихата Актюбинской области от 2 декабря 2024 года № 234 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)

    '
  title:
    rus: О внесении изменений в решение Кобдинского районного маслихата от 24 апреля 2009 года № 86 «Жер салығының базалық мөлшерлемесін жоғарылату туралы»
    kaz: Қобда аудандық мәслихатының 2009 жылғы 24 сәуірдегі № 86 «Жер салығының базалық мөлшерлемесін жоғарылату туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/119919/rus
