act_code: '44408'
requisite: Ақтөбе облысы Қобда аудандық мәслихатының 2009 жылғы 29 қаңтардағы N 77 шешімі. Ақтөбе облысының Қобда аудандық әділет басқармасында 2009 жылдың 20 ақпанда N 3-7-61 тіркелді. Күші жойылды - Ақтөбе облысы Қобда аудандық мәслихатының 2011 жылғы 30 қыркүйектегі № 232 шешімімен
title:
  rus: Тіркелген салық ставкаларының 2009 жылға арналған мөлшерін белгілеу туралы
  kaz: Тіркелген салық ставкаларының 2009 жылға арналған мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-29
approved_by:
- '153012000002'
version_date:
  kaz: 2009-01-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/44408/kaz/29.01.2009
