act_code: '59965'
requisite: Решение акима Бестауского сельского округа Кобдинского района Актюбинской области от 8 июля 2011 года № 3. Зарегистрировано Управлением юстиции Кобдинского района Актюбинской области 8 августа 2011 года № 3-7-114
title:
  rus: О наименовании и переименовании улиц аула Бестау
  kaz: Бестау ауылы көшелеріне атау беру және атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-07-08
approved_by:
- '153012002002'
version_date:
  kaz: 2011-07-07
  rus: 2011-07-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/59965/kaz/07.07.2011
  rus: https://zan.gov.kz/client/#!/doc/59965/rus/07.07.2011
