act_code: '59965'
requisite: Решение акима Бестауского сельского округа Кобдинского района Актюбинской области от 8 июля 2011 года № 3. Зарегистрировано Управлением юстиции Кобдинского района Актюбинской области 8 августа 2011 года № 3-7-114
title:
  rus: О наименовании и переименовании улиц аула Бестау
  kaz: Бестау ауылы көшелеріне атау беру және атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-07-08
approved_by:
- '153012002002'
version_date:
  kaz: 2014-12-12
  rus: 2014-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/59965/kaz/12.12.2014
  rus: https://zan.gov.kz/client/#!/doc/59965/rus/12.12.2014
caused_by:
  code: '85917'
  requisite: Решение акима Бестауского сельского округа Хобдинского района Актюбинской области от 12 декабря 2014 года № 5. Зарегистрировано Департаментом юстиции Актюбинской области 14 января 2015 года № 4149
  title:
    rus: О внесении изменений в решение акима Бестауского аульного округа от 8 июля 2011 года № 3 «О наименовании и переименовании улиц аула Бестау»
    kaz: Бестау ауылдық округі әкімінің 2011 жылғы 8 шілдедегі № 3 «Бестау ауылы көшелеріне атау беру және атауларын өзгерту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/85917/rus
