act_code: '44589'
requisite: Ақтөбе облысы Байғанин аудандық мәслихатының 2009 жылғы 28 қаңтардағы N 71 шешімі. Ақтөбе облысының Байғанин аудандық әділет басқармасында 2009 жылдың 23 ақпанда N 3-4-65 тіркелді. Күші жойылды - Ақтөбе облысы Байғанин аудандық мәслихатының 2009 жылғы 24 сәуірдегі N 91 шешімімен
title:
  rus: Ойын бизнесі бойынша тіркелген салық ставкаларын белгілеу туралы
  kaz: Ойын бизнесі бойынша тіркелген салық ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-28
approved_by:
- '153005000002'
version_date:
  kaz: 2009-01-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/44589/kaz/28.01.2009
