act_code: '151985'
requisite: Решение Кобдинского районного маслихата Актюбинской области от 5 января 2021 года № 427. Зарегистрировано Департаментом юстиции Актюбинской области 14 января 2021 года № 8009. Утратило силу решением Кобдинского районного маслихата Актюбинской области от 4 апреля 2024 года № 173
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Кобдинском районе
  kaz: Қобда ауданында тұрғын үй көмегін көрсету мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-01-05
approved_by:
- '153012000002'
version_date:
  kaz: 2021-01-05
  rus: 2021-01-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/151985/kaz/05.01.2021
  rus: https://zan.gov.kz/client/#!/doc/151985/rus/05.01.2021
