act_code: '77092'
requisite: Решение маслихата Мартукского района Актюбинской области от 25 декабря 2013 года № 100. Зарегистрировано Департаментом юстиции Актюбинской области 17 января 2014 года № 3744
title:
  rus: О предоставлении в 2014 году подъемного пособия и бюджетного кредита специалистам, прибывшим для работы и проживания в Мартукский район
  kaz: Мәртөк ауданына жұмыс істеуге және тұруға келген мамандарына 2014 жылы көтерме жәрдемақы және бюджеттік кредит беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-25
approved_by:
- '153008000002'
version_date:
  kaz: 2013-12-25
  rus: 2013-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/77092/kaz/25.12.2013
  rus: https://zan.gov.kz/client/#!/doc/77092/rus/25.12.2013
