act_code: '52600'
requisite: Решение от 22.04.2010 № 8, Акимат сельского округа Дон
title:
  rus: '"Дөң" ауылдық округіндегі көше атауын өзгерту туралы'
  kaz: '"Дөң" ауылдық округіндегі көше атауын өзгерту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-22
approved_by:
- '153013006001'
version_date:
  kaz: 2010-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/52600/kaz/22.04.2010
