act_code: '220960'
requisite: Решение Айтекебийского районного маслихата Актюбинской области от 30 декабря 2025 года № 457
title:
  rus: Об утверждении бюджета Аралтогайского сельского округа на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған Аралтоғай ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-30
approved_by:
- '153003000002'
version_date:
  kaz: 2026-06-05
  rus: 2026-06-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/220960/kaz/05.06.2026
  rus: https://zan.gov.kz/client/#!/doc/220960/rus/05.06.2026
caused_by:
  code: '226246'
  requisite: Решение Айтекебийского районного маслихата Актюбинской области от 5 июня 2026 года № 526
  title:
    rus: О внесении изменений в решение Айтекебийского районного маслихата от 30 декабря 2025 года № 457 «Об утверждении бюджета Аралтогайского сельского округа на 2026-2028 годы»
    kaz: Әйтеке би аудандық мәслихаттың 2025 жылғы 30 желтоқсандағы № 457 «2026-2028 жылдарға арналған Аралтоғай ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/226246/rus
