act_code: '184163'
requisite: Решение акима Кос-Истекского сельского округа Каргалинского района Актюбинской области от 18 июля 2023 года № 19. Утратило силу решением акима Кос-Истекского сельского округа Каргалинского района Актюбинской области от 14 сентября 2023 года № 26
title:
  rus: Об установлении карантинных мер по улицам Д. Кунаева, А. Жубанова села Кос-Истек Кос-Истекского сельского округа Каргалинского района
  kaz: Қарғалы ауданы Қос Естек ауылдық округіне қарасты Қос Естек ауылының Д. Қонаев көшесі мен А. Жұбанов көшесіне карантин белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-07-18
approved_by:
- '153007006002'
version_date:
  kaz: 2023-07-18
  rus: 2023-07-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/184163/kaz/18.07.2023
  rus: https://zan.gov.kz/client/#!/doc/184163/rus/18.07.2023
