act_code: '63251'
requisite: Решение акима Кенестуского сельского округа Темирского района Актюбинской области от 28 декабря 2011 года № 24. Зарегистрировано Управлением юстиции Темирского района Актюбинской области 3 февраля 2012 года № 3-10-157
title:
  rus: О наименовании составных частей Кенестуского сельского округа
  kaz: Кеңестуы ауылдық округінің құрамды бөліктерін атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-28
approved_by:
- '153010006001'
version_date:
  kaz: 2011-12-28
  rus: 2011-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/63251/kaz/28.12.2011
  rus: https://zan.gov.kz/client/#!/doc/63251/rus/28.12.2011
