act_code: '63251'
requisite: Решение акима Кенестуского сельского округа Темирского района Актюбинской области от 28 декабря 2011 года № 24. Зарегистрировано Управлением юстиции Темирского района Актюбинской области 3 февраля 2012 года № 3-10-157
title:
  rus: О наименовании составных частей Кенестуского сельского округа
  kaz: Кеңестуы ауылдық округінің құрамды бөліктерін атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-28
approved_by:
- '153010006001'
version_date:
  kaz: 2016-07-13
  rus: 2016-07-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/63251/kaz/13.07.2016
  rus: https://zan.gov.kz/client/#!/doc/63251/rus/13.07.2016
caused_by:
  code: '105218'
  requisite: Решение акима Кенестуского сельского округа Темирского района Актюбинской области от 13 июля 2016 года № 14. Зарегистрировано Департаментом юстиции Актюбинской области 4 августа 2016 года № 5025
  title:
    rus: О внесении изменений в решение от 28 декабря 2011 года № 24 «О наименовании составных частей Кенестуского сельского округа»
    kaz: «Кеңестуы селолық округінің құрамды бөліктерін атау туралы» 2011 жылғы 28 желтоқсандағы № 24 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/105218/rus
