act_code: '43170'
requisite: Ақтөбе облысы Алға аудандық әкімиятының 2008 жылғы 18 желтоқсандағы N 2 шешімі. Ақтөбе облысының Алға аудандық Әділет басқармасында 2009 жылдың 6 қаңтарда N 3-3-66 тіркелді. Күші жойылды - Ақтөбе облысы Алға аудандық әкімиятының 2010 жылғы 6 қаңтардағы N 1 шешімімен
title:
  rus: Алға ауданы Қорғаныс істері бөлімінің шақыру участкесіне 1992 жылы туылған ер азаматтарды тіркеуге алу жұмысын жүргізу туралы
  kaz: Алға ауданы Қорғаныс істері бөлімінің шақыру участкесіне 1992 жылы туылған ер азаматтарды тіркеуге алу жұмысын жүргізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-18
approved_by:
- '153004000001'
version_date:
  kaz: 2008-12-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/43170/kaz/18.12.2008
