act_code: '40467'
requisite: Ақтөбе облысы Әйтеке би ауданы Сұлукөл ауылдық округі әкімінің 2008 жылғы 23 маусымдағы N 1 шешімі. Ақтөбе облысының Әйтеке би аудандық әділет басқармасында 2008 жылдың 4 шілдеде N 3-2-48 тіркелді
title:
  rus: Көшелерді қайта атау туралы
  kaz: Көшелерді қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-06-23
approved_by:
- '153003012002'
version_date:
  kaz: 2016-06-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/40467/kaz/24.06.2016
caused_by:
  code: '104799'
  requisite: Решение акима Сулукольского сельского округа Айтекебийского района Актюбинской области от 24 июня 2016 года № 8. Зарегистрировано Департаментом юстиции Актюбинской области 22 июля 2016 года № 5008
  title:
    rus: О внесении изменений в некоторые решение акима Сулукольского сельского округа
    kaz: Сұлукөл ауылдық округі әкімінің кейбір шешімдеріне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/104799/rus
