act_code: '155626'
requisite: Решение акима Сарыжарского сельского округа Мартукского района Актюбинской области от 30 апреля 2021 года № 4. Зарегистрировано Департаментом юстиции Актюбинской области 4 мая 2021 года № 8286
title:
  rus: О переименовании некоторых улиц села Сарыжар Сарыжарского сельского округа Мартукского района
  kaz: Мәртөк ауданы Сарыжар ауылдық округі Сарыжар ауылының кейбір көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-04-30
approved_by:
- '153008009002'
version_date:
  kaz: 2021-04-30
  rus: 2021-04-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/155626/kaz/30.04.2021
  rus: https://zan.gov.kz/client/#!/doc/155626/rus/30.04.2021
