act_code: '193170'
requisite: Решение Мартукского районного маслихата Актюбинской области от 6 февраля 2024 года № 86
title:
  rus: Об утверждении минимального размера расходов на управление объектом кондоминиума и содержание общего имущества объекта кондоминиума по Мартукскому району на 2024 год
  kaz: Мәртөк ауданы бойынша 2024 жылға арналған кондоминиум объектісін басқаруға және кондоминиум объектісінің ортақ мүлкін күтіп-ұстауға арналған шығыстардың ең төмен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-06
approved_by:
- '153008000002'
version_date:
  kaz: 2024-02-06
  rus: 2024-02-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/193170/kaz/06.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193170/rus/06.02.2024
