act_code: '43171'
requisite: Ақтөбе облысы Хромтау аудандық әкімиятының 2008 жылғы 25 желтоқсандағы N 6 шешімі. Ақтөбе облысының Хромтау аудандық әділет басқармасында 2009 жылдың 6 қаңтарда N 3-12-75 тіркелді. Орындалу мерзімі аяқталуына байланысты күші жойылды - Ақтөбе облысы Хромтау аудандық әкімдігінің 2012 жылғы 16 қазандағы № 1308 хатымен
title:
  rus: Шақыру учаскесіне 2009 оқу жылында 1992 жылы туған азаматтарды тіркеу туралы
  kaz: Шақыру учаскесіне 2009 оқу жылында 1992 жылы туған азаматтарды тіркеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-25
approved_by:
- '153013000001'
version_date:
  kaz: 2008-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/43171/kaz/25.12.2008
