act_code: '109164'
requisite: Решение маслихата Мугалжарского района Актюбинской области от 21 декабря 2016 года № 56. Зарегистрировано Департаментом юстиции Актюбинской области 11 января 2017 года № 5219
title:
  rus: Об утверждении Мугалжарского районного бюджета на 2017-2019 годы
  kaz: 2017-2019 жылдарға арналған Мұғалжар аудандық бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-21
approved_by:
- '153009000002'
version_date:
  kaz: 2016-12-21
  rus: 2016-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/109164/kaz/21.12.2016
  rus: https://zan.gov.kz/client/#!/doc/109164/rus/21.12.2016
