act_code: '118190'
requisite: Решение Темирского районного маслихата Актюбинской области от 28 декабря 2017 года № 185. Зарегистрировано Департаментом юстиции Актюбинской области 15 января 2018 года № 5855
title:
  rus: Об утверждении бюджета Кенестуского сельского округа на 2018–2020 годы
  kaz: 2018-2020 жылдарға арналған Кеңестуы ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-28
approved_by:
- '153010000002'
version_date:
  kaz: 2018-03-19
  rus: 2018-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/118190/kaz/19.03.2018
  rus: https://zan.gov.kz/client/#!/doc/118190/rus/19.03.2018
caused_by:
  code: '120502'
  requisite: Решение маслихата Темирского района Актюбинской области от 19 марта 2018 года № 211. Зарегистрировано Управлением юстиции Темирского района Департамента юстиции Актюбинской области 9 апреля 2018 года № 3-10-184
  title:
    rus: О внесении изменений в решение районного маслихата от 28 декабря 2017 года № 185 «Об утверждении бюджета Кенестуского сельского округа на 2018–2020 годы»
    kaz: Аудандық мәслихаттың 2017 жылғы 28 желтоқсандағы № 185 «2018–2020 жылдарға арналған Кеңестуы ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/120502/rus
