act_code: '194670'
requisite: Решение акима Карауылкелдинского сельского округа Байганинского района Актюбинской области от 20 марта 2024 года № 35
title:
  rus: О снятии ограничительных мероприятий и признании утратившим силу решения акима Карауылкелдинского сельского округа от 25 января 2024 года № 12 «Об установлении ограничительных мероприятий»
  kaz: Шектеу іс-шараларын алу және Қарауылкелді ауылдық округі әкімінің «Шектеу іс-шараларын белгілеу туралы» 2024 жылғы 25 қаңтардағы № 12 шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-20
approved_by:
- '153005008002'
version_date:
  kaz: 2024-03-20
  rus: 2024-03-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/194670/kaz/20.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194670/rus/20.03.2024
