act_code: '59033'
requisite: Решение маслихата Хромтауского района Актюбинской области от 27 апреля 2011 года № 239. Зарегистрировано Управлением юстиции Хромтауского района Актюбинской области 17 мая 2011 года № 3-12-135. Утратило силу решением Хромтауского районного маслихата Актюбинской области от 26 апреля 2012 года № 30
title:
  rus: Об определении мер социальной поддержки специалистов сферы здравоохранения, образования, социального обеспечения, культуры и спорта на 2011 год
  kaz: Денсаулық сақтау, білім, әлеуметтік қамсыздандыру, мәдениет және спорт саласының мамандарын әлеуметтік қолдау шараларының 2011 жылға арналған мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-04-27
approved_by:
- '153013000002'
version_date:
  kaz: 2011-04-27
  rus: 2011-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/59033/kaz/27.04.2011
  rus: https://zan.gov.kz/client/#!/doc/59033/rus/27.04.2011
