act_code: '124325'
requisite: Решение акима сельского округа имени И. Билтабанова Кобдинского района Актюбинской области от 15 августа 2018 года № 10. Зарегистрировано Управлением юстиции Кобдинского района Департамента юстиции Актюбинской области 28 августа 2018 года № 3-7-176
title:
  rus: О переименовании улицы Жастар села имени И. Билтабанова сельского округа имени И. Билтабанова Кобдинского района
  kaz: Қобда ауданы И. Білтабанов атындағы ауылдық округінің И. Білтабанов атындағы ауылының Жастар көшесін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-08-15
approved_by:
- '153012005002'
version_date:
  kaz: 2018-08-15
  rus: 2018-08-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/124325/kaz/15.08.2018
  rus: https://zan.gov.kz/client/#!/doc/124325/rus/15.08.2018
