act_code: '16372'
requisite: Решение маслихата Актюбинской области от 2 июля 2003 года № 6. Зарегистрировано Управлением юстиции Актюбинской области 28 июля 2003 года № 2284
title:
  rus: О Программе молодежной политики в Актюбинской области на 2003-2005 годы
  kaz: Ақтөбе облысындағы жастар саясатының 2003-2005 жылдарға арналған Бағдарламасы туралы
form: РЕШ
type_codes:
- ПРОГ
- РЕШ
approved_on: 2003-07-01
approved_by:
- '153000000002'
version_date:
  kaz: 2003-07-01
  rus: 2003-07-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/16372/kaz/01.07.2003
  rus: https://zan.gov.kz/client/#!/doc/16372/rus/01.07.2003
