act_code: '43499'
requisite: Ақтөбе облысы Әйтеке би аудандық мәслихатының 2008 жылғы 23 желтоқсандағы N 80 шешімі. Ақтөбе облысының Әйтеке би аудандық Әділет басқармасында 2009 жылғы 15 қаңтарда N 3-2-67 тіркелді. Күші жойылды - Ақтөбе облысы Әйтеке би аудандық мәслихатының 2010 жылғы 5 ақпандағы № 176 шешімімен
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-23
approved_by:
- '153003000002'
version_date:
  kaz: 2009-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/43499/kaz/26.11.2009
caused_by:
  code: '49216'
  requisite: Ақтөбе облысы Әйтеке би аудандық мәслихатының 2009 жылғы 26 қарашадағы N 150 шешімі. Ақтөбе облысының Әйтеке би аудандық әділет басқармасында 2009 жылдың 10 желтоқсанда N 3-2-87 тіркелді. Күші жойылды - Ақтөбе облысы Әйтеке би аудандық мәслихатының 2010 жылғы 5 ақпандағы № 176 шешімімен
  title:
    rus: Аудандық мәслихаттың 2008 жылғы 23 желтоқсандағы қабылданған № 80 "2009 жылға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Аудандық мәслихаттың 2008 жылғы 23 желтоқсандағы қабылданған № 80 "2009 жылға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/49216/rus
