act_code: '42629'
requisite: Ақтөбе облысы Мұғалжар ауданы Еңбек ауылдық округі әкімінің 2008 жылғы 20 қарашадағы N 21 шешімі. Ақтөбе облысының Мұғалжар аудандық әділет басқармасында 2008 жылдың 1 желтоқсанда N 3-9-83 тіркелді
title:
  rus: Мұғалжар ауданы Еңбек ауылдық округі Тепсең-Қарабұлақ ауылына көше атауын беру туралы
  kaz: Мұғалжар ауданы Еңбек ауылдық округі Тепсең-Қарабұлақ ауылына көше атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-11-20
approved_by:
- '153009008001'
version_date:
  kaz: 2008-11-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/42629/kaz/20.11.2008
