act_code: '59969'
requisite: Решение акима сельского округа имени И. Билтабанова Кобдинского района Актюбинской области от 12 июля 2011 года № 7. Зарегистрировано Управлением юстиции Кобдинского района Актюбинской области 9 августа 2011 года № 3-7-117
title:
  rus: О присвоении наименований и переименовании улиц некоторых населенных пунктов сельского округа имени И. Билтабанова
  kaz: И. Білтабанов атындағы ауылдық округінің кейбір елді мекендерінің көшелеріне атау беру және атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-07-12
approved_by:
- '153012005002'
version_date:
  kaz: 2014-12-12
  rus: 2014-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/59969/kaz/12.12.2014
  rus: https://zan.gov.kz/client/#!/doc/59969/rus/12.12.2014
caused_by:
  code: '85987'
  requisite: Решение акима сельского округа имени И.Билтабанова Хобдинского района Актюбинской области от 12 декабря 2014 года № 7. Зарегистрировано Департаментом юстиции Актюбинской области 13 января 2015 года № 4146
  title:
    rus: 'О внесении изменений в решение акима аульного округа имени И. Билтабанова от 12 июля 2011 года № 7 «О наименовании и переименовании улиц в аульном округе имени  Имангали Билтабанова» '
    kaz: И.Білтабанов атындағы ауылдық округі әкімінің 2011 жылғы 12 шілдедегі № 7 «Иманғали Білтабанов атындағы ауылдық округіндегі көшелерді атау және атауларын өзгерту  туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/85987/rus
