act_code: '18309'
requisite: Решение акима Актюбинской области от 29 декабря 2003 года № 16. Зарегистрировано Департаментом юстиции Актюбинской области 26 января 2004 года № 2526
title:
  rus: О приписке граждан
  kaz: Азаматтарды тіркеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-12-29
approved_by:
- '153000000003'
version_date:
  kaz: 2003-12-29
  rus: 2003-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/18309/kaz/29.12.2003
  rus: https://zan.gov.kz/client/#!/doc/18309/rus/29.12.2003
