act_code: '144690'
requisite: Решение Уилского районного маслихата Актюбинской области от 1 июля 2020 года № 416. Зарегистрировано Департаментом юстиции Актюбинской области 8 июля 2020 года № 7287. Утратило силу решением Уилского районного маслихата Актюбинской области от 9 марта 2022 года № 112
title:
  rus: О повышении базовых ставок земельного налога на не используемые земли сельскохозяйственного назначения по Уилскому району
  kaz: Ойыл ауданы бойынша пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының базалық мөлшерлемелерін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-07-01
approved_by:
- '153011000002'
version_date:
  kaz: 2020-07-01
  rus: 2020-07-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/144690/kaz/01.07.2020
  rus: https://zan.gov.kz/client/#!/doc/144690/rus/01.07.2020
