act_code: '145830'
requisite: Решение Уилского районного маслихата Актюбинской области от 17 августа 2020 года № 425. Зарегистрировано Департаментом юстиции Актюбинской области 27 августа 2020 года № 7343. Утратило силу решением Уилского районного маслихата Актюбинской области от 28 марта 2024 года № 124
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Уилском районе
  kaz: Ойыл ауданында тұрғын үй көмегін көрсету мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-08-17
approved_by:
- '153011000002'
version_date:
  kaz: 2023-07-04
  rus: 2023-07-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/145830/kaz/04.07.2023
  rus: https://zan.gov.kz/client/#!/doc/145830/rus/04.07.2023
caused_by:
  code: '183898'
  requisite: Решение Уилского районного маслихата Актюбинской области от 4 июля 2023 года № 49. Зарегистрировано Департаментом юстиции Актюбинской области 13 июля 2023 года № 8382. Утратило силу решением Уилского районного маслихата Актюбинской области от 28 марта 2024 года № 124
  title:
    rus: О внесении изменения в решение Уилского районного маслихата от 17 августа 2020 года № 425 «Об определении размера и порядка оказания жилищной помощи в Уилском районе»
    kaz: Ойыл аудандық мәслихатының 2020 жылғы 17 тамыздағы № 425 «Ойыл ауданында тұрғын үй көмегін көрсету мөлшерін және тәртібін айқындау туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/183898/rus
