act_code: '103391'
requisite: Решение акима Уилского сельского округа Уилского района Актюбинской области от 29 февраля 2016 года № 31
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын алу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-02-29
approved_by:
- '153011007001'
version_date:
  kaz: 2016-02-29
  rus: 2016-02-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/103391/kaz/29.02.2016
  rus: https://zan.gov.kz/client/#!/doc/103391/rus/29.02.2016
