act_code: '48349'
requisite: ''
title:
  rus: ''
  kaz: Көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-09-16
approved_by:
- '153006001001'
version_date:
  kaz: 2015-02-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/48349/kaz/20.02.2015
caused_by:
  code: '87575'
  requisite: ''
  title:
    rus: О внесении изменений в решении акима Аманкольского сельского округа от 16 сентября 2009 года № 10 «О присвоении наименования улицам»
    kaz: Аманкөл селолық округі әкімінің 2009 жылғы 16 қыркүйектегі № 10 «Көшелерге атау беру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/87575/rus
