act_code: '48349'
requisite: ''
title:
  rus: ''
  kaz: Көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-09-16
approved_by:
- '153006001001'
version_date:
  kaz: 2009-09-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/48349/kaz/16.09.2009
