act_code: '46066'
requisite: Ақтөбе облысы Байғанин аудандық мәслихатының 2009 жылғы 24 сәуірдегі N 94 шешімі. Ақтөбе облысының Байғанин аудандық әділет басқармасында 2009 жылдың 20 мамырда N 3-4-78 тіркелді. Күші жойылды - Ақтөбе облысы Байғанин аудандық мәслихатының 2012 жылғы 18 маусымдағы № 23 шешімімен
title:
  rus: Байғанин ауданы аумағындағы елді мекендерде иттер мен мысықтарды қолда ұстау Қағидасын бекіту туралы
  kaz: Байғанин ауданы аумағындағы елді мекендерде иттер мен мысықтарды қолда ұстау Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-24
approved_by:
- '153005000002'
version_date:
  kaz: 2009-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/46066/kaz/24.04.2009
