act_code: '175938'
requisite: Решение маслихата города Актобе Актюбинской области от 22 декабря 2022 года № 220
title:
  rus: Об утверждении бюджета города Актобе на 2023 - 2025 годы
  kaz: 2023 - 2025 жылдарға арналған Ақтөбе қаласының бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-22
approved_by:
- '153002000002'
version_date:
  kaz: 2023-05-05
  rus: 2023-05-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/175938/kaz/05.05.2023
  rus: https://zan.gov.kz/client/#!/doc/175938/rus/05.05.2023
caused_by:
  code: '181217'
  requisite: Решение маслихата города Актобе Актюбинской области от 5 мая 2023 года № 22
  title:
    rus: О внесении изменений в решение маслихата города Актобе от 22 декабря 2022 года № 220 «Об утверждении бюджета города Актобе на 2023-2025 годы»
    kaz: Ақтөбе қалалық мәслихатының 2022 жылғы 22 желтоқсандағы № 220 «2023-2025 жылдарға арналған Ақтөбе қаласының бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/181217/rus
