act_code: '193172'
requisite: Решение Темирского районного маслихата Актюбинской области от 5 февраля 2024 года № 156. Зарегистрировано Департаментом юстиции Актюбинской области 9 февраля 2024 года № 8493. Утратило силу решением Темирского районного маслихата Актюбинской области от 11 ноября 2024 года № 241 (вводится в действие с 01.01.2025)
title:
  rus: О понижении размера ставки налогов при применении специального налогового режима розничного налога в Темирском районе
  kaz: Темір ауданында бөлшек салықтың арнаулы салық режимін қолдану кезінде салық мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-05
approved_by:
- '153010000002'
version_date:
  kaz: 2024-02-05
  rus: 2024-02-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/193172/kaz/05.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193172/rus/05.02.2024
repealed_on: 2025-01-01
repealed_by:
  code: '202823'
  requisite: Решение Темирского районного маслихата Актюбинской области от 11 ноября 2024 года № 241. Зарегистрировано Департаментом юстиции Актюбинской области 18 ноября 2024 года № 8651-04. Утратило силу решением Темирского районного маслихата Актюбинской области от 29 декабря 2025 года № 410 (вводится в действие с 01.01.2026)
  title:
    rus: О понижении размера ставки налогов при применении специального налогового режима розничного налога в Темирском районе
    kaz: Темір ауданында бөлшек салықтың арнаулы салық режимін қолдану кезінде салық мөлшерлемесінің мөлшерін төмендету туралы
  link: https://zan.gov.kz/client/#!/doc/202823/rus
