act_code: '98189'
requisite: Решение Хобдинского районного маслихата Актюбинской области от 23 декабря 2015 года № 227. Зарегистрировано Департаментом юстиции Актюбинской области 22 января 2016 года № 4700. Срок действия решения – до 1 января 2017 года
title:
  rus: Об утверждении бюджета Хобдинского района на 2016-2018 годы
  kaz: 2016-2018 жылдарға арналған Қобда ауданының бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-23
approved_by:
- '153012000002'
version_date:
  kaz: 2016-04-08
  rus: 2016-04-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/98189/kaz/08.04.2016
  rus: https://zan.gov.kz/client/#!/doc/98189/rus/08.04.2016
caused_by:
  code: '101662'
  requisite: Решение маслихата Хобдинского района Актюбинской области от 8 апреля 2016 года № 13. Зарегистрировано Департаментом юстиции Актюбинской области 26 апреля 2016 года № 4867
  title:
    rus: О внесении изменений и дополнений в решение районного маслихата от 23 декабря 2015 года № 227 «Об утверждении бюджета Хобдинского района на 2016-2018 годы»
    kaz: «2016-2018 жылдарға арналған Қобда ауданының бюджетін бекіту туралы» 2015 жылғы 23 желтоқсандағы № 227 аудандық мәслихаттың шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/101662/rus
