act_code: '48461'
requisite: Решение от 08.10.2009 №2, Акимат Токмансайского сельского округа
title:
  rus: Тоқмансай ауылдық округіне қарасты елді мекендерге көше атауын беру туралы
  kaz: Тоқмансай ауылдық округіне қарасты елді мекендерге көше атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-08
approved_by:
- '153004011001'
version_date:
  kaz: 2009-10-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/48461/kaz/08.10.2009
