act_code: '46223'
requisite: Ақтөбе облысы Мәртөк аудандық мәслихатының 2009 жылғы 24 сәуірдегі № 98 шешімі. Ақтөбе облысының Мәртөк аудандық Әділет басқармасында 2009 жылдың 27 мамырда № 3-8-88 тіркелді. Күші жойылды - Ақтөбе облысы Мәртөк аудандық мәслихатының 2013 жылғы 29 қаңтардағы № 59 шешімімен
title:
  rus: Қызметі эпизодикалық сипаттағы жеке тұлғаларды қосқанда базарларда тауарлар сататындар үшін біржолғы талондар құнын белгілеу туралы
  kaz: Қызметі эпизодикалық сипаттағы жеке тұлғаларды қосқанда базарларда тауарлар сататындар үшін біржолғы талондар құнын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-24
approved_by:
- '153008000002'
version_date:
  kaz: 2009-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/46223/kaz/24.04.2009
