act_code: '54215'
requisite: Ақтөбе облысы Шалқар аудандық мәслихатының 2010 жылғы 20 шілдедегі № 212 шешімі. Ақтөбе облысы Шалқар ауданының Әділет басқармасында 2010 жылғы 24 тамызда № 3-13-138 тіркелді. Күші жойылды - Ақтөбе облысы Шалқар аудандық мәслихатының 2017 жылғы 22 мамырдағы № 112 шешімімен
title:
  rus: Шалқар ауданы бойынша табысы аз отбасыларына (азаматтарға) тұрғын үй көмегін көрсету қағидаларын бекіту туралы
  kaz: Шалқар ауданы бойынша табысы аз отбасыларына (азаматтарға) тұрғын үй көмегін көрсету қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2010-07-20
approved_by:
- '153014000002'
version_date:
  kaz: 2013-11-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/54215/kaz/08.11.2013
caused_by:
  code: '75642'
  requisite: Решение маслихата Шалкарского района Актюбинской области от 8 ноября 2013 года № 113. Зарегистрировано Департаментом юстиции Актюбинской области 29 ноября 2013 года № 3690. Утратило силу решением маслихата Шалкарского района Актюбинской области от 22 мая 2017 года № 112
  title:
    rus: О внесении изменений в решение районного маслихата от 20 июля 2010 года № 212 "О размере и порядке оказания жилищной помощи"
    kaz: Аудандық мәслихаттың 2010 жылғы 20 шілдедегі № 212 "Тұрғын үй көмегін көрсетудің мөлшері мен тәртібі туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/75642/rus
