act_code: '49314'
requisite: Ақтөбе облысы Қарғалы ауданының Бадамша ауылдық округі әкімінің 2009 жылғы 30 қазандағы N 1 шешімі. Ақтөбе облысы Қарғалы аудандық әділет басқармасында 2009 жылғы 4 желтоқсанда N 3-6-92 тіркелді
title:
  rus: Бадамша ауылдық округінің Кемпірсай станциясындағы көшелерге атау беру туралы
  kaz: Бадамша ауылдық округінің Кемпірсай станциясындағы көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-30
approved_by:
- '153007008002'
version_date:
  kaz: 2009-10-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/49314/kaz/30.10.2009
