act_code: '163998'
requisite: Решение Мугалжарского районного маслихата Актюбинской области от 30 декабря 2021 года № 138
title:
  rus: Об утверждении бюджета Кайындинского сельского округа на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Қайыңды ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '153009000002'
version_date:
  kaz: 2022-04-08
  rus: 2022-04-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/163998/kaz/08.04.2022
  rus: https://zan.gov.kz/client/#!/doc/163998/rus/08.04.2022
caused_by:
  code: '166603'
  requisite: Решение Мугалжарского районного маслихата Актюбинской области от 8 апреля 2022 года № 171
  title:
    rus: О внесении изменений в решение Мугалжарского районного маслихата от 30 декабря 2021 года № 138 «Об утверждении бюджета Кайындинского сельского округа на 2022-2024 годы»
    kaz: Мұғалжар аудандық мәслихатының 2021 жылғы 30 желтоқсандағы № 138 «2022-2024 жылдарға арналған Қайыңды ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/166603/rus
