act_code: '37663'
requisite: Ақтөбе облысы Ырғыз аудандық әкімиятының 2008 жылғы 8 қаңтардағы N 1 шешімі. Ақтөбе облысы Ырғыз ауданының Әділет басқармасында 2008 жылғы 23 қаңтарда N 3-5-67 тіркелді. Күші жойылды - Ақтөбе облысы Ырғыз аудандық әкімиятының 2008 жылғы 15 желтоқсандағы N 5 шешімімен
title:
  rus: Аудандық қорғаныс істері жөніндегі бөлімінің шақыру учаскесіне 1991 жылы туылған азаматтарды кезекті тіркеу және медициналық куәландыру жайлы
  kaz: Аудандық қорғаныс істері жөніндегі бөлімінің шақыру учаскесіне 1991 жылы туылған азаматтарды кезекті тіркеу және медициналық куәландыру жайлы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-01-08
approved_by:
- '153006000001'
version_date:
  kaz: 2008-01-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/37663/kaz/08.01.2008
