act_code: '225132'
requisite: Решение Мартукского районного маслихата Актюбинской области от 5 мая 2026 года № 315. Утратило силу решением Мартукского районного маслихата Актюбинской области от 15.07.2026 № 338 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об оказании дополнительной социальной помощи отдельным категориям нуждающихся граждан Мартукского района в связи с 40 годовщиной ликвидации последствий катастрофы на Чернобыльской атомной электростанции
  kaz: Чернобыль атом электр станциясындағы апат салдарын жоюдың 40 жылдығына орай Мәртөк ауданының мұқтаж азаматтарының санаттарына қосымша әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-05-05
approved_by:
- '153008000002'
version_date:
  kaz: 2026-05-05
  rus: 2026-05-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/225132/kaz/05.05.2026
  rus: https://zan.gov.kz/client/#!/doc/225132/rus/05.05.2026
