act_code: '84555'
requisite: Решение акима Токмансайского сельского округа Алгинского района Актюбинской области от 11 ноября 2014 года № 18. Зарегистрировано Департаментом юстиции Актюбинской области 25 ноября 2014 года № 4081
title:
  rus: О переименовании улицы
  kaz: Көшені қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-11-11
approved_by:
- '153004011001'
version_date:
  kaz: 2014-11-11
  rus: 2014-11-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/84555/kaz/11.11.2014
  rus: https://zan.gov.kz/client/#!/doc/84555/rus/11.11.2014
