act_code: '205612'
requisite: Решение Кобдинского районного маслихата Актюбинской области от 25 декабря 2024 года № 260
title:
  rus: Об утверждении Кобдинского районного бюджета на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Қобда аудандық бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '153012000002'
version_date:
  kaz: 2024-12-25
  rus: 2024-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/205612/kaz/25.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205612/rus/25.12.2024
