act_code: '73771'
requisite: Решение Хромтауского районного маслихата Актюбинской области от 10 июля 2013 года № 112. Зарегистрировано Департаментом юстиции Актюбинской области 31 июля 2013 года № 3623. Утратило силу решением Хромтауского районного маслихата Актюбинской области от 27 мая 2014 года № 186
title:
  rus: О предоставлении мер социальной поддержки специалистам здравоохранения, образования, социального обеспечения, культуры, спорта и ветеринарии, прибывшим для работы и проживания в сельские населенные пункты
  kaz: Ауылдық елді мекендерге жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және ветеринария  мамандарына әлеуметтік қолдау шараларын ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-07-10
approved_by:
- '153013000002'
version_date:
  kaz: 2013-07-10
  rus: 2013-07-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/73771/kaz/10.07.2013
  rus: https://zan.gov.kz/client/#!/doc/73771/rus/10.07.2013
