act_code: '41812'
requisite: Решение маслихата Мартукского района Актюбинской области от 25 сентября 2008 года N 61. Зарегистрировано в Управлении юстиции Мартукского района Актюбинской области 7 октября 2008 года за N 3-8-59. Утратило силу решением маслихата Мартукского района Актюбинской области от 23 апреля 2010 года N 167
title:
  rus: Об оказании социальной помощи членам малообеспеченных семей
  kaz: Аз қамтылған отбасы мүшелеріне әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-09-25
approved_by:
- '153008000002'
version_date:
  kaz: 2008-09-25
  rus: 2008-09-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/41812/kaz/25.09.2008
  rus: https://zan.gov.kz/client/#!/doc/41812/rus/25.09.2008
