act_code: '219861'
requisite: Решение Каргалинского районного маслихата Актюбинской области от 23 декабря 2025 года № 417
title:
  rus: Об утверждении бюджета Кос-Истекского сельского округа на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған Қос Естек ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-23
approved_by:
- '153007000002'
version_date:
  kaz: 2026-02-20
  rus: 2026-02-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/219861/kaz/20.02.2026
  rus: https://zan.gov.kz/client/#!/doc/219861/rus/20.02.2026
caused_by:
  code: '222589'
  requisite: Решение Каргалинского районного маслихата Актюбинской области от 20 февраля 2026 года № 440
  title:
    rus: О внесении изменений в решение Каргалинского районного маслихата от 23 декабря 2025 года № 417 «Об утверждении бюджета Кос-Истекского сельского округа на 2026-2028 годы»
    kaz: Қарғалы аудандық мәслихатының 2025 жылғы 23 желтоқсандағы № 417 «2026-2028 жылдарға арналған Қос Естек ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/222589/rus
