act_code: '42898'
requisite: Решение акима сельского округа Аккудык Мартукского района Актюбинской области от 22 декабря 2008 года N 1. Зарегистрировано Управлением юстиции Мартукского района Актюбинской области 24 декабря 2008 года за N 3-8-70
title:
  rus: О присвоении наименований улицам населенных пунктов аульного округа "Аккудык"
  kaz: Аққұдық ауылдық округінің елді мекендерінің көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-22
approved_by:
- '153008012002'
version_date:
  kaz: 2019-05-27
  rus: 2019-05-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/42898/kaz/27.05.2019
  rus: https://zan.gov.kz/client/#!/doc/42898/rus/27.05.2019
caused_by:
  code: '132072'
  requisite: Решение акима Аккудыкского сельского округа Мартукского района Актюбинской области от 27 мая 2019 года № 1. Зарегистрировано Департаментом юстиции Актюбинской области 29 мая 2019 года № 6204
  title:
    rus: О внесении изменения в решение акима Аккудыкского сельского округа от 22 декабря 2008 года № 1 «О присвоении наименований улицам населенных пунктов Аккудыкского сельского округа»
    kaz: Аққұдық ауылдық округі әкімінің 2008 жылғы 22 желтоқсандағы № 1 «Аққұдық ауылдық округінің елді мекендерінің көшелеріне атау беру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/132072/rus
