act_code: '96553'
requisite: Решение маслихата Уилского района Актюбинской области от 9 ноября 2015 года № 268. Зарегистрировано Департаментом юстиции Актюбинской области 9 декабря 2015 года № 4630. Утратило силу решением маслихата Уилского района Актюбинской области от 29 февраля 2016 года № 296
title:
  rus: Об утверждении методики ежегодной оценки деятельности административных государственных служащих корпуса "Б" государственного учреждения "Аппарат Уилского районного маслихата"
  kaz: '"Ойыл аудандық мәслихатының аппараты" мемлекеттік мекемесінің "Б" корпусы мемлекеттік әкімшілік қызметшілерінің қызметін жыл сайынғы бағалау әдістемесін бекіту туралы'
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2015-11-09
approved_by:
- '153011000002'
version_date:
  kaz: 2015-11-09
  rus: 2015-11-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/96553/kaz/09.11.2015
  rus: https://zan.gov.kz/client/#!/doc/96553/rus/09.11.2015
