act_code: '1733'
requisite: Решение акима Актюбинской области от 23 сентября 1998 года № 141. Зарегистрировано Управлением юстиции Актюбинской области 11 ноября 1998 года № 55. Утратило силу в связи с истечением срока действия согласно письма акимата Актюбинской области от 24 марта 2006 года № 07-4/670
title:
  rus: Об обеспечении безопасности при использовании сжиженного газа в быту
  kaz: Тұрмыста сұйық газды пайдалану қауіпсіздігін сақтау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-09-22
approved_by:
- '153000000003'
version_date:
  kaz: 1998-09-22
  rus: 1998-09-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/1733/kaz/22.09.1998
  rus: https://zan.gov.kz/client/#!/doc/1733/rus/22.09.1998
