act_code: '138888'
requisite: Решение Айтекебийского районного маслихата Актюбинской области от 6 января 2020 года № 354. Зарегистрировано Департаментом юстиции Актюбинской области 15 января 2020 года № 6730
title:
  rus: Об утверждении бюджета Айкенского сельского округа на 2020 - 2022 годы
  kaz: 2020 – 2022 жылдарға арналған Әйке ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-06
approved_by:
- '153003000002'
version_date:
  kaz: 2020-09-14
  rus: 2020-09-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/138888/kaz/14.09.2020
  rus: https://zan.gov.kz/client/#!/doc/138888/rus/14.09.2020
caused_by:
  code: '146725'
  requisite: Решение Айтекебийского районного маслихата Актюбинской области от 14 сентября 2020 года № 454. Зарегистрировано Департаментом юстиции Актюбинской области 24 сентября 2020 года № 7460
  title:
    rus: О внесении изменений в решение районного маслихата от 6 января 2020 года № 354 «Об утверждении бюджета Айкенского сельского округа на 2020 - 2022 годы»
    kaz: Аудандық мәслихатының 2020 жылғы 6 қаңтардағы № 354 «2020 - 2022 жылдарға арналған Әйке ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/146725/rus
