act_code: '51299'
requisite: Ақтөбе облысы Алға аудандық мәслихатының 2010 жылғы 22 ақпандағы № 4 шешімі. Ақтөбе облысының Алға аудандық Әділет басқармасында 2010 жылдың 17 наурызда № 3-3-105 тіркелді. Күші жойылды - Ақтөбе облысы Алға аудандық мәслихатының 2013 жылғы 31 қаңтардағы № 70 шешімімен
title:
  rus: Тұрғын үй көмегін көрсету Қағидасын бекіту туралы
  kaz: Тұрғын үй көмегін көрсету Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-22
approved_by:
- '153004000002'
version_date:
  kaz: 2010-02-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/51299/kaz/22.02.2010
