act_code: '49328'
requisite: Ақтөбе облысы Мәртөк аудандық әкімінің 2009 жылғы 11 желтоқсандағы N 10 шешімі. Ақтөбе облысы Мәртөк аудандық әділет басқармасында 2009 жылғы 14 желтоқсанда N 3-8-102 тіркелді. Күші жойылды - Ақтөбе облысы Мәртөк ауданының әкімінің 2011 жылғы 17 қаңтардағы № 1 шешімімен
title:
  rus: 2010 жылдың қаңтар-наурыз айларында 1993 жылы туылған азаматтарды Мәртөк ауданының шақыру учаскесіне тіркеу туралы
  kaz: 2010 жылдың қаңтар-наурыз айларында 1993 жылы туылған азаматтарды Мәртөк ауданының шақыру учаскесіне тіркеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-11
approved_by:
- '153008000001'
version_date:
  kaz: 2009-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/49328/kaz/11.12.2009
