act_code: '220792'
requisite: Решение Мугалжарского районного маслихата Актюбинской области от 26 декабря 2025 года № 506
title:
  rus: Об утверждении бюджета сельского округа имени К. Жубанова на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған Қ. Жұбанов атындағы ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-26
approved_by:
- '153009000002'
version_date:
  kaz: 2026-07-15
  rus: 2026-07-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/220792/kaz/15.07.2026
  rus: https://zan.gov.kz/client/#!/doc/220792/rus/15.07.2026
caused_by:
  code: '228033'
  requisite: Решение Мугалжарского районного маслихата Актюбинской области от 15 июля 2026 года № 593
  title:
    rus: О внесении изменений в решение Мугалжарского районного маслихата от 26 декабря 2025 года № 506 «Об утверждении бюджета сельского округа имени К. Жубанова на 2026-2028 годы»
    kaz: Мұғалжар аудандық мәслихатының 2025 жылғы 26 желтоқсандағы № 506 «2026-2028 жылдарға арналған Қ. Жұбанов атындағы ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/228033/rus
