act_code: '220803'
requisite: Решение Темирского районного маслихата Актюбинской области от 29 декабря 2025 года № 401
title:
  rus: Об утверждении бюджета Алтыкарасуского сельского округа на 2026–2028 годы
  kaz: 2026–2028 жылдарға арналған Алтықарасу ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-29
approved_by:
- '153010000002'
version_date:
  kaz: 2026-08-06
  rus: 2026-08-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/220803/kaz/06.08.2026
  rus: https://zan.gov.kz/client/#!/doc/220803/rus/06.08.2026
caused_by:
  code: '228731'
  requisite: Решение Темирского районного маслихата Актюбинской области от 6 августа 2026 года № 463
  title:
    rus: О внесении изменений в решение Темирского районного маслихата от 29 декабря 2025 года № 401 «Об утверждении бюджета Алтыкарасуского сельского округа на 2026–2028 годы»
    kaz: Темір аудандық мәслихатының 2025 жылғы 29 желтоқсандағы № 401 «2026–2028 жылдарға арналған Алтықарасу ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/228731/rus
