act_code: '23994'
requisite: Решение Мартукского районного маслихата Актюбинской области от 9 декабря 2005 года № 169. Зарегистрировано Управлением юстиции Мартукского района Департамента юстиции Актюбинской области 14 декабря 2005 года № 3-8-12
title:
  rus: О бюджете Мартукского района на 2006 год
  kaz: Мәртөк ауданының 2006 жылға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-12-09
approved_by:
- '153008000002'
version_date:
  kaz: 2005-12-09
  rus: 2005-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/23994/kaz/09.12.2005
  rus: https://zan.gov.kz/client/#!/doc/23994/rus/09.12.2005
