act_code: '47647'
requisite: Ақтөбе облысы Шалқар ауданы Тоғыз ауылдық округі әкімінің 2009 жылғы 31 шілдедегі N 3 шешімі. Ақтөбе облысының Шалқар аудандық әділет басқармасында 2009 жылдың 3 қыркүйекте N 3-13-115 тіркелді
title:
  rus: Тоғыз селолық округіне қарасты елді мекендерге көше атауларын беру туралы
  kaz: Тоғыз селолық округіне қарасты елді мекендерге көше атауларын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-07-31
approved_by:
- '153014008002'
version_date:
  kaz: 2021-01-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/47647/kaz/20.01.2021
caused_by:
  code: '152357'
  requisite: Решение акима Тогызского сельского округа Шалкарского района Актюбинской области от 20 января 2021 года № 1. Зарегистрировано Департаментом юстиции Актюбинской области 20 января 2021 года № 8018
  title:
    rus: О внесении изменений в решение акима Тогызского сельского округа от 31 июля 2009 года № 3 «Тоғыз ауылдық округіне қарасты елді мекендерге көше атауларын беру туралы»
    kaz: Тоғыз ауылдық округі әкімінің 2009 жылғы 31 шілдедегі № 3 «Тоғыз ауылдық округіне қарасты елді мекендерге көше атауларын беру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/152357/rus
