act_code: '77164'
requisite: Решение акима города Актобе Актюбинской области от 20 января 2014 года № 1. Зарегистрировано Департаментом юстиции Актюбинской области 27 января 2014 года № 3768. Утратило силу решением акима города Актобе Актюбинской области от 29 ноября 2018 года № 4
title:
  rus: Об образовании избирательных участков на территории города Актобе
  kaz: Ақтөбе қаласының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-01-20
approved_by:
- '153002000001'
version_date:
  kaz: 2015-10-21
  rus: 2015-10-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/77164/kaz/21.10.2015
  rus: https://zan.gov.kz/client/#!/doc/77164/rus/21.10.2015
caused_by:
  code: '94762'
  requisite: Решение акима города Актобе Актюбинской области от 21 октября 2015 года № 13. Зарегистрировано Департаментом юстиции Актюбинской области 23 октября 2015 года № 4548. Утратило силу решением акима города Актобе Актюбинской области от 29 ноября 2018 года № 4
  title:
    rus: О внесении изменений и дополнений в решение акима города Актобе от 20 января 2014 года № 1 "Об образовании избирательных участков на территории города Актобе"
    kaz: Ақтөбе қаласы әкімінің 2014 жылғы 20 қаңтардағы № 1 "Ақтөбе қаласының аумағында сайлау учаскелерін құру туралы" шешіміне өзгерістер және толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/94762/rus
