act_code: '151133'
requisite: Решение Байганинского районного маслихата Актюбинской области от 29 декабря 2020 года № 403. Зарегистрировано Департаментом юстиции Актюбинской области 31 декабря 2020 года № 7896
title:
  rus: Об утверждении бюджета Ащынского сельского округа на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Ащы ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-29
approved_by:
- '153005000002'
version_date:
  kaz: 2020-12-29
  rus: 2020-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/151133/kaz/29.12.2020
  rus: https://zan.gov.kz/client/#!/doc/151133/rus/29.12.2020
