act_code: '176734'
requisite: Решение Кобдинского районного маслихата Актюбинской области от 28 декабря 2022 года № 273
title:
  rus: Об утверждении бюджета Жарыкского сельского округа на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Жарық ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-28
approved_by:
- '153012000002'
version_date:
  kaz: 2023-12-07
  rus: 2023-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/176734/kaz/07.12.2023
  rus: https://zan.gov.kz/client/#!/doc/176734/rus/07.12.2023
caused_by:
  code: '190070'
  requisite: Решение Кобдинского районного маслихата Актюбинской области от 7 декабря 2023 года № 104
  title:
    rus: О внесении изменений в решение Кобдинского районного маслихата от 28 декабря 2022 года № 273 «Об утверждении бюджета Жарыкского сельского округа на 2023-2025 годы»
    kaz: Қобда аудандық мәслихатының 2022 жылғы 28 желтоқсандағы № 273 «2023-2025 жылдарға арналған Жарық ауылдық бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/190070/rus
