act_code: '139021'
requisite: Решение Темирского районного маслихата Актюбинской области от 6 января 2020 года № 434. Зарегистрировано Департаментом юстиции Актюбинской области 17 января 2020 года № 6740
title:
  rus: Об утверждении бюджета города Темира на 2020 - 2022 годы
  kaz: 2020 – 2022 жылдарға арналған Темір қаласы бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-06
approved_by:
- '153010000002'
version_date:
  kaz: 2020-11-20
  rus: 2020-11-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/139021/kaz/20.11.2020
  rus: https://zan.gov.kz/client/#!/doc/139021/rus/20.11.2020
caused_by:
  code: '149112'
  requisite: Решение Темирского районного маслихата Актюбинской области от 20 ноября 2020 года № 543. Зарегистрировано Департаментом юстиции Актюбинской области 27 ноября 2020 года № 7716
  title:
    rus: О внесении изменений и дополнения в решение районного маслихата от 6 января 2020 года № 434 «Об утверждении бюджета города Темира на 2020–2022 годы»
    kaz: Аудандық мәслихаттың 2020 жылғы 6 қаңтардағы № 434 «2020–2022 жылдарға арналған Темір қаласы бюджетін бекіту туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149112/rus
