act_code: '53792'
requisite: Решение от 28.06.2010 №7, Акимат Бугетсайского сельского округа
title:
  rus: Бөгетсай ауылдық округі Бөгетсай ауылының көшелеріне атаулар беру туралы
  kaz: Бөгетсай ауылдық округі Бөгетсай ауылының көшелеріне атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-28
approved_by:
- '153013005001'
version_date:
  kaz: 2010-06-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/53792/kaz/28.06.2010
