act_code: '174679'
requisite: Решение акима Жиренкопинского сельского округа Кобдинского района Актюбинской области от 25 ноября 2022 года № 12. Зарегистрировано в Министерстве юстиции Республики Казахстан 29 ноября 2022 года № 30824
title:
  rus: О переименовании улицы села Жиренкопа Жиренкопинского сельского округа Кобдинского района
  kaz: Қобда ауданы Жиренқопа ауылдық округінің Жиренқопа ауылының көшесін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-11-25
approved_by:
- '153012009002'
version_date:
  kaz: 2022-11-25
  rus: 2022-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/174679/kaz/25.11.2022
  rus: https://zan.gov.kz/client/#!/doc/174679/rus/25.11.2022
