act_code: '198848'
requisite: Решение Актюбинского областного маслихата от 10 июля 2024 года № 156. Зарегистрировано Департаментом юстиции Актюбинской области 16 июля 2024 года № 8608-04. Утратило силу решением Актюбинского областного маслихата от 12 декабря 2024 года № 190 (вводится в действие после дня его первого официального опубликования)
title:
  rus: Об определении перечня социально значимых автомобильных сообщений города Хромтау, подлежащих субсидированию в 2024-2026 годах
  kaz: 2024-2026 жылдары субсидиялауға жататын Хромтау қаласының әлеуметтік маңызы бар автомобиль қатынастарының тізбесін айқындау туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2024-07-10
approved_by:
- '153000000002'
version_date:
  kaz: 2024-07-10
  rus: 2024-07-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/198848/kaz/10.07.2024
  rus: https://zan.gov.kz/client/#!/doc/198848/rus/10.07.2024
