act_code: '105371'
requisite: Решение акима Аккудукского сельского округа Хромтауского района Актюбинской области от 12 августа 2016 года № 7
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын алып тастау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-08-12
approved_by:
- '153013004001'
version_date:
  kaz: 2016-08-12
  rus: 2016-08-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/105371/kaz/12.08.2016
  rus: https://zan.gov.kz/client/#!/doc/105371/rus/12.08.2016
