act_code: '193984'
requisite: Решение Темирского районного маслихата Актюбинской области от 27 февраля 2024 года № 159. Зарегистрировано Департаментом юстиции Актюбинской области 5 марта 2024 года № 8523-04
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2024 год по Темирскому району
  kaz: Темір ауданы бойынша 2024 жылға шетелдіктер үшін туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-27
approved_by:
- '153010000002'
version_date:
  kaz: 2024-02-27
  rus: 2024-02-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/193984/kaz/27.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193984/rus/27.02.2024
