act_code: '221877'
requisite: Решение Актюбинского областного маслихата от 30 января 2026 года № 309
title:
  rus: Об утверждении размера платы за один кубический метр питьевой воды, поданной из систем водоснабжения, включенных в перечень систем водоснабжения, стоимость услуг по подаче питьевой воды которых подлежит субсидированию в Актюбинской области
  kaz: Ақтөбе облысында ауыз суды беру жөніндегі қызметтердің құны субсидиялауға жататын сумен жабдықтау жүйелерінің тізбесіне енгізілген сумен жабдықтау жүйелерінен берілген ауыз судың бір текше метріне төленетін төлемақының мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-01-30
approved_by:
- '153000000002'
version_date:
  kaz: 2026-01-30
  rus: 2026-01-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/221877/kaz/30.01.2026
  rus: https://zan.gov.kz/client/#!/doc/221877/rus/30.01.2026
