act_code: '50903'
requisite: Ақтөбе облысы Темір аудандық мәслихатының 2010 жылғы 12 ақпандағы № 177 шешімі. Ақтөбе облысының Темір аудандық Әділет басқармасында 2010 жылдың 26 ақпанда № 3-10-122 тіркелді
title:
  rus: Тіркелген салықтың мөлшерлемелерін белгілеу туралы
  kaz: Тіркелген салықтың мөлшерлемелерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-12
approved_by:
- '153010000002'
version_date:
  kaz: 2010-02-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/50903/kaz/12.02.2010
