act_code: '60990'
requisite: Решение акима Жанажолского сельского округа Байганинского района Актюбинской области от 5 октября 2011 года № 4. Зарегистрировано Управлением юстиции Байганинского района Актюбинской области 25 октября 2011 года № 3-4-124
title:
  rus: О присвоении наименований улицам села Оймауыт Жанажолского сельского округа
  kaz: Жаңажол ауылдық округі Оймауыт ауылының көшелеріне атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-10-05
approved_by:
- '153005002002'
version_date:
  kaz: 2011-10-05
  rus: 2011-10-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/60990/kaz/05.10.2011
  rus: https://zan.gov.kz/client/#!/doc/60990/rus/05.10.2011
