act_code: '117099'
requisite: Решение маслихата Актюбинской области от 8 декабря 2017 года № 217. Зарегистрировано Департаментом юстиции Актюбинской области 27 декабря 2017 года № 5771
title:
  rus: Об областном бюджете на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-08
approved_by:
- '153000000002'
version_date:
  kaz: 2018-12-10
  rus: 2018-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/117099/kaz/10.12.2018
  rus: https://zan.gov.kz/client/#!/doc/117099/rus/10.12.2018
caused_by:
  code: '126755'
  requisite: Решение маслихата Актюбинской области от 10 декабря 2018 года № 349. Зарегистрировано Департаментом юстиции Актюбинской области 12 декабря 2018 года № 5960
  title:
    rus: О внесении изменений в решение областного маслихата от 8 декабря 2017 года № 217 «Об областном бюджете на 2018-2020 годы»
    kaz: Облыстық мәслихаттың 2017 жылғы 8 желтоқсандағы № 217«2018-2020 жылдарға арналған облыстық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/126755/rus
