act_code: '97235'
requisite: Решение Актюбинского областного маслихата от 11 декабря 2015 года № 346. Зарегистрировано Департаментом юстиции Актюбинской области 8 января 2016 года № 4667
title:
  rus: Об областном бюджете на 2016-2018 годы
  kaz: 2016-2018 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-11
approved_by:
- '153000000002'
version_date:
  kaz: 2016-10-28
  rus: 2016-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/97235/kaz/28.10.2016
  rus: https://zan.gov.kz/client/#!/doc/97235/rus/28.10.2016
caused_by:
  code: '107213'
  requisite: Решение маслихата Актюбинской области от 28 октября 2016 года № 69. Зарегистрировано Департаментом юстиции Актюбинской области 2 ноября 2016 года № 5119
  title:
    rus: О внесении изменений и дополнений в решение областного маслихата от 11 декабря 2015 года № 346 "Об областном бюджете на 2016-2018 годы"
    kaz: '"2016 - 2018 жылдарға арналған облыстық бюджет туралы" облыстық мәслихаттың 2015 жылғы 11 желтоқсандағы № 346 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/107213/rus
