act_code: '61289'
requisite: Решение маслихата Уилского района Актюбинской области от 25 октября 2011 года № 296. Зарегистрировано Департаментом юстиции Актюбинской области 15 ноября 2011 года № 3-11-101. Утратило силу в связи с истечением срока действия - письмо маслихата Уилского района Актюбинской области от 30 марта 2012 года № 27
title:
  rus: О предоставлении в 2011 году подъемного пособия и бюджетного кредита для социальной поддержки специалистов здравоохранения, образования, социального обеспечения, культуры и спорта, прибывшим для работы и проживания в сельские населенные пункты
  kaz: 2011 жылғы денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына әлеуметтік қолдау ретінде көтерме жәрдемақы мен бюджеттік кредит беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-10-25
approved_by:
- '153011000002'
version_date:
  kaz: 2011-10-25
  rus: 2011-10-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/61289/kaz/25.10.2011
  rus: https://zan.gov.kz/client/#!/doc/61289/rus/25.10.2011
