act_code: '77067'
requisite: Решение от 25.12.2013 №103, Маслихат Мартукского района. Утратило силу решением маслихата Мартукского района Актюбинской области от 10.06.2015 № 181
title:
  rus: Об утверждении предельных размеров социальной помощи, предоставляемой отдельным категориям нуждающихся граждан, при наступлении трудной жизненной ситуации
  kaz: Мұқтаж азаматтардың жекелеген санаттарына өмірлік қиын жағдай туындаған кезде көрсететін әлеуметтік көмектің шекті мөлшерлерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-25
approved_by:
- '153008000002'
version_date:
  kaz: 2013-12-25
  rus: 2013-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/77067/kaz/25.12.2013
  rus: https://zan.gov.kz/client/#!/doc/77067/rus/25.12.2013
