act_code: '46372'
requisite: Ақтөбе облысы Шалқар ауданы Мөңке би ауылдық округі әкімінің 2009 жылғы 20 мамырдағы N 3 шешімі. Ақтөбе облысының Шалқар аудандық әділет басқармасында 2009 жылдың 5 маусымда N 3-13-111 тіркелді
title:
  rus: Көшелерге атау беру туралы
  kaz: Көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-05-20
approved_by:
- '153014013002'
version_date:
  kaz: 2014-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/46372/kaz/05.12.2014
caused_by:
  code: '85108'
  requisite: Решение от 05.12.2014 №18, Акимат Монкебийского сельского округа
  title:
    rus: О внесении изменений в решение акима Монкебийского сельского округа Шалкарского района от 20 мая 2009 года № 3 "О присвоении наименования улицам"
    kaz: Шалқар ауданы Мөңке би селолық округі әкімінің 2009 жылғы 20 мамырдағы № 3 "Көшелерге атау беру туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/85108/rus
