act_code: '52546'
requisite: Ақтөбе облысы Мәртөк аудандық мәслихатының 2010 жылғы 23 сәуірдегі № 168 шешімі. Ақтөбе облысының Мәртөк аудандық Әділет басқармасында 2010 жылдың 18 мамырда № 3-8-113 тіркелді. Күші жойылды - Ақтөбе облысы Мәртөк аудандық мәслихатының 2012 жылғы 9 тамыздағы № 34 шешімімен
title:
  rus: Мәртөк ауданының елді мекендеріндегі үй жануарларын ұстау Қағидасын бекіту туралы
  kaz: Мәртөк ауданының елді мекендеріндегі үй жануарларын ұстау Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-23
approved_by:
- '153008000002'
version_date:
  kaz: 2010-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/52546/kaz/23.04.2010
