act_code: '50370'
requisite: Ақтөбе облысы Байғанин аудандық мәслихатының 2009 жылғы 25 желтоқсандағы N 111 шешімі. Ақтөбе облысының Байғанин аудандық Әділет басқармасында 2010 жылдың 25 қаңтарда N 3-4-90 тіркелді. Күші жойылды - Ақтөбе облысы Байғанин аудандық мәслихатының 2011 жылғы 26 шілдедегі № 186 шешімімен
title:
  rus: 2010-2012 жылдарға арналған Байғанин ауданының бюджеті туралы
  kaz: 2010-2012 жылдарға арналған Байғанин ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '153005000002'
version_date:
  kaz: 2010-02-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/50370/kaz/24.02.2010
caused_by:
  code: '51161'
  requisite: Ақтөбе облысы Байғанин аудандық мәслихатының 2010 жылғы 24 ақпандағы N 131 шешімі. Ақтөбе облысы Байғанин ауданының Әділет басқармасында 2010 жылғы 11 наурызда N 3-4-96 тіркелді. Күші жойылды - Ақтөбе облысы Байғанин аудандық мәслихатының 2011 жылғы 26 шілдедегі № 186 шешімімен
  title:
    rus: 2009 жылғы 25 желтоқсандағы № 111 "2010-2012 жылдарға арналған Байғанин ауданының бюджеті туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: 2009 жылғы 25 желтоқсандағы № 111 "2010-2012 жылдарға арналған Байғанин ауданының бюджеті туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/51161/rus
