act_code: '48184'
requisite: Ақтөбе облысы Қобда ауданы Қобда ауылдық округі әкімінің 2009 жылғы 28 тамыздағы N 43 шешімі. Ақтөбе облысының Қобда аудандық әділет басқармасында 2009 жылдың 14 қазанда N 3-7-76 тіркелді
title:
  rus: Қобда ауылындағы Желтоқсан көшесінің атауын өзгерту туралы
  kaz: Қобда ауылындағы Желтоқсан көшесінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-08-28
approved_by:
- '153012016001'
version_date:
  kaz: 2009-08-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/48184/kaz/28.08.2009
