act_code: '225134'
requisite: Решение Темирского районного маслихата Актюбинской области от 5 мая 2026 года № 438
title:
  rus: Об оказании дополнительной социальной помощи отдельным категориям нуждающихся граждан по Темирскому району в связи с 40-й годовщиной ликвидации последствий катастрофы на Чернобыльской атомной электростанции
  kaz: Чернобыль атом электр станциясындағы апат салдарын жоюдың 40-жылдығына орай Темір ауданы бойынша мұқтаж азаматтарының санаттарына қосымша әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-05-05
approved_by:
- '153010000002'
version_date:
  kaz: 2026-05-05
  rus: 2026-05-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/225134/kaz/05.05.2026
  rus: https://zan.gov.kz/client/#!/doc/225134/rus/05.05.2026
