act_code: '117763'
requisite: Решение маслихата Хромтауского района Актюбинской области от 21 декабря 2017 года № 177. Зарегистрировано Департаментом юстиции Актюбинской области 8 января 2018 года № 5804
title:
  rus: Об утверждении бюджета Коктауского сельского округа на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған Көктау ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-21
approved_by:
- '153013000002'
version_date:
  kaz: 2018-04-02
  rus: 2018-04-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/117763/kaz/02.04.2018
  rus: https://zan.gov.kz/client/#!/doc/117763/rus/02.04.2018
caused_by:
  code: '120371'
  requisite: Решение Хромтауского районного маслихата Актюбинской области от 2 апреля 2018 года № 205. Зарегистрировано Управлением юстиции Хромтауского района Актюбинской области 10 апреля 2018 года № 3-12-167
  title:
    rus: О внесении изменений в решение районного маслихата от 21 декабря 2017 года № 177 «Об утверждении бюджета Коктауского сельского округа на 2018-2020 годы»
    kaz: Аудандық мәслихаттың 2017 жылғы 21 желтоқсандағы № 177 «2018-2020 жылдарға арналған Көктау ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/120371/rus
