act_code: '195807'
requisite: Решение Мартукского районного маслихата Актюбинской области от 10 апреля 2024 года № 108. Зарегистрировано Департаментом юстиции Актюбинской области 16 апреля 2024 года № 8572-04
title:
  rus: Об утверждении размера и Правил оказания жилищной помощи в Мартукском районе
  kaz: Мәртөк ауданында тұрғын үй көмегін көрсетудің мөлшері мен қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2024-04-10
approved_by:
- '153008000002'
version_date:
  kaz: 2025-09-10
  rus: 2025-09-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/195807/kaz/10.09.2025
  rus: https://zan.gov.kz/client/#!/doc/195807/rus/10.09.2025
caused_by:
  code: '214250'
  requisite: Решение Мартукского районного маслихата Актюбинской области от 10 сентября 2025 года № 241. Зарегистрировано в Министерстве юстиции Республики Казахстан 11 сентября 2025 года № 36820
  title:
    rus: О внесении изменений в решение Мартукского районного маслихата от 10 апреля 2024 года № 108 «Об определении размера и порядка оказания жилищной помощи в Мартукском районе»
    kaz: Мәртөк аудандық мәслихатының 2024 жылғы 10 сәуірдегі № 108 «Мәртөк ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/214250/rus
