act_code: '163571'
requisite: Решение Алгинского районного маслихата Актюбинской области от 29 декабря 2021 года № 133
title:
  rus: Об утверждении бюджета Токмансайского сельского округа на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Тоқмансай ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-29
approved_by:
- '153004000002'
version_date:
  kaz: 2022-06-22
  rus: 2022-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/163571/kaz/22.06.2022
  rus: https://zan.gov.kz/client/#!/doc/163571/rus/22.06.2022
caused_by:
  code: '169509'
  requisite: Решение Алгинского районного маслихата Актюбинской области от 22 июня 2022 года № 189
  title:
    rus: О внесении изменений в решение Алгинского районного маслихата от 29 декабря 2021 года № 133 «Об утверждении бюджета Токмансайского сельского округа на 2022-2024 годы»
    kaz: Алға аудандық мәслихатының 2021 жылғы 29 желтоқсандағы № 133 «2022-2024 жылдарға арналған Тоқмансай ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/169509/rus
