act_code: '54033'
requisite: Ақтөбе облысы Әйтеке би аудандық мәслихатының 2010 жылғы 22 шілдедегі № 199 шешімі. Ақтөбе облысы Әйтеке би ауданының Әділет басқармасында 2010 жылғы 10 тамызда № 3-2-97 тіркелді. Күші жойылды - Ақтөбе облысы Әйтеке би аудандық мәслихатының 2017 жылғы 12 шілдедегі № 142 шешімімен
title:
  rus: Әйтеке би ауданы бойынша бейбіт жиналыстар, митингілер, шерулер, пикеттер мен демонстрацияларды өткізудің тәртібі мен орынын қосымша регламенттеу туралы
  kaz: Әйтеке би ауданы бойынша бейбіт жиналыстар, митингілер, шерулер, пикеттер мен демонстрацияларды өткізудің тәртібі мен орынын қосымша регламенттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-22
approved_by:
- '153003000002'
version_date:
  kaz: 2010-07-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/54033/kaz/22.07.2010
