act_code: '61116'
requisite: Решение акима Сарыжарского сельского округа Мартукского района Актюбинской области от 14 октября 2011 года № 1. Зарегистрировано Управлением юстиции Мартукского района Актюбинской области 31 октября 2011 года № 3-8-139
title:
  rus: О переименовании улиц Сарыжарского сельского округа
  kaz: Сарыжар ауылдық округі көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-10-14
approved_by:
- '153008009002'
version_date:
  kaz: 2011-10-14
  rus: 2011-10-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/61116/kaz/14.10.2011
  rus: https://zan.gov.kz/client/#!/doc/61116/rus/14.10.2011
