act_code: '206079'
requisite: Решение Иргизского районного маслихата Актюбинской области от 25 декабря 2024 года № 181
title:
  rus: Об утверждении Иргизского районного бюджета на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Ырғыз аудандық бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '153006000002'
version_date:
  kaz: 2025-03-04
  rus: 2025-03-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/206079/kaz/04.03.2025
  rus: https://zan.gov.kz/client/#!/doc/206079/rus/04.03.2025
caused_by:
  code: '207743'
  requisite: Решение Иргизского районного маслихата Актюбинской области от 4 марта 2025 года № 215
  title:
    rus: О внесении изменений в решение районного маслихата от 25 декабря 2024 года № 181 «Об утверждении Иргизского районного бюджета на 2025-2027 годы»
    kaz: Аудандық мәслихаттың 2024 жылғы 25 желтоқсандағы № 181 «2025-2027 жылдарға арналған Ырғыз аудандық бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/207743/rus
