act_code: '139122'
requisite: Решение Айтекебийского районного маслихата Актюбинской области от 6 января 2020 года № 367. Зарегистрировано Департаментом юстиции Актюбинской области 15 января 2020 года № 6770
title:
  rus: Об утверждении бюджета Сулукольского сельского округа на 2020 - 2022 годы
  kaz: 2020 – 2022 жылдарға арналған Сұлукөл ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-06
approved_by:
- '153003000002'
version_date:
  kaz: 2020-09-14
  rus: 2020-09-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/139122/kaz/14.09.2020
  rus: https://zan.gov.kz/client/#!/doc/139122/rus/14.09.2020
caused_by:
  code: '146825'
  requisite: Решение Айтекебийского районного маслихата Актюбинской области от 14 сентября 2020 года № 467. Зарегистрировано Департаментом юстиции Актюбинской области 24 сентября 2020 года № 7478
  title:
    rus: О внесении изменения в решение районного маслихата от 6 января 2020 года № 367 «Об утверждении бюджета Сулукольского сельского округа на  2020 - 2022 годы»
    kaz: Аудандық мәслихатының 2020 жылғы 6 қаңтардағы № 367 «2020 - 2022 жылдарға арналған Сұлукөл ауылдық округ бюджетін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/146825/rus
