act_code: '163971'
requisite: Решение Мугалжарского районного маслихата Актюбинской области от 30 декабря 2021 года № 135
title:
  rus: Об утверждении бюджета Егиндыбулакского сельского округа на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Егіндібұлақ ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '153009000002'
version_date:
  kaz: 2022-09-09
  rus: 2022-09-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/163971/kaz/09.09.2022
  rus: https://zan.gov.kz/client/#!/doc/163971/rus/09.09.2022
caused_by:
  code: '171841'
  requisite: Решение Мугалжарского районного маслихата Актюбинской области от 9 сентября 2022 года № 245
  title:
    rus: О внесении изменений в решение Мугалжарского районного маслихата от 30 декабря 2021 года № 135 «Об утверждении бюджета Егиндыбулакского сельского округа на 2022-2024 годы»
    kaz: Мұғалжар аудандық мәслихатының 2021 жылғы 30 желтоқсандағы № 135 «2022-2024 жылдарға арналған Егіндібұлақ ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/171841/rus
