act_code: '40472'
requisite: Ақтөбе облысы Әйтеке би ауданы Жамбыл селолық округі әкімінің 2008 жылғы 25 маусымдағы N 1 шешімі. Ақтөбе облысының Әйтеке би аудандық әділет басқармасында 2008 жылдың 8 шілдеде N 3-2-53 тіркелді
title:
  rus: Көшелер атауын өзгерту туралы
  kaz: Көшелер атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-06-25
approved_by:
- '153003008002'
version_date:
  kaz: 2008-06-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/40472/kaz/25.06.2008
