act_code: '40472'
requisite: Ақтөбе облысы Әйтеке би ауданы Жамбыл селолық округі әкімінің 2008 жылғы 25 маусымдағы N 1 шешімі. Ақтөбе облысының Әйтеке би аудандық әділет басқармасында 2008 жылдың 8 шілдеде N 3-2-53 тіркелді
title:
  rus: Көшелер атауын өзгерту туралы
  kaz: Көшелер атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-06-25
approved_by:
- '153003008002'
version_date:
  kaz: 2017-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/40472/kaz/27.03.2017
caused_by:
  code: '111344'
  requisite: Решение акима Жамбылского сельского округа Айтекебийского района Актюбинской области от 27 марта 2017 года № 4. Зарегистрировано Департаментом юстиции Актюбинской области 4 апреля 2017 года № 5388
  title:
    rus: О внесении изменения в решение акима Жамбылского сельского округа от 25 июня 2008 года № 1 «Көшелер атауын өзгерту туралы»
    kaz: Жамбыл ауылдық округі әкімінің 2008 жылғы 25 маусымдағы № 1 «Көшелер атауын өзгерту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/111344/rus
