act_code: '206472'
requisite: Решение Хромтауского районного маслихата Актюбинской области от 27 декабря 2024 года № 284
title:
  rus: Об утверждении бюджета Кудыксайского сельского округа на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Құдыксай ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '153013000002'
version_date:
  kaz: 2025-09-24
  rus: 2025-09-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/206472/kaz/24.09.2025
  rus: https://zan.gov.kz/client/#!/doc/206472/rus/24.09.2025
caused_by:
  code: '215108'
  requisite: Решение Хромтауского районного маслихата Актюбинской области от 24 сентября 2025 года № 375
  title:
    rus: О внесении изменений в решение Хромтауского районного маслихата от 27 декабря 2024 года № 284 «Об утверждении бюджета Кудыксайского сельского округа на 2025-2027 годы»
    kaz: Хромтау аудандық мәслихатының 2024 жылғы 27 желтоқсандағы № 284 «2025-2027 жылдарға арналған Құдықсай ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/215108/rus
