act_code: '132354'
requisite: Решение акима Каиндинского сельского округа Темирского района Актюбинской области от 7 июня 2019 года № 1. Зарегистрировано Департаментом юстиции Актюбинской области 10 июня 2019 года № 6243. Утратило силу решением акима Каиндинского сельского округа Темирского района Актюбинской области от 4 декабря 2020 года № 16
title:
  rus: Об установлении ограничительных мероприятий на территории села Кумкудук Каиндинского сельского округа
  kaz: Қайыңды ауылдық округінің Құмқұдық ауылы аумағында шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-06-07
approved_by:
- '153010005002'
version_date:
  kaz: 2019-06-07
  rus: 2019-06-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/132354/kaz/07.06.2019
  rus: https://zan.gov.kz/client/#!/doc/132354/rus/07.06.2019
