act_code: '46373'
requisite: Ақтөбе облысы Шалқар ауданы Бершүгір ауылдық округі әкімінің 2009 жылғы 18 мамырдағы N 3 шешімі. Ақтөбе облысының Шалқар аудандық әділет басқармасында 2009 жылдың 5 маусымда N 3-13-112 тіркелді
title:
  rus: Көшелерге атау беру туралы
  kaz: Көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-05-18
approved_by:
- '153014011002'
version_date:
  kaz: 2017-03-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/46373/kaz/24.03.2017
caused_by:
  code: '111493'
  requisite: Решение акима Биршогырского сельского округа Шалкарского района Актюбинсой области от 24 марта 2017 года № 3. Зарегистрировано Департаментом юстиции Актюбинской области 12 апреля 2017 года № 5426
  title:
    rus: О внесении изменения в решение акима Биршогырского сельского округа Шалкарского района от 18 мая 2009 года № 3 "Көшелерге атау беру туралы"
    kaz: Шалқар ауданы Біршоғыр селолық округі әкімінің 2009 жылғы 18 мамырдағы № 3 "Көшелерге атау беру туралы" шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/111493/rus
