act_code: '54216'
requisite: Ақтөбе облысы Шалқар аудандық мәслихатының 2010 жылғы 20 шілдедегі № 211 шешімі. Ақтөбе облысы Шалқар ауданының Әділет басқармасында 2010 жылғы 24 тамызда № 3-13-139 тіркелді. Күші жойылды - Ақтөбе облысы Шалқар аудандық мәслихатының 2013 жылғы 29 маусымдағы № 85 шешімімен
title:
  rus: Шалқар ауданы аймағындағы ауылдық жерлерде тұратын және жұмыс істейтін денсаулық сақтау, білім беру, мәдениет спорт және ветеринария ұйымдарының мамандарына отын сатып алу үшін әлеуметтік көмек мөлшерін белгілеу туралы
  kaz: Шалқар ауданы аймағындағы ауылдық жерлерде тұратын және жұмыс істейтін денсаулық сақтау, білім беру, мәдениет спорт және ветеринария ұйымдарының мамандарына отын сатып алу үшін әлеуметтік көмек мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-20
approved_by:
- '153014000002'
version_date:
  kaz: 2012-11-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/54216/kaz/02.11.2012
caused_by:
  code: '68573'
  requisite: Решение маслихата Шалкарского района Актюбинской области от 2 ноября 2012 года № 41. Зарегистрировано Департаментом юстиции Актюбинской области 16 ноября 2012 года № 3443. Утратило силу решением маслихата Шалкарского района Актюбинской области от 29 июня 2013 года № 85
  title:
    rus: О внесении изменений в решение районного маслихата от 20 июля 2010 года № 211 "Об определении размера социальной помощи на приобретение топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры и спорта проживающим и работающим в сельских населенных пунктах Шалкарского района специалистам здравоохранения, образования, культуры и спорта"
    kaz: Аудандық мәслихатының 2010 жылғы 20 шілдедегі № 211 "Шалқар ауданы аймағындағы ауылдық жерлерде тұратын және жұмыс істейтін денсаулық сақтау, білім беру, мәдениет және спорт ұйымдарының мамандарына отын сатып алу үшін әлеуметтік көмек мөлшерін белгілеу туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/68573/rus
