act_code: '51370'
requisite: Ақтөбе облысы Қобда аудандық мәслихатының 2010 жылғы 19 ақпандағы N 136 шешімі. Ақтөбе облысы Қобда ауданының Әділет басқармасында 2010 жылғы 19 наурызда N 3-7-86 тіркелді. Күші жойылды - Ақтөбе облысы Қобда аудандық мәслихатының 2011 жылғы 27 шілдедегі № 212 шешімімен
title:
  rus: Денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт салаларының мамандарына 2010 жылға көтерме жәрдемақы және бюджеттік кредит беру туралы
  kaz: Денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт салаларының мамандарына 2010 жылға көтерме жәрдемақы және бюджеттік кредит беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-19
approved_by:
- '153012000002'
version_date:
  kaz: 2010-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/51370/kaz/19.02.2010
