act_code: '162738'
requisite: Решение Байганинского районного маслихата Актюбинской области от 28 декабря 2021 года № 110
title:
  rus: Об утверждении бюджета Сартогайского сельского округа на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Сартоғай ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-28
approved_by:
- '153005000002'
version_date:
  kaz: 2021-12-28
  rus: 2021-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/162738/kaz/28.12.2021
  rus: https://zan.gov.kz/client/#!/doc/162738/rus/28.12.2021
