act_code: '230037'
requisite: Решение Айтекебийского районного маслихата Актюбинской области от 8 сентября 2026 года № 539
title:
  rus: Об утверждении Положения государственного учреждения «Аппарат Айтекебийского районного маслихата»
  kaz: «Әйтеке би аудандық мәслихатының аппараты» мемлекеттік мекемесінің Ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-09-08
approved_by:
- '153003000002'
version_date:
  kaz: 2026-09-08
  rus: 2026-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/230037/kaz/08.09.2026
  rus: https://zan.gov.kz/client/#!/doc/230037/rus/08.09.2026
