act_code: '44449'
requisite: Решение маслихата Актюбинской области от 6 февраля 2009 года № 159. Зарегистрировано Департаментом юстиции Актюбинской области 23 февраля 2009 года № 3283. Утратило силу решением Актюбинского областного маслихата от 10 декабря 2014 года № 273
title:
  rus: О повышении базовых ежемесячных ставок платы по объектам наружной (визуальной) рекламы в населенных пунктах Актюбинской области
  kaz: Ақтөбе облысының елді мекендерінде сыртқы (көрнекі) жарнама объектілері бойынша ай сайынғы базалық төлемақы ставкаларын арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-06
approved_by:
- '153000000002'
version_date:
  kaz: 2009-02-06
  rus: 2009-02-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/44449/kaz/06.02.2009
  rus: https://zan.gov.kz/client/#!/doc/44449/rus/06.02.2009
