act_code: '47581'
requisite: Ақтөбе облысы Ойыл аудандық мәслихатының 2009 жылғы 17 шілдедегі № 144 шешімі. Ақтөбе облысының Ойыл аудандық әділет басқармасында 2009 жылдың 21 тамызда N 3-11-68 тіркелді
title:
  rus: Салық салу мақсаттары үшін жерлерді аймақтарға бөлу сұлбасы (схемасы) және жер салығының базалық ставкаларының түзету коэффициенттері туралы
  kaz: Салық салу мақсаттары үшін жерлерді аймақтарға бөлу сұлбасы (схемасы) және жер салығының базалық ставкаларының түзету коэффициенттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-07-17
approved_by:
- '153011000002'
version_date:
  kaz: 2009-07-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/47581/kaz/17.07.2009
