act_code: '45989'
requisite: Решение Хромтауского районного маслихата от 22 апреля 2009 года N 118. Зарегистрировано Управлением юстиции Хромтауского района Актюбинской области 20 мая 2009 года N 3-12-90. Утратило силу решением маслихата Хромтауского района Актюбинской области от 28 января 2010 года № 172
title:
  rus: О предоставлении специалистам подьемного пособия
  kaz: Мамандарға көтерме жәрдемақы ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-22
approved_by:
- '153013000002'
version_date:
  kaz: 2009-04-22
  rus: 2009-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/45989/kaz/22.04.2009
  rus: https://zan.gov.kz/client/#!/doc/45989/rus/22.04.2009
