act_code: '139074'
requisite: Решение Мугалжарского районного маслихата Актюбинской области от 6 января 2020 года № 400. Зарегистрировано Департаментом юстиции Актюбинской области 20 января 2020 года № 6754
title:
  rus: Об утверждении бюджета Талдысайского сельского округа на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Талдысай ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-06
approved_by:
- '153009000002'
version_date:
  kaz: 2020-11-11
  rus: 2020-11-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/139074/kaz/11.11.2020
  rus: https://zan.gov.kz/client/#!/doc/139074/rus/11.11.2020
caused_by:
  code: '148736'
  requisite: Решение Мугалжарского районного маслихата Актюбинской области от 11 ноября 2020 года № 522. Зарегистрировано Департаментом юстиции Актюбинской области 18 ноября 2020 года № 7660
  title:
    rus: О внесении изменений в решение Мугалжарского районного маслихата от 6 января 2020 года № 400 «Об утверждении бюджета Талдысайского сельского округа на 2020-2022 годы»
    kaz: Мұғалжар аудандық мәслихатының 2020 жылғы 6 қаңтардағы № 400 «2020-2022 жылдарға арналған Талдысай ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/148736/rus
