act_code: '46067'
requisite: Ақтөбе облысы Мәртөк аудандық мәслихатының 2009 жылғы 24 сәуірдегі N 106 шешімі. Ақтөбе облысы Мәртөк аудандық әділет басқармасында 2009 жылғы 21 мамырда N 3-8-85 тіркелді. Күші жойылды - Ақтөбе облысы Мәртөк аудандық мәслихатының 2013 жылғы 25 желтоқсандағы № 102 шешімімен
title:
  rus: Мұқтаж азаматтардың жекелген топтарына әлеуметтік көмек көрсету туралы
  kaz: Мұқтаж азаматтардың жекелген топтарына әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-24
approved_by:
- '153008000002'
version_date:
  kaz: 2009-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/46067/kaz/24.04.2009
