act_code: '206566'
requisite: Решение Мугалжарского районного маслихата Актюбинской области от 30 декабря 2024 года № 329
title:
  rus: Об утверждении бюджета сельского округа имени К. Жубанова на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Қ. Жұбанов атындағы ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '153009000002'
version_date:
  kaz: 2025-09-24
  rus: 2025-09-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/206566/kaz/24.09.2025
  rus: https://zan.gov.kz/client/#!/doc/206566/rus/24.09.2025
caused_by:
  code: '215104'
  requisite: Решение Мугалжарского районного маслихата Актюбинской области от 24 сентября 2025 года № 442
  title:
    rus: О внесении изменений в решение Мугалжарского районного маслихата от 30 декабря 2024 года № 329 «Об утверждении бюджета сельского округа имени К. Жубанова на 2025-2027 годы»
    kaz: Мұғалжар аудандық мәслихатының 2024 жылғы 30 желтоқсандағы № 329 «2025-2027 жылдарға арналған Қ. Жұбанов атындағы ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/215104/rus
