act_code: '206253'
requisite: Решение Шалкарского районного маслихата Актюбинской области от 30 декабря 2024 года № 382
title:
  rus: Об утверждении бюджета Жанаконысского сельского округа на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Жаңақоныс ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '153014000002'
version_date:
  kaz: 2024-12-30
  rus: 2024-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/206253/kaz/30.12.2024
  rus: https://zan.gov.kz/client/#!/doc/206253/rus/30.12.2024
