act_code: '76215'
requisite: Решение акима Кызылжарского аульного округа Кобдинского района Актюбинской области от 18 декабря 2013 года № 3. Зарегистрировано Департаментом юстиции Актюбинской области 27 декабря 2013 года № 3722. Утратило силу решением акима Кызылжарского сельского округа Хобдинского района Актюбинской области от 3 ноября 2015 года № 7
title:
  rus: Об установлении ветеринарного режима с введением ограничительных мероприятий
  kaz: Шектеу іс-шараларын енгізе отырып ветеринариялық режимін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-18
approved_by:
- '153012012001'
version_date:
  kaz: 2013-12-18
  rus: 2013-12-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/76215/kaz/18.12.2013
  rus: https://zan.gov.kz/client/#!/doc/76215/rus/18.12.2013
