act_code: '206440'
requisite: Решение Кобдинского районного маслихата Актюбинской области от 31 декабря 2024 года № 280
title:
  rus: Об утверждении бюджета Сугалинского сельского округа на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Сөгәлі ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-31
approved_by:
- '153012000002'
version_date:
  kaz: 2025-02-24
  rus: 2025-02-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/206440/kaz/24.02.2025
  rus: https://zan.gov.kz/client/#!/doc/206440/rus/24.02.2025
caused_by:
  code: '207521'
  requisite: Решение Кобдинского районного маслихата Актюбинской области от 24 февраля 2025 года № 306
  title:
    rus: Об внесении изменений в решение Қобдинского районного маслихата от 31 декабря 2024 года № 280 «Об утверждении бюджета Сугалинского сельского округа на 2025-2027 годы»
    kaz: Қобда аудандық мәслихатының 2024 жылғы 31 желтоқсандағы № 280 «2025-2027 жылдарға арналған Сөгәлі ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/207521/rus
