act_code: '59846'
requisite: Решение акима Иргизского сельского округа Иргизского района Актюбинской области от 30 июня 2011 года № 49. Зарегистрировано Управлением юстиции Иргизского района Актюбинской области 27 июля 2011 года № 3-5-135
title:
  rus: О наименовании улиц села Иргиз, Калыбай, Калалыкол Иргизского сельского округа
  kaz: Ырғыз ауылдық округінің Ырғыз, Қалыбай, Қалалыкөл ауылдарының көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-06-30
approved_by:
- '153006006001'
version_date:
  kaz: 2011-06-30
  rus: 2011-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/59846/kaz/30.06.2011
  rus: https://zan.gov.kz/client/#!/doc/59846/rus/30.06.2011
