act_code: '95880'
requisite: Решение от 11.11.2015 №37, Акимат Кенестуского сельского округа
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-11-11
approved_by:
- '153010006001'
version_date:
  kaz: 2015-11-11
  rus: 2015-11-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/95880/kaz/11.11.2015
  rus: https://zan.gov.kz/client/#!/doc/95880/rus/11.11.2015
