act_code: '44155'
requisite: Ақтөбе облысы Ырғыз аудандық мәслихатының 2009 жылғы 30 қаңтардағы N 69 шешімі. Ақтөбе облысының Ырғыз аудандық әділет басқармасында 2009 жылдың 9 ақпанда N 3-5-89 тіркелді
title:
  rus: Тіркелген салықтың мөлшерлемелерін белгілеу туралы
  kaz: Тіркелген салықтың мөлшерлемелерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-30
approved_by:
- '153006000002'
version_date:
  kaz: 2017-02-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/44155/kaz/20.02.2017
caused_by:
  code: '110674'
  requisite: Решение маслихата Иргизского района Актюбинской области от 20 февраля 2017 года № 65. Зарегистрировано Департаментом юстиции Актюбинской области 7 марта 2017 года № 5292. Утратило силу решением маслихата Иргизского района Актюбинской области от 5 марта 2018 года № 133
  title:
    rus: О внесении изменений и дополнения в решение районного маслихата от 30 января 2009 года № 69 "Тіркелген салықтың ставкаларын белгілеу туралы"
    kaz: Аудандық мәслихаттың 2009 жылғы 30 қаңтардағы № 69 "Тіркелген салықтың ставкаларын белгілеу туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/110674/rus
