act_code: '52765'
requisite: Ақтөбе облысы Мұғалжар ауданы Құмжарған ауылдық округі әкімінің 2010 жылғы 21 сәуірдегі № 8 шешімі. Ақтөбе облысы Мұғалжар ауданының Әділет басқармасында 2010 жылғы 19 мамырда № 3-9-124 тіркелді
title:
  rus: Мұғалжар ауданы Құмжарған ауылдық округі Бірлік ауылындағы көшелер атауларын өзгерту туралы
  kaz: Мұғалжар ауданы Құмжарған ауылдық округі Бірлік ауылындағы көшелер атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-21
approved_by:
- '153009011002'
version_date:
  kaz: 2010-04-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/52765/kaz/21.04.2010
