act_code: '178123'
requisite: Решение Хромтауского районного маслихата Актюбинской области от 30 декабря 2022 года № 322
title:
  rus: Об утверждении бюджета Коктобинского сельского округа на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Көктөбе ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-30
approved_by:
- '153013000002'
version_date:
  kaz: 2023-04-14
  rus: 2023-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/178123/kaz/14.04.2023
  rus: https://zan.gov.kz/client/#!/doc/178123/rus/14.04.2023
caused_by:
  code: '180169'
  requisite: Решение Хромтауского районного маслихата Актюбинской области от 14 апреля 2023 года № 21
  title:
    rus: О внесении изменений в решение Хромтауского районного маслихата от 30 декабря 2022 года № 322 «Об утверждении бюджета Коктобинского сельского округа на 2023-2025 годы»
    kaz: Хромтау аудандық мәслихатының 2022 жылғы 30 желтоқсандағы № 322 «2023-2025 жылдарға арналған Көктөбе ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/180169/rus
