act_code: '6723'
requisite: Решение акима Актюбинской области от 14 апреля 2000 года № 60. Зарегистрировано Управлением юстиции Актюбинской области 23 июня 2000 года № 575. Утратило силу в связи с истечением срока применения – письмо акимата Актюбинской области от 21 декабря 2004 года № 08-3/2691
title:
  rus: О выполнении постановления Правительства Республики Казахстан от 16 февраля 2000 года № 253 «О программе обеспечения прав на землю в Республике Казахстан на 2000-2003 годы»
  kaz: «Қазақстан Республикасында Жерге құқықтарды қамтамасыз етудің 2000-2003 жылдарға арналған бағдарламасы туралы» Қазақстан Республикасы Үкіметінің 2000 жылғы 16 ақпандағы № 253 қаулысын орындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-04-13
approved_by:
- '153000000003'
version_date:
  kaz: 2000-04-13
  rus: 2000-04-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/6723/kaz/13.04.2000
  rus: https://zan.gov.kz/client/#!/doc/6723/rus/13.04.2000
