act_code: '205764'
requisite: Решение Шалкарского районного маслихата Актюбинской области от 25 декабря 2024 года № 366
title:
  rus: Об утверждении Шалкарского районного бюджета на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Шалқар аудандық бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '153014000002'
version_date:
  kaz: 2025-09-08
  rus: 2025-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/205764/kaz/08.09.2025
  rus: https://zan.gov.kz/client/#!/doc/205764/rus/08.09.2025
caused_by:
  code: '214068'
  requisite: Решение Шалкарского районного маслихата Актюбинской области от 8 сентября 2025 года № 498
  title:
    rus: О внесении изменений в решение Шалкарского районного маслихата от 25 декабря 2024 года № 366 «Об утверждении Шалкарского районного бюджета на 2025-2027 годы»
    kaz: Шалқар аудандық мәслихатының 2024 жылғы 25 желтоқсандағы № 366 «2025-2027 жылдарға арналған Шалқар аудандық бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/214068/rus
