act_code: '100961'
requisite: Решение Кобдинского районного маслихата Актюбинской области от 24 марта 2016 года № 11. Зарегистрировано Департаментом юстиции Актюбинской области 6 апреля 2016 года № 4839. Утратило силу решением Кобдинского районного маслихата Актюбинской области от 26 марта 2018 года № 148
title:
  rus: О повышении базовых ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения по Кобдинскому району
  kaz: Қобда ауданында пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының базалық мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-03-24
approved_by:
- '153012000002'
version_date:
  kaz: 2016-12-02
  rus: 2016-12-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/100961/kaz/02.12.2016
  rus: https://zan.gov.kz/client/#!/doc/100961/rus/02.12.2016
caused_by:
  code: '108461'
  requisite: Решение Кобдинского районного маслихата Актюбинской области от 2 декабря 2016 года № 48. Зарегистрировано Департаментом юстиции Актюбинской области 23 декабря 2016 года № 5172. Утратило силу решением Кобдинского районного маслихата Актюбинской области от 26 марта 2018 года № 148
  title:
    rus: О внесении дополнения в решение районного маслихата от 24 марта 2016 года № 11 «О повышении базовых ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения по Кобдинскому району»
    kaz: «Қобда ауданында пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының базалық мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы» 2016 жылғы 24 наурыздағы № 11 аудандық мәслихатының шешіміне толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/108461/rus
