act_code: '138811'
requisite: Решение Алгинского районного маслихата Актюбинской области от 8 января 2020 года № 343. Зарегистрировано Департаментом юстиции Актюбинской области 15 января 2020 года № 6710
title:
  rus: Об утверждении бюджета Ушкудыкского сельского округа на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Үшқұдық ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-08
approved_by:
- '153004000002'
version_date:
  kaz: 2020-11-05
  rus: 2020-11-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/138811/kaz/05.11.2020
  rus: https://zan.gov.kz/client/#!/doc/138811/rus/05.11.2020
caused_by:
  code: '148465'
  requisite: Решение Алгинского районного маслихата Актюбинской области от 5 ноября 2020 года № 449. Зарегистрировано Департаментом юстиции Актюбинской области 10 ноября 2020 года № 7614
  title:
    rus: О внесении изменения в решение Алгинского районного маслихата от 8 января 2020 года № 343 «Об утверждении  бюджета Ушкудыкского сельского округа на 2020-2022 годы»
    kaz: Алға аудандық мәслихатының 2020 жылғы 8 қаңтардағы № 343 «2020-2022 жылдарға арналған Үшқұдық ауылдық округ бюджетін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/148465/rus
