act_code: '27710'
requisite: Ақтөбе қаласы әкімдігінің 2006 жылғы 21 сәуірдегі N 706 қаулысы. Ақтөбе қаласының әділет басқармасында 2006 жылдың 12 мамырда N 3-1-49 тіркелді. Күші жойылды - Ақтөбе қалалық әкімдігінің 2009 жылғы 20 сәуірдегі N 911 қаулысымен
title:
  rus: Сотталғандар үшін қоғамдық жұмыстарды ұйымдастыру туралы
  kaz: Сотталғандар үшін қоғамдық жұмыстарды ұйымдастыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-04-21
approved_by:
- '153002000001'
version_date:
  kaz: 2006-04-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/27710/kaz/21.04.2006
