act_code: '23765'
requisite: Ақтөбе облысы Темір аудандық мәслихатының 2005 жылғы 10 қазандағы № 100 шешімі. Ақтөбе облысы Әділет департаментінің Темір ауданының Әділет басқармасында 2005 жылғы 26 қазанда № 3-10-17 болып тіркелді
title:
  rus: Бейбіт жиналыстар, митингілер және пикеттер өткізудің тәртібі мен орнын регламенттеу туралы
  kaz: Бейбіт жиналыстар, митингілер және пикеттер өткізудің тәртібі мен орнын регламенттеу туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2005-10-10
approved_by:
- '153010000002'
version_date:
  kaz: 2005-10-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/23765/kaz/10.10.2005
