act_code: '67086'
requisite: Решение акима Кемпирсайского сельского округа Каргалинского района Актюбинской области от 12 июля 2012 года № 2. Зарегистрировано Департаментом юстиции Актюбинской области 8 августа 2012 года № 3-6-147
title:
  rus: О присвоении наименований улицам населенных пунктов, относящихся к Кемпирсайскому сельскому округу
  kaz: Кемпірсай ауылдық округіне қарасты елді мекендердің көшелеріне атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-07-12
approved_by:
- '153007005001'
version_date:
  kaz: 2012-07-12
  rus: 2012-07-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/67086/kaz/12.07.2012
  rus: https://zan.gov.kz/client/#!/doc/67086/rus/12.07.2012
