act_code: '132785'
requisite: Решение маслихата Актюбинской области от 19 июня 2019 года № 431. Зарегистрировано Департаментом юстиции Актюбинской области 25 июня 2019 года № 6264
title:
  rus: Об определении перечня социально значимых сообщений Актюбинской области
  kaz: Ақтөбе облысының әлеуметтік маңызы бар қатынастар тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-06-19
approved_by:
- '153000000002'
version_date:
  kaz: 2023-12-13
  rus: 2023-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/132785/kaz/13.12.2023
  rus: https://zan.gov.kz/client/#!/doc/132785/rus/13.12.2023
caused_by:
  code: '190620'
  requisite: Решение Актюбинского областного маслихата от 13 декабря 2023 года № 83. Зарегистрировано Департаментом юстиции Актюбинской области 20 декабря 2023 года № 8468
  title:
    rus: О внесении изменений в решение Актюбинского областного маслихата от 19 июня 2019 года № 431 «Об определении перечня социально значимых внутриобластных сообщений Актюбинской области»
    kaz: «Ақтөбе облысының әлеуметтік маңызы бар облысішілік қатынастар тізбесін айқындау туралы» Ақтөбе облыстық мәслихаттың 2019 жылғы 19 маусымдағы № 431 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/190620/rus
