act_code: '77745'
requisite: Решение акима Шалкарского района Актюбинской области от 7 февраля 2014 года № 06. Зарегистрировано Департаментом юстиции Актюбинской области 3 марта 2014 года № 3786
title:
  rus: Об образовании избирательных участков на территории Шалкарского района
  kaz: Шалқар ауданы аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-02-07
approved_by:
- '153014000003'
version_date:
  kaz: 2015-02-26
  rus: 2015-02-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/77745/kaz/26.02.2015
  rus: https://zan.gov.kz/client/#!/doc/77745/rus/26.02.2015
caused_by:
  code: '87246'
  requisite: ''
  title:
    rus: О внесении изменений и дополнений в решение акима Шалкарского района от 7 февраля 2014 года № 6 "Об образовании избирательных участков на территории Шалкарского района"
    kaz: Шалқар ауданы әкімінің 2014 жылғы 7 ақпандағы № 6 "Шалқар ауданы аумағында сайлау учаскелерін құру туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/87246/rus
