act_code: '46845'
requisite: Ақтөбе облысы Қобда аудандық мәслихатының 2009 жылғы 16 маусымдағы N 96 шешімі. Ақтөбе облысының Қобда аудандық әділет басқармасында 2009 жылдың 15 шілдеде N 3-7-72 тіркелді. Күші жойылды - Ақтөбе облысы Қобда аудандық мәслихатының 2010 жылғы 19 ақпандағы N 136 шешімімен
title:
  rus: Денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт салаларының мамандарына 2009 жылға көтерме жәрдемақы беру туралы
  kaz: Денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт салаларының мамандарына 2009 жылға көтерме жәрдемақы беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-06-16
approved_by:
- '153012000002'
version_date:
  kaz: 2009-06-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/46845/kaz/16.06.2009
