act_code: '1306'
requisite: Решение акима Актюбинской области от 30 июля 1998 года № 117. Зарегистрировано Управлением юстиции Актюбинской области 24 сентября 1998 года № 45. Утратило силу - постановлением акимата Актюбинской области от 11 июля 2002 года № 105
title:
  rus: Об областной комиссии по обеспечению безопасности на транспорте
  kaz: Көлікте қауіпсіздікті қамтамасыз ету жөніндегі облыстық комиссия туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 1998-07-29
approved_by:
- '153000000003'
version_date:
  kaz: 1998-07-29
  rus: 1998-07-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/1306/kaz/29.07.1998
  rus: https://zan.gov.kz/client/#!/doc/1306/rus/29.07.1998
