act_code: '53883'
requisite: Ақтөбе облысы Қобда аудандық мәслихатының 2010 жылғы 7 шілдедегі № 141 шешімі. Ақтөбе облысы Қобда ауданының Әділет басқармасында 2010 жылғы 6 тамызда № 3-7-94 тіркелді. Күші жойылды - Ақтөбе облысы Қобда аудандық мәслихатының 2011 жылғы 27 шілдедегі № 215 шешімімен
title:
  rus: Ауылдық елді мекендерде жұмыс істейтін әлеуметтік қамсыздандыру, мәдениет, білім беру, спорт және денсаулық салаларындағы мамандарына отын сатып алу үшін 2010 жылға әлеуметтік көмек беру туралы
  kaz: Ауылдық елді мекендерде жұмыс істейтін әлеуметтік қамсыздандыру, мәдениет, білім беру, спорт және денсаулық салаларындағы мамандарына отын сатып алу үшін 2010 жылға әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-07
approved_by:
- '153012000002'
version_date:
  kaz: 2010-07-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/53883/kaz/07.07.2010
