act_code: '65726'
requisite: Решение маслихата Каргалинского района Актюбинской области от 27 апреля 2012 года № 18. Зарегистрировано Департаментом юстиции Актюбинской области 23 мая 2012 года № 3-6-139. Утратило силу в связи с истечением срока применения - (письмо маслихата Каргалинского района Актюбинской области от 15 января 2013 года № 03-14/18)
title:
  rus: Об определении мер социальной поддержки специалистов сферы здравоохранения, образования, социального обеспечения, культуры, спорта и ветеринарии на 2012 год
  kaz: 2012 жылға денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және ветеринария мамандарына әлеуметтік қолдау шараларының мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-04-27
approved_by:
- '153007000002'
version_date:
  kaz: 2012-04-27
  rus: 2012-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/65726/kaz/27.04.2012
  rus: https://zan.gov.kz/client/#!/doc/65726/rus/27.04.2012
