act_code: '205065'
requisite: Решение Иргизского районного маслихата Актюбинской области от 25 декабря 2024 года № 183. Зарегистрировано Департаментом юстиции Актюбинской области 27 декабря 2024 года № 8674-04
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2025 год по Иргизскому району
  kaz: Ырғыз ауданы бойынша шетелдіктер үшін 2025 жылға арналған туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '153006000002'
version_date:
  kaz: 2024-12-25
  rus: 2024-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/205065/kaz/25.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205065/rus/25.12.2024
