act_code: '41271'
requisite: Ақтөбе облысы Әйтеке би аудандық мәслихатының 2008 жылғы 12 тамыздағы N 62 шешімі. Ақтөбе облысының Әйтеке би аудандық әділет басқармасында 2008 жылдың 22 тамызда N 3-2-60 тіркелді. Күші жойылды - Ақтөбе облысы Әйтеке би аудандық мәслихатының 2011 жылғы 28 шілдедегі № 257 шешімімен
title:
  rus: Аз қамтылған отбасылары және ең төменгі зейнетақы алатын зейнеткерлерге әлеуметтік көмек көрсету туралы
  kaz: Аз қамтылған отбасылары және ең төменгі зейнетақы алатын зейнеткерлерге әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-08-12
approved_by:
- '153003000002'
version_date:
  kaz: 2008-08-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/41271/kaz/12.08.2008
