act_code: '145243'
requisite: Решение акима города Алга Алгинского района Актюбинской области от 29 июля 2020 года № 189. Зарегистрировано Департаментом юстиции Актюбинской области 30 июля 2020 года № 7318. Утратило силу решением акима города Алга Алгинского района Актюбинской области от 11 января 2021 года № 5
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-07-29
approved_by:
- '153004001002'
version_date:
  kaz: 2020-07-29
  rus: 2020-07-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/145243/kaz/29.07.2020
  rus: https://zan.gov.kz/client/#!/doc/145243/rus/29.07.2020
