act_code: '62717'
requisite: Решение маслихата Кобдинского района Актюбинской области от 20 декабря 2011 года № 239. Зарегистрировано Департаментом юстиции Актюбинской области 16 января 2012 года № 3-7-137. Утратило силу в связи с истечением срока применения - (письмо аппарата Кобдинского районного маслихата Актюбинской области от 8 января 2013 года № 5-05/03)
title:
  rus: О районном бюджете на 2012-2014 годы
  kaz: 2012-2014 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-20
approved_by:
- '153012000002'
version_date:
  kaz: 2012-04-25
  rus: 2012-04-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/62717/kaz/25.04.2012
  rus: https://zan.gov.kz/client/#!/doc/62717/rus/25.04.2012
caused_by:
  code: '65468'
  requisite: Решение маслихата Кобдинского района Актюбинской области от 25 апреля 2012 года № 18. Зарегистрировано Департаментом юстиции Актюбинской области 14 мая 2012 года № 3-7-142. Утратило силу в связи с истечением срока применения - (письмо аппарата Кобдинского районного маслихата Актюбинской области от 8 января 2013 года № 5-05/03)
  title:
    rus: О внесении изменений и дополнений в решение районного маслихата от 20 декабря 2011 года № 239 "О районном бюджете на 2012-2014 годы"
    kaz: Аудандық мәслихаттың 2011 жылғы 20 желтоқсандағы № 239 "2012-2014 жылдарға арналған аудан бюджеті туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/65468/rus
