act_code: '128508'
requisite: Решение Уилского районного маслихата Актюбинской области от 4 января 2019 года № 248. Зарегистрировано Управлением юстиции Уилского района Департамента юстиции Актюбинской области 10 января 2019 года № 3-11-156
title:
  rus: Об утверждении бюджета Уилского сельского округа на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Ойыл ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-04
approved_by:
- '153011000002'
version_date:
  kaz: 2019-01-04
  rus: 2019-01-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/128508/kaz/04.01.2019
  rus: https://zan.gov.kz/client/#!/doc/128508/rus/04.01.2019
