act_code: '31312'
requisite: Решение очередной тридцать пятой сессии Маслихата города Актобе от 26 декабря 2006 года N 294. Зарегистрировано в Управлении юстиции города Актобе 17 января 2007 года за N 3-1-64. Утратило силу решением маслихата города Актобе Актюбинской области от 25 апреля 2009 года N 169
title:
  rus: О предоставлении льгот за коммунальные услуги (тепло-, водо-, газо-, электроснабжение, мусороудаление, обслуживание лифтов) и услуги связи (абонентская плата) участникам и инвалидам Великой Отечественной войны 1941 - 1945 годов, бывшим военнослужащим, призванным в ряды Советской Армии в годы Великой Отечественной войны и работникам органов внутренних дел, награжденным медалью "За Победу над Германией в Великой Отечественной войне 1941 - 1945 годов", вдовам воинов, погибших в Великой Отечественной войне 1941 - 1945 годов
  kaz: 1941-1945 жылдары Ұлы Отан соғысына қатысушылар және мүгедектер, 1941-1945 жылы Ұлы Отан соғысы жылдарында Кеңес Армиясының қатарына шақырылған бұрынғы әскери қызметкерлер және ішкі істер органдарының қызметкерлері "1941-1945 Ұлы Отан соғысы жылдарында Германияны жеңгені үшін" медалімен марапатталғандар, Ұлы Отан соғысында қаза болған жауынгерлердің жесірлерінің коммуналдық қызметтері (жылу, су, көгілдір отын, электрмен қамту) және байланыс қызметтері үшін (абоненттік төлемақы) жеңілдіктер беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-26
approved_by:
- '153002000002'
version_date:
  kaz: 2006-12-26
  rus: 2006-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/31312/kaz/26.12.2006
  rus: https://zan.gov.kz/client/#!/doc/31312/rus/26.12.2006
