act_code: '46572'
requisite: Ақтөбе облысы Алға ауданы Сарықобда ауылдық округінің әкімі 2009 жылғы 11 мамырдағы № 1 шешімі. Ақтөбе облысының Алға аудандық әділет басқармасында 2009 жылдың 18 маусымда № 3-3-83 тіркелді
title:
  rus: Сарықобда селолық округіне қарасты елді мекендерге көше атауын беру туралы
  kaz: Сарықобда селолық округіне қарасты елді мекендерге көше атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-05-11
approved_by:
- '153004013002'
version_date:
  kaz: 2019-07-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/46572/kaz/18.07.2019
caused_by:
  code: '133452'
  requisite: Решение акима Сарыхобдинского сельского округа Алгинского района Актюбинской области от 18 июля 2019 года № 10. Зарегистрировано Департаментом юстиции Актюбинской области 19 июля 2019 года № 6279
  title:
    rus: О внесении изменений в решение акима Сарыхобдинского сельского округа 11 мая 2009 года № 1 «Сарықобда селолық округіне қарасты елді мекендерге көше атауын беру туралы»
    kaz: Сарықобда селолық округі әкімінің 2009 жылғы 11 мамырдағы № 1 «Сарықобда селолық округіне қарасты елді мекендерге көше атауын беру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/133452/rus
