act_code: '54217'
requisite: Ақтөбе облысы Шалқар аудандық мәслихатының 2010 жылғы 20 шілдедегі № 210 шешімі. Ақтөбе облысы Шалқар ауданының Әділет басқармасында 2010 жылғы 25 тамызда № 3-13-140 тіркелді
title:
  rus: Жер салығының базалық мөлшерлемесін арттыру туралы
  kaz: Жер салығының базалық мөлшерлемесін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-20
approved_by:
- '153014000002'
version_date:
  kaz: 2010-07-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/54217/kaz/20.07.2010
