act_code: '39317'
requisite: Ақтөбе облысы Мұғалжар аудандық мәслихатының 2008 жылғы 20 наурыздағы № 38 шешімі. Ақтөбе облысы Мұғалжар ауданының Әділет басқармасында 2008 жылғы 23 сәуірде № 3-9-61 болып тіркелді. Күші жойылды - Ақтөбе облысы Мұғалжар аудандық мәслихатының 2009 жылғы 26 наурыздағы № 100 шешімімен
title:
  rus: Аз қамтылған азаматтарға және ең төменгі мөлшерде зейнетақы алатын зейнеткерлерге қосымша әлеуметтік көмек көрсету туралы
  kaz: Аз қамтылған азаматтарға және ең төменгі мөлшерде зейнетақы алатын зейнеткерлерге қосымша әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-03-20
approved_by:
- '153009000002'
version_date:
  kaz: 2008-09-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/39317/kaz/26.09.2008
caused_by:
  code: '42016'
  requisite: Решение маслихата Мугалжарского района Актюбинской области от 26 сентября 2008 года № 66. Зарегистрировано Управлением юстиции Мугалжарского района Актюбинской области 28 октября 2008 года № 3-9-72. Утратило силу решением маслихата Мугалжарского района Актюбинской области от 26 марта 2009 года N 100
  title:
    rus: О внесении изменения в решение районного маслихата от 20 марта года № 38 «О социальной помощи малообеспеченным гражданам и пенсионерам получающим минимальную пенсию»
    kaz: Аундық мәслихаттың 2008 жылғы 20 нарыздағы «Аз қамтылған азаматтарға және ең төменгі мөлшерде зейнетақы алатын зейнеткерлерге қосымша әлеуметтік көмек көрсету туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/42016/rus
