act_code: '142200'
requisite: Решение акима Журынского сельского округа Мугалжарского района Актюбинской области от 24 апреля 2020 года № 9. Зарегистрировано Департаментом юстиции Актюбинской области 24 апреля 2020 года № 7071. Утратило силу решением акима Журынского сельского округа Мугалжарского района Актюбинской области от 18 ноября 2020 года № 30
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-04-24
approved_by:
- '153009009002'
version_date:
  kaz: 2020-04-24
  rus: 2020-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/142200/kaz/24.04.2020
  rus: https://zan.gov.kz/client/#!/doc/142200/rus/24.04.2020
