act_code: '86209'
requisite: ''
title:
  rus: 'О бюджете Уилского района на 2015-2017 годы   '
  kaz: '2015-2017 жылдарға арналған Ойыл ауданының бюджеті туралы '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '153011000002'
version_date:
  kaz: 2015-11-09
  rus: 2015-11-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/86209/kaz/09.11.2015
  rus: https://zan.gov.kz/client/#!/doc/86209/rus/09.11.2015
caused_by:
  code: '96066'
  requisite: Решение Уилского районного маслихата Актюбинской области от 9 ноября 2015 года № 259. Зарегистрировано Департаментом юстиции Актюбинской области 26 ноября 2015 года № 4604. Срок действия решения - до 1 января 2016 года
  title:
    rus: О внесении изменений и дополнений в решение районного маслихата от 24 декабря 2014 года № 202 "О бюджете Уилского района на 2015-2017 годы"
    kaz: Аудандық мәслихаттың "2015-2017 жылдарға арналған Ойыл ауданының бюджеті туралы" 2014 жылғы 24 желтоқсандағы № 202 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/96066/rus
