act_code: '44186'
requisite: Ақтөбе облысы Хромтау ауданы Тасөткел селолық округі әкімінің 2009 жылғы 6 ақпандағы N 1 шешімі. Ақтөбе облысының Хромтау аудандық әділет басқармасында 2009 жылдың 11 ақпанда N 3-12-83 тіркелді
title:
  rus: Тасөткел ауылдық округіне қарасты елді мекендерге көше атауын беру туралы
  kaz: Тасөткел ауылдық округіне қарасты елді мекендерге көше атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-06
approved_by:
- '153013012002'
version_date:
  kaz: 2017-11-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/44186/kaz/28.11.2017
caused_by:
  code: '116919'
  requisite: Решение акима Тасуткельского сельского округа Хромтауского района Актюбинской области от 28 ноября 2017 года № 10. Зарегистрировано Департаментом юстиции Актюбинской области 14 декабря 2017 года № 5738
  title:
    rus: О внесении изменения в решение акима Тасуткельского сельского округа от 6 февраля 2009 года № 1 «Тасөткел ауылдық округіне қарасты елді мекендерге көше атауын беру туралы»
    kaz: Тасөткел ауылдық округі әкімінің 2009 жылғы 6 ақпандағы № 1 «Тасөткел ауылдық округіне қарасты елді мекендерге көше атауын беру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/116919/rus
