act_code: '44186'
requisite: Ақтөбе облысы Хромтау ауданы Тасөткел селолық округі әкімінің 2009 жылғы 6 ақпандағы N 1 шешімі. Ақтөбе облысының Хромтау аудандық әділет басқармасында 2009 жылдың 11 ақпанда N 3-12-83 тіркелді
title:
  rus: Тасөткел ауылдық округіне қарасты елді мекендерге көше атауын беру туралы
  kaz: Тасөткел ауылдық округіне қарасты елді мекендерге көше атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-06
approved_by:
- '153013012002'
version_date:
  kaz: 2015-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/44186/kaz/27.04.2015
caused_by:
  code: '90330'
  requisite: Решение №2 от 27.04.2015, Акимат Тасоткельского сельского округа
  title:
    rus: О внесении изменений в решение от 6 февраля 2009 года № 1 «О наименовании улиц населенных пунктов Тасуткельского сельского округа»
    kaz: «Тасөткел селолық округіне қарасты елді мекендерге көше атауын беру туралы» 2009 жылғы 6 ақпандағы № 1 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/90330/rus
