act_code: '98179'
requisite: Решение акима Уилского сельского округа Уилского района Актюбинской области от 21 декабря 2015 года № 135. Зарегистрировано Департаментом юстиции Актюбинской области 12 января 2016 года № 4672. Утратило силу решением акима Уилского сельского округа Уилского района Актюбинской области от 8 августа 2016 года № 117
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-21
approved_by:
- '153011007001'
version_date:
  kaz: 2015-12-21
  rus: 2015-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/98179/kaz/21.12.2015
  rus: https://zan.gov.kz/client/#!/doc/98179/rus/21.12.2015
