act_code: '101015'
requisite: Решение маслихата Хобдинского района Актюбинской области от 24 марта 2016 года № 8. Зарегистрировано Департаментом юстиции Актюбинской области 7 апреля 2016 года № 4841. Утратило силу решением маслихата Хобдинского района Актюбинской области от 24 февраля 2017 года № 61
title:
  rus: Об утверждении методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Хобдинского районного маслихата»
  kaz: «Қобда аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2016-03-24
approved_by:
- '153012000002'
version_date:
  kaz: 2016-03-24
  rus: 2016-03-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/101015/kaz/24.03.2016
  rus: https://zan.gov.kz/client/#!/doc/101015/rus/24.03.2016
