act_code: '41096'
requisite: Ақтөбе облысы Ойыл аудандық мәслихатының 2008 жылғы 21 шілдедегі N 68 шешімі. Ақтөбе облысы Ойыл аудандық әділет басқармасында 2008 жылғы 5 тамызда N 3-11-49 тіркелді. Күші жойылды - Ақтөбе облысы Ойыл аудандық мәслихатының 2012 жылғы 28 сәуірдегі № 40 шешімімен
title:
  rus: Аз қамтылған отбасыларға әлеуметтік көмек көрсету туралы
  kaz: Аз қамтылған отбасыларға әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-07-21
approved_by:
- '153011000002'
version_date:
  kaz: 2009-01-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/41096/kaz/29.01.2009
caused_by:
  code: '44535'
  requisite: Ақтөбе облысы Ойыл аудандық мәслихатының 2009 жылғы 29 қаңтардағы N 114 шешімі. Ақтөбе облысының Ойыл аудандық әділет басқармасында 2009 жылдың 24 ақпанда N 3-11-58 тіркелді. Күші жойылды - Ақтөбе облысы Ойыл аудандық мәслихатының 2012 жылғы 28 сәуірдегі № 40 шешімімен
  title:
    rus: Аудандық мәслихаттың 2008 жылғы 21 шілдедегі VII сессиясының N 68 "Аз қамтылған отбасыларға әлеуметтік көмек көрсету туралы" шешіміне өзгерістер мен толықтырулар енгізу жәйлі
    kaz: Аудандық мәслихаттың 2008 жылғы 21 шілдедегі VII сессиясының N 68 "Аз қамтылған отбасыларға әлеуметтік көмек көрсету туралы" шешіміне өзгерістер мен толықтырулар енгізу жәйлі
  link: https://zan.gov.kz/client/#!/doc/44535/rus
