act_code: '113520'
requisite: Решение Уилского районного маслихата Актюбинской области от 13 июня 2017 года № 107. Зарегистрировано Департаментом юстиции Актюбинской области 17 июля 2017 года № 5602. Утратило силу решением Уилского районного маслихата Актюбинской области от 12 июня 2020 года № 408
title:
  rus: Об утверждении Правил выдачи служебного удостоверения государственных служащих государственного учреждения "Аппарат Уилского районного маслихата" и его описания
  kaz: '"Ойыл аудандық мәслихатының аппараты" мемлекеттік мекемесінің мемлекеттік қызметшілерінің қызметтік куәлігін беру Қағидаларын және оның сипаттамасын бекіту туралы'
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2017-06-13
approved_by:
- '153011000002'
version_date:
  kaz: 2017-06-13
  rus: 2017-06-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/113520/kaz/13.06.2017
  rus: https://zan.gov.kz/client/#!/doc/113520/rus/13.06.2017
