act_code: '51373'
requisite: Ақтөбе облысы Ырғыз аудандық мәслихатының 2010 жылғы 17 ақпандағы № 123 шешімі. Ақтөбе облысы Ырғыз ауданының Әділет басқармасында 2010 жылдың 18 наурызда № 3-5-114 тіркелді. Күші жойылды - Ақтөбе облысы Ырғыз аудандық мәслихатының 2011 жылғы 27 шілдедегі № 180 шешімімен
title:
  rus: Ауданға жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына әлеуметтік қолдау ұсыну туралы
  kaz: Ауданға жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына әлеуметтік қолдау ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-17
approved_by:
- '153006000002'
version_date:
  kaz: 2010-02-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/51373/kaz/17.02.2010
