act_code: '206216'
requisite: Решение Шалкарского районного маслихата Актюбинской области от 30 декабря 2024 года № 380
title:
  rus: Об утверждении бюджета Бозойского сельского округа на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Бозой ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '153014000002'
version_date:
  kaz: 2025-07-18
  rus: 2025-07-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/206216/kaz/18.07.2025
  rus: https://zan.gov.kz/client/#!/doc/206216/rus/18.07.2025
caused_by:
  code: '212811'
  requisite: Решение Шалкарского районного маслихата Актюбинской области от 18 июля 2025 года № 475
  title:
    rus: О внесении изменений в решение Шалкарского районного маслихата от 30 декабря 2024 год № 380 «Об утверждении бюджета Бозойского сельского округа на 2025-2027 годы»
    kaz: Шалқар аудандық мәслихатының 2024 жылғы 30 желтоқсандағы № 380 «2025-2027 жылдарға арналған Бозой ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/212811/rus
