act_code: '157718'
requisite: Решение Иргизского районного маслихата Актюбинской области от 23 июля 2021 года № 48
title:
  rus: Об утверждении плана по управлению пастбищами и их использованию по Иргизскому району на 2021–2022 годы
  kaz: Ырғыз ауданы бойынша 2021–2022 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарын бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2021-07-23
approved_by:
- '153006000002'
version_date:
  kaz: 2021-07-23
  rus: 2021-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/157718/kaz/23.07.2021
  rus: https://zan.gov.kz/client/#!/doc/157718/rus/23.07.2021
