act_code: '206526'
requisite: Решение Кобдинского районного маслихата Актюбинской области от 31 декабря 2024 года № 287
title:
  rus: Об утверждении бюджета Кызылжарского сельского округа на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Қызылжар ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-31
approved_by:
- '153012000002'
version_date:
  kaz: 2025-07-15
  rus: 2025-07-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/206526/kaz/15.07.2025
  rus: https://zan.gov.kz/client/#!/doc/206526/rus/15.07.2025
caused_by:
  code: '212643'
  requisite: Решение Кобдинского районного маслихата Актюбинской области от 15 июля 2025 года № 359
  title:
    rus: О внесении изменений в решение Кобдинского районного маслихата от 31 декабря 2024 года № 287 «Об утверждении бюджета Кызылжарского сельского округа на 2025-2027 годы»
    kaz: Қобда аудандық мәслихатының 2024 жылғы 31 желтоқсандағы «2025-2027 жылдарға арналған Қызылжар ауылдық округінің бюджетін екіту туралы» № 287 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/212643/rus
