act_code: '103721'
requisite: Решение маслихата Каргалинского района Актюбинской области от 10 июня 2016 года № 35
title:
  rus: О признании утратившим силу решения районного маслихата от 30 апреля 2013 года № 114 "О дополнительном регламентировании порядка проведения мирных собраний, митингов, шествий, пикетов и демонстраций в Каргалинском районе"
  kaz: Аудандық мәслихатының 2013 жылғы 30 сәуірдегі № 114 "Қарғалы ауданы аумағында бейбіт жиналыстар, митингілер, шерулер, пикеттер және демонстрациялар өткізу тәртібін қосымша реттеу туралы" шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-06-10
approved_by:
- '153007000002'
version_date:
  kaz: 2016-06-10
  rus: 2016-06-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/103721/kaz/10.06.2016
  rus: https://zan.gov.kz/client/#!/doc/103721/rus/10.06.2016
