act_code: '44236'
requisite: Ақтөбе облысы Шалқар аудандық мәслихатының 2009 жылғы 30 қаңтардағы N 103 шешімі. Ақтөбе облысының Шалқар аудандық әділет басқармасында 2009 жылдың 12 ақпанда N 3-13-96 тіркелді
title:
  rus: Тіркелген салық мөлшерлемесін белгілеу туралы
  kaz: Тіркелген салық мөлшерлемесін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-30
approved_by:
- '153014000002'
version_date:
  kaz: 2009-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/44236/kaz/24.04.2009
caused_by:
  code: '45806'
  requisite: Ақтөбе облысы Шалқар аудандық мәслихатының 2009 жылғы 24 сәуірдегі N 132 шешімі. Ақтөбе облысының Шалқар аудандық әділет басқармасында 2009 жылдың 13 мамырда N 3-13-107 тіркелді
  title:
    rus: 2009 жылғы 30 қаңтардағы N 103 "Тіркелген салық ставкасын бекіту туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: 2009 жылғы 30 қаңтардағы N 103 "Тіркелген салық ставкасын бекіту туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/45806/rus
