act_code: '44236'
requisite: Ақтөбе облысы Шалқар аудандық мәслихатының 2009 жылғы 30 қаңтардағы N 103 шешімі. Ақтөбе облысының Шалқар аудандық әділет басқармасында 2009 жылдың 12 ақпанда N 3-13-96 тіркелді
title:
  rus: Тіркелген салық мөлшерлемесін белгілеу туралы
  kaz: Тіркелген салық мөлшерлемесін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-30
approved_by:
- '153014000002'
version_date:
  kaz: 2017-02-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/44236/kaz/17.02.2017
caused_by:
  code: '110616'
  requisite: Решение маслихата Шалкарского района Актюбинской области от 17 февраля 2017 года № 84. Зарегистрировано Департаментом юстиции Актюбинской области 14 марта 2017 года № 5321. Утратило силу решением маслихата Шалкарского района Актюбинской области от 27 марта 2018 года № 202
  title:
    rus: О внесении изменений в решение Шалкарского районного маслихата от 30 января 2009 года № 103 «Тіркелген салық ставкасын белгілеу туралы»
    kaz: Шалқар аудандық мәслихатының 2009 жылғы 30 қаңтардағы № 103 «Тіркелген салық ставкасын белгілеу туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/110616/rus
