act_code: '63252'
requisite: Решение акима Саркульского сельского округа Темирского района Актюбинской области от 4 января 2012 года № 1. Зарегистрировано Управлением юстиции Темирского района Актюбинской области 3 февраля 2012 года № 3-10-155
title:
  rus: О наименовани составных частей Саркульского сельского округа
  kaz: Саркөл ауылдық округінің құрамдас бөліктерін атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-01-04
approved_by:
- '153010010001'
version_date:
  kaz: 2012-01-04
  rus: 2012-01-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/63252/kaz/04.01.2012
  rus: https://zan.gov.kz/client/#!/doc/63252/rus/04.01.2012
