act_code: '3041'
requisite: Решение акима Актюбинской области от 21 апреля 1999 года № 59. Зарегистрировано Управлением юстиции Актюбинской области 20 мая 1999 года № 105
title:
  rus: О предоставлении Компании "Ферст Интернейшнл Ойл Корпорейшн" права временного пользования земельными участками для бурения разведочной скважины на территории Байганинского района
  kaz: Байғанин ауданы территориясынан барлау скважинасын бұрғылау үшін "Ферст Интернейшнл Ойл Корпорейшн" Компаниясына уақытша жер учаскесін пайдалану құқығын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-04-20
approved_by:
- '153000000003'
version_date:
  kaz: 1999-04-20
  rus: 1999-04-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/3041/kaz/20.04.1999
  rus: https://zan.gov.kz/client/#!/doc/3041/rus/20.04.1999
