act_code: '194909'
requisite: Решение Шалкарского районного маслихата Актюбинской области от 15 марта 2024 года № 221. Зарегистрировано Департаментом юстиции Актюбинской области 27 марта 2024 года № 8540-04
title:
  rus: Об утверждении размера и правил оказания жилищной помощи в Шалкарском районе
  kaz: Шалқар ауданында тұрғын үй көмегін көрсетудің мөлшері мен қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-15
approved_by:
- '153014000002'
version_date:
  kaz: 2024-03-15
  rus: 2024-03-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/194909/kaz/15.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194909/rus/15.03.2024
