act_code: '76921'
requisite: Решение маслихата Мугалжарского района Актюбинской области от 25 декабря 2013 года № 129. Зарегистрировано Департаментом юстиции Актюбинской области 21 января 2014 года № 3755. Утратило силу решением маслихата Мугалжарского района Актюбинской области от 10 июня 2015 года № 234
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан в Мугалжарском районе
  kaz: Мұғалжар ауданында әлеуметтік көмек көрсету, мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2013-12-25
approved_by:
- '153009000002'
version_date:
  kaz: 2013-12-25
  rus: 2013-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/76921/kaz/25.12.2013
  rus: https://zan.gov.kz/client/#!/doc/76921/rus/25.12.2013
