act_code: '178131'
requisite: Решение Хромтауского районного маслихата Актюбинской области от 30 декабря 2022 года № 324
title:
  rus: Об утверждении бюджета Кудыксайского сельского округа на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Құдықсай ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-30
approved_by:
- '153013000002'
version_date:
  kaz: 2023-11-08
  rus: 2023-11-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/178131/kaz/08.11.2023
  rus: https://zan.gov.kz/client/#!/doc/178131/rus/08.11.2023
caused_by:
  code: '188521'
  requisite: Решение Хромтауского районного маслихата Актюбинской области от 8 ноября 2023 года № 89
  title:
    rus: О внесении изменений в решение Хромтауского районного маслихата от 30 декабря 2022 года № 324 «Об утверждении бюджета села Кудыксайского сельского округа на 2023-2025 годы»
    kaz: Хромтау аудандық маслихатының 2022 жылғы 30 желтоқсандағы № 324 2023-2025 жылдарға арналған Құдықсай ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/188521/rus
