act_code: '176738'
requisite: Решение Кобдинского районного маслихата Актюбинской области от 28 декабря 2022 года № 268
title:
  rus: Об утверждении бюджета Сарбулакского сельского округа на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Сарбұлақ ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-28
approved_by:
- '153012000002'
version_date:
  kaz: 2023-05-03
  rus: 2023-05-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/176738/kaz/03.05.2023
  rus: https://zan.gov.kz/client/#!/doc/176738/rus/03.05.2023
caused_by:
  code: '181193'
  requisite: Решение Кобдинского районного маслихата Актюбинской области от 3 мая 2023 года № 18
  title:
    rus: О внесении изменений в решение Кобдинского районного маслихата от 28 декабря 2022 года № 268 «Об утверждении бюджета Сарбулакского сельского округа на 2023-2025 годы»
    kaz: Қобда аудандық мәслихатының 2022 жылғы 28 желтоқсандағы № 268 «2023-2025 жылдарға арналған Сарбұлақ ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/181193/rus
