act_code: '42863'
requisite: Ақтөбе облысы Шалқар ауданы Кішіқұм ауылдық округі әкімінің 2008 жылғы 20 қарашадағы N 5 шешімі. Ақтөбе облысының Шалқар аудандық әділет басқармасында 2008 жылдың 22 желтоқсанда N 3-13-90 тіркелді
title:
  rus: Елді мекендерге көше атауын беру туралы
  kaz: Елді мекендерге көше атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-11-20
approved_by:
- '153014012002'
version_date:
  kaz: 2021-01-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/42863/kaz/19.01.2021
caused_by:
  code: '152267'
  requisite: Решение акима Кишикумского сельского округа Шалкарского района Актюбинской области от 19 января 2021 года № 4. Зарегистрировано Департаментом юстиции Актюбинской области 19 января 2021 года № 8015
  title:
    rus: О внесении изменений в решение акима Кишикумского сельского округа от 20 ноября 2008 года № 5 «Елді мекендерге көше атауын беру туралы»
    kaz: Кішіқұм ауылдық округі әкімінің 2008 жылғы 20 қарашадағы № 5 «Елді мекендерге көше атауын беру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/152267/rus
