act_code: '66656'
requisite: Решение акима Кумсайского сельского округа Мугалжарского района Актюбинской области от 18 июня 2012 года № 4. Зарегистрировано Управлением юстиции Мугалжарского района Актюбинской области 11 июля 2012 года № 3-9-172
title:
  rus: О присвоении наименований безымянным улицам сел Құмсай, Жамбыл, Шилі, Терісбұтақ Кумсайского сельского округа Мугалжарского района
  kaz: Мұғалжар ауданы Құмсай ауылдық округі Құмсай, Жамбыл, Шилі, Терісбұтақ ауылдарының атаусыз көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-06-18
approved_by:
- '153009012002'
version_date:
  kaz: 2017-05-11
  rus: 2017-05-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/66656/kaz/11.05.2017
  rus: https://zan.gov.kz/client/#!/doc/66656/rus/11.05.2017
caused_by:
  code: '112356'
  requisite: Решение акима Кумсайского сельского округа Мугалжарского района Актюбинской области от 11 мая 2017 года № 2. Зарегистрировано Департаментом юстиции Актюбинской области 17 мая 2017 года № 5496
  title:
    rus: О внесении изменения в решение акима Кумсайского аульного округа Мугалжарского района от 18 июня 2012 года № 4 «О присвоении наименований безымянным улицам сел Құмсай, Жамбыл, Шилі, Терісбұтақ Кумсайского сельского округа Мугалжарского района»
    kaz: Мұғалжар ауданы Құмсай ауылдық округі әкімінің 2012 жылғы 18 маусымдағы № 4 «Мұғалжар ауданы Құмсай ауылдық округі Құмсай, Жамбыл, Шилі, Терісбұтақ ауылдарының атаусыз көшелеріне атау беру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/112356/rus
