act_code: '66656'
requisite: Решение акима Кумсайского сельского округа Мугалжарского района Актюбинской области от 18 июня 2012 года № 4. Зарегистрировано Управлением юстиции Мугалжарского района Актюбинской области 11 июля 2012 года № 3-9-172
title:
  rus: О присвоении наименований безымянным улицам сел Құмсай, Жамбыл, Шилі, Терісбұтақ Кумсайского сельского округа Мугалжарского района
  kaz: Мұғалжар ауданы Құмсай ауылдық округі Құмсай, Жамбыл, Шилі, Терісбұтақ ауылдарының атаусыз көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-06-18
approved_by:
- '153009012002'
version_date:
  kaz: 2012-06-18
  rus: 2012-06-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/66656/kaz/18.06.2012
  rus: https://zan.gov.kz/client/#!/doc/66656/rus/18.06.2012
