act_code: '193307'
requisite: Решение маслихата города Актобе Актюбинской области от 8 февраля 2024 года № 146. Зарегистрировано Департаментом юстиции Актюбинской области 14 февраля 2024 года № 8505
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2024 год по городу Актобе
  kaz: Ақтөбе қаласы бойынша шетелдіктер үшін 2024 жылға арналған туристік жарнаның мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-08
approved_by:
- '153002000002'
version_date:
  kaz: 2024-02-08
  rus: 2024-02-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/193307/kaz/08.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193307/rus/08.02.2024
