act_code: '206384'
requisite: Решение Шалкарского районного маслихата Актюбинской области от 30 декабря 2024 года № 385
title:
  rus: Об утверждении бюджета Монкебийского сельского округа на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Мөңке би ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '153014000002'
version_date:
  kaz: 2025-03-04
  rus: 2025-03-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/206384/kaz/04.03.2025
  rus: https://zan.gov.kz/client/#!/doc/206384/rus/04.03.2025
caused_by:
  code: '207855'
  requisite: Решение Шалкарского районного маслихата Актюбинской области от 4 марта 2025 года № 412
  title:
    rus: О внесении изменений в решение Шалкарского районного маслихата от 30 декабря 2024 года № 385 «Об утверждении бюджета Монкебийского сельского округа на 2025-2027 годы»
    kaz: Шалқар аудандық мәслихатының 2024 жылғы 30 желтоқсандағы № 385 «2025-2027 жылдарға арналған Монке би ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/207855/rus
