act_code: '206540'
requisite: Решение Мугалжарского районного маслихата Актюбинской области от 30 декабря 2024 года № 322
title:
  rus: Об утверждении бюджета города Жем на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Жем қаласының бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '153009000002'
version_date:
  kaz: 2025-02-21
  rus: 2025-02-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/206540/kaz/21.02.2025
  rus: https://zan.gov.kz/client/#!/doc/206540/rus/21.02.2025
caused_by:
  code: '207530'
  requisite: Решение Мугалжарского районного маслихата Актюбинской области от 21 февраля 2025 года № 348
  title:
    rus: О внесении изменений в решение Мугалжарского районного маслихата от 30 декабря 2024 года № 322 «Об утверждении бюджета города Жем на 2025-2027 годы»
    kaz: Мұғалжар аудандық мәслихатының 2024 жылғы 30 желтоқсандағы № 322 «2025-2027 жылдарға арналған Жем қаласының бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/207530/rus
