act_code: '50566'
requisite: Ақтөбе облысы Темір аудандық мәслихатының 2009 жылғы 24 желтоқсандағы № 146 шешімі. Ақтөбе облысының Темір аудандық Әділет басқармасында 2010 жылдың 4 ақпанда № 3-10-119 тіркелді. Күші жойылды - Ақтөбе облысы Темір аудандық мәслихатының 2012 жылғы 11 маусымдағы № 43 шешімімен
title:
  rus: Темір ауданы елді-мекендерінің аумағын көріктендіру Қағидасын бекіту туралы
  kaz: Темір ауданы елді-мекендерінің аумағын көріктендіру Қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2009-12-24
approved_by:
- '153010000002'
version_date:
  kaz: 2009-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/50566/kaz/24.12.2009
