act_code: '44747'
requisite: Ақтөбе облысы Әйтеке би ауданы Сарат ауылдық округі әкімінің 2009 жылғы 17 ақпандағы N 1 шешімі. Ақтөбе облысының Әйтеке би аудандық әділет басқармасында 2009 жылдың 12 наурызда N 3-2-73 тіркелді
title:
  rus: Көшелерге атау беру туралы
  kaz: Көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-17
approved_by:
- '153003013002'
version_date:
  kaz: 2016-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/44747/kaz/27.06.2016
caused_by:
  code: '104803'
  requisite: Решение акима Саратского сельского округа Айтекебийского района Актюбинской области от 27 июня 2016 года № 8. Зарегистрировано Департаментом юстиции Актюбинской области 22 июля 2016 года № 5009
  title:
    rus: О внесении изменений в решение от 17 февраля 2009 года № 1 «Көшелерге атау беру туралы»
    kaz: «Көшелеріне атау беру туралы» 2009 жылғы 17 ақпандағы № 1 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/104803/rus
