act_code: '43234'
requisite: Ақтөбе облысы Ырғыз аудандық мәслихатының 2008 жылғы 18 желтоқсандағы N 58 шешімі. Ақтөбе облысының Ырғыз аудандық Әділет басқармасында 2009 жылдың 6 қаңтарда N 3-5-85 тіркелді. Күші жойылды - Ақтөбе облысы Ырғыз аудандық мәслихатының 2010 жылғы 15 сәуірдегі N 133 шешімімен
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-18
approved_by:
- '153006000002'
version_date:
  kaz: 2008-12-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/43234/kaz/18.12.2008
