act_code: '50904'
requisite: Ақтөбе облысы Темір аудандық мәслихатының 2010 жылғы 12 ақпандағы № 179 шешімі. Ақтөбе облысының Темір аудандық Әділет басқармасында 2010 жылдың 26 ақпанда № 3-10-123 тіркелді. Күші жойылды - Ақтөбе облысы Темір аудандық мәслихатының 2017 жылғы 17 ақпандағы № 84 шешімімен
title:
  rus: Аз қамтамасыз етілген азаматтарға тұрғын үй көмегін көрсету қағидасы туралы
  kaz: Аз қамтамасыз етілген азаматтарға тұрғын үй көмегін көрсету қағидасы туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2010-02-12
approved_by:
- '153010000002'
version_date:
  kaz: 2010-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/50904/kaz/27.12.2010
caused_by:
  code: '57036'
  requisite: Решение маслихата Темирского района Актюбинской области от 27 декабря 2010 года № 218. Зарегистрировано Управлением юстиции Темирского района Актюбинской области 10 января 2011 года за № 3-10-139. Утратило силу решением маслихата Темирского района Актюбинской области от 17 февраля 2017 года № 84
  title:
    rus: О внесении изменения в решение районного маслихата от 12 февраля 2010 года № 179 "Об правилах предоставления жилищной помощи малообеспеченным гражданам"
    kaz: Аудандық мәслихаттың 2010 жылғы 12 ақпандағы № 179 "Аз қамтамасыз етілген азаматтарға тұрғын үй көмегін көрсету қағидасы туралы" шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/57036/rus
