act_code: '205381'
requisite: Решение Темирского районного маслихата Актюбинской области от 27 декабря 2024 года № 286
title:
  rus: Об утверждении бюджета Шубаркудыкского сельского округа на 2025–2027 годы
  kaz: 2025–2027 жылдарға арналған Шұбарқұдық ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '153010000002'
version_date:
  kaz: 2025-03-12
  rus: 2025-03-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/205381/kaz/12.03.2025
  rus: https://zan.gov.kz/client/#!/doc/205381/rus/12.03.2025
caused_by:
  code: '208171'
  requisite: Решение Темирского районного маслихата Актюбинской области от 12 марта 2025 года № 314
  title:
    rus: О внесении изменений в решение Темирского районного маслихата от 27 декабря 2024 года № 286 «Об утверждении бюджета Шубаркудыкского сельского округа на 2025–2027 годы»
    kaz: Темір аудандық мәслихатының 2024 жылғы 27 желтоқсандағы № 286 «2025–2027 жылдарға арналған Шұбарқұдық ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/208171/rus
