act_code: '5748'
requisite: Решение акима Актюбинской области от 16 сентября 1999 года № 158. Зарегистрировано Управлением юстиции Актюбинской области 12 апреля 2000 года № 447. Утратило силу - письмо Департамента юстиции Актюбинской области от 24 апреля 2007 года № 4-19/4853
title:
  rus: О плане действий по улучшению положения женщин в области
  kaz: Облыста әйелдер жағдайын жақсартудың іс-қимыл жоспары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-09-15
approved_by:
- '153000000003'
version_date:
  kaz: 1999-09-15
  rus: 1999-09-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/5748/kaz/15.09.1999
  rus: https://zan.gov.kz/client/#!/doc/5748/rus/15.09.1999
