act_code: '104825'
requisite: Решение маслихата Уилского района Актюбинской области от 7 июня 2016 года № 28. Зарегистрировано Департаментом юстиции Актюбинской области 15 июля 2016 года № 4999
title:
  rus: Об утверждении границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки села Уил Уилского района
  kaz: Ойыл ауданы Ойыл ауылының бағалау аймақтарының шекараларын және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-06-07
approved_by:
- '153011000002'
version_date:
  kaz: 2016-06-07
  rus: 2016-06-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/104825/kaz/07.06.2016
  rus: https://zan.gov.kz/client/#!/doc/104825/rus/07.06.2016
