act_code: '3500'
requisite: Решение акима Актюбинской области от 7 июня 1999 года № 97. Зарегистрировано Управлением юстиции Актюбинской области 15 июля 1999 года № 130
title:
  rus: О создании уполномоченного органа по вопросам занятости и социальной защиты безработных
  kaz: Жұмыспен қамту және жұмыссыздарды әлеуметтік қорғау мәселелері жөніндегі өкілетті орган құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-06-06
approved_by:
- '153000000003'
version_date:
  kaz: 1999-06-06
  rus: 1999-06-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/3500/kaz/06.06.1999
  rus: https://zan.gov.kz/client/#!/doc/3500/rus/06.06.1999
