act_code: '56821'
requisite: Решение маслихата Хромтауского района Актюбинской области от 24 декабря 2010 года № 207. Зарегистрировано Управлением юстиции Хромтауского района Актюбинской области 17 января 2011 года № 3-12-128. Утратило силу в связи с истечением срока применения - (письмо аппарата маслихата Хромтауского района Актюбинской области от 14 февраля 2013 года № 59)
title:
  rus: О бюджете Хромтауского района на 2011-2013 годы
  kaz: Хромтау ауданының 2011-2013 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '153013000002'
version_date:
  kaz: 2011-11-10
  rus: 2011-11-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/56821/kaz/10.11.2011
  rus: https://zan.gov.kz/client/#!/doc/56821/rus/10.11.2011
caused_by:
  code: '61596'
  requisite: Решение маслихата Хромтауского района Актюбинской области от 10 ноября 2011 года № 269. Зарегистрировано Департаментом юстиции Актюбинской области 24 ноября 2011 года № 3-12-140. Утратило силу в связи с истечением срока применения - (письмо аппарата маслихата Хромтауского района Актюбинской области от 14 февраля 2013 года № 59)
  title:
    rus: О внесении изменений в решение районного маслихата от 24 декабря 2010 года № 207 "О бюджете Хромтауского района на 2011-2013 годы"
    kaz: Аудандық мәслихаттың 2010 жылғы 24 желтоқсандағы № 207 "Хромтау ауданының 2011-2013 жылдарға арналған бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/61596/rus
