act_code: '155340'
requisite: Решение акима сельского округа Танирберген Мартукского района Актюбинской области от 26 апреля 2021 года № 4. Зарегистрировано Департаментом юстиции Актюбинской области 28 апреля 2021 года № 8281
title:
  rus: О присвоении наименований безымянным улицам сел Саржансай и Кенсахара сельского округа Танирберген Мартукского района
  kaz: Мәртөк ауданы Тәңірберген ауылдық округінің Саржансай және Кеңсахара ауылдарының атаусыз көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-04-26
approved_by:
- '153008006002'
version_date:
  kaz: 2021-04-26
  rus: 2021-04-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/155340/kaz/26.04.2021
  rus: https://zan.gov.kz/client/#!/doc/155340/rus/26.04.2021
