act_code: '56912'
requisite: Решение маслихата Каргалинского района Актюбинской области от 24 декабря 2010 года № 243. Зарегистрировано Управлением юстиции Каргалинского района Актюбинской области 14 января 2011 года за № 3-6-114. Утратило силу в связи с истечением срока применения - (письмо маслихата Каргалинского района Актюбинской области от 4 мая 2012 года № 03-14/68)
title:
  rus: О бюджете Каргалинского района на 2011-2013 годы
  kaz: 2011-2013 жылдарға арналған Қарғалы ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '153007000002'
version_date:
  kaz: 2011-03-28
  rus: 2011-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/56912/kaz/28.03.2011
  rus: https://zan.gov.kz/client/#!/doc/56912/rus/28.03.2011
caused_by:
  code: '58176'
  requisite: Решение маслихата Каргалинского района Актюбинской области от 28 марта 2011 года № 275. Зарегистрировано Управлением юстиции Каргалинского района 13 апреля 2011 года за № 3-6-118. Утратило силу в связи с истечением срока применения - (письмо маслихата Каргалинского района Актюбинской области от 4 мая 2012 года № 03-14/68)
  title:
    rus: О внесении изменений и дополнений в решение районного маслихата от 24 декабря 2010 года № 243 "О бюджете Каргалинского района на 2011-2013 годы"
    kaz: Аудандық мәслихаттың 2010 жылғы 24 желтоқсандағы № 243 "2011-2013 жылдарға арналған Қарғалы ауданының бюджеті туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/58176/rus
