act_code: '42625'
requisite: Ақтөбе облысы Хромтау ауданы Аққұдық ауылдық әкімінің 2008 жылғы 6 қарашадағы N 5 шешімі. Ақтөбе облысының Хромтау аудандық Әділет басқармасында 2008 жылғы 5 желтоқсанда N 3-12-66 тіркелді
title:
  rus: '"Аққұдық ауылдық округіне қарасты елді мекендерге көше атауын беру туралы"'
  kaz: '"Аққұдық ауылдық округіне қарасты елді мекендерге көше атауын беру туралы"'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-11-06
approved_by:
- '153013004002'
version_date:
  kaz: 2015-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/42625/kaz/14.07.2015
caused_by:
  code: '92633'
  requisite: Решение от 14.07.2015 №2, Акимат Аккудукского сельского округа
  title:
    rus: О внесении изменений в решение от 06 ноября 2008 года № 5 "О присвоении названии улицам и населенным пунктам сельского округа"
    kaz: '"Аққұдық селолық округіне қарасты елді мекендерге көше атауын беру туралы" 2008 жылғы 06 қарашадағы № 5 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/92633/rus
