act_code: '115990'
requisite: Решение Шалкарского районного маслихата Актюбинской области от 30 октября 2017 года № 135. Зарегистрировано Департаментом юстиции Актюбинской области 9 ноября 2017 года № 5688. Утратило силу решением Шалкарского районного маслихата Актюбинской области от 20 октября 2021 года № 111
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов по городу Шалкар
  kaz: Шалқар қаласы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-10-30
approved_by:
- '153014000002'
version_date:
  kaz: 2019-05-06
  rus: 2019-05-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/115990/kaz/06.05.2019
  rus: https://zan.gov.kz/client/#!/doc/115990/rus/06.05.2019
caused_by:
  code: '131579'
  requisite: Решение Шалкарского районного маслихата Актюбинской области от 6 мая 2019 года № 335. Зарегистрировано Департаментом юстиции Актюбинской области 14 мая 2019 года № 6137. Утратило силу решением Шалкарского районного маслихата Актюбинской области от 20 октября 2021 года № 111
  title:
    rus: О внесении изменения в решение Шалкарского районного маслихата от 30 октября 2017 года № 135 «Об утверждении норм образования и накопления коммунальных отходов по городу Шалкар»
    kaz: Шалқар аудандық мәслихатының 2017 жылғы 30 қазандағы № 135 «Шалқар қаласы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/131579/rus
