act_code: '6040'
requisite: Решение акима Актюбинской области от 15 февраля 2000 года № 26. Зарегистрировано Департаментом юстиции Актюбинской области 17 мая 2000 года № 513. Утратило силу - письмо Департамента юстиции Актюбинской области от 15 февраля 2007 года № 4-19/1525
title:
  rus: О службах Гражданской обороны и чрезвычайных ситуаций
  kaz: Азаматтық қорғаныс пен төтенше жағдайлардың қызметтері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-02-15
approved_by:
- '153000000003'
version_date:
  kaz: 2000-02-15
  rus: 2000-02-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/6040/kaz/15.02.2000
  rus: https://zan.gov.kz/client/#!/doc/6040/rus/15.02.2000
