act_code: '44234'
requisite: Ақтөбе облысы Қобда ауданы Қобда ауылдық округі әкімінің 2009 жылғы 23 қаңтардағы N 4 шешімі. Ақтөбе облысының Қобда аудандық әділет басқармасында 2009 жылдың 13 ақпанда N 3-7-59 тіркелді
title:
  rus: Қобда ауылының жаңа көшелеріне атау беру туралы
  kaz: Қобда ауылының жаңа көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-23
approved_by:
- '153012016001'
version_date:
  kaz: 2016-10-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/44234/kaz/13.10.2016
caused_by:
  code: '107570'
  requisite: Решение акима Кобдинского сельского округа Кобдинского района Актюбинской области от 13 октября 2016 года № 214. Зарегистрировано Департаментом юстиции Актюбинской области 3 ноября 2016 года № 5121
  title:
    rus: О внесении изменения в решение акима Кобдинского сельского округа от 23 января 2009 года № 4 "Қобда ауылының жаңа көшелеріне атау беру туралы"
    kaz: '"Қобда ауылыңың жаңа көшелеріне атау беру туралы" Қобда ауылдық округі әкімінің 2009 жылғы 23 қаңтардағы № 4 шешіміне өзгеріс енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/107570/rus
