act_code: '138834'
requisite: Решение Каргалинского районного маслихата Актюбинской области от 6 января 2020 года № 409. Зарегистрировано Департаментом юстиции Актюбинской области 15 января 2020 года № 6716
title:
  rus: Об утверждении бюджета Велиховского сельского округа на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Велихов ауылдық округі бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-06
approved_by:
- '153007000002'
version_date:
  kaz: 2020-11-23
  rus: 2020-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/138834/kaz/23.11.2020
  rus: https://zan.gov.kz/client/#!/doc/138834/rus/23.11.2020
caused_by:
  code: '149128'
  requisite: Решение Каргалинского районного маслихата Актюбинской области от 23 ноября 2020 года № 521. Зарегистрировано Департаментом юстиции Актюбинской области 30 ноября 2020 года № 7737
  title:
    rus: О внесении изменений в решение Каргалинского районного маслихата от 6 января 2020 года № 409 «Об утверждении бюджета Велиховского сельского округа на 2020-2022 годы»
    kaz: Қарғалы аудандық мәслихатының 2020 жылғы 6 қаңтардағы № 409 «2020-2022 жылдарға арналған Велихов ауылдық округі бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149128/rus
