act_code: '117997'
requisite: Решение маслихата Каргалинского района Актюбинской области от 22 декабря 2017 года № 209. Зарегистрировано Департаментом юстиции Актюбинской области 12 января 2018 года № 5840
title:
  rus: Об утверждении бюджета Бадамшинского сельского округа на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған Бадамша ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-22
approved_by:
- '153007000002'
version_date:
  kaz: 2018-09-11
  rus: 2018-09-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/117997/kaz/11.09.2018
  rus: https://zan.gov.kz/client/#!/doc/117997/rus/11.09.2018
caused_by:
  code: '125099'
  requisite: Решение Каргалинского районного маслихата Актюбинской области от 11 сентября 2018 года № 269. Зарегистрировано Управлением юстиции Каргалинского района Департамента юстиции Актюбинской области 2 октября 2018 года № 3-6-173
  title:
    rus: О внесении изменения в решение районного маслихата от 22 декабря 2017 года № 209 «Об утверждении бюджета Бадамшинского сельского округа на 2018-2020 годы»
    kaz: Аудандық мәслихаттың 2017 жылғы 22 желтоқсандағы № 209 «2018-2020 жылдарға арналған Бадамша ауылдық округ бюджетін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/125099/rus
