act_code: '42807'
requisite: Решение акима Тассайского сельского округа Хромтауского района Актюбинской области от 11 декабря 2008 года № 5. Зарегистрировано Управлением юстиции Хромтауского района Актюбинской области 18 декабря 2008 года № 3-12-72
title:
  rus: О присвоении наименований улицам населенных пунктов Тассайского сельского округа
  kaz: Тассай ауылдық округіне қарасты елді мекендерге көше атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-11
approved_by:
- '153013013002'
version_date:
  kaz: 2008-12-11
  rus: 2008-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/42807/kaz/11.12.2008
  rus: https://zan.gov.kz/client/#!/doc/42807/rus/11.12.2008
