act_code: '42807'
requisite: Решение акима Тассайского сельского округа Хромтауского района Актюбинской области от 11 декабря 2008 года № 5. Зарегистрировано Управлением юстиции Хромтауского района Актюбинской области 18 декабря 2008 года № 3-12-72
title:
  rus: О присвоении наименований улицам населенных пунктов Тассайского сельского округа
  kaz: Тассай ауылдық округіне қарасты елді мекендерге көше атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-11
approved_by:
- '153013013002'
version_date:
  kaz: 2017-04-06
  rus: 2017-04-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/42807/kaz/06.04.2017
  rus: https://zan.gov.kz/client/#!/doc/42807/rus/06.04.2017
caused_by:
  code: '111392'
  requisite: Решение акима Тассайского сельского округа Хромтауского района Актюбинской области от 6 апреля 2017 года № 5. Зарегистрировано Департаментом юстиции Актюбинской области 13 апреля 2017 года № 5433
  title:
    rus: О внесении изменений в решение акима Тассайского сельского округа от 11 декабря 2008 года № 5 «О присвоении названии улиц населенным пунктам сельского округа»
    kaz: Тассай ауылдық округі әкімінің 2008 жылғы 11 желтоқсандағы № 5 «Тассай ауылдық округіне қарасты елді мекендерге көше атауын беру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/111392/rus
