act_code: '199371'
requisite: Решение Мугалжарского районного маслихата Актюбинской области от 24 июля 2024 года № 255. Зарегистрировано Департаментом юстиции Актюбинской области 30 июля 2024 года № 8613-04
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан в Мугалжарском районе
  kaz: Мұғалжар ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2024-07-24
approved_by:
- '153009000002'
version_date:
  kaz: 2025-09-11
  rus: 2025-09-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/199371/kaz/11.09.2025
  rus: https://zan.gov.kz/client/#!/doc/199371/rus/11.09.2025
caused_by:
  code: '214458'
  requisite: Решение Мугалжарского районного маслихата Актюбинской области от 11 сентября 2025 года № 428
  title:
    rus: О внесении изменений в решение Мугалжарского районного маслихата от 24 июля 2024 года № 255 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан в Мугалжарском районе»
    kaz: Мұғалжар аудандық мәслихатының 2024 жылғы 24 шілдедегі № 255 «Мұғалжар ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/214458/rus
