act_code: '97968'
requisite: 'Решение маслихата Актюбинской области от 11 декабря 2015 года № 351. Зарегистрировано Департаментом юстиции Актюбинской области 21 января 2016 года № 4685. Утратило силу решением Актюбинского областного маслихата от 27 августа 2025 года № 246 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)  '
title:
  rus: Об утверждении Правил общего водопользования на водных объектах Актюбинской области
  kaz: Ақтөбе облысының су объектілерінде ортақ су пайдаланудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2015-12-11
approved_by:
- '153000000002'
version_date:
  kaz: 2023-07-05
  rus: 2023-07-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/97968/kaz/05.07.2023
  rus: https://zan.gov.kz/client/#!/doc/97968/rus/05.07.2023
caused_by:
  code: '184015'
  requisite: Решение Актюбинского областного маслихата от 5 июля 2023 года № 45. Зарегистрировано Департаментом юстиции Актюбинской области 14 июля 2023 года № 8384. Утратило силу решением Актюбинского областного маслихата от 27 августа 2025 года № 246 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения и дополнения в решение областного маслихата от 11 декабря 2015 года № 351 «Об утверждении Правил общего водопользования на водных объектах Актюбинской области»
    kaz: «Ақтөбе облысының су объектілерінде ортақ су пайдаланудың Қағидаларын бекіту туралы» облыстық мәслихаттың 2015 жылғы 11 желтоқсандағы № 351 шешіміне өзгеріс пен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/184015/rus
