act_code: '128518'
requisite: Решение Темирского районного маслихата Актюбинской области от 4 января 2019 года № 310. Зарегистрировано Управлением юстиции Темирского района Департамента юстиции Актюбинской области 10 января 2019 года № 3-10-239
title:
  rus: Об утверждении бюджета Шубаркудыкского сельского округа на 2019–2021 годы
  kaz: 2019–2021 жылдарға арналған Шұбарқұдық ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-04
approved_by:
- '153010000002'
version_date:
  kaz: 2019-11-01
  rus: 2019-11-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/128518/kaz/01.11.2019
  rus: https://zan.gov.kz/client/#!/doc/128518/rus/01.11.2019
caused_by:
  code: '135798'
  requisite: Решение Темирского районного маслихата Актюбинской области от 1 ноября 2019 года № 395. Зарегистрировано Департаментом юстиции Актюбинской области 5 ноября 2019 года № 6444
  title:
    rus: О внесении изменений в решение районного маслихата от 4 января 2019 года № 310 «Об утверждении бюджета Шубаркудыкского сельского округа на 2019-2021 годы»
    kaz: Аудандық мәслихаттың 2019 жылғы 4 қаңтардағы № 310 «2019-2021 жылдарға арналған Шұбарқұдық ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/135798/rus
