act_code: '103244'
requisite: Решение акима Жайсанбайского сельского округа Иргизского района Актюбинской области от 23 мая 2016 года № 5. Зарегистрировано Департаментом юстиции Актюбинской области 10 июня 2016 года № 4953. Утратило силу решением акима Жайсанбайского сельского округа Иргизского района Актюбинской области от 22 июля 2016 года № 6
title:
  rus: Об установлении карантина
  kaz: Карантин белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-05-23
approved_by:
- '153006007001'
version_date:
  kaz: 2016-05-23
  rus: 2016-05-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/103244/kaz/23.05.2016
  rus: https://zan.gov.kz/client/#!/doc/103244/rus/23.05.2016
