act_code: '193173'
requisite: Решение Уилского районного маслихата Актюбинской области от 8 февраля 2024 года № 114. Зарегистрировано Департаментом юстиции Актюбинской области 9 февраля 2024 года № 8494
title:
  rus: О понижении размера ставки налогов при применении специального налогового режима розничного налога в Уилском районе
  kaz: Ойыл ауданында бөлшек салықтың арнаулы салық режимін қолдану кезінде салық мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-08
approved_by:
- '153011000002'
version_date:
  kaz: 2024-02-08
  rus: 2024-02-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/193173/kaz/08.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193173/rus/08.02.2024
