act_code: '6381'
requisite: Решение акима Актюбинской области от 17 марта 2000 года № 39. Зарегистрировано Управлением юстиции Актюбинской области 23 июня 2000 года № 572
title:
  rus: О рейтинговой системе оценки социально-экономического положения районов и г. Актобе
  kaz: Ақтөбе қаласы мен аудандардың әлеуметтік-экономикалық жағдайын рейтингтік бағалау жүйесі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-03-17
approved_by:
- '153000000003'
version_date:
  kaz: 2000-03-17
  rus: 2000-03-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/6381/kaz/17.03.2000
  rus: https://zan.gov.kz/client/#!/doc/6381/rus/17.03.2000
