act_code: '185843'
requisite: Решение Уилского районного маслихата Актюбинской области от 31 августа 2023 года № 75
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов, тарифов для населения на сбор, транспортировку, сортировку и захоронение твердых бытовых отходов по Уилскому району
  kaz: Ойыл ауданы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын, халық үшін тұрмыстық қатты қалдықтарды жинауға, тасымалдауға, сұрыптауға және көмуге арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-08-31
approved_by:
- '153011000002'
version_date:
  kaz: 2023-08-31
  rus: 2023-08-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/185843/kaz/31.08.2023
  rus: https://zan.gov.kz/client/#!/doc/185843/rus/31.08.2023
