act_code: '193246'
requisite: Решение маслихата города Актобе Актюбинской области от 8 февраля 2024 года № 145. Зарегистрировано Департаментом юстиции Актюбинской области 13 февраля 2024 года № 8501. Утратило силу решением маслихата города Актобе Актюбинской области от 18 декабря 2025 года № 369 (вводится в действие с 01.01.2026)
title:
  rus: О понижении размера ставки налогов при применении специального налогового режима розничного налога в городе Актобе
  kaz: Ақтөбе қаласында бөлшек салықтың арнаулы салық режимін қолдану кезінде салық мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-08
approved_by:
- '153002000002'
version_date:
  kaz: 2024-02-08
  rus: 2024-02-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/193246/kaz/08.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193246/rus/08.02.2024
