act_code: '105296'
requisite: Решение акима Уилского сельского округа Уилского района Актюбинской области от 8 августа 2016 года № 117
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын алу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-08-08
approved_by:
- '153011007001'
version_date:
  kaz: 2016-08-08
  rus: 2016-08-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/105296/kaz/08.08.2016
  rus: https://zan.gov.kz/client/#!/doc/105296/rus/08.08.2016
