act_code: '46849'
requisite: Ақтөбе облысы Шалқар ауданы Қауылжыр ауылдық округі әкімінің 2009 жылғы 11 маусымдағы N 14 шешімі. Ақтөбе облысының Шалқар аудандық әділет басқармасында 2009 жылдың 10 шілдеде N 3-13-113 тіркелді
title:
  rus: Көшелерге атау беру туралы
  kaz: Көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-06-11
approved_by:
- '153014007002'
version_date:
  kaz: 2009-06-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/46849/kaz/11.06.2009
