act_code: '205290'
requisite: Решение Мартукского районного маслихата Актюбинской области от 23 декабря 2024 года № 166
title:
  rus: Об утверждении Мартукского районного бюджета на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Мәртөк аудандық бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-23
approved_by:
- '153008000002'
version_date:
  kaz: 2024-12-23
  rus: 2024-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/205290/kaz/23.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205290/rus/23.12.2024
