act_code: '128516'
requisite: Решение Темирского районного маслихата Актюбинской области от 4 января 2019 года № 308. Зарегистрировано Управлением юстиции Темирского района Департамента юстиции Актюбинской области 10 января 2019 года № 3-10-237
title:
  rus: Об утверждении бюджета Кенестуского сельского округа на 2019–2021 годы
  kaz: 2019–2021 жылдарға арналған Кеңестуы ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-04
approved_by:
- '153010000002'
version_date:
  kaz: 2019-05-28
  rus: 2019-05-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/128516/kaz/28.05.2019
  rus: https://zan.gov.kz/client/#!/doc/128516/rus/28.05.2019
caused_by:
  code: '132185'
  requisite: Решение Темирского районного маслихата Актюбинской области от 28 мая 2019 года № 346. Зарегистрировано Департаментом юстиции Актюбинской области 30 мая 2019 года № 6214
  title:
    rus: О внесении изменений и дополнения в решение районного маслихата от 4 января 2019 года № 308 «Об утверждении бюджета Кенестуского сельского округа на 2019-2021 годы»
    kaz: Аудандық мәслихаттың 2019 жылғы 4 қаңтардағы № 308 «2019–2021 жылдарға арналған Кеңестуы ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/132185/rus
