act_code: '102028'
requisite: Решение маслихата Иргизского района Актюбинской области от 13 апреля 2016 года № 12. Зарегистрировано Департаментом юстиции Актюбинской области 6 мая 2016 года № 4904. Утратило силу решением Иргизского районного маслихата Актюбинской области от 18 ноября 2019 года № 251
title:
  rus: Об установлении повышенных на двадцать пять процентов должностных окладов и тарифных ставок специалистам в области здравоохранения, социального обеспечения, образования, культуры, спорта, ветеринарии, лесного хозяйства и особо охраняемых природных территорий, являющимся гражданскими служащими и работающим в сельской местности по Иргизскому району
  kaz: Ырғыз ауданы бойынша азаматтық қызметшілер болып табылатын және ауылдық жерде жұмыс істейтін денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет спорт, ветеринария, орман шаруашылығы және ерекше қорғалатын табиғи аумақтар саласындағы мамандарға жиырма бес пайызға жоғарылатылған лауазымдық айлықақылар мен тарифтік мөлшерлемелерді белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-04-13
approved_by:
- '153006000002'
version_date:
  kaz: 2016-04-13
  rus: 2016-04-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/102028/kaz/13.04.2016
  rus: https://zan.gov.kz/client/#!/doc/102028/rus/13.04.2016
