act_code: '167761'
requisite: Решение Уилского районного маслихата Актюбинской области от 6 мая 2022 года № 137. Зарегистрировано в Министерстве юстиции Республики Казахстан 13 мая 2022 года № 28020
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Уилском районе
  kaz: Ойыл ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсалған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-05-06
approved_by:
- '153011000002'
version_date:
  kaz: 2022-11-09
  rus: 2022-11-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/167761/kaz/09.11.2022
  rus: https://zan.gov.kz/client/#!/doc/167761/rus/09.11.2022
caused_by:
  code: '173691'
  requisite: Решение Уилского районного маслихата Актюбинской области от 9 ноября 2022 года № 183. Зарегистрировано в Министерстве юстиции Республики Казахстан 14 ноября 2022 года № 30516
  title:
    rus: О внесении изменений в решение Уилского районного маслихата Актюбинской области от 6 мая 2022 года № 137 «Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану в Уилском районе»
    kaz: Ақтөбе облысы Ойыл аудандық  мәслихатының 2022 жылғы 6 мамырдағы № 137 «Ойыл ауданында мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібін және мөлшерін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/173691/rus
