act_code: '80421'
requisite: Решение от 11.05.2014 № 4, Акимат аульного округа Бегалы. Зарегистрировано Департаментом юстиции Актюбинской области 30 мая 2014 года № 3914. Утратило силу решением акима Бегалинского сельского округа Хобдинского района Актюбинской области от 2 ноября 2015 года № 9
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-05-11
approved_by:
- '153012011001'
version_date:
  kaz: 2014-05-11
  rus: 2014-05-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/80421/kaz/11.05.2014
  rus: https://zan.gov.kz/client/#!/doc/80421/rus/11.05.2014
