act_code: '206383'
requisite: Решение Шалкарского районного маслихата Актюбинской области от 30 декабря 2024 года № 386
title:
  rus: Об утверждении бюджета Тогызского сельского округа на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Тоғыз ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '153014000002'
version_date:
  kaz: 2025-09-09
  rus: 2025-09-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/206383/kaz/09.09.2025
  rus: https://zan.gov.kz/client/#!/doc/206383/rus/09.09.2025
caused_by:
  code: '214291'
  requisite: Решение Шалкарского районного маслихата Актюбинской области от 9 сентября 2025 года № 510
  title:
    rus: О внесении изменений в решение Шалкарского  районного маслихата от 30 декабря 2024 года № 386 «Об утверждении бюджета Тогызского сельского округа на 2025-2027 годы»
    kaz: Шалқар аудандық мәслихатының 2024 жылғы 30 желтоқсандағы № 386 «2025-2027  жылдарға арналған Тоғыз ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/214291/rus
