act_code: '176106'
requisite: Решение маслихата города Актобе Актюбинской области от 22 декабря 2022 года № 226. Зарегистрировано в Министерстве юстиции Республики Казахстан 23 декабря 2022 года № 31235. Утратило силу решением маслихата города Актобе Актюбинской области от 25 сентября 2023 года № 83
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2023 год по городу Актобе
  kaz: Ақтөбе қаласы бойынша шетелдіктер үшін 2023 жылға арналған туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-22
approved_by:
- '153002000002'
version_date:
  kaz: 2022-12-22
  rus: 2022-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/176106/kaz/22.12.2022
  rus: https://zan.gov.kz/client/#!/doc/176106/rus/22.12.2022
