act_code: '80724'
requisite: Решение маслихата Айтекебийского района Актюбинской области от 28 мая 2014 года № 164. Зарегистрировано Департаментом юстиции Актюбинской области 13 июня 2014 года № 3946. Утратило силу решением маслихата Айтекебийского района Актюбинской области от 17 февраля 2017 года № 102
title:
  rus: Об установлении повышенных на двадцать пять процентов должностных окладов и тарифных ставок специалистам здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, работающим в сельской местности Айтекебийского района
  kaz: Әйтеке би ауданы бойынша азаматтық қызметші болып табылатын және ауылдық жерде жұмыс істейтін денсаулық сақтау, әлеуметтік қамсыздандыру, білім   беру, мәдениет, спорт және ветеринария саласындағы мамандарына жиырма бес пайызға жоғарылатылған лауазымдық айлықақылар мен тарифтік ставкаларды белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-05-28
approved_by:
- '153003000002'
version_date:
  kaz: 2014-05-28
  rus: 2014-05-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/80724/kaz/28.05.2014
  rus: https://zan.gov.kz/client/#!/doc/80724/rus/28.05.2014
