act_code: '139058'
requisite: Решение Алгинского районного маслихата Актюбинской области от 8 января 2020 года № 339. Зарегистрировано Департаментом юстиции Актюбинской области 20 января 2020 года № 6750
title:
  rus: Об утверждении бюджета Маржанбулакского сельского округа на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Маржанбұлақ ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-08
approved_by:
- '153004000002'
version_date:
  kaz: 2020-09-11
  rus: 2020-09-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/139058/kaz/11.09.2020
  rus: https://zan.gov.kz/client/#!/doc/139058/rus/11.09.2020
caused_by:
  code: '146608'
  requisite: Решение Алгинского районного маслихата Актюбинской области от 11 сентября 2020 года № 416. Зарегистрировано Департаментом юстиции Актюбинской области 21 сентября 2020 года № 7445
  title:
    rus: О внесении изменений в решение Алгинского районного маслихата от 8 января 2020 года № 339 «Об утверждении бюджета Маржанбулакского сельского округа на 2020-2022 годы»
    kaz: Алға аудандық мәслихатының 2020 жылғы 8 қаңтардағы № 339 «2020-2022 жылдарға арналған Маржанбұлақ ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/146608/rus
