act_code: '102269'
requisite: Решение маслихата Хромтауского района Актюбинской области от 25 апреля 2016 года № 17. Зарегистрировано Департаментом юстиции Актюбинской области 12 мая 2016 года № 4925. Утратило силу решением Хромтауского районного маслихата Актюбинской области от 5 ноября 2021 года № 120
title:
  rus: О повышении базовых ставок земельного налога на не используемые земли сельскохозяйственного назначения в Хромтауском районе
  kaz: Хромтау ауданында пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының базалық мөлшерлемелерін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-04-25
approved_by:
- '153013000002'
version_date:
  kaz: 2018-03-02
  rus: 2018-03-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/102269/kaz/02.03.2018
  rus: https://zan.gov.kz/client/#!/doc/102269/rus/02.03.2018
caused_by:
  code: '119853'
  requisite: Решение маслихата Хромтауского района Актюбинской области от 2 марта 2018 года № 188. Зарегистрировано Управлением юстиции Хромтауского района Актюбинской области 19 марта 2018 года № 3-12-160. Утратило силу решением Хромтауского районного маслихата Актюбинской области от 5 ноября 2021 года № 120
  title:
    rus: О внесении изменений в решение районного маслихата от 25 апреля 2016 года № 17 «О повышении базовых ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения по Хромтаускому району»
    kaz: Аудандық мәслихаттың 2016 жылғы 25 сәуірдегі № 17 «Хромтау ауданы бойынша пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының базалық мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/119853/rus
