act_code: '41011'
requisite: Ақтөбе облысы Мұғалжар ауданы Батпақкөл ауылдық округі әкімінің 2008 жылғы 30 маусымдағы N 8 шешімі. Ақтөбе облысының Мұғалжар аудандық әділет басқармасында 2008 жылдың 4 тамызда N 3-9-68 тіркелді
title:
  rus: Мұғалжар ауданы, Батпақкөл ауылдық округі, Жағабұлақ ауылында көше атауын қайта атау туралы
  kaz: Мұғалжар ауданы, Батпақкөл ауылдық округі, Жағабұлақ ауылында көше атауын қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-06-30
approved_by:
- '153009006002'
version_date:
  kaz: 2008-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/41011/kaz/30.06.2008
