act_code: '373'
requisite: Решение акима Актюбинской области от 28 мая 1997 года № 106. Зарегистрировано Управлением юстиции Актюбинской области 24 ноября 1997 года № 6. Утратило силу - в связи с истечением срока действия - письмо Департамента юстиции Актюбинской области от 24 апреля 2007 года № 4-19/4895
title:
  rus: О мероприятиях медицинской реабилитации населения, пострадавшего вследствие ядерных испытаний на бывшем Семипалатинском ядерном испытательном полигоне в 1949-1990 годах
  kaz: 1949-1990 жылдардағы бұрынғы Семей ядролық сынақ полигонында ядролық жарылыстардың әсерінен зардап шеккен азаматтарды медициналық реабилитациялау шаралары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1997-05-27
approved_by:
- '153000000003'
version_date:
  kaz: 1997-05-27
  rus: 1997-05-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/373/kaz/27.05.1997
  rus: https://zan.gov.kz/client/#!/doc/373/rus/27.05.1997
