act_code: '51044'
requisite: Ақтөбе облысы Байғанин аудандық мәслихатының 2010 жылғы 5 ақпандағы N 128 шешімі. Ақтөбе облысының Байғанин аудандық әділет басқармасында 2010 жылдың 4 наурызда N 3-4-95 тіркелді. Күші жойылды - Ақтөбе облысы Байғанин аудандық мәслихатының 2013 жылғы 29 қаңтардағы № 58 шешімімен
title:
  rus: Базарларда тауарлар өткізу, жұмыстар орындау, қызметтер көрсету және үй жануарларын бағуды жүзеге асыратын жеке тұлғалар үшін бір жолғы талон құнын белгілеу туралы
  kaz: Базарларда тауарлар өткізу, жұмыстар орындау, қызметтер көрсету және үй жануарларын бағуды жүзеге асыратын жеке тұлғалар үшін бір жолғы талон құнын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-05
approved_by:
- '153005000002'
version_date:
  kaz: 2010-02-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/51044/kaz/05.02.2010
