act_code: '147125'
requisite: Решение акима Культабанского сельского округа Байганинского района Актюбинской области от 29 сентября 2020 года № 21. Зарегистрировано Департаментом юстиции Актюбинской области 5 октября 2020 года № 7514. Утратило силу решением акима Культабанского сельского округа Байганинского района Актюбинской области от 9 декабря 2020 года № 46
title:
  rus: Об установлении карантина
  kaz: Карантин белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-29
approved_by:
- '153005004002'
version_date:
  kaz: 2020-11-20
  rus: 2020-11-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/147125/kaz/20.11.2020
  rus: https://zan.gov.kz/client/#!/doc/147125/rus/20.11.2020
caused_by:
  code: '149014'
  requisite: Решение акима Культабанского сельского округа Байганинского района Актюбинской области от 20 ноября 2020 года № 39. Зарегистрировано Департаментом юстиции Актюбинской области 24 ноября 2020 года № 7699. Отменено решением акима Культабанского сельского округа Байганинского района Актюбинской области от 13 августа 2024 года № 21 (вводится в действие со дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение акима Культабанского сельского округа от 29 сентября 2020 года № 21 «Об установлении карантина»
    kaz: Көлтабан ауылдық округі әкімінің 2020 жылғы 29 қыркүйектегі № 21 «Карантин белгілеу туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149014/rus
