act_code: '51406'
requisite: Ақтөбе облысы Шалқар аудандық мәслихатының 2010 жылғы 17 ақпандағы № 190 шешімі. Ақтөбе облысы Шалқар ауданының Әділет басқармасында 2010 жылғы 18 наурызда № 3-13-127 тіркелді. Күші жойылды - Ақтөбе облысы Шалқар аудандық мәслихатының 2010 жылғы 20 шілдедегі № 212 шешімімен
title:
  rus: Тұрғын үй көмегін көрсетудің мөлшері туралы
  kaz: Тұрғын үй көмегін көрсетудің мөлшері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-17
approved_by:
- '153014000002'
version_date:
  kaz: 2010-02-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/51406/kaz/17.02.2010
