act_code: '213114'
requisite: Решение Байганинского районного маслихата Актюбинской области от 1 августа 2025 года № 303
title:
  rus: Об установлении размера стимулирующих надбавок к должностным окладам работников организаций, финансируемых из бюджета Байганинского района
  kaz: Байғанин ауданының бюджетінен қаржыландырылатын ұйымдар жұмыскерлерінің лауазымдық айлықақыларына ынталандыру үстемақының мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-08-01
approved_by:
- '153005000002'
version_date:
  kaz: 2025-08-01
  rus: 2025-08-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/213114/kaz/01.08.2025
  rus: https://zan.gov.kz/client/#!/doc/213114/rus/01.08.2025
