act_code: '7347'
requisite: Решение Актюбинского областного маслихата от 13 октября 2000 года № 1. Зарегистрировано Управлением юстиции Актюбинской области 10 ноября 2000 года № 769. Утратило силу в связи с истечением срока применения – письмо маслихата Актюбинской области от 20 декабря 2004 года № 1/5-282
title:
  rus: Об индикативном плане социально-экономического развития Актюбинской области на 2001-2005 годы
  kaz: Ақтөбе облысының 2001-2005 жылдарға арналған әлеуметтік – экономикалық дамуының индикативтік жоспары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-10-12
approved_by:
- '153000000002'
version_date:
  kaz: 2000-10-12
  rus: 2000-10-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/7347/kaz/12.10.2000
  rus: https://zan.gov.kz/client/#!/doc/7347/rus/12.10.2000
