act_code: '91650'
requisite: Решение Уилского районного маслихата Актюбинской области от 11 июня 2015 года № 243. Зарегистрировано Департаментом юстиции Актюбинской области 9 июля 2015 года № 4425. Утратило силу решением маслихата Уилского района Актюбинской области от 29 февраля 2016 года № 296
title:
  rus: О повышении базовых ставок земельного налога и ставок единого земельного налога на неиспользуемые земли сельскохозяйственного назначения
  kaz: Пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының базалық мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-06-11
approved_by:
- '153011000002'
version_date:
  kaz: 2015-06-11
  rus: 2015-06-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/91650/kaz/11.06.2015
  rus: https://zan.gov.kz/client/#!/doc/91650/rus/11.06.2015
