act_code: '173300'
requisite: Решение акима Уилского сельского округа Уилского района Актюбинской области от 17 октября 2022 года № 107. Зарегистрировано в Министерстве юстиции Республики Казахстан 26 октября 2022 года № 30312
title:
  rus: О переименовании улиц села Акшатау Уилского сельского округа Уилского района
  kaz: Ойыл ауданының Ойыл ауылдық округінің Ақшатау ауылының көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-10-17
approved_by:
- '153011007002'
version_date:
  kaz: 2022-10-17
  rus: 2022-10-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/173300/kaz/17.10.2022
  rus: https://zan.gov.kz/client/#!/doc/173300/rus/17.10.2022
