act_code: '43285'
requisite: Ақтөбе облысы Ойыл аудандық мәслихатының 2008 жылғы 19 желтоқсандағы N 98 шешімі. Ақтөбе облысының Ойыл аудандық Әділет басқармасында 2008 жылдың 29 желтоқсанда N 3-11-53 тіркелді. Күші жойылды - Ақтөбе облысы Ойыл аудандық мәслихатының 2010 жылғы 15 сәуірдегі N 207 шешімімен
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-19
approved_by:
- '153011000002'
version_date:
  kaz: 2009-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/43285/kaz/26.11.2009
caused_by:
  code: '49295'
  requisite: Ақтөбе облысы Ойыл аудандық мәслихатының 2009 жылғы 26 қарашадағы № 171 шешімі. Ақтөбе облысының Ойыл аудандық Әділет басқармасында 2009 жылдың 11 желтоқсанда N 3-11-70 тіркелді. Күші жойылды - Ақтөбе облысы Ойыл аудандық мәслихатының 2010 жылғы 15 сәуірдегі № 207 шешімімен
  title:
    rus: Аудандық мәслихаттың 2008 жылғы 19 желтоқсандағы № 98 "2009 жылға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Аудандық мәслихаттың 2008 жылғы 19 желтоқсандағы № 98 "2009 жылға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/49295/rus
