act_code: '206446'
requisite: Решение Кобдинского районного маслихата Актюбинской области от 31 декабря 2024 года № 281
title:
  rus: Об утверждении бюджета Кобдинского сельского округа на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Қобда ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-31
approved_by:
- '153012000002'
version_date:
  kaz: 2025-09-10
  rus: 2025-09-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/206446/kaz/10.09.2025
  rus: https://zan.gov.kz/client/#!/doc/206446/rus/10.09.2025
caused_by:
  code: '214378'
  requisite: Решение Кобдинского районного маслихата Актюбинской области от 10 сентября 2025 года № 366
  title:
    rus: О внесении изменений в решение Кобдинского районного маслихата от 31 декабря 2024 года № 281 «Об утверждении бюджета Кобдинского сельского округа на 2025-2027 годы»
    kaz: Қобда аудандық мәслихатының 2024 жылғы 31 желтоқсандағы № 281 «2025-2027 жылдарға арналған Қобда ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/214378/rus
