act_code: '163966'
requisite: Решение Мугалжарского районного маслихата Актюбинской области от 30 декабря 2021 года № 129
title:
  rus: Об утверждении бюджета города Эмба на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Ембі қаласының бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '153009000002'
version_date:
  kaz: 2022-09-09
  rus: 2022-09-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/163966/kaz/09.09.2022
  rus: https://zan.gov.kz/client/#!/doc/163966/rus/09.09.2022
caused_by:
  code: '171839'
  requisite: Решение Мугалжарского районного маслихата Актюбинской области от 9 сентября 2022 года № 241
  title:
    rus: О внесении изменений в решение Мугалжарского районного маслихата от 30 декабря 2021 года № 129 «Об утверждении бюджета города Эмба на 2022-2024 годы»
    kaz: Мұғалжар аудандық мәслихатының 2021 жылғы 30 желтоқсандағы № 129 «2022-2024 жылдарға арналған Ембі қаласының бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/171839/rus
