act_code: '50376'
requisite: Ақтөбе облысы Байғанин ауданы Қарауылкелді ауылдық округінің 2010 жылғы 5 қаңтардағы № 1 шешімі. Ақтөбе облысының Байғанин аудандық Әділет басқармасында 2010 жылдың 27 қаңтарда № 3-4-91 тіркелді
title:
  rus: Көшені атау туралы
  kaz: Көшені атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-01-05
approved_by:
- '153005008001'
version_date:
  kaz: 2010-01-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/50376/kaz/05.01.2010
