act_code: '98226'
requisite: Решение маслихата Иргизского района Актюбинской области от 23 декабря 2015 года № 223. Зарегистрировано Департаментом юстиции Актюбинской области 05 января 2016 года № 4661
title:
  rus: О предоставлении мер социальной поддержки, в области здравоохранения, образования,социального обеспечения, культуры, спорта и агропромышленного комплекса прибывшим для работы и проживания в сельские населенные аункты Иргизского района на 2016 год
  kaz: Ырғыз ауданының ауылдық елді мекендеріне жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға 2016 жылға әлеуметтік қолдау шараларын ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-23
approved_by:
- '153006000002'
version_date:
  kaz: 2015-12-23
  rus: 2015-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/98226/kaz/23.12.2015
  rus: https://zan.gov.kz/client/#!/doc/98226/rus/23.12.2015
