act_code: '151948'
requisite: Решение Кобдинского районного маслихата Актюбинской области от 5 января 2021 года № 422. Зарегистрировано Департаментом юстиции Актюбинской области 13 января 2021 года № 7992
title:
  rus: Об утверждении бюджета Отекского сельского округа на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Өтек ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-01-05
approved_by:
- '153012000002'
version_date:
  kaz: 2021-09-16
  rus: 2021-09-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/151948/kaz/16.09.2021
  rus: https://zan.gov.kz/client/#!/doc/151948/rus/16.09.2021
caused_by:
  code: '158887'
  requisite: Решение Кобдинского районного маслихата Актюбинской области от 16 сентября 2021 года № 87
  title:
    rus: О внесении изменений в решение Кобдинского районного маслихата от 5 января 2021 года № 422 «Об утверждении бюджета Отекского сельского округа на 2021-2023 годы»
    kaz: Қобда аудандық мәслихатының 2021 жылғы 5 қаңтардағы № 422 «2021-2023 жылдарға арналған Өтек ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/158887/rus
