act_code: '43108'
requisite: Ақтөбе облысы Темір аудандық әкімиятының 2008 жылғы 18 желтоқсандағы N 7 шешімі. Ақтөбе облысының Темір аудандық Әділет басқармасында 2008 жылдың 25 желтоқсанда N 3-10-88 тіркелді. Күші жойылды - Ақтөбе облысы Темір аудандық әкімдігінің 2009 жылғы 7 желтоқсандағы № 8 шешімімен
title:
  rus: 1992 жылы туған азаматтарды аудандық қорғаныс істері жөніндегі бөлімнің шақыру учаскесіне тіркеу туралы
  kaz: 1992 жылы туған азаматтарды аудандық қорғаныс істері жөніндегі бөлімнің шақыру учаскесіне тіркеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-18
approved_by:
- '153010000003'
version_date:
  kaz: 2008-12-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/43108/kaz/18.12.2008
