act_code: '204669'
requisite: Решение Темирского районного маслихата Актюбинской области от 13 декабря 2024 года № 262. Зарегистрировано Департаментом юстиции Актюбинской области 24 декабря 2024 года № 8668-04
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2025 год по Темирскому району
  kaz: Темір ауданы бойынша 2025 жылға шетелдіктер үшін туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-13
approved_by:
- '153010000002'
version_date:
  kaz: 2024-12-13
  rus: 2024-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/204669/kaz/13.12.2024
  rus: https://zan.gov.kz/client/#!/doc/204669/rus/13.12.2024
