act_code: '33687'
requisite: Ақтөбе қалалық мәслихатының кезекті отыз тоғызыншы сессиясының 2007 жылғы 30 мамырдағы N 342 шешімі. Ақтөбе қаласының Әділет басқармасында 2007 жылғы 11 маусымда N 3-1-72 тіркелді. Күші жойылды - Ақтөбе қалалық мәслихатының 2009 жылғы 25 сәуірдегі N 169 шешімімен
title:
  rus: Ақтөбе қаласы аумағында сыртқы (көрнекі) жарнама орналастыру үшін төлем ставкалары мөлшерлерін белгілеу туралы
  kaz: Ақтөбе қаласы аумағында сыртқы (көрнекі) жарнама орналастыру үшін төлем ставкалары мөлшерлерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-05-30
approved_by:
- '153002000002'
version_date:
  kaz: 2007-05-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/33687/kaz/30.05.2007
