act_code: '116361'
requisite: Решение Алгинского районного маслихата Актюбинской области от 20 ноября 2017 года № 128. Зарегистрировано Департаментом юстиции Актюбинской области 4 декабря 2017 года № 5719. Утратило силу решением Алгинского районного маслихата Актюбинской области от 14 апреля 2021 года № 43
title:
  rus: Об утверждении Правил управления бесхозяйными отходами, признанными решением суда поступившими в коммунальную собственность Алгинского района
  kaz: Алға ауданында сот шешімімен коммуналдық меншікке түскен болып танылған иесіз қалдықтарды басқару Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2017-11-20
approved_by:
- '153004000002'
version_date:
  kaz: 2019-09-18
  rus: 2019-09-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/116361/kaz/18.09.2019
  rus: https://zan.gov.kz/client/#!/doc/116361/rus/18.09.2019
caused_by:
  code: '134789'
repealed_on: 2021-07-01
repealed_by:
  code: '154792'
  requisite: Решение Алгинского районного маслихата Актюбинской области от 14 апреля 2021 года № 43. Зарегистрировано Департаментом юстиции Актюбинской области 16 апреля 2021 года № 8246
  title:
    rus: О признании утратившими силу некоторых решений Алгинского районного маслихата
    kaz: Алға аудандық мәслихатының кейбір шешімдерінің күші жойылды деп тану туралы
  link: https://zan.gov.kz/client/#!/doc/154792/rus
