act_code: '117756'
requisite: Решение маслихата города Актобе Актюбинской области от 21 декабря 2017 года № 272. Зарегистрировано Департаментом юстиции Актюбинской области 10 января 2018 года № 5831. Утратило силу решением маслихата города Актобе Актюбинской области от 15 декабря 2021 года № 116
title:
  rus: Об утверждении Правил управления бесхозяйными отходами, признанными решением суда поступившими в коммунальную собственность по городу Актобе
  kaz: Ақтөбе қаласы бойынша сот шешімімен коммуналдық меншікке түскен болып танылған иесіз қалдықтарды басқару қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2017-12-21
approved_by:
- '153002000002'
version_date:
  kaz: 2021-03-05
  rus: 2021-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/117756/kaz/05.03.2021
  rus: https://zan.gov.kz/client/#!/doc/117756/rus/05.03.2021
caused_by:
  code: '153328'
  requisite: Решение маслихата города Актобе Актюбинской области от 5 марта 2021 года № 25. Зарегистрировано Департаментом юстиции Актюбинской области 10 марта 2021 года № 8089. Утратило силу решением маслихата города Актобе Актюбинской области от 15 декабря 2021 года № 116
  title:
    rus: О внесении изменений в решение маслихата города Актобе от 21 декабря 2017 года № 272 «Об утверждении Правил управления бесхозяйными отходами, признанными решением суда поступившими в коммунальную собственность по городу Актобе»
    kaz: Ақтөбе қалалық мәслихатының 2017 жылғы 21 желтоқсандағы № 272 «Ақтөбе қаласы бойынша сот шешімімен қоммуналдық меншікке түскен болып танылған иесіз қалдықтарды басқару қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/153328/rus
