act_code: '42891'
requisite: Решение акима Байторысайского сельского округа Мартукского района Актюбинской области от 27 ноября 2008 года № 1. Зарегистрировано Управлением юстиции Мартукского района Актюбинской области 22 декабря 2008 года за № 3-8-63
title:
  rus: О присвоении названий улицам населенных пунктов Байторысайского сельского округа
  kaz: Байторысай ауылдық округінің елді мекендерінің көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-11-27
approved_by:
- '153008001001'
version_date:
  kaz: 2019-05-17
  rus: 2019-05-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/42891/kaz/17.05.2019
  rus: https://zan.gov.kz/client/#!/doc/42891/rus/17.05.2019
caused_by:
  code: '131683'
  requisite: Решение акима Байторысайского сельского округа Мартукского района Актюбинской области от 17 мая 2019 года № 1. Зарегистрировано Департаментом юстиции Актюбинской области 20 мая 2019 года № 6163
  title:
    rus: О внесении изменения в решение акима Байторысайского сельского округа от 27 ноября 2008 года № 1 «О присвоении наименования улицам населенных пунктов Байторысайского сельского округа»
    kaz: Байторысай ауылдық округі әкімінің 2008 жылғы 27 қарашадағы № 1 «Байторысай ауылдық округінің елді мекендерінің көшелеріне атау беру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/131683/rus
