act_code: '42891'
requisite: Решение акима Байторысайского сельского округа Мартукского района Актюбинской области от 27 ноября 2008 года № 1. Зарегистрировано Управлением юстиции Мартукского района Актюбинской области 22 декабря 2008 года за № 3-8-63
title:
  rus: О присвоении названий улицам населенных пунктов Байторысайского сельского округа
  kaz: Байторысай ауылдық округінің елді мекендерінің көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-11-27
approved_by:
- '153008001001'
version_date:
  kaz: 2008-11-27
  rus: 2008-11-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/42891/kaz/27.11.2008
  rus: https://zan.gov.kz/client/#!/doc/42891/rus/27.11.2008
