act_code: '49933'
requisite: Ақтөбе облысы Әйтеке би аудандық әкімдігінің 2009 жылғы 24 желтоқсандағы № 17 шешімі. Ақтөбе облысы Әйтеке би ауданының Әділет басқармасында 2010 жылғы 12 қаңтарда № 3-2-88 тіркелді. Күші жойылды - Ақтөбе облысы Әйтеке би аудандық әкімдігінің 2010 жылғы 30 қарашадағы № 8 шешімімен
title:
  rus: 1993 жылы туылған азаматтарды Әйтеке би ауданының қорғаныс істері жөніндегі бөлімінің шақыру учаскесінде тіркеуді өткізу туралы
  kaz: 1993 жылы туылған азаматтарды Әйтеке би ауданының қорғаныс істері жөніндегі бөлімінің шақыру учаскесінде тіркеуді өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-24
approved_by:
- '153003000003'
version_date:
  kaz: 2009-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/49933/kaz/24.12.2009
