act_code: '102848'
requisite: Решение акима Аккемирского сельского округа Мугалжарского района Актюбинской области от 13 мая 2016 года № 19. Зарегистрировано Департаментом юстиции Актюбинской области 02 июня 2016 года № 4944. Утратило силу решением акима Аккемирского сельского округа Мугалжарского района Актюбинской области от 02 августа 2016 года № 49
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-05-13
approved_by:
- '153009004001'
version_date:
  kaz: 2016-05-13
  rus: 2016-05-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/102848/kaz/13.05.2016
  rus: https://zan.gov.kz/client/#!/doc/102848/rus/13.05.2016
