act_code: '133776'
requisite: Решение маслихата Актюбинской области от 2 августа 2019 года № 455. Зарегистрировано Департаментом юстиции Актюбинской области 6 августа 2019 года № 6330
title:
  rus: Об определении размера и перечня категорий получателей жилищных сертификатов по Актюбинской области
  kaz: Ақтөбе облысы бойынша тұрғын үй сертификаттарының мөлшерін және алушылар санаттарының тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-08-02
approved_by:
- '153000000002'
version_date:
  kaz: 2025-12-10
  rus: 2025-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/133776/kaz/10.12.2025
  rus: https://zan.gov.kz/client/#!/doc/133776/rus/10.12.2025
caused_by:
  code: '218956'
  requisite: Решение Актюбинского областного маслихата от 10 декабря 2025 года № 279
  title:
    rus: О внесении изменений в решение областного маслихата от 2 августа 2019 года № 455 «Об определении размера и перечня категорий получателей жилищных сертификатов по Актюбинской области»
    kaz: «Ақтөбе облысы бойынша тұрғын үй сертификаттарының мөлшерін және алушылар санаттарының тізбесін айқындау туралы» облыстық мәслихаттың 2019 жылғы 2 тамыздағы № 455 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/218956/rus
