act_code: '151112'
requisite: Решение Байганинского районного маслихата Актюбинской области от 29 декабря 2020 года № 404. Зарегистрировано Департаментом юстиции Актюбинской области 30 декабря 2020 года № 7892
title:
  rus: Об утверждении бюджета Жанажолского сельского округа на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Жаңажол ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-29
approved_by:
- '153005000002'
version_date:
  kaz: 2021-06-28
  rus: 2021-06-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/151112/kaz/28.06.2021
  rus: https://zan.gov.kz/client/#!/doc/151112/rus/28.06.2021
caused_by:
  code: '156936'
  requisite: Решение Байганинского районного маслихата Актюбинской области от 28 июня 2021 года № 48. Зарегистрировано в Министерстве юстиции Республики Казахстан 9 июля 2021 года № 23436
  title:
    rus: О внесении изменений в решение «Об утверждении бюджета Жанажолского сельского округа на 2021-2023 годы» от 29 декабря 2020 года № 404
    kaz: «2021-2023 жылдарға арналған Жаңажол ауылдық округінің бюджетін бекіту туралы» 2020 жылғы 29 желтоқсандағы № 404 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/156936/rus
