act_code: '17838'
requisite: Ақтөбе облысы Шалқар аудандық мәслихатының 2003 жылғы 24 қарашадағы № 7 шешімі. Ақтөбе облысының Әділет басқармасында 2003 жылғы 19 желтоқсанда № 2480 тіркелді. Күші жойылды - Ақтөбе облысы Шалқар аудандық мәслихатының 2006 жылғы 29 маусымдағы № 12 шешімімен
title:
  rus: Шалқар ауданы демалыс орындарының жұмыс Ережесін бекіту туралы.
  kaz: Шалқар ауданы демалыс орындарының жұмыс Ережесін бекіту туралы.
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2003-11-24
approved_by:
- '153014000002'
version_date:
  kaz: 2003-11-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/17838/kaz/24.11.2003
