act_code: '120311'
requisite: Решение Мартукского районного маслихата Актюбинской области от 13 марта 2018 года № 141. Зарегистрировано Управлением юстиции Мартукского района Актюбинской области 2 апреля 2018 года № 3-8-168. Утратило силу решением Мартукского районного маслихата Актюбинской области от 28 августа 2023 года № 40
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Мартукского районного маслихата»
  kaz: «Мәртөк аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың Әдістемесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-03-13
approved_by:
- '153008000002'
version_date:
  kaz: 2023-04-28
  rus: 2023-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/120311/kaz/28.04.2023
  rus: https://zan.gov.kz/client/#!/doc/120311/rus/28.04.2023
caused_by:
  code: '181261'
  requisite: Решение Мартукского районного маслихата Актюбинской области от 28 апреля 2023 года № 18. Утратило силу решением Мартукского районного маслихата Актюбинской области от 28 августа 2023 года № 40
  title:
    rus: О внесении изменения в решение Мартукского районного маслихата от 13 марта 2018 года № 141 «Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Мартукского районного маслихата»
    kaz: Мәртөк аудандық мәслихатының 2018 жылғы 13 наурыздағы № 141 «Мәртөк аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың Әдістемесін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/181261/rus
