act_code: '173117'
requisite: Решение Кобдинского районного маслихата Актюбинской области от 7 октября 2022 года № 228. Зарегистрировано в Министерстве юстиции Республики Казахстан 21 октября 2022 года № 30257. Утратило силу решением Кобдинского районного маслихата Актюбинской области от 15 июля 2025 года № 351 (вводится в действие по истечении десяти календарных дней его первого официального опубликования)
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов по Кобдинскому району
  kaz: Қобда ауданы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-10-07
approved_by:
- '153012000002'
version_date:
  kaz: 2023-10-30
  rus: 2023-10-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/173117/kaz/30.10.2023
  rus: https://zan.gov.kz/client/#!/doc/173117/rus/30.10.2023
caused_by:
  code: '187904'
  requisite: Решение Кобдинского районного маслихата Актюбинской области от 30 октября 2023 года № 84. Утратило силу решением Кобдинского районного маслихата Актюбинской области от 15 июля 2025 года № 351 (вводится в действие по истечении десяти календарных дней его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Кобдинского районного маслихата от 7 октября 2022 года № 228 «Об утверждении норм образования и накопления коммунальных отходов по Кобдинскому району»
    kaz: Қобда аудандық мәслихатының 2022 жылғы 7 қазандағы № 228 «Қобда ауданы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/187904/rus
