act_code: '50046'
requisite: Ақтөбе облысы Ойыл аудандық мәслихатының 2009 жылғы 29 желтоқсандағы N 175 шешімі. Ақтөбе облысы Ойыл ауданының Әділет басқармасында 2010 жылғы 20 қаңтарда N 3-11-71 тіркелді. Күші жойылды - Ақтөбе облысы Ойыл аудандық мәслихатының 2011 жылғы 31 наурыздағы № 267 шешімімен
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-29
approved_by:
- '153011000002'
version_date:
  kaz: 2010-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/50046/kaz/19.02.2010
caused_by:
  code: '51295'
  requisite: Ақтөбе облысы Ойыл аудандық мәслихатының 2010 жылғы 19 ақпандағы N 193 шешімі. Ақтөбе облысы Ойыл ауданының Әділет басқармасында 2010 жылғы 9 наурызда N 3-11-75 тіркелді. Күші жойылды - Ақтөбе облысы Ойыл аудандық мәслихатының 2011 жылғы 31 наурыздағы № 267 шешімімен
  title:
    rus: Аудандық мәслихаттың 2009 жылғы 29 желтоқсандағы N 193 "2010-2012 жылдарға арналған аудандық бюджеті туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Аудандық мәслихаттың 2009 жылғы 29 желтоқсандағы N 193 "2010-2012 жылдарға арналған аудандық бюджеті туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/51295/rus
