act_code: '88090'
requisite: Решение Байганинского районного маслихата Актюбинской области от 13 марта 2015 года № 160. Зарегистрировано Департаментом юстиции Актюбинской области 3 апреля 2015 года № 4278
title:
  rus: Об установлении повышенных на двадцать пять процентов окладов и тарифных ставок специалистам в области социального обеспечения, культуры и спорта являющимся гражданскими служащими и работающим в сельских населенных пунктах по Байганинскому району
  kaz: Байғанин ауданы бойынша азаматтық қызметші болып табылатын және ауылдық елдi мекендерде жұмыс iстейтiн әлеуметтiк қамсыздандыру, мәдениет және спорт саласындағы мамандарға жиырма бес пайызға жоғарылатылған айлықақылар мен тарифтiк мөлшерлемелер белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-03-13
approved_by:
- '153005000002'
version_date:
  kaz: 2024-06-05
  rus: 2024-06-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/88090/kaz/05.06.2024
  rus: https://zan.gov.kz/client/#!/doc/88090/rus/05.06.2024
caused_by:
  code: '197541'
  requisite: Решение Байганинского районного маслихата Актюбинской области от 5 июня 2024 года № 177. Зарегистрировано Департаментом юстиции Актюбинской области 10 июня 2024 года № 8592-04
  title:
    rus: О внесении изменений в решение Байганинского районного маслихата от 13 марта 2015 года № 160 «Об установлении повышенных на двадцать пять процентов окладов и тарифных ставок специалистам в области социального обеспечения, образования, культуры, спорта и ветеринарии, являющимся гражданскими служащими и работающим в сельских населенных пунктах по Байганинскому району»
    kaz: Байғанин аудандық мәслихатының 2015 жылғы 13 наурыздағы № 160 «Байғанин ауданы бойынша азаматтық қызметші болып табылатын және ауылдық елдi мекендерде жұмыс iстейтiн әлеуметтiк қамсыздандыру, бiлiм беру, мәдениет, спорт және ветеринария саласындағы мамандарға жиырма бес пайызға жоғарылатылған айлықақылар мен тарифтiк мөлшерлемелер белгілеу туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/197541/rus
