act_code: '4512'
requisite: Решение акима Актюбинской области от 30 сентября 1999 года № 167. Зарегистрировано Управлением юстиции Актюбинской области 11 ноября 1999 года № 259
title:
  rus: О создании специализированной пожарной части по тушению крупных пожаров, ведению первоочередных аварийно-спасательных работ на базе специализированной пожарной части № 1
  kaz: № 1 мамандырылған өрт сөндіру бөлімінің негізінде ірі көлемді өрттерді сөндіру және апаттан құтқарудың бірінші кезектегі жұмыстарын жүргізу жөніндегі мамандырылған өрт сөндіру бөлімін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-09-29
approved_by:
- '153000000003'
version_date:
  kaz: 1999-09-29
  rus: 1999-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/4512/kaz/29.09.1999
  rus: https://zan.gov.kz/client/#!/doc/4512/rus/29.09.1999
