act_code: '185120'
requisite: Решение акима Карауылкелдинского сельского округа Байганинского района Актюбинской области от 13 июля 2023 года № 99
title:
  rus: О снятии ограничительных мероприятий и признании утратившим силу решения акима Карауылкелдинского сельского округа от 16 марта 2023 года № 38 «Об установлении ограничительных мероприятий»
  kaz: Шектеу іс-шараларын алу және Қарауылкелді ауылдық округі әкімінің 2023 жылғы 16 наурыздағы «Шектеу іс-шараларын белгілеу туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-07-13
approved_by:
- '153005008002'
version_date:
  kaz: 2023-07-13
  rus: 2023-07-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/185120/kaz/13.07.2023
  rus: https://zan.gov.kz/client/#!/doc/185120/rus/13.07.2023
