act_code: '48703'
requisite: Ақтөбе облысы Алға ауданы Қарақобда ауылдық округі әкімінің 2009 жылғы 26 қазандағы № 4 шешімі. Ақтөбе облысының Алға аудандық әділет басқармасында 2009 жылдың 16 қарашада № 3-3-94 тіркелді
title:
  rus: Құмсай ауылының көшесіне атау беру туралы
  kaz: Құмсай ауылының көшесіне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-26
approved_by:
- '153004008001'
version_date:
  kaz: 2009-10-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/48703/kaz/26.10.2009
