act_code: '48703'
requisite: Ақтөбе облысы Алға ауданы Қарақобда ауылдық округі әкімінің 2009 жылғы 26 қазандағы № 4 шешімі. Ақтөбе облысының Алға аудандық әділет басқармасында 2009 жылдың 16 қарашада № 3-3-94 тіркелді
title:
  rus: Құмсай ауылының көшесіне атау беру туралы
  kaz: Құмсай ауылының көшесіне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-26
approved_by:
- '153004008001'
version_date:
  kaz: 2016-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/48703/kaz/29.12.2016
caused_by:
  code: '109584'
  requisite: Решение акима Карахобдинского сельского округа Алгинского района Актюбинской области от 29 декабря 2016 года № 29. Зарегистрировано Департаментом юстиции Актюбинской области 24 января 2017 года № 5250
  title:
    rus: О внесении изменений в решение от 26 октября 2009 года № 4 «Құмсай ауылының көшесіне атау беру туралы»
    kaz: «Құмсай ауылының көшесіне атау беру туралы» 2009 жылғы 26 қазандағы № 4 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/109584/rus
