act_code: '162123'
requisite: Решение маслихата Актюбинской области от 9 декабря 2021 года № 80. Зарегистрировано в Министерстве юстиции Республики Казахстан 22 декабря 2021 года № 25883
title:
  rus: Об областном бюджете на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-09
approved_by:
- '153000000002'
version_date:
  kaz: 2022-08-17
  rus: 2022-08-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/162123/kaz/17.08.2022
  rus: https://zan.gov.kz/client/#!/doc/162123/rus/17.08.2022
caused_by:
  code: '170997'
  requisite: Решение маслихата Актюбинской области от 17 августа 2022 года № 144. Зарегистрировано в Министерстве юстиции Республики Казахстан 24 августа 2022 года № 29247
  title:
    rus: О внесении изменений и дополнения в решение областного маслихата «Об областном бюджете на 2022-2024 годы» от 9 декабря 2021 года № 80
    kaz: «2022-2024 жылдарға арналған облыстық бюджет туралы» облыстық мәслихаттың 2021 жылғы 9 желтоқсандағы № 80 шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/170997/rus
