act_code: '177398'
requisite: Решение Мугалжарского районного маслихата Актюбинской области от 29 декабря 2022 года № 288
title:
  rus: Об утверждении бюджета Аккемирского сельского округа на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Ақкемер ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-29
approved_by:
- '153009000002'
version_date:
  kaz: 2023-11-14
  rus: 2023-11-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/177398/kaz/14.11.2023
  rus: https://zan.gov.kz/client/#!/doc/177398/rus/14.11.2023
caused_by:
  code: '188858'
  requisite: Решение Мугалжарского районного маслихата Актюбинской области от 14 ноября 2023 года № 109
  title:
    rus: О внесении изменений в решение Мугалжарского районного маслихата от 29 декабря 2022 года № 288 «Об утверждении бюджета Аккемирского сельского округа на 2023-2025 годы»
    kaz: Мұғалжар аудандық маслихатының 2022 жылғы 29 желтоқсандағы № 288 «2023-2025 жылдарға арналған Ақкемер ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/188858/rus
