act_code: '15109'
requisite: Решение маслихата Актюбинской области от 27 марта 2003 года № 5. Зарегистрировано Управлением юстиции Актюбинской области 17 апреля 2003 года № 2093
title:
  rus: О Программе борьбы с коррупцией в Актюбинской области на 2003-2005 годы
  kaz: Ақтөбе облысында сыбайлас жемқорлыққа қарсы күрестің 2003-2005 жылдарға арналған Бағдарламасы туралы
form: РЕШ
type_codes:
- ПРОГ
- РЕШ
approved_on: 2003-03-27
approved_by:
- '153000000002'
version_date:
  kaz: 2003-10-14
  rus: 2003-10-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/15109/kaz/14.10.2003
  rus: https://zan.gov.kz/client/#!/doc/15109/rus/14.10.2003
caused_by:
  code: '17562'
  requisite: Решение маслихата Актюбинской области от 15 октября 2003 года № 20. Зарегистрировано Управлением юстиции Актюбинской области 25 ноября 2003 года № 2447
  title:
    rus: О внесении изменений в решение областного маслихата от 27 марта 2003 года № 5 «О Программе борьбы с коррупцией в Актюбинской области на 2003-2005 годы», зарегистрированное от 17 апреля 2003 года за № 2093
    kaz: Облыстық мәслихаттың 2003 жылғы 17 сәуірде № 2093 тіркелген 2003 жылғы 27 наурыздағы № 5 «Ақтөбе облысында сыбайлас жемқорлыққа қарсы күрестің 2003-2005 жылдарға арналған Бағдарламасы туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/17562/rus
