act_code: '48765'
requisite: Ақтөбе облысы Мәртөк ауданы Мәртөк ауылдық округі әкімінің 2009 жылғы 24 қазанда № 4 шешімі. Ақтөбе облысының Мәртөк аудандық әділет басқармасында 2009 жылғы 24 қарашада № 3-8-100 тіркелді
title:
  rus: Мәртөк ауылы көшелеріне атау беру туралы
  kaz: Мәртөк ауылы көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-24
approved_by:
- '153008011002'
version_date:
  kaz: 2009-10-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/48765/kaz/24.10.2009
