act_code: '48765'
requisite: Ақтөбе облысы Мәртөк ауданы Мәртөк ауылдық округі әкімінің 2009 жылғы 24 қазанда № 4 шешімі. Ақтөбе облысының Мәртөк аудандық әділет басқармасында 2009 жылғы 24 қарашада № 3-8-100 тіркелді
title:
  rus: Мәртөк ауылы көшелеріне атау беру туралы
  kaz: Мәртөк ауылы көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-24
approved_by:
- '153008011002'
version_date:
  kaz: 2017-05-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/48765/kaz/12.05.2017
caused_by:
  code: '112713'
  requisite: Решение акима Мартукского сельского округа Мартукского района Актюбинской области от 12 мая 2017 года № 1. Зарегистрировано Департаментом юстиции Актюбинской области 1 июня 2017 года № 5517
  title:
    rus: О внесении изменений в решение акима Мартукского сельского округа от 24 октября 2009 года № 4 «Мәртөк ауылы көшелеріне атау беру туралы»
    kaz: Мәртөк ауылдық округі әкімінің 2009 жылғы 24 қазандағы № 4 «Мәртөк ауылы көшелеріне атау беру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/112713/rus
