act_code: '62068'
requisite: Решение акима Иргизского сельского округа Иргизского района Актюбинской области от 5 декабря 2011 года № 94. Зарегистрировано Управлением юстиции Иргизского района Актюбинской области 14 декабря 2011 года № 3-5-149
title:
  rus: О присвоении наименования улице села Иргиз
  kaz: Ырғыз ауылының көшесіне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-05
approved_by:
- '153006006001'
version_date:
  kaz: 2011-12-05
  rus: 2011-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/62068/kaz/05.12.2011
  rus: https://zan.gov.kz/client/#!/doc/62068/rus/05.12.2011
