act_code: '163278'
requisite: Решение Уилского районного маслихата Актюбинской области от 30 декабря 2021 года № 110
title:
  rus: Об утверждении бюджетов сельских округов Уилского района на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Ойыл ауданының ауылдық округтерінің бюджеттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '153011000002'
version_date:
  kaz: 2022-11-15
  rus: 2022-11-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/163278/kaz/15.11.2022
  rus: https://zan.gov.kz/client/#!/doc/163278/rus/15.11.2022
caused_by:
  code: '173947'
  requisite: Решение Уилского районного маслихата Актюбинской области от 15 ноября 2022 года № 189
  title:
    rus: О внесении изменений в решение Уилского районного маслихата Актюбинской области от 30 декабря 2021 года № 110 «Об утверждении бюджетов сельских округов Уилского района на 2022-2024 годы»
    kaz: Ақтөбе облысы Ойыл аудандық мәслихатының 2021 жылғы 30 желтоқсандағы № 110 «2022-2024 жылдарға арналған Ойыл ауданының ауылдық округтерінің бюджеттерін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/173947/rus
