act_code: '116570'
requisite: Решение Кобдинского районного маслихата Актюбинской области от 20 ноября 2017 года № 112. Зарегистрировано Департаментом юстиции Актюбинской области 4 декабря 2017 года № 5720. Утратило силу решением Кобдинского районного маслихата Актюбинской области от 30 декабря 2021 года № 135
title:
  rus: Об утверждении Правил управления бесхозяйными отходами, признанными решением суда поступившими в коммунальную собственность по Кобдинскому району
  kaz: Қобда ауданы бойынша сот шешімімен коммуналдық меншікке түскен болып танылған иесіз қалдықтарды басқару Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2017-11-20
approved_by:
- '153012000002'
version_date:
  kaz: 2020-04-09
  rus: 2020-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/116570/kaz/09.04.2020
  rus: https://zan.gov.kz/client/#!/doc/116570/rus/09.04.2020
caused_by:
  code: '141876'
  requisite: Решение Кобдинского районного маслихата Актюбинской области от 9 апреля 2020 года № 323. Зарегистрировано Департаментом юстиции Актюбинской области 16 апреля 2020 года № 7057. Утратило силу решением Кобдинского районного маслихата Актюбинской области от 30 декабря 2021 года № 135
  title:
    rus: О внесении изменения в решение Кобдинского районного маслихата от 20 ноября 2017 года № 112 «Об утверждении Правил управления бесхозяйными отходами, признанными решением суда поступившими в коммунальную собственность по Кобдинскому району»
    kaz: Қобда аудандық мәслихатының 2017 жылғы 20 қарашадағы № 112 «Қобда ауданы бойынша сот шешімімен коммуналдық меншікке түскен болып танылған иесіз қалдықтарды басқару Қағидаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/141876/rus
