act_code: '45804'
requisite: Ақтөбе облысы Әйтеке би аудандық мәслихатының 2009 жылғы 21 сәуірдегі № 126 шешімі. Ақтөбе облысының Әйтеке би аудандық әділет басқармасында 2009 жылдың 12 мамырда № 3-2-80 тіркелді
title:
  rus: Әйтеке би ауданында салық салуды негіздеу мақсатында жерді аймақтарға бөлу және жер салығының базалық мөлшерлемелерін арттыру туралы
  kaz: Әйтеке би ауданында салық салуды негіздеу мақсатында жерді аймақтарға бөлу және жер салығының базалық мөлшерлемелерін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-21
approved_by:
- '153003000002'
version_date:
  kaz: 2021-03-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/45804/kaz/10.03.2021
caused_by:
  code: '153650'
  requisite: Решение Айтекебийского районного маслихата Актюбинской области от 10 марта 2021 года № 19. Зарегистрировано Департаментом юстиции Актюбинской области 15 марта 2021 года № 8119
  title:
    rus: О внесении изменений в решение районного маслихата от 21 апреля 2009 года № 126 «Әйтеке би ауданында салық салуды негіздеу мақсатында жерді аймақтарға бөлу және жер салығының базалық мөлшерлемелерін жоғарылатуын белгілеу туралы»
    kaz: Аудандық мәслихаттың 2009 жылғы 21 сәуірдегі № 126 «Әйтеке би ауданында салық салуды негіздеу мақсатында жерді аймақтарға бөлу және жер салығының базалық мөлшерлемелерін жоғарылатуын белгілеу туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/153650/rus
