act_code: '153452'
requisite: Решение Шалкарского районного маслихата Актюбинской области от 5 марта 2021 года № 17. Зарегистрировано Департаментом юстиции Актюбинской области 10 марта 2021 года № 8093
title:
  rus: Об утверждении проектов (схем) зонирования земель, границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки в городе Шалкар, Бозойском, Айшуакском, Шалкарском, Бершугирском, Кауылжырском сельских округах
  kaz: Шалқар қаласында, Бозой, Айшуақ, Бершүгір, Шалқар, Қауылжыр ауылдық округтерінде жерді аймақтарға бөлу жобаларын (схемаларын), бағалау аймақтарының шекараларын және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-03-05
approved_by:
- '153014000002'
version_date:
  kaz: 2021-03-05
  rus: 2021-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/153452/kaz/05.03.2021
  rus: https://zan.gov.kz/client/#!/doc/153452/rus/05.03.2021
