act_code: '77018'
requisite: Решение маслихата Хромтауского района Актюбинской области от 20 декабря 2013 года № 152. Зарегистрировано Департаментом юстиции Актюбинской области 22 января 2014 года № 3758. Утратило силу решением маслихата Хромтауского района Актюбинской области от 18 февраля 2016 года № 321
title:
  rus: Об утверждении Правил оказания социальной помощи и определения перечня отдельных категорий нуждающихся граждан в Хромтауском районе
  kaz: Хромтау ауданында әлеуметтік көмек көрсету және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-20
approved_by:
- '153013000002'
version_date:
  kaz: 2013-12-20
  rus: 2013-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/77018/kaz/20.12.2013
  rus: https://zan.gov.kz/client/#!/doc/77018/rus/20.12.2013
