act_code: '45046'
requisite: Ақтөбе облысы Шалқар ауданының Есет Көтібарұлы селолық округі әкімінің 2009 жылғы 4 наурыздағы N 16 шешімі. Ақтөбе облысының Шалқар аудандық әділет басқармасында 2009 жылдың 30 наурызында N 3-13-102 тіркелді
title:
  rus: Көшелерге атау беру туралы
  kaz: Көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-03-04
approved_by:
- '153014005002'
version_date:
  kaz: 2017-04-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/45046/kaz/04.04.2017
caused_by:
  code: '111880'
  requisite: Решение акима Есет Котибарулского сельского округа Шалкарского района Актюбинской области от 4 апреля 2017 года № 2. Зарегистрировано Департаментом юстиции Актюбинской области 19 апреля 2017 года № 5452
  title:
    rus: О внесении изменения в решение акима Есет Котибарулы сельского округа Шалкарского района от 4 марта 2009 года № 16 "Көшелерге атау беру туралы"
    kaz: Шалқар ауданы Есет Көтібарұлы селолық округі әкімінің 2009 жылғы 4 наурыздағы № 16 "Көшелерге атау беру туралы" шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/111880/rus
