act_code: '45046'
requisite: Ақтөбе облысы Шалқар ауданының Есет Көтібарұлы селолық округі әкімінің 2009 жылғы 4 наурыздағы N 16 шешімі. Ақтөбе облысының Шалқар аудандық әділет басқармасында 2009 жылдың 30 наурызында N 3-13-102 тіркелді
title:
  rus: Көшелерге атау беру туралы
  kaz: Көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-03-04
approved_by:
- '153014005002'
version_date:
  kaz: 2015-01-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/45046/kaz/12.01.2015
caused_by:
  code: '86629'
  requisite: Решение акима Есет Котибарулского сельского округа Шалкарского района Актюбинской области от 12 января 2015 года № 1. Зарегистрировано Департаментом юстиции Актюбинской области 16 февраля 2015 года № 4199. Утратило силу решением акима Есет Котибарулского сельского округа Шалкарского района Актюбинской области от 14 сентября 2016 № 7.
  title:
    rus: О внесении изменений в решение акима сельского округа Есет Котибарулы от 4 марта 2009 года № 16 «О присвоении наименования улицам»
    kaz: Есет Көтібарұлы селолық округі әкімінің 2009 жылғы 4 наурыздағы № 16 «Көшелерге атау беру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/86629/rus
