act_code: '45046'
requisite: Ақтөбе облысы Шалқар ауданының Есет Көтібарұлы селолық округі әкімінің 2009 жылғы 4 наурыздағы N 16 шешімі. Ақтөбе облысының Шалқар аудандық әділет басқармасында 2009 жылдың 30 наурызында N 3-13-102 тіркелді
title:
  rus: Көшелерге атау беру туралы
  kaz: Көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-03-04
approved_by:
- '153014005002'
version_date:
  kaz: 2009-03-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/45046/kaz/03.03.2009
