act_code: '74085'
requisite: Решение Уилского районного маслихата Актюбинской области от 31 июля 2013 года № 110. Зарегистрировано Департаментом юстиции Актюбинской области 27 августа 2013 года № 3642. Утратило силу решением маслихата Уилского района Актюбинской области от 13 марта 2017 года № 86
title:
  rus: Об утверждении Правил определения размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам) в Уилском районе
  kaz: Ойыл ауданында аз қамтамасыз етілген отбасыларына (азаматтарға) тұрғын үй көмегін көрсетудің мөлшерін және тәртібін айқындау Ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-07-31
approved_by:
- '153011000002'
version_date:
  kaz: 2013-07-31
  rus: 2013-07-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/74085/kaz/31.07.2013
  rus: https://zan.gov.kz/client/#!/doc/74085/rus/31.07.2013
