act_code: '117924'
requisite: Решение маслихата Айтекебийского района Актюбинской области от 22 декабря 2017 года № 178. Зарегистрировано Департаментом юстиции Актюбинской области 9 января 2018 года № 5826
title:
  rus: Об утверждении бюджета Комсомольского сельского округа на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған Комсомол ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-22
approved_by:
- '153003000002'
version_date:
  kaz: 2018-04-19
  rus: 2018-04-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/117924/kaz/19.04.2018
  rus: https://zan.gov.kz/client/#!/doc/117924/rus/19.04.2018
caused_by:
  code: '121337'
  requisite: Решение маслихата Айтекебийского района Актюбинской области от 19 апреля 2018 года № 209. Зарегистрировано Управлением юстиции Айтекебийского района Департамента юстиции Актюбинской области 25 апреля 2018 года № 3-2-153
  title:
    rus: О внесении изменений в решение районного маслихата от 22 декабря 2017 года № 178 «Об утверждении бюджета Комсомольского сельского округа на 2018-2020 годы»
    kaz: Аудандық мәслихатының 2017 жылғы 22 желтоқсандағы № 178 «2018-2020 жылдарға арналған Комсомол ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/121337/rus
