act_code: '195060'
requisite: Решение Айтекебийского районного маслихата Актюбинской области от 27 марта 2024 года № 177
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Айтекебийскому району на 2024-2025 годы
  kaz: Әйтеке би ауданы бойынша 2024-2025 жылдары жайылымдарды басқару және оларды пайдалану жөніндегі жоспарын бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2024-03-27
approved_by:
- '153003000002'
version_date:
  kaz: 2024-03-27
  rus: 2024-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/195060/kaz/27.03.2024
  rus: https://zan.gov.kz/client/#!/doc/195060/rus/27.03.2024
