act_code: '51984'
requisite: Ақтөбе облысы Темір ауданы Ақсай селолық округ әкімінің 2010 жылғы 29 наурыздағы № 03 шешімі. Ақтөбе облысының Темір аудандық Әділет басқармасында 2010 жылдың 26 сәуірде № 3-10-128 тіркелді. Күші жойылды - Ақтөбе облысы Темір ауданы Ақсай селолық округ әкімінің 2010 жылғы 31 мамырдағы № 10 шешімімен
title:
  rus: Ақсай селолық округінің "Үміт" шаруа қожалығында қой малы арасынан листериоз ауруы шығуына байланысты шектеу қою туралы
  kaz: Ақсай селолық округінің "Үміт" шаруа қожалығында қой малы арасынан листериоз ауруы шығуына байланысты шектеу қою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-29
approved_by:
- '153010003002'
version_date:
  kaz: 2010-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/51984/kaz/29.03.2010
