act_code: '1730'
requisite: Решение акима Актюбинской области от 12 октября 1998 года № 156. Зарегистрировано Управлением юстиции Актюбинской области 6 ноября 1998 года № 52. Утратило силу постановлением акимата Актюбинской области от 19 марта 2002 года № 38
title:
  rus: О реализации постановления Правительства Республики Казахстан N 840 от 04.09.98 года "Об утверждении Правил о порядке уплаты и ставках сборов за право реализации товаров (работ, услуг) на рынках Республики Казахстан"
  kaz: '"Казақстан республикасының базарларында тауарларды (жұмыстарды, қызмет көрсетулерді) сату құқығы үшін ақы төлеудің тәртібі мен алымдардың ставкалары туралы" Ережені бекіту туралы Қазақстан Республикасы Үкіметінің 1998 жылғы 4 қыркүйектегі № 840 қаулысын жүзеге асыру туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-10-11
approved_by:
- '153000000003'
version_date:
  kaz: 1998-10-11
  rus: 1998-10-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/1730/kaz/11.10.1998
  rus: https://zan.gov.kz/client/#!/doc/1730/rus/11.10.1998
