act_code: '44716'
requisite: Решение маслихата Мугалжарского района Актюбинской области от 30 января 2009 года N 95. Зарегистрировано управлением юстиции Мугалжарского района Актюбинской области 06 марта 2009 года за N 3-9-95. Утратило силу решением маслихата Мугалжарского района Актюбинской области от 16 февраля 2018 года № 163
title:
  rus: Об установлении ставок фиксированного налога по Мугалжарскому району
  kaz: Мұғалжар ауданы бойынша тіркелген салық мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-30
approved_by:
- '153009000002'
version_date:
  kaz: 2017-03-13
  rus: 2017-03-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/44716/kaz/13.03.2017
  rus: https://zan.gov.kz/client/#!/doc/44716/rus/13.03.2017
caused_by:
  code: '111280'
  requisite: Решение маслихата Мугалжарского района Актюбинской области от 13 марта 2017 года № 74. Зарегистрировано Департаментом юстиции Актюбинской области 3 апреля 2017 года № 5382. Утратило силу решением маслихата Мугалжарского района Актюбинской области от 16 февраля 2018 года № 163
  title:
    rus: О внесении изменений в решение Мугалжарского районного маслихата от 30 января 2009 года № 95 «Об установлении ставок фиксированного налога по Мугалжарскому району»
    kaz: Мұғалжар аудандық мәслихатының 2009 жылғы 30 қаңтардағы № 95 «Мұғалжар ауданы бойынша тіркелген салық мөлшерін белгілеу туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/111280/rus
