act_code: '137712'
requisite: Решение Айтекебийского районного маслихата Актюбинской области от 25 декабря 2019 года № 347. Зарегистрировано Департаментом юстиции Актюбинской области 27 декабря 2019 года № 6616
title:
  rus: Об утверждении Айтекебийского районного бюджета на 2020 - 2022 годы
  kaz: 2020 – 2022 жылдарға арналған Әйтеке би аудандық бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-25
approved_by:
- '153003000002'
version_date:
  kaz: 2020-12-14
  rus: 2020-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/137712/kaz/14.12.2020
  rus: https://zan.gov.kz/client/#!/doc/137712/rus/14.12.2020
caused_by:
  code: '150111'
  requisite: Решение Айтекебийского районного маслихата Актюбинской области от 14 декабря 2020 года № 496. Зарегистрировано Департаментом юстиции Актюбинской области 15 декабря 2020 года № 7802
  title:
    rus: О внесении изменений в решение районного маслихата от 25 декабря 2019 года № 347 «Об утверждении Айтекебийского районного бюджета на 2020 - 2022 годы»
    kaz: Аудандық мәслихатының 2019 жылғы 25 желтоқсандағы № 347 «2020 – 2022 жылдарға арналған Әйтеке би аудандық бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/150111/rus
