act_code: '98768'
requisite: Решение маслихата Иргизского района Актюбинской области от 14 января 2016 года № 235
title:
  rus: О признании утратившим силу решения Иргизского районного маслихата № 211 от 30 октября 2015 года "Об утверждении Методики ежегодной оценки деятельности административных государственных служащих корпуса "Б" государственного учреждения "аппарат маслихата Иргизского района"
  kaz: Ырғыз аудандық міслихатының 2015 жылғы 30 қазандағы № 211 "Ырғыз аудандық мәслихатының аппараты" мемлекеттік мекемесінің "Б" корпусы мемлекеттік әкімшілік қызметшілерінің қызметін жыл сайынғы бағалау әдістемесін бекіту туралы" шешімінің күшін жою деп тану туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-01-14
approved_by:
- '153006000002'
version_date:
  kaz: 2016-01-14
  rus: 2016-01-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/98768/kaz/14.01.2016
  rus: https://zan.gov.kz/client/#!/doc/98768/rus/14.01.2016
