act_code: '226146'
requisite: Решение акима Булакского сельского округа Кобдинского района Актюбинской области от 5 июня 2026 года № 10
title:
  rus: О присвоении наименования безымянной улице
  kaz: Атауы жоқ көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-06-05
approved_by:
- '153012003002'
version_date:
  kaz: 2026-06-05
  rus: 2026-06-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/226146/kaz/05.06.2026
  rus: https://zan.gov.kz/client/#!/doc/226146/rus/05.06.2026
