act_code: '203066'
requisite: Решение Байганинского районного маслихата Актюбинской области от 15 ноября 2024 года № 214. Зарегистрировано Департаментом юстиции Актюбинской области 22 ноября 2024 года № 8655-04. Утратило силу решением Байганинского районного маслихата Актюбинской области от 18 декабря 2025 года № 344 (вводится в действие с 01.01.2026)
title:
  rus: О понижении размера ставки налогов при применении специального налогового режима розничного налога в Байганинском районе
  kaz: Байғанин ауданында бөлшек салықтың арнаулы салық режимін қолдану кезінде салық мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-11-15
approved_by:
- '153005000002'
version_date:
  kaz: 2024-11-15
  rus: 2024-11-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/203066/kaz/15.11.2024
  rus: https://zan.gov.kz/client/#!/doc/203066/rus/15.11.2024
