act_code: '92917'
requisite: Решение Мартукского районного маслихата Актюбинской области от 31 июля 2015 года № 195. Зарегистрировано Департаментом юстиции Актюбинской области 19 августа 2015 года № 4475. Утратило силу решением маслихата Мартукского района Актюбинской области от 23 февраля 2016 года № 224
title:
  rus: О повышении ставок земельного налога и единого земельного налога на не используемые земли сельскохозяйственного назначения по Мартукскому району
  kaz: Мәртөк ауданы бойынша пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-07-31
approved_by:
- '153008000002'
version_date:
  kaz: 2015-07-31
  rus: 2015-07-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/92917/kaz/31.07.2015
  rus: https://zan.gov.kz/client/#!/doc/92917/rus/31.07.2015
