act_code: '98185'
requisite: Решение маслихата Каргалинского района Актюбинской области от 24 декабря 2015 года № 373. Зарегистрировано Департаментом юстиции Актюбинской области 18 января 2016 года № 4680
title:
  rus: О бюджете Каргалинского района на 2016-2018 годы
  kaz: 2016-2018 жылдарға арналған Қарғалы ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-24
approved_by:
- '153007000002'
version_date:
  kaz: 2016-06-10
  rus: 2016-06-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/98185/kaz/10.06.2016
  rus: https://zan.gov.kz/client/#!/doc/98185/rus/10.06.2016
caused_by:
  code: '103816'
  requisite: Решение маслихата Каргалинского района Актюбинской области от 10 июня 2016 года № 34. Зарегистрировано Департаментом юстиции Актюбинской области 30 июня 2016 года № 4972
  title:
    rus: О внесении изменений и дополнения в решение районного маслихата от 24 декабря 2015 года № 373 "О бюджете Каргалинского района на 2016 - 2018 годы"
    kaz: '"2016-2018 жылдарға арналған Қарғалы ауданының бюджеті туралы" аудандық мәслихаттың 2015 жылғы 24 желтоқсандағы № 373 шешіміне өзгерістер мен толықтыру енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/103816/rus
