act_code: '98185'
requisite: Решение маслихата Каргалинского района Актюбинской области от 24 декабря 2015 года № 373. Зарегистрировано Департаментом юстиции Актюбинской области 18 января 2016 года № 4680
title:
  rus: О бюджете Каргалинского района на 2016-2018 годы
  kaz: 2016-2018 жылдарға арналған Қарғалы ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-24
approved_by:
- '153007000002'
version_date:
  kaz: 2016-04-12
  rus: 2016-04-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/98185/kaz/12.04.2016
  rus: https://zan.gov.kz/client/#!/doc/98185/rus/12.04.2016
caused_by:
  code: '101715'
  requisite: Решение маслихата Каргалинского района Актюбинской области от 12 апреля 2016 года № 17. Зарегистрировано Департаментом юстиции Актюбинской области 25 апреля 2016 года № 4861
  title:
    rus: О внесении изменений и дополнений в решение районного маслихата от 24 декабря 2015 года № 373 «О бюджете Каргалинского района на 2016-2018 годы»
    kaz: Аудандық мәслихаттың 2015 жылғы 24 желтоқсандағы № 373 «2016-2018 жылдарға арналған Қарғалы ауданының бюджеті туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/101715/rus
