act_code: '54372'
requisite: Решение маслихата города Актобе Актюбинской области от 28 июля 2010 года № 265. Зарегистрировано Управлением юстиции города Актобе Актюбинской области 7 сентября 2010 года № 3-1-140. Утратило силу решением маслихата города Актобе Актюбинской области от 12 декабря 2017 года № 247
title:
  rus: Об утверждении Правил определения размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам) в городе Актобе
  kaz: Ақтөбе қаласында аз қамтамасыз етілген отбасыларына (азаматтарға) тұрғын үй көмегін көрсетудің мөлшерін және тәртібін айқындау Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2010-07-28
approved_by:
- '153002000002'
version_date:
  kaz: 2013-12-20
  rus: 2013-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/54372/kaz/20.12.2013
  rus: https://zan.gov.kz/client/#!/doc/54372/rus/20.12.2013
caused_by:
  code: '76236'
  requisite: Решение маслихата города Актобе Актюбинской области от 20 декабря 2013 года № 190. Зарегистрировано Департаментом юстиции Актюбинской области 28 декабря 2013 года № 3723. Утратило силу решением маслихата города Актобе Актюбинской области от 12 декабря 2017 года № 247
  title:
    rus: О внесении изменений в решение маслихата города Актобе от 28 июля 2010 года № 265 "Об утверждении Правил определения размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам) в городе Актобе"
    kaz: '"Ақтөбе қаласында аз қамтамасыз етілген отбасыларына (азаматтарға) тұрғын үй көмегін көрсетудің мөлшерін және тәртібін айқындау Ережесін бекіту туралы" Ақтөбе қалалық мәслихатының 2010 жылдың 28 шілдедегі № 265 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/76236/rus
