act_code: '230349'
requisite: Решение Мугалжарского районного маслихата Актюбинской области от 18 сентября 2026 года № 609
title:
  rus: Об утверждении Положения государственного учреждения «Аппарат Мугалжарского районного маслихата»
  kaz: «Мұғалжар аудандық мәслихатының аппараты» мемлекеттік мекемесінің Ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-09-18
approved_by:
- '153009000002'
version_date:
  kaz: 2026-09-18
  rus: 2026-09-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/230349/kaz/18.09.2026
  rus: https://zan.gov.kz/client/#!/doc/230349/rus/18.09.2026
