act_code: '43096'
requisite: Решение акима Богетсайского сельского округа Хромтауского района Актюбинской области от 12 декабря 2008 года № 8. Зарегистрировано Управлением юстиции Хромтауского района Актюбинской области 26 декабря 2008 года № 3-12-74
title:
  rus: «О присвоении названии улицам населенных пунктов Богетсайского сельского округа»
  kaz: Бөгетсай ауылдық округінің елді мекендерінің көшелеріне атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-12
approved_by:
- '153013005001'
version_date:
  kaz: 2015-09-07
  rus: 2015-09-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/43096/kaz/07.09.2015
  rus: https://zan.gov.kz/client/#!/doc/43096/rus/07.09.2015
caused_by:
  code: '93791'
  requisite: Решение от 07.09.2015 №21, Акимат Бугетсайского сельского округа
  title:
    rus: О внесении изменений в решение от 12 декабря 2008 года № 8 "О присвоении названии улицам населенных пунктов Богетсайского сельского округа"
    kaz: '"Бөгетсай селолық округіне қарасты елді мекендерге көше атауын беру туралы" 2008 жылғы 12 желтоқсандағы № 8 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/93791/rus
