act_code: '43096'
requisite: Решение акима Богетсайского сельского округа Хромтауского района Актюбинской области от 12 декабря 2008 года № 8. Зарегистрировано Управлением юстиции Хромтауского района Актюбинской области 26 декабря 2008 года № 3-12-74
title:
  rus: «О присвоении названии улицам населенных пунктов Богетсайского сельского округа»
  kaz: Бөгетсай ауылдық округінің елді мекендерінің көшелеріне атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-12
approved_by:
- '153013005001'
version_date:
  kaz: 2008-12-12
  rus: 2008-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/43096/kaz/12.12.2008
  rus: https://zan.gov.kz/client/#!/doc/43096/rus/12.12.2008
