act_code: '76239'
requisite: Решение маслихата города Актобе Актюбинской области от 20 декабря 2013 года № 188. Зарегистрировано Департаментом юстиции Актюбинской области 28 декабря 2013 года № 3726. Утратило силу решением маслихата города Актобе Актюбинской области от 23 ноября 2016 года № 114
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан в городе Актобе
  kaz: Ақтөбе қаласында әлеуметтік көмек көрсету, мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2013-12-20
approved_by:
- '153002000002'
version_date:
  kaz: 2016-02-17
  rus: 2016-02-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/76239/kaz/17.02.2016
  rus: https://zan.gov.kz/client/#!/doc/76239/rus/17.02.2016
caused_by:
  code: '100313'
  requisite: Решение маслихата города Актобе Актюбинской области от 17 февраля 2016 года № 421. Зарегистрировано Департаментом юстиции Актюбинской области 17 марта 2016 года № 4793. Утратило силу решением маслихата города Актобе Актюбинской области от 23 ноября 2016 года № 114
  title:
    rus: О внесении изменений и дополнений в решение маслихата города Актобе от 20 декабря 2013 года № 188 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня категорий нуждающихся граждан в городе Актобе»
    kaz: «Ақтөбе қаласында әлеуметтік көмек көрсету, мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидаларын бекіту туралы» Ақтөбе қалалық мәслихатының 2013 жылғы 20 желтоқсандағы № 188 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/100313/rus
