act_code: '76239'
requisite: Решение маслихата города Актобе Актюбинской области от 20 декабря 2013 года № 188. Зарегистрировано Департаментом юстиции Актюбинской области 28 декабря 2013 года № 3726. Утратило силу решением маслихата города Актобе Актюбинской области от 23 ноября 2016 года № 114
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан в городе Актобе
  kaz: Ақтөбе қаласында әлеуметтік көмек көрсету, мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2013-12-20
approved_by:
- '153002000002'
version_date:
  kaz: 2016-07-27
  rus: 2016-07-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/76239/kaz/27.07.2016
  rus: https://zan.gov.kz/client/#!/doc/76239/rus/27.07.2016
caused_by:
  code: '105824'
  requisite: Решение маслихата города Актобе Актюбинской области от 27 июля 2016 года № 81. Зарегистрировано Департаментом юстиции Актюбинской области 31 августа 2016 года № 5042. Утратило силу решением маслихата города Актобе Актюбинской области от 23 ноября 2016 года № 114
  title:
    rus: О внесении изменений в решение маслихата города Актобе от 20 декабря 2013 года № 188 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня категорий нуждающихся граждан в городе Актобе»
    kaz: «Ақтөбе қаласында әлеуметтік көмек көрсету, мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидаларын бекіту туралы» Ақтөбе қалалық мәслихатының 2013 жылғы 20 желтоқсандағы № 188 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/105824/rus
