act_code: '7401'
requisite: Решение акима Актюбинской области от 2 октября 2000 года № 145. Зарегистрировано Управлением юстиции Актюбинской области 20 ноября 2000 года № 791. Утратило силу в связи с истечением срока применения – письмо акимата Актюбинской области от 21 декабря 2004 года № 08-3/2691
title:
  rus: Об очередном призыве граждан на срочную военную службу в октябре-декабре 2000 года
  kaz: 2000 жылдың қазан-желтоқсан айларында азаматтарды кезекті мерзімді әскери қызметке шақыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-10-01
approved_by:
- '153000000003'
version_date:
  kaz: 2000-10-01
  rus: 2000-10-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/7401/kaz/01.10.2000
  rus: https://zan.gov.kz/client/#!/doc/7401/rus/01.10.2000
