act_code: '52547'
requisite: Ақтөбе облысы Мәртөк аудандық мәслихатының 2010 жылғы 23 сәуірдегі № 167 шешімі. Ақтөбе облысы Мәртөк ауданының Әділет басқармасында 2010 жылдың 18 мамырда № 3-8-114 тіркелді. Күші жойылды - Ақтөбе облысы Мәртөк аудындық мәслихатының 2011 жылғы 3 ақпандағы № 220 шешімімен
title:
  rus: Аз қамтылған отбасы мүшелеріне әлеуметтік көмек көрсету туралы
  kaz: Аз қамтылған отбасы мүшелеріне әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-23
approved_by:
- '153008000002'
version_date:
  kaz: 2010-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/52547/kaz/23.04.2010
