act_code: '218914'
requisite: Решение Актюбинского областного маслихата от 10 декабря 2025 года № 277
title:
  rus: Об установлении ставок арендной платы за использование памятников истории и культуры местного значения Актюбинской области
  kaz: Ақтөбе облысының жергілікті маңызы бар тарих және мәдениет ескерткіштерін пайдаланғаны үшін жалға алу ақысының мөлшерлемелерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-10
approved_by:
- '153000000002'
version_date:
  kaz: 2025-12-10
  rus: 2025-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/218914/kaz/10.12.2025
  rus: https://zan.gov.kz/client/#!/doc/218914/rus/10.12.2025
