act_code: '146574'
requisite: Решение Шалкарского районного маслихата Актюбинской области от 10 сентября 2020 года № 524. Зарегистрировано Департаментом юстиции Актюбинской области 18 сентября 2020 года № 7444
title:
  rus: Об определении специализированных мест для организации и проведения мирных собраний, порядка использования специализированных мест для организации и проведения мирных собраний, норм их предельной заполняемости, а также требований к материально-техническому и организационному обеспечению специализированных мест для организации и проведения мирных собраний, границ прилегающих территорий, в которых запрещено проведение пикетирования в Шалкарском районе
  kaz: Шалқар ауданында бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды пайдалану тәртібін, олардың шекті толу нормаларын, сондай-ақ бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптарды, пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекараларын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-10
approved_by:
- '153014000002'
version_date:
  kaz: 2020-09-10
  rus: 2020-09-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/146574/kaz/10.09.2020
  rus: https://zan.gov.kz/client/#!/doc/146574/rus/10.09.2020
