act_code: '5355'
requisite: Решение акима Актюбинской области от 8 декабря 1999 года № 210. Зарегистрировано Управлением юстиции Актюбинской области 21 февраля 2000 года № 372. Утратило силу в связи с истечением срока применения – письмо акима Актюбинской области от 21 декабря 2004 года № 08-3/2691
title:
  rus: О предоставлении компании "Шелл Темир Петролеум Девелопмент Б. В." права временного пользования земельным участком для бурения разведочной скважины Сайгак Восточный на территории землепользования крестьянского хозяйства "Берды" в Темирском районе
  kaz: Темір ауданының "Берді" шаруа қожалығы жерінің аумағындағы батыс Сайғак барлау скважинасын бұрғылау үшін жер учаскесін уақытша пайдалану құқын "Шелл Темір Петролеум Девелопмент Б. В." компаниясына беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-12-08
approved_by:
- '153000000003'
version_date:
  kaz: 1999-12-08
  rus: 1999-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/5355/kaz/08.12.1999
  rus: https://zan.gov.kz/client/#!/doc/5355/rus/08.12.1999
