act_code: '38844'
requisite: Решение маслихата Каргалинского района Актюбинской области от 27 марта 2008 года N 46. Зарегистрировано Управлением юстиции Каргалинского района Актюбинской области 11 апреля 2008 года N 3-6-61. Утратило силу решением маслихата Каргалинского района Актюбинской области от 24 апреля 2009 года № 140
title:
  rus: Об установлении ставок на разовые талоны
  kaz: Бір жолғы талон мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-03-27
approved_by:
- '153007000002'
version_date:
  kaz: 2008-03-27
  rus: 2008-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/38844/kaz/27.03.2008
  rus: https://zan.gov.kz/client/#!/doc/38844/rus/27.03.2008
