act_code: '214302'
requisite: Решение Мартукского районного маслихата Актюбинской области от 10 сентября 2025 года № 242
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов, тарифов для населения на сбор, транспортировку, сортировку и захоронение твердых бытовых отходов по Мартукскому району
  kaz: Мәртөк ауданы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын, халық үшін тұрмыстық қатты қалдықтарды жинауға, тасымалдауға, сұрыптауға және көмуге арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-10
approved_by:
- '153008000002'
version_date:
  kaz: 2025-09-10
  rus: 2025-09-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/214302/kaz/10.09.2025
  rus: https://zan.gov.kz/client/#!/doc/214302/rus/10.09.2025
