act_code: '220698'
requisite: Решение Шалкарского районного маслихата Актюбинской области от 24 декабря 2025 года № 563
title:
  rus: Об утверждении бюджета Бершугирского сельского округа на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған Бершүгір ауылдық округ бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-24
approved_by:
- '153014000002'
version_date:
  kaz: 2026-08-20
  rus: 2026-08-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/220698/kaz/20.08.2026
  rus: https://zan.gov.kz/client/#!/doc/220698/rus/20.08.2026
caused_by:
  code: '229359'
  requisite: Решение Шалкарского районного маслихата Актюбинской области от 20 августа 2026 года № 680
  title:
    rus: О внесении изменений в решение Шалкарского районного маслихата от 24 декабря 2025 года № 563 «Об утверждении бюджета Бершугирского сельского округа на 2026-20278 годы»
    kaz: Шалқар аудандық мәслихатының 2025 жылғы 24 желтоқсандағы № 563 «2026-2028 жылға арналған Бершүгір ауылдық округ бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/229359/rus
