act_code: '46001'
requisite: Ақтөбе облысы Алға ауданы Бестамақ ауылдық округі әкімінің 2009 жылғы 13 сәуірдегі N 18 шешімі. Ақтөбе облысының Алға аудандық әділет басқармасында 2009 жылдың 18 мамырдағы N 3-3-77 тіркелді
title:
  rus: Бестамақ ауылының көшелерін қайта атау және жаңа көшелерге атау беру туралы
  kaz: Бестамақ ауылының көшелерін қайта атау және жаңа көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-13
approved_by:
- '153004003002'
version_date:
  kaz: 2019-07-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/46001/kaz/24.07.2019
caused_by:
  code: '133742'
  requisite: Решение акима Бестамакского сельского округа Алгинского района Актюбинской области от 24 июля 2019 года № 56. Зарегистрировано Департаментом юстиции Актюбинской области 26 июля 2019 года № 6308
  title:
    rus: О внесении изменений в решение акима Бестамакского сельского округа от 13 апреля 2009 года № 18 «Бестамақ ауылының көшелерін қайта атау және жаңа көшелерге атау беру туралы»
    kaz: Бестамақ селолық округі әкімінің 2009 жылғы 13 сәуірдегі № 18 «Бестамақ ауылының көшелерін қайта атау және жаңа көшелерге атау беру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/133742/rus
