act_code: '139145'
requisite: Решение Хромтауского районного маслихата Актюбинской области от 20 января 2020 года № 419. Зарегистрировано Департаментом юстиции Актюбинской области 24 января 2020 года № 6779
title:
  rus: Об утверждении бюджета села Никельтау на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Никельтау ауылының бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-20
approved_by:
- '153013000002'
version_date:
  kaz: 2020-09-09
  rus: 2020-09-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/139145/kaz/09.09.2020
  rus: https://zan.gov.kz/client/#!/doc/139145/rus/09.09.2020
caused_by:
  code: '146553'
  requisite: Решение Хромтауского районного маслихата Актюбинской области от 9 сентября 2020 года № 512. Зарегистрировано Департаментом юстиции Актюбинской области 18 сентября 2020 года № 7432
  title:
    rus: О внесении изменений в решение Хромтауского районного маслихата от 20 января 2020 года № 419 «Об утверждении бюджета села Никельтау на 2020-2022 годы»
    kaz: Хромтау аудандық мәслихатының 2020 жылғы 20 қаңтардағы № 419 «2020-2022 жылдарға арналған Никельтау ауылының бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/146553/rus
