act_code: '106768'
requisite: Решение акима Талдысайского сельского округа Мугалжарского района Актюбинской области от 30 сентября 2016 года № 21. Зарегистрировано Департаментом юстиции Актюбинской области 20 октября 2016 года № 5109. Утратило силу решением акима Талдысайского сельского округа Мугалжарского района Актюбинской области от 27 июня 2017 года № 9
title:
  rus: Об установлении ограничительных мероприятий на территории села Енбек Талдысайского сельского округа Мугалжарского района
  kaz: Мұғалжар ауданы Талдысай ауылдық округі Еңбек ауылы аумағында шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-09-30
approved_by:
- '153009015002'
version_date:
  kaz: 2016-09-30
  rus: 2016-09-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/106768/kaz/30.09.2016
  rus: https://zan.gov.kz/client/#!/doc/106768/rus/30.09.2016
